### ISSUE TITLE
testscr_check_spec fails with custom KDB_DB_SPEC path

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#1000]
# Describe what you wanted to do

I tried to configure a custom SPEC path within my build directory:

```
cmake -DDEBUG=ON -DVERBOSE=ON -DBUILD_STATIC=OFF -DCMAKE_INSTALL_PREFIX=./install -DKDB_DB_SYSTEM=./kdbsystem -DKDB_DB_SPEC=./spec ..
```
# Describe what you expected

I expected it to place the spec files in that directory.
# Describe what actually happened

The following tests FAILED:
     78 - testscr_check_spec (Failed)
# System Information
- Elektra Version: master
- OS: macOS
# Further Log Files and Output

[testscr_check_spec.txt](https://github.com/ElektraInitiative/libelektra/files/504479/testscr_check_spec.txt)

**Comment by markus2330** [comment]
Thank you for reporting! I could reproduce it on Linux, but only once. When I run the test cases again the error does not occur.

It seems to be related to resolver maybe there are troubles creating the "." directory (which should be ignored and not created).

As workaround: did you try to not use "./" for the paths?

Btw. "hooray" because this is the 1000 th issue!

**Comment by mpranj** [comment]
You're right, it works when:
- I run the tests again
- I don't use  "./"

The issue is not a biggie but I encountered it today so I just wanted to document it.
I wouldn't be mad if we just close #1000 and #1001 if nobody cares :D

**Comment by markus2330** [comment]
Maybe we should introduce a cmake validation for paths.
