### ISSUE TITLE
python plugin: avoid output of errors to console

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1003]
Is there a specific reason why errors are not fetched via `PyErr_Fetch` and added to errors text? That would avoid the `/print` workaround.

**Comment by manuelm** [comment]
The reason is you cannot easily convert the variables/objects from `PyErr_Fetch` to the same output as `PyErr_Print`. Reading https://github.com/python/cpython/blob/caba55b3b735405b280273f7d99866a046c18281/Python/pythonrun.c#L637 it looks like `PyErr_Print` sets the traceback as current object and the python interpreter will do the unfolding. Since we cannot capture normal python output we would have to do the unfolding ourself. e.g. something like this: https://github.com/shelmesky/cloud_perf_api/blob/739156fcde5dc95a9d6841cd8809d796cbe5e4c6/py_exception.c (not tested or compared to normal output)

**Comment by markus2330** [comment]
Yes, code like py_exception.c should enable us to put the reason of an python error as normal Elektra warning/error. It would be, however, a nice-to-have.

**Comment by markus2330** [comment]
@manuelm ping as requested (it is a low-priority issue though, as the print plugin option workaround works well)
