### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1011]
- [x] Report issues on github: Text always visible, other color
- [x] Convert snippet: use arrow only in (the) one direction
- [x] Popup right side should be longer visible (longer visible for longer texts?)
- [x] "New snippet" text (upper right) hardly visible, maybe put it next to Convert snippet? (Note: might be irrelevant if there is a way to create a new snippet from the converted snippet: then it might be even better to distribute it)
- [x] When reporting issues, use label instead of "[Website]" in title? ("help wanted" would be ok)
- [x] old text remains in output on failed conversion?
- [x] after reporting issue (not sure if this is the reason), converting was no longer possible (when pressing convert the only indicator was the small progress bar on the very top, but no other feedback). There should be always some feedback, also if backend is down or similar.
- [ ] create snippet based on input or output of the snippet conversion.
- [ ] try to reproduce crashes for simpleini/fstab

**Comment by Namoshek** [comment]
Thank you for the detailed feedback! I will change most of the points right away, but I'have some questions/explanation:

> Report issues on github: Text always visible, other color

I thought it might be better to have this function a bit hidden so we don't get flooded with issues. Do you think the icon alone is not enough to get attention? And what color do you suggest? Orange?

> Convert snippet: use arrow only in (the) one direction

Interestingly, I had this icon at first, but then I searched for a conversion icon and found that the `exchange` one was suggested by someone. But I think you are right, the single arrow makes more sense in our case, I'll change it again.

> Popup right side should be longer visible (longer visible for longer texts?)

Currently I have a global setting for the time, but I think I can easily override it. I can also enable a small progress bar on the lower end of the popup that indicates how long it will stay (which can be stopped by hovering it). I removed it because I thought it might be distracting, but I'll enable it so you can give feedback!

(Note for me: Check if the notification duration can be based on the text length.)

> "New snippet" text (upper right) hardly visible, maybe put it next to Convert snippet? (Note: might be irrelevant if there is a way to create a new snippet from the converted snippet: then it might be even better to distribute it)

Haven't thought about creating snippets from a conversion yet (is it really a usecase?), but definitely only a minor change. The reason I have it in the top menu is that it requires a login (and permissions). An alternative would be to move it to the second menu on the right side (administration stuff is there at the moment, but ofc you didn't see it without the necessary rank yet).

I think I'll move it to the second menu and leave space in the top menu for a profile/settings link. What do you think?

> When reporting issues, use label instead of "[Website]" in title? ("help wanted" would be ok)

As soon as I found out how to pre-fill labels, absolutely no problem at all! :+1: 

> after reporting issue (not sure if this is the reason), converting was no longer possible (when pressing convert the only indicator was the small progress bar on the very top, but no other feedback). There should be always some feedback, also if backend is down or similar.

I think it has nothing to do with the report, but rather with the crashed backend. I'll have a look what I can do for such cases. I think they are a bit tricky because there is no response of the server. Maybe I can work with a global timeout function.

**Comment by markus2330** [comment]
> I thought it might be better to have this function a bit hidden so we don't get flooded with issues. Do you think the icon alone is not enough to get attention?

I would suggest to not hide it, at the moment we have a *massive* problem of people getting frustrated with bugs but not reporting them. When we get spammed, we can change it back.

> And what color do you suggest? Orange?

What about the same color github uses for creating new issues? (green)

> Dynamic duration for longer texts doesn't seem to work

If it is long enough, there should be no issue.

> Haven't thought about creating snippets from a conversion yet (is it really a usecase?), but definitely only a minor change. The reason I have it in the top menu is that it requires a login (and permissions). An alternative would be to move it to the second menu on the right side (administration stuff is there at the moment, but ofc you didn't see it without the necessary rank yet).

It is about optimizing the flow so that as much quality snippets as possible are created. But you are right, if the workflow does not support registering/login and then continuing uploading the snippet, the effect might be very low. If it does, it might be a very good place for involving people into the sharing platform.

> I think I'll move it to the second menu and leave space in the top menu for a profile/settings link. What do you think?

As I edited above your current solution might be very fine if there is a nice workflow from conversion -> sharing. If this workflow is not possible (too much effort), we can rethink this problem together with the design of the menu hierarchy.

> Maybe I can work with a global timeout function.

Yes, even if we restart and monitor the service, there is always the possibility of malfunction where there is no response at all.

**Comment by Namoshek** [comment]
> I would suggest to not hide it, at the moment we have a massive problem of people getting frustrated with bugs but not reporting them. When we get spammed, we can change it back.

Ok, will change.

> What about the same color github uses for creating new issues? (green)

Personally, I would not go and look for a green button when I encounter a problem. On GitHub you are in the "Issues" section when you want to create a new entry and therefore it is fine if the button is green (common practice to have the button for new entries green). But on our page it is more an issue, so I would only decide between orange and red to be honest. What is your problem with the current red?

> As I edited above your current solution might be very fine if there is a nice workflow from conversion -> sharing. If this workflow is not possible (too much effort), we can rethink this problem together with the design of the menu hierarchy.

I totally understand you, but if you convert a snippet, isn't it then the format you had initially on your hands that should be shared (because this seems to be the original format of the config)? Sharing the same snippet in various formats doesn't seem to be useful at all (we already cover that use case by multi-format export, so it would only spam the database).

> Yes, even if we restart and monitor the service, there is always the possibility of malfunction where there is no response at all.

I added a global interceptor that checks for error responses without an actual server response (i.e. connection issues). It then displays a globally defined error notification. Unfortunately this means I cannot really add to the message what actually failed, but I don't think that this is all that important at all. The only situation I encountered a weird message (from a users perspective) was on a page-refresh when the page tries to load the user data for the currently authenticated user, because this request is not triggered by a direct user action. But I guess we can live with that, as it shouldn't happen (often)?...

**Comment by markus2330** [comment]
> What is your problem with the current red?

It might look like "press on outmost emergency", and not "please help us and report if something that does not work". But we can ask others what they think.

> isn't it then the format you had initially on your hands that should be shared

Yes, most likely the user wants to share what he/she has on the left side.
I agree its very minor, because its unclear if users will actually have this workflow.

> Unfortunately this means I cannot really add to the message what actually failed, but I don't think that this is all that important.

Isn't it a valid assumption to say "..server outage, please try again later..". I do not think the user will care why exactly there was no reponse. I personally prefer outage due to too much traffic ;)

> But I guess we can live with that, as it shouldn't happen (often)?...

If we have a feedback cycle and fix issues soon, it should work nicely. Hopefully the people causing a crash press the "report issue" button ;)

**Comment by Namoshek** [comment]
> Isn't it a valid assumption to say "..server outage, please try again later..". I do not think the user will care why exactly there was no reponse. I personally prefer outage due to too much traffic ;)

That's not the issue. ^^
The new interceptor catches responses of every failed request, also requests that have not been triggered by an explicit user action like pressing a button (i.e. background-requests). So there might be random service-not-available messages appearing on the users screen. But as I said, it looks minor to me.

**Comment by markus2330** [comment]
> I've no problem with changing it, but green is definitely the wrong color. Then better something neutral.

Yes, the green might not fit with the other colors anyway.

> of every failed request

Can you give me examples of failed request not due to server outage? Is a return code 5xx already a failed request?

> So there might be random service-not-available messages appearing on the users screen.

Yes, obviously you cannot know when the service works again without trying again and risking another timeout.

**Comment by Namoshek** [comment]
> Can you give me examples of failed request not due to server outage? Is a return code 5xx already a failed request?

The angularjs $http service considers all status codes between 200 and 299 a success; all others are considered a fail (not possible to change). Of course a failed request doesn't always imply a connection issue - that's why I'm handling this error separately (actually angular returns status code -1 if the server did not respond / was not reachable /  a timeout occured, so this check is straight forward. But it makes more sense to check it only one time in an interceptor than for every single request, which would only give slightly more context info for a high price).

> Yes, obviously you cannot know when the service works again without trying again and risking another timeout.

I think the $http service doesn't even wait for the request to time-out if the server could not be reached at all. The error appears quite instantaneously when the server is down, at least from what I experienced.

**Comment by markus2330** [comment]
Is there any open question? (Or why is it waiting for decision?)

**Comment by Namoshek** [comment]
It can be closed, so far everything seems decided or resolved.

**Comment by markus2330** [comment]
Thanks!

In the top post there is a list with two unresolved items:

- [ ] create snippet based on input or output of the snippet conversion.
- [ ] try to reproduce crashes for simpleini/fstab

Maybe you can create further issues with the crashes.

**Comment by Namoshek** [comment]
I thought we had the first point already discussed and the latter is an ongoing thing. I'll make an issue for one small problem later.

**Comment by markus2330** [comment]
Yes, I also thought we had it discussed and only the tick is missing.

> I'll make an issue for one small problem later.

Thank would be great!

**Comment by Namoshek** [comment]
> Thanks, that would be great!

I couldn't reproduce the error anymore when testing with the recent changes that were done to the `simpleini` plugin. I've different versions of the plugin on my server and on my local development machine; on the server the process crashes if key names contain spaces, on my local machine all works fine. `simpleini` does now also produce relative paths and basically 1:1 the same content as `ini`, so all fine!

**Comment by markus2330** [comment]
Yes, I know the errors are sometimes sophisticated to reproduce, one character different and it might already work. Your "report issue" in the snippet converter is key for more and better bug reports. Then everyone can immediately try to reproduce it in the snippet converter and press the button to report a fully filled out issue.
