### ISSUE TITLE
Yajl - Iconv doesn't work together

### ISSUE THREAD

**Issue by krit0n** [ElektraInitiative/libelektra#1079]
While writing on the tutorials I discovered this. I imagine that one will hardly use yajl and iconv together, but maybe this is a problem that arises in other plugin combinations too.

# Describe what you wanted to do
I tried to mount a backend with the yajl and iconv plugin.
# Describe what you expected
I expected the yajl plugin to create a correct json and convert the values.
# Describe what actually happened
               $ mkdir issue && cd $_
               $ mount kdb mount /issue.json dir/issue yajl iconv from=UTF-8,to=ISO-8859-1
               $ kdb set dir/issue/a öäß
               $ cat issue.json
               {
                     "a"
               }
               $ kdb get dir/test/a
               The command get failed while accessing the key database with the info:
               Error (#77) occurred!
               Description: Yajl parser error
               Ingroup: plugin
               Module: yajl
               At: /home/kriton/Code/libelektra/src/plugins/yajl/yajl_parse.c:381
               Reason: parse error: object key and value must be separated by a colon (':')
                                            {     "a" } 
                                    (right here) ------^

               Mountpoint: dir/test
               Configfile: /home/kriton/issue/test.json

# System Information

- Elektra Version: 0.8.18

**Comment by markus2330** [comment]
Thank you for reporting, it is an interesting issue!

> I imagine that one will hardly use yajl and iconv together

The issue actually is not the combination, but yajl only supporting utf8.

I changed now the code so that the json file is generated correctly. Yajl will still fail when parsing it, but I think the error:

```
The command get failed while accessing the key database with the info:
Error (#77) occurred!
Description: Yajl parser error
Ingroup: plugin
Module: yajl
At: /home/markus/Projekte/Elektra/current/src/plugins/yajl/yajl_parse.c:381
Reason: lexical error: invalid bytes in UTF8 string.
                          {     "a": "����" } 
                     (right here) ------^

Mountpoint: dir/issue
Configfile: /home/markus/issue/issue.json
```

is much clearer about what is going on. Additonally I documented the restriction.

I am afraid that there is no easy solution to detect this problem during mount time. A generic solution to detect feature interaction such as system's locales or the iconv plugin with "wrong" `to` paramter would be required.

Please reopen if you the problem is not fixed for you.
