### ISSUE TITLE
opening configuration with 'kdb editor <path> ini' purges metadata

### ISSUE THREAD

**Issue by krit0n** [ElektraInitiative/libelektra#1093]
# Describe what you wanted to do
I opened a `ni` file with the kdb editor.

# Describe what you expected
I expected that the file stays unchanged if I just open the file.

# Describe what actually happened
    $ sudo kdb mount example.ni user/example ni
    $ kdb set user/example/key value
    $ kdb setmeta user/example/key metakey metavalue
    $ cat $(kdb file user/example)
    ;Ni1
    ; Generated by Nickel Plugin using Elektra (see libelektra.org).

    key = value

    [key]
    metakey = metavalue

Now the error happens:

    $ kdb editor user/example ini <--- just open file, don't edit it
    $ cat $(kdb file user/example)
    ;Ni1
    ; Generated by Nickel Plugin using Elektra (see libelektra.org).

    key = value

    [key]
     ini/key/number = #0
     parent = user/example
     order = #0

# System Information

- Elektra Version: 0.8.18

**Comment by markus2330** [comment]
Thanks for reporting the issue!

I suppose you already know that the error would not happen when you use `kdb editor user/example ni` or once we have #1025.

But you are right, without even saving the content of the editor it is unexpected that the file content gets imported into KDB. Please reopen if the issue is not fixed.
