### ISSUE TITLE
kdbGet with cascading key yields too many results

### ISSUE THREAD

**Issue by Namoshek** [ElektraInitiative/libelektra#1152]
I think it is counter-intuitive that `kdbGet()` yields several equal keys from different namespaces when using a cascading key as parentKey. E.g. for `/sw/elektra/restbackend` I get
```
dir/sw/elektra/restbackend/something/here
spec/sw/elektra/restbackend/something/here
system/sw/elektra/restbackend/something/here
user/sw/elektra/restbackend/something/here
```
If you know what key you need, `ksLookup` solves the problem for you. But if you want to iterate a keyset and do something with it, you get way too many keys. Because they are not sorted by namespace, you'll also end up with overrides from lower namespaces if you do not filter them in some way (see above).

There seems to be some sort of solution for the issue with [keysetget.hpp](../blob/master/src/bindings/cpp/include/keysetget.hpp), but I think that it is not sufficient, because it does not solve the issue for the `spec` namespace; or in other words it seems to not create keys for default values in spec (or something like that).

Maybe the issue could be solved together with the "default-values from spec problem"?

**Comment by markus2330** [comment]
Thank you for reporting the issue here!

> several equal keys from different namespaces

You are right, that is an important concept from Elektra that is not well explained (physical vs. logical view of configuration). http://tree.libelektra.org/doc/help/elektra-cascading.md does not really mention it neither are there any hints in the API description (in particular not where iteration is explained).

>  But if you want to iterate a keyset

Yes, currently the iteration API is really low-level and gives you every physical key.

If your application defines every key via spec you can simply *only* use spec keys.
Otherwise, you need quite some code to handle every case.

An API that would solve the problem quite elegantly would be a hierarchical nesting of the logical keys as done for python in http://tree.libelektra.org/src/tools/gen/support/nested.py. But we do not have it yet.

> they are not sorted by namespace

What do you mean here? They are sorted by namespace.

> does not solve the issue for the `spec`

As long default keys do not get added by `kdbGet` this is a bug.

> Maybe the issue could be solved together with the "default-values from spec problem"?

We could add every logical key within the keyset, which would allow you to iterate over the logical keys. The problem there would be that logical keys never get transferred back to the key database (to which file should they? It is the namespaces purpose to tell!) Additionally, you could easily create mismatches between what a cascading lookup should yield and the value of the logical key.

But we certainly need to clarify these topics before releasing 1.0. Thanks again for writing this up!

**Comment by Namoshek** [comment]
> If your application defines every key via spec you can simply only use spec keys.

You mean filtering all spec keys, iterating over them and using `ksLookup()` for each one?

> What do you mean here? They are sorted by namespace.

Oh yeah, sure, as the keys are sorted, they are also sorted by namespace. But the namespaces itself do not follow the override order. Because `u` comes after `d` in the alphabet, the `user` namespace will override the `dir` namespace if you simply iterate over the keyset to find what you need (or to transform and set the values somewhere else). If we had a keyset like
```
spec/sw/elektra/restbackend/something/here
system/sw/elektra/restbackend/something/here
user/sw/elektra/restbackend/something/here
dir/sw/elektra/restbackend/something/here
proc/sw/elektra/restbackend/something/here
```
we could iterate over it and in the end we had the right values because the namespace with highest priority comes last.

> But we certainly need to clarify these topics before releasing 1.0. 

Yes, it could also be with an additional wrapper for `kdbGet()` that does it for you. Creating cascading keys from the other keys sounds like it could work.

**Comment by markus2330** [comment]
> You mean filtering all spec keys, iterating over them and using ksLookup() for each one?

Filtering is not really necessary, simply iterate over everything, ignoring everything but spec. In any way, doing `ksLookup` for each one is of vital importance.

> we could iterate over it and in the end we had the right values because the namespace with highest priority comes last.

No, that is not the whole story: `ksLookup` does more: it allows to ignore namespaces and also handles symlinks. Applications should not try to workaround `ksLookup`, otherwise it will be impossible to get consistent behaviour between applications.

> Creating cascading keys from the other keys sounds like it could work.

They help in the issue that `ksLookup` might modify the keyset, but you will always need a `ksLookup` to get to the virtual keys.

**Comment by Namoshek** [comment]
> Filtering is not really necessary, simply iterate over everything, ignoring everything but spec. In any way, doing ksLookup for each one is of vital importance.

Sure, iterating instead of filtering works too. But I have to do a second iteration as well, because I can't expect every key to have a spec key (cppcms keys). My solution works, just have to fix another issue before I can push it.

**Comment by markus2330** [comment]
> I can't expect every key to have a spec key

Yes, less assumptions are better. There is also not really a reason to not do a cascading lookup for every key.

Anyway, you brought up a very good point. Most developer want this solved on higher level and directly work with their datatypes, with arrays, and with hierarchical structure.

Hopefully, @domhof will work on this topic and implement such APIs.

Maybe you can elaborate a bit more on how you like the json::value interface (it is hierarchical structured, has arrays and has typed access). So it is a candidate for how we could design our higher-level interface.
