### ISSUE TITLE
Problem with tutorials

### ISSUE THREAD

**Issue by eschnett** [ElektraInitiative/libelektra#1189]
I am looking a libelektra, in particular at the tutorials. I want to go through the tutorials to learn some first steps. The main README points me to https://github.com/ElektraInitiative/libelektra/tree/master/doc/tutorials .

This page suggests to go through three particular tutorials: Namespaces, Cascading, and Mount Configuration Files. Here I provide some feedback on these tutorials:

In the "Namespaces" tutorial, there are graphics that are not displayed by my browser, e.g. the figure after the "kdb set" example, or the figure labelled "At this point the key database should have this structure".

The tutorial requires me to use `sudo`. I would much prefer a tutorial where this was not the case; I don't like evaluating software with root permission. In this case, simply changing the examples should work.

I also see that the tutorials create configuration settings, but they don't clean up. I am left with useless configuration settings. After looking around in my home directory, I concluded that deleting `~/.config/default.ecf` should do the trick.

I did not enter any of the sudo commands, since this seems much too dangerous -- any error I make in the tutorial could destroy my laptop's configuration. For example, playing with `/etc/hosts` could destroy my network settings.

Maybe a "sandbox mode" would be convenient, if a tutorial that changes important system configuration settings is important?

I don't understand why mounting `/etc/hosts` requires `sudo` privileges. Why can't I mount it read-only? Presumably, many applications would run without `sudo` privileges, and still want to access system configuration files. This should be explained in the tutorial.

**Comment by markus2330** [comment]
Thank you for your detailed analysis! We really appreciate your help, but it will take some time to thoroughly fix the issues.

> In the "Namespaces" tutorial, there are graphics that are not displayed by my browser

This will be resolved with the webpage we are developing:
https://web.libelektra.org/tutorials/namespaces
It shows the svg images and also renders everything else nicer.

> The tutorial requires me to use sudo. I would much prefer a tutorial where this was not the case; I don't like evaluating software with root permission. In this case, simply changing the examples should work.

This is actually a larger issue. We are thinking about how to mount as non-root (see #1074) but it has wide-reaching consequences with (ironically) severe consequences for security if done in naïve ways. (Mostly because it allows you to inject code using `LD_PRELOAD`.).

Because `kdb mount` needs root anyway we thought modifying `/etc/hosts` is a realistic example (and goes beyond pointless manipulation in different configuration file syntaxes). Once we have `kdb mount` without root, we certainly will also provide examples that do not need `sudo`.

> I also see that the tutorials create configuration settings, but they don't clean up.

Sorry about that. Our tutorial checker currently does not check if the tutorial correctly undid everything (see #1132).

> I concluded that deleting ~/.config/default.ecf should do the trick.

Exactly. Doing `kdb rm` on the keys will also remove the files.

> I did not enter any of the sudo commands, since this seems much too dangerous -- any error I make in the tutorial could destroy my laptop's configuration. For example, playing with /etc/hosts could destroy my network settings.

We use `kdb set` on hosts regularly and the validation should actually not let you do something harmful. But you are right, there is some danger, e.g. one could remove `localhost`. (We actually could avoid even that, but there might actually be usecases to have non-standard localhosts.)

**Comment by markus2330** [comment]
Thank you, we vastly improved the tutorials with automatic checks.
