### ISSUE TITLE
ronn: precompile man pages for releases

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1211]
It seems to be a major issue to install ronn (for both CentOS and brew) in the package specific ways (not using `gem`).

I propose that we already compile the man pages and to include them either

1. into the repo itself, or
2. into the release .tar.gz

What do you think?

**Comment by sanssecours** [comment]
Including the man pages in the repository sound like a good idea, since it would allow us to drop the `ronn` dependency in the [Homebrew formula](https://github.com/ElektraInitiative/homebrew-elektra/blob/master/Formula/elektra.rb) altogether. This would remove the last two of the three problems mentioned in [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/pull/7850#issuecomment-267851986):

> There's 
> • too many things here that need to be compiled with custom options, 
> • use paths and
> • needing a Gem 
> for this to be a good fit for homebrew/core…

.

**Comment by markus2330** [comment]
Ok, then we should have it directly in the repo, so that it also works with the master build?

What is meant with the first two points?

**Comment by sanssecours** [comment]
> Ok, then we should have it directly in the repo, so that it also works with the master build?

Yeah that would be great, since then `brew install --HEAD elektra` would also install the man pages, even if the user did not install `ronn`.

> What is meant with the first two points?

• **“Too many things here that need to be compiled with custom options”:** I think [Mike](https://github.com/MikeMcQuaid) means that the formula provides too many switches for optional dependencies (see below).

  ```
  elektrainitiative/elektra/elektra: stable 0.8.19 (bottled), HEAD
  Configuration Framework
  https://web.libelektra.org
  Not installed
  From: https://github.com/ElektraInitiative/homebrew-elektra/blob/master/Formula/elektra.rb
  ==> Dependencies
  Build: cmake ✔, discount --with-fenced-code ✔, doxygen --with-graphviz --with-llvm ✔
  Optional: augeas ✔, boost ✔, dbus ✔, libgit2 ✔, lua ✔, qt5 ✔, yajl ✔
  ==> Requirements
  Build: ronn (ruby module) ✔
  ==> Options
  --with-augeas
  	Build with augeas support
  --with-boost
  	Build with boost support
  --with-dbus
  	Build with dbus support
  --with-libgit2
  	Build with libgit2 support
  --with-lua
  	Build with lua support
  --with-qt5
  	Build with qt5 support
  --with-yajl
  	Build with yajl support
  --HEAD
  	Install HEAD version
  ```

• **“Use paths”:** Currently the formula [inherits the environment](https://github.com/ElektraInitiative/homebrew-elektra/blob/master/Formula/elektra.rb#L15) (`PATH`) of the current user. I enabled this option, since otherwise building the man pages would not work if the user installed `ronn` via [rbenv](https://github.com/rbenv/rbenv).

**Comment by markus2330** [comment]
Ahh okay, so removing ronn as deps would solve two of the issues ;)
So we definitely should do it, the task also shouldn't be too hard.

Another option we have is to let the build server compile it and download the man pages during installation (when ronn is missing)?

> formula provides too many switches for optional dependencies

Strange, they are only 8 (which are not many?) and they all can be ignored without problems (if you do not need them)? We should rename them to make more clear what they do, e.g. `--with-gui` instead of `--with-qt5`? Maybe you should look into other software with many compile time choices how brew handles them.

I would rather see `--with-graphviz --with-llvm` for doxygen as problem as it might conflict with already existing doxygen installations.

**Comment by sanssecours** [comment]
> Ahh okay, so removing ronn as deps would solve two of the issues ;)
> So we definitely should do it, the task also shouldn't be too hard.

That would be great.

> Another option we have is to let the build server compile it and download the man pages during installation (when ronn is missing)?

I think that would work, but it also makes things more complicated. I would prefer if we include the man pages in the repository.

>> formula provides too many switches for optional dependencies

> Strange, they are only 8 (which are not many?)…

I would say so too, on the other hand even the formula for Qt 5 only has 7 switches.

> … and they all can be ignored without problems (if you do not need them)?

Yes.

> We should rename them to make more clear what they do, e.g. `--with-gui` instead of `--with-qt5`?

I changed the name of the options `--with-qt5` and `--with-libgit2` to `--with-gui` and `--with-gitresolver`. The other names look fine, especially since they provide important information about the required dependencies. 

I also think it is not common to change the name of these switches at all. I searched other formulas and not a single one of them uses `Dependency.new` directly. I might have overlooked an other way to change the name of the switches though.

> I would rather see `--with-graphviz --with-llvm` for doxygen as problem as it might conflict with already existing doxygen installations.

You might be right. Maybe what [Mike meant](https://github.com/Homebrew/homebrew-core/pull/7850#issuecomment-267851986) with “too many things here that need to be compiled with custom options” is that we require that `discount` was built with the the option `--with-fenced-code` and that `doxygen` was built with the options `--with-graphviz --with-llvm`. However, I do not think that these dependencies are that big of a problem, since we only require them at build time.

**Comment by markus2330** [comment]
> I would prefer we include the man pages in the repository.

Ok, then decided. Then we also need a build job that checks if all man pages are up-to-date. (Similar to if all code was reformatted). Thus we need a new release to make it useful for homebrew, the ticket is not really urgent, is it?

> `--with-gitresolver`

Maybe this confuses people even more. What about `--with-dep-plugins` which adds all plugins that have additional dependencies? (Which are not in hombrew core?)

> I also think it is not common to change the name of these switches at all.

Maybe it is better to group instead of rename them. (like with `dep-plugins`).

>  `discount --with-fenced-code`

This is a small thing and really is an essential feature to actually get a nice docu within qt-gui (without qt-gui we do not need it anyway, maybe the deps were wrong there?), but

> `--with-graphviz --with-llvm`

is a huge dep and actually not really necessary.

> However, I do not think that these dependencies are that big of a problem, since we only require them at build time.

If their build agents need to recompile doxygen every time, it might be a big problem.

Maybe it was only a communication problem and we should state more clearly what the deps are for and that they are only build time.

**Comment by reox** [comment]
Sorry, i do not have a real oppinion on that topic. But i would prefer to have them in the git repo as well. In this case you can download the tar's from github as well and compile without having ronn installed.

**Comment by markus2330** [comment]
Ok, thanks. Then we will do just that!

**Comment by sanssecours** [comment]
> Maybe this confuses people even more. What about --with-dep-plugins which adds all plugins that have additional dependencies? Maybe it is better to group instead of rename them. (like with dep-plugins).

I added the switch `--with-dep-plugins` in commit [31bf3e19](https://github.com/ElektraInitiative/homebrew-elektra/commit/31bf3e19). The text below shows the current output of `brew info elektra`.

```
elektrainitiative/elektra/elektra: stable 0.8.19 (bottled), HEAD
Configuration Framework
https://web.libelektra.org
Not installed
From: https://github.com/ElektraInitiative/homebrew-elektra/blob/master/Formula/elektra.rb
==> Dependencies
Build: cmake ✔, doxygen ✔
Optional: augeas ✔, dbus ✔, libgit2 ✔, boost ✔, yajl ✔, lua ✔, qt5 ✔
==> Requirements
Build: ronn (ruby module) ✔
==> Options
--with-dep-plugins
	Build with additional plugins: augeas, dbus, gitresolver, tcl, yajl
--with-gui
	Build with gui support
--with-lua
	Build with lua support
--HEAD
	Install HEAD version
```

> (Which are not in hombrew core?)

Currently the formula does not specify any dependency that is not in [homebrew/core][]. Do you have some specific dependency in mind?

> This is a small thing and really is an essential feature to actually get a nice docu within qt-gui (without qt-gui we do not need it anyway, maybe the deps were wrong there?), but…

Oh, I just assumed we needed `discount` at build time too. I removed `discount` from the list of build dependencies in commit [55fb0ce5](https://github.com/ElektraInitiative/homebrew-elektra/commit/55fb0ce5).

> …but `--with-graphviz --with-llvm` is a huge dep and actually not really necessary.

Okay, I removed the switches in commit [1d85edc5](https://github.com/ElektraInitiative/homebrew-elektra/commit/1d85edc5).

> Maybe it was only a communication problem and we should state more clearly what the deps are for and that they are only build time.

I guess we could try to move the formula into [homebrew/core][] a second time, after we remove the dependency for `ronn` and release Elektra 0.8.20.

[homebrew/core]: https://github.com/Homebrew/homebrew-core

**Comment by markus2330** [comment]
> I added the switch --with-dep-plugins in commit 31bf3e19. The text below shows the current output of brew info elektra.

That is much better! :+1: 

> Currently the formula does not specify any dependency that is not in homebrew/core. Do you have some specific dependency in mind?

libxml2, Java, Ruby, Python2+3?

> Oh, I just assumed we needed discount at build time too.

It is needed when qt-gui is built. I do not know how the optional dependencies need to be specified in such cases.

> I guess we could try to move the formula into homebrew/core a second time, after we remove the dependency for ronn and release Elektra 0.8.20.

Exactly, but maybe even a third time 0.8.21 and so on ;) Sometimes you need a lot of patience for such things.

Important is that you always say that you addressed everything which was said the last time.

**Comment by sanssecours** [comment]
>> Currently the formula does not specify any dependency that is not in homebrew/core. Do you have some specific dependency in mind?

> libxml2, Java, Ruby, Python2+3?

All of these dependencies (except for Java) are available via [homebrew/core](https://github.com/Homebrew/homebrew-core). [Java](https://github.com/caskroom/homebrew-cask/blob/master/Casks/java.rb) is available via Homebrew Cask, a place for binary only formulas.

**Comment by markus2330** [comment]
Thanks for looking it up! Having python would be nice, but maybe we should be very conservative for the next PR to get it accepted.
