### ISSUE TITLE
add depth/levels option to kdb ls

### ISSUE THREAD

**Issue by tom-wa** [ElektraInitiative/libelektra#1237]
there should be a way to limit the depth of kdb ls (and probably kdb export too)

**Comment by markus2330** [comment]
Thanks for the input! Can you please also describe the usecase you think of?

Its obvious why we need a list of keys that are direct below (so to say "non-recursive"), but why do we need other depths?

Btw. the issue might be related to #1167

**Comment by tom-wa** [comment]
keys direct below would the the primary usecase, other levels would be needed for special usecases (and most likely used together with / parsed for some other option like the actual keybasename) 

kinda related: list/output only keynames having a metakey or keybasename specified as a ls or export option

**Comment by markus2330** [comment]
> other levels would be needed for special usecases (and most likely used together with / parsed for some other option like the actual keybasename)

Can you name one of the special usecases? If there are none, we should rather go for recursive/non-recursive which is a more convenient interface than a `--max-depth=<number>`.

> kinda related: list/output only keynames having a metakey or keybasename specified as a ls or export option

Yes, it is related: `max-depth` is something which I would expect in such a query interface, but not so in a ls/list interface.

Your use case can be implemented quite easily as plugin, we would only need a way to specify an arbitrary number of plugins to `kdb export`, see suggestion in #1229.

Btw.  #867 is related: it suggests that we allow to have plugins as filter, also on API level. But #867 is actually not needed to export using a filter.

**Comment by markus2330** [comment]
@e1528532 should be a very easy task thus `kdb complete` already implements this feature.

**Comment by e1528532** [comment]
You are right, it was not that much effort anymore.

I was not sure if you want a max-depth or a recursive option now, but since kdb complete already makes use of max-depth and min-depth, i've tried to archieve a similar behavior for kdb ls to have a more or less uniform meaning of those two parameters.

This might seem a bit strange though for kdb ls. Consider `kdb ls user/test --max-depth=1`, it would give you user/test as a result (its just showing the current level that way. If you want to show the next level, you would type `kdb ls user/test/` as the last slash indicates that we want to see whats under this key. But thats how it has to be if we want the same behavior as for kdb complete.

If you make no use of the options, the output should be exactly the same as it was before, so there is no depth limitation.

See the PR #1345

**Comment by e1528532** [comment]
i think this is done already, closing before we forget this issue completely
