### ISSUE TITLE
Integrate command-line arguments and environment variables

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1252]
While code generation already considers command-line (even though it does not use the correct namespace, should be fixed, too), without code generation there is currently no automatic way to facilitate command-line arguments and environment variables.

I propose to implement the function  
`int elektraGetEnv(KeySet *ks, int argc, char ** argv, char ** envp)`

which goes through every key in `spec` and looks for meta-keys `opt`, `opt/long` and `env`. If it finds them, it will try to parse argv/envp. If the command-line argument or environment variable is available, it will add a new key with namespace `proc` accordingly.

For example, if it finds  the key of namespace `spec` (written down in ni syntax):
```
[spec/sw/elektra/restbackend/#0/current/cppcms/service/ip]
check/type=string
description=This option defines the IPv4/IPv6 IP the application should listen on.
opt=i
opt/long=ip
env=CPPCMS_IP
```
it will add `proc/sw/elektra/restbackend/#0/current/cppcms/service/ip` if:

1. `-i` was passed as command-line argument
2. `--ip` was passed as command-line argument
3. `CPPCMS_IP` is available as environment variable (in that order, so env has no effect if command-line were already there)

depending on the type (#1092), it will also use `optarg` for command-line parsing.

The description, type, default, and other info should be displayed when using `--help`.

Furthermore I propose a global plugin that calls `elektraGetEnv` (getting the argc, argv and envp from `/proc/cmdline` and `environ` on Linux, `GetCommandLine` on Windows, `_NSGetArgv` and `_NSGetArgc` on MacOSX) so that it will also work for applications not directly calling `elektraGetEnv`. This idea also plays nicely with order preserving hash map and mmap: We could always add the `proc` keys, but disable them.

Implementation should be in C, in a new library `src/libs/getenv` and a new plugin `src/plugins/getenv`.

Please comment on the proposal.

**Comment by kodebach** [comment]
### Regarding type checking

It absolutely would make sense to check, whether a command-line argument (or environment variable) matches the specified type. But I think we should actually check the whole specification, i.e. also verify `check/path` constraints for example.

The problem is that all these checks are done by plugins in the `kdbSet` stage. Because running `kdbSet` is not feasible for various reasons (expensive, needs `kdbGet` aftwards, `proc` namespace ignored, etc.), I don't see a good way to check the specification.

The only possibility I see is to create a modified version of `kdbSet` which doesn't actually store data. As well as a modified version of `kdbGet` (to enable plugins that only use `kdbGet`) which doesn't load from a file, but takes a `KeySet` and run those two functions. This might be possible through a kind of dummy storage plugin, that stores the `KeySet` it receives in `kdbSet` in memory and returns it in `kdbGet`.

But every solution to this problem will be a bit of a hack, because I think the problem actually lies somewhere else.
There are at least 20 plugins that use `kdbSet` or `kdbGet` doing some kind of check, conversion, filtering, etc. which need to be executed, if we want command line options to be 1:1 overrides of setting via `kdb set`.
The problem is that these checks and conversions cannot be run separately. The only real solution in my mind is to create a separate `kdbConvert` call for plugins which should be used for all these checks (return value indicates error) and conversions. This call would be executed before each `kdbSet` and after each `kdbGet` (a parameter would specify whether we are in read, or write mode). It could also be executed separately, as is needed for command line arguments.
This would, however, require rewriting of a lot of plugins, and should therefore probably be combined with the effort to allow more plugins at once (if we choose to create `kdbConvert`).

**Comment by markus2330** [comment]
I think I now understood what you said. Basically, Elektra has the same problem if someone modifies values directly in configuration files, without using Elektra for doing that.

Some of the validation plugins currently do not check during kdbGet, but only during kdbSet, effectively passing wrong configuration to the applications.

I currently (#1291 #868 are older thoughts) think our best way forward to fix both problems is:

- make validation plugins behave the same for kdbGet/kdbSet
- make the KDB framework to not fail on validation problems in kdbGet:
   - continue to yield the configuration, despite the error, so that admins are always able to use Elektra to fix configuration problems
   - but make the high-level API fail on such errors (as the high-level API is not suitable for admin purposes anyway and applications should never start with wrong configuration)

Let us discuss the details on Tuesday.

**Comment by kodebach** [comment]
We could introduce a new type of plugin that is called after getstorage plugins but before postgetstorage plugins. That way `getopts` would receive the whole configuration and all the check and filter plugins would always receive the results from `getopts`.

> I currently (#1291 #869 are older thoughts) think our best way forward to fix both problems is:

We should definitely do those things. I would also suggest a version of `kdb set` that accepts multiple key value pairs, so that a configuration with multiple invalid keys can be fixed easily.

**Comment by markus2330** [comment]
> that is called after getstorage plugins but before postgetstorage 

Why not directly at getstorage? (So simply as storage plugin)

> I would also suggest a version of kdb set that accepts multiple key value pairs, so that a configuration with multiple invalid keys can be fixed easily.

Yes, that would be very useful. `kdb import` and `kdb fstab` do already such things, see #1188 for discussion about `kdb fstab`.

**Comment by markus2330** [comment]
@kodebach can we close this issue?

**Comment by kodebach** [comment]
The global plugin still has to be implemented. Other than that everything described in the original issue is implemented.
