### ISSUE TITLE
kdb: Support Non-Colored Output

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1282]
# Problem Description

I decided to review pull request #1281. Since I use [fish](http://fishshell.com), a shell that currently does not support command completion for `kdb`, I created a very basic completion file called `kdb.fish`. Currently this file looks like this:

```fish
function __fish_kdb_complete
  kdb | awk '/Known commands are:/,empty' | awk '{if(NR>1)print}'
end

complete --command kdb --exclusive --arguments '(__fish_kdb_complete)'
```

. The problem with the completion command is, that `kdb` prints escape sequences to color its output. These escape sequences are currently also part of the completion:

<img width="794" alt="completion" src="https://cloud.githubusercontent.com/assets/691989/21986956/d4add5d2-dc01-11e6-92c2-54d40bd10141.png">

. I tried to call `kdb` with the option `-C` to disable color output, but unfortunately that does not work:

```
The command kdb -C is not known
…
```

. As far as I can remember the Bash completion command has the same problem. Is there an easy way to disable colored out for the command `kdb`? If there is none, could we please add an option to disable the colored output.

# System Information

- **Elektra Version:** master
- **Operating System:** macOS 10.12.2

**Comment by markus2330** [comment]
> I decided to review pull request #1281.

You should keep in mind that this PR is more about requirement gathering than something finished. Maybe you can also give hints what would be needed for the fish shell.

> The problem with the completion command is, that kdb prints escape sequences to color its output.
> Is there an easy way to disable colored out for the command kdb?

It is difficult to fix because unknown commands abort before command-line parsing starts. Thus `-C` has no effect in these early-abort situations.

> If there is none, could we please add an option to disable the colored output.

I fixed it with a new command `list-commands` which supports listing the commands without explanations and also supports `-0` and `-C`.
