### ISSUE TITLE
documentation search

### ISSUE THREAD

**Issue by e1528532** [ElektraInitiative/libelektra#1315]
While working on elektra, i often felt that it would be nice to have a documentation search function. For example i wanted to look up bookmarks but i had no idea where i should look for it on the website.
So i ended up doing `grep -rn "bookmark" *` on the doc folder of the sources, which quickly lead me to the correct document (https://www.libelektra.org/manpages/kdb). But to be more user friendly, we could include some search functionality in our website.

**Comment by markus2330** [comment]
This is quite a hard problem because (1) the structure file provides only a one-way-mapping of  real files to pages at website (it is even difficult to display where you currently are on the website, see  #1284)  and (2) not being able to easily retrieve content of the website (making use of external crawlers hard).

Furthermore, one would also expect the API docu to be integrated. (Btw. for doxygen there is `SEARCHENGINE` which easily could be turned on).

Shortly put: There was a reason why @Namoshek excluded this functionality, it is not worth the effort.

And the search engines out there already solve all the issues. Hosting something ourselves does not make much sense: we cannot compete with them.

Alternative proposal: let us upload more snippets, which would make the current search bar more useful!

**Comment by e1528532** [comment]
You are right, with google i would have found it. I usually use duckduckgo though which didn't find it per default (at least not in the top results). Should have limited it to the libelektra site by searching for "bookmark site:libelektra.org", then you also find it with duckduckgo.
Anyway, i agree that it doesn't make too much sense and a search engine does the job (if used correctly), so closing this issue.

**Comment by markus2330** [comment]
What we could do is adding google/duckduckgo/startpage links with the search phrase and the `site:libelektra.org` restrictions on the search-results page. Maybe you find a nice solution while investigating for #1251

**Comment by Namoshek** [comment]
There could actually be a solution to provide a search functionality, but it would involve adding all used documentation files completely to the structure file that is consumed by the frontend. In other words, we could change lazy loading of documentation files to eager loading by adding their content to the structure file, but this would increase its size significantly and I'm not sure if this makes everything better. I also don't know whether the browsers would perform a good/fast search or not; better search functionality itself (e.g. regex-like search) is something that we cannot provide very easily.

**Comment by markus2330** [comment]
Thanks for your input! Good to know!

But if we do it, we should do it properly with ranking of hits and so on. And I am skeptical if we really could provide added value to having links to search engines.
