### ISSUE TITLE
Essential plugins/tools/bindings

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1327]
For 1.0 we should have a more strict policy what "non-experimental" means. Please make suggestions what we should make experimental or even delete.

I would suggest:

- [ ] code generation
  - [ ] getopt code generation (to be deleted)
- [ ] plugins
  - [x] cachefilter
  - [ ] iterate
  - [x] struct
  - [x] simplespeclang
  - [ ] tcl
  - [ ] xmltool
  - [x] regexstore

@ElektraInitiative/elektradevelopers Please add further suggestions.

**Comment by markus2330** [comment]
Please also add which plugins/tools/bindings are essential and must be brought to a 1.0 state!

**Comment by sanssecours** [comment]
> I would suggest:
> - code generation
> - every new plugin by default (non-experimental at earliest after one release), e.g. date

The suggestions above make sense from my perspective. I would also mark each plugin/tool that still has known bugs before we release Elektra 1.0 as experimental.

> Please also add which plugins/tools/bindings are essential and must be brought to a 1.0 state!

My list of essential bindings would probably only include the **C bindings**. It might also make sense to put some work into the **Python bindings**, since Python seems to be the [favourite scripting](http://www.tiobe.com/tiobe-index) language of most developers today.

Elektra‘s most essential tools are probably **`kdb`** and the **Qt GUI**. As far as I can tell, both of them are already ready for an 1.0 release.

The most essential plugin in my opinion is the **default storage plugin**. I think it makes sense to still use `dump` as default storage plugin in 1.0. Later (`1.x`) we should probably replace `dump` with `ini` or another storage plugin that uses a more human readable text based format.

One last thing: I think we should also fix the problems of the **Shell Recorder** and the **Markdown Shell Recorder** in the next months. This should help us to detect and fix a lot of smaller bugs before we release Elektra 1.0.

**Comment by markus2330** [comment]
Thanks for the great feedback!

>  Later (1.x) we should probably replace dump with ini

Isn't such a migration painful for users? (Or quite expensive for us if we provide a parser that can parse both ini and dump as fallback).

> Shell Recorder and the Markdown Shell Recorder

I absolutely agree! @tom-wa is already doing everything he can, so hopefully someone else will also support these efforts.

**Comment by sanssecours** [comment]
> Isn't such a migration painful for users? (Or quite expensive for us if we provide a parser that can parse both ini and dump as fallback).

You are right. Maybe we should only change the default storage format in `2.0`. I still think changing the default format sounds like a good idea, since a lot of people edit their configuration files with a text editor. As it stands today, the `dump` format is not particularly well suited for manual editing. For example, I am pretty sure I would rather edit something like this:

```ini
key = value
```

instead of this

```
kdbOpen 1
ksNew 1
keyNew 9 6
user/keyvalue
keyEnd
ksEnd
```
.

**Comment by tom-wa** [comment]
adding keys or metadata with a text editor to dump files is even more fun ;)

i've been using the ini plugin as default storage for .. a while now, but i guess i'm the only one ? has anyone else tested it as a default storage plugin ?

**Comment by markus2330** [comment]
> I still think changing the default format sounds like a good idea

I also think so, dump only exists because it was easy to implement.
Unless you ( @sanssecours ) create a better plugin, the ini-plugin might be our best option.
When we want lcdproc people to use it, it must be mature anyway.

**Comment by markus2330** [comment]
- storage plugins that are not relative
- validation plugins that do not export validator

**Comment by markus2330** [comment]
@sanssecours wrote:
>  It might also make sense to put some work into the Python bindings, since Python seems to be the favourite scripting language of most developers today.

Any specific work you propose here?

> The most essential plugin in my opinion is the default storage plugin. I think it makes sense to still use dump as default storage plugin in 1.0. Later (1.x) we should probably replace dump with ini or another storage plugin that uses a more human readable text based format.

I fully agree, #2330

> One last thing: I think we should also fix the problems of the Shell Recorder and the Markdown Shell Recorder in the next months. This should help us to detect and fix a lot of smaller bugs before we release Elektra 1.0.

I fully agree. Something specific still missing?

Otherwise I think we can close this issue, for cleanup tasks we have #2987 now.

**Comment by sanssecours** [comment]
> Any specific work you propose here?

Nope, I did only used the Python bindings once though.

> Something specific still missing?

Proper multiline command support would be nice. However, for that we probably have to parse Shell code. I do not think that multiline support is that essential…

> Otherwise I think we can close this issue, …

Yep, I think we can close this issue too.
