### ISSUE TITLE
Prefix Key and KeySet with KDB

### ISSUE THREAD

**Issue by domhof** [ElektraInitiative/libelektra#1331]
To avoid naming conflicts, we should be careful not to use too generic names for public types, e.g. Key and KeySet in the C API. I propose to prefix them with "KDB" (KDBKey KDBKeySet).

What's your opinion on that?

**Comment by sanssecours** [comment]
> What's your opinion on that?

While I think naming conflicts in C are [very problematic](http://stackoverflow.com/questions/678254/what-should-i-do-if-two-libraries-provide-a-function-with-the-same-name-generati), I see two problems with this prefixing proposal: 

- Software developers that already use Elektra have to rename all their calls to the Elektra API. I do not think that this would make them very happy. Although this might be only a minor problem, since they can solve this issue via an regex search and replacement in their favourite text editor, or via the renaming facility of their favourite IDE.
- Prefixing is kind of useless when you have no naming conflicts. In that case naming something `KDBKey` instead of `Key` does not add any useful information at all in my opinion. I would even argue that prefixing in this case makes the code less readable.

Did you ever encounter naming conflicts yourself in C? I know them from Python, where naming conflicts are not problematic at all, since Python offers functionality to handle them properly (namespaces, renaming).

**Comment by tom-wa** [comment]
i kind agree with @sanssecours and the proposed high level api will take care of possible naming conflicts. 

i've only encountered a naming conflict once in C, and the reason was a missing guard in a header.

**Comment by domhof** [comment]
@sanssecours I've encountered naming conflicts in Objective-C a few times. There it is common to prefix classes with 2-3 letters for the same reason. It may not happen very often, but when it happens it's a PITA, especially if you elektrify an existing application that uses the term "Key" throughout the code. As for readability, I would even argue that naming types a bit more explicit after what they actually are, actually increases readability, in the sense that it is then more clear which "kind" of a Key it is.

**Comment by markus2330** [comment]
Structures do not end up as symbols in the binary, so there are always workarounds available (do not use headers in the same file or `#define` hacks). More severe would be a clash of symbols, e.g. `keyNew`. Proper prefixing would be adding a string to every function (e.g. to `elektraKeyNew`).

Some libs do a weird workaround: They `#define keyNew elektraKeyNew`, so the user uses `keyNew`, but the symbols in the binary are `elektraKeyNew`.

Some people, however, argue that C only defines symbols to be 8 characters long, so by the standard `elektra` alone would nearly use up the complete available characters.

So for your concrete proposal: The most important source of clashes `KDB` is not addressed, nor are clashes of symbols `keyNew` or kdbOpen`.

Did you check on a source search engine which of these symbols/function names really clash?

Btw. we already now `kdb.h` clashes with kerberos, thus #817 is something we definitely need to address.

**Comment by domhof** [comment]
> Structures do not end up as symbols in the binary, so there are always workarounds available (do not use headers in the same file or #define hacks). 

Yes, it's only about the header, I just think that Key as name is not so uncommon (and as a user I would be frustrated if a library used it).

> More severe would be a clash of symbols, e.g. keyNew. Proper prefixing would be adding a string to every function (e.g. to elektraKeyNew).

What was the reason not to use a shorter prefix?

> Did you check on a source search engine which of these symbols/function names really clash?

No I didn't search for every elektra symbol/function. I just wanted to discuss it in general and understand why the names where chosen this way, since after 1.0.0 they probably shouldn't be altered anymore for as long as possible.

**Comment by markus2330** [comment]
> Yes, it's only about the header, I just think that Key as name is not so uncommon (and as a user I would be frustrated if a library used it).

If it is only about the header, in C++ everything is within a namespace which allows you to use Key for other purposes, too. For C you are right...

Btw. I am not really happy about the name `Key`, because it actually is a Key/Value or  Setting and definitely not only a key, see also discussion #920

>   What was the reason not to use a shorter prefix?

Nobody came up with the suggestion.

> No I didn't search for every elektra symbol/function.

Before final decisions you should. It is an important metric.

> I just wanted to discuss it in general and understand why the names where chosen this way, since after 1.0.0 they probably shouldn't be altered anymore for as long as possible.

Exactly! We must not till 2.0 and even for 2.0 we are quite limited with changes users will accept.

**Comment by domhof** [comment]
> Btw. I am not really happy about the name Key, because it actually is a Key/Value or Setting and definitely not only a key, see also discussion #920

Exactly, actually I was thinking the same. When I first looked at the tutorials I interpreted Key as a structure that holds only the key string while in fact it also holds the value (after lookup). While it is easy to get behind this, it is still somehow misleading. The first thing that came to my mind was "Entry" (or KDBEntry), or even to split it up into two structures Key and Value (not sure if this really makes sense though...).

> Before final decisions you should. It is an important metric.

I totally agree. 🙂

**Comment by sanssecours** [comment]
> Btw. I am not really happy about the name Key, because it actually is a Key/Value or Setting…

> The first thing that came to my mind was "Entry" (or KDBEntry)…

`Entry` sounds good to me. My personal suggestion would be `Mapping`.

**Comment by markus2330** [comment]
We should also have a solution for KeySet.

- EntrySet or EntryMap is okay (but much too generic?)
- MappingSet or MappingMap does not make much sense?
- SettingSet or SettingMap also isn't brilliant.

Btw. Larry Wall (creator of Perl) argues that for such decisions the everyday meaning of words should be more important than data structure terminology.

**Comment by sanssecours** [comment]
> We should also have a solution for KeySet.

How about
  
- `Key` → `Mapping`
- `KeySet` → `Mappings`

then? The names above might be too similar though.

**Comment by markus2330** [comment]
Yes, same issue with `Setting` and `Settings`. And we wanted to use only singular for the API (see doc/DESIGN.md)

`KeyEntry` and `KeySet` would work but the improvement is too little to justify the massive changes.

To be more in line with @domhof suggestion: `KDBEntry` and `KDBSet` (or `KDBSetting`) would be another option, so:

- `KDB` → `KDBHandle` or `KDBRepo`
- `Key` → `KDBEntry`
- `KeySet` → `KDBSetting` (would need plural?)

**Comment by markus2330** [comment]
Changing these fundamental terms is too much work. It also does not provide a benefit to `#define` in cases of clashes.
