### ISSUE TITLE
handling "disabled" keys?

### ISSUE THREAD

**Issue by BernhardDenner** [ElektraInitiative/libelektra#1376]
What about having a "disabled" keys feature?

For e.g. many config files look something like
```
#
# /etc/sysctl.conf - Configuration file for setting system variables
# See /etc/sysctl.d/ for additional system variables.
# See sysctl.conf (5) for information.
#

#kernel.domainname = example.com

# Uncomment the following to stop low-level messages on console
#kernel.printk = 3 4 1 3

##############################################################3
# Functions previously found in netbase
#

# Uncomment the next two lines to enable Spoof protection (reverse-path filter)
# Turn on Source Address Verification in all interfaces to
# prevent some spoofing attacks
#net.ipv4.conf.default.rp_filter=1
#net.ipv4.conf.all.rp_filter=1
...
```

We could treat all "commented" keys as disabled keys and enable them on demand.

But I'm not sure how to flagging a key as disabled?
* if only a special metadata flag is added, an application not aware of this feature will "oversee" this?
* modification to the keyname, e.g. add and `.` (dot) in front of it?
* ...

## Problems
* sometimes config files do not follow this rule completely, e.g. my sysctl.conf contains on "miss behaving" line
* application has to be aware of this
* API changes?

**Comment by markus2330** [comment]
Thank you for starting the proposal!

I am afraid it will be impossible to guess if a user wanted to uncomment a key, or is simply mentioning another key in the comment.

Some ways we can and could offer (without needing the application to be aware of it):

## Using Spec

Instead of including all keys commented out in config files, the spec could contain "templates" (actually `description` and `default` already contain what is currently usually written commented out in config files). Tools then simply add (all of) these templates to a config file, if someone needs it. For example, we could add a feature: `kdb editor --start-from-spec system/sysctl` and the user gets a file, similar to your example, generated.

Distributions could keep `/etc` empty.

## Hiding/Disabling keys

Instead of actually commenting out keys, one could simply add meta data that some keys are deactivated/hidden. So distributions would change the config files they deliver to something like:

```
# Remove the line below to to stop low-level messages on console
#@META disabled
kernel.printk = 3 4 1 3
```

Then the parsers would know to which key the comments refer to. (Which is hardly possible if every option is commented out).

Btw. the difference between hiding and disabling is: `hidden` is a plugin that removes all keys that start with `.`, disabling is a not-implemented feature that would make `ksLookup` not find keys.

Hiding would also work without any meta-data:
```
# Remove the dot before kernel to stop low-level messages on console
.kernel.printk = 3 4 1 3
```

## Using special comments

Iirc this is already done for samba. The idea is simply that commenting out keys is done differently than writing comments. We could write a plugin that transforms `comment/#` with the special comments to disabled keys.

For example:
```
# Uncomment the following to stop low-level messages on console
;kernel.printk = 3 4 1 3
```

We *could* (I would not recommend it) make different comments dependent on indentation. At least it seems to be that way in `/etc/sysctl.conf` (no space after `#` indicates it is a disabled key)

**Comment by markus2330** [comment]
@kodebach here is the proposal for inactive keys. As discussed, for 1.0 we will remove keyIsInactive.
