### ISSUE TITLE
ini plugin allow empty values

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#139]
inih claims to be compatible to Python's ConfigParser

The ini plugin, however, yields following error:

   Error (#98) occurred!
   Description: invalid ini syntax

on files that have keys without value, e.g.

    [sec]
    a = b
    def
    c = x

The line with "def" yields the error. Python's ConfigParser accepts this value (even though it crashes on some special cases)

Expected outcome:
create a key "def" without a value.

Is this a problem of inih or the ini plugin?

**Comment by fberlakovich** [comment]
Yes, it turns out to be a parser limitation. The inih parser expects `=` or `:` after a key name. Therefore an empty value would have to look like (untested, I just studied the inih code)
```
[section1]
emptykey =
```
I have never seen INI files making use of this kind of syntax. However, if you would like I could patch the inih parser used by the ini plugin. Yet another patch won't hurt because we don't use the upstream version anyway.

**Comment by markus2330** [comment]
Hello,

you wrote:
> I have never seen INI files making use of this kind of syntax. However, if

At first, I also found the syntax very strage. But it allows you to write kind 
of literal configuration files (everything is a "comment" not having an = in its 
line) which is now used in a project heavily.

> you would like I could patch the inih parser used by the ini plugin. Yet
> another patch won't hurt because we don't use the upstream version anyway.

Only do patch if you also find the feature useful and the change in the code 
maintainable. Changing something like that is quite an intervention in a 
parser.

Other features like the new comments (for more syntax preserving) are more 
important.

**Comment by markus2330** [comment]
Decided not to do it. Please document it in README.md (which features are and are not supported)
