### ISSUE TITLE
JSON error in webinterface

### ISSUE THREAD

**Issue by reox** [ElektraInitiative/libelektra#1424]
I get this error message popping up:
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

is there a way to debug this more?

i added the single instance fix both with env variable and in kdb but it seems not to work...
Using now nodejs 6.10.0

**Comment by omnidan** [comment]
@reox I am `kdb export`ing to a temporary buffer file, because there are no official node.js bindings yet, and there was an issue with exporting/importing through stdout on linux. This buffer file should be in `/tmp/elektra-web.buffer.json`. You can try checking the contents of this file, or deleting it and then restarting elektra-web.

Sometimes there is an issue with it not being fully written, although this very rarely happened to me in developer mode, and never happened in production mode.

If it persistently happens, please let me know your specs (OS + version, elektra version, ...) so I can try to reproduce it.

**Comment by reox** [comment]
hi!
The file looks like a empty json file to me:
```
sebastian@pcs:~$ cat /tmp/elektra-web.buffer.json
{

}
sebastian@pcs:~$ hd /tmp/elektra-web.buffer.json
00000000  7b 0a 0a 7d 0a                                    |{..}.|
00000005
```

Maybe because there is not much configuration else?

**Comment by omnidan** [comment]
@reox should be fine then - does this error happen every time and persist through refreshes? which OS and elektra version is it running on?

**Comment by markus2330** [comment]
@omnidan Are you sure you do not run `kdb` concurrently with the same buffer? Why not use fresh names for every buffer and unlink the file afterwards?

**Comment by reox** [comment]
@omnidan added the information in the last comment. No it comes on every action. Maybe this is a problem because of the nginx reverse proxy? Do i need to pass some extra arguments? I just did `proxy_pass`, nothing else.

**Comment by markus2330** [comment]
@omnidan And please improve the error messages, "SyntaxError: Unexpected token < in JSON at position 0" isn't something a user should read.

**Comment by reox** [comment]
When I start it with the INSTANCE set, should there be a button Add Instance? I also set the corresponding elektra key, but there is no effect... Is it possible this bug is due to some missing settings?

**Comment by markus2330** [comment]
In any case, the error message is really troublesome. @omnidan Please add some checks if everything is as expected and give better error messages.
