### ISSUE TITLE
spec implicit global position

### ISSUE THREAD

**Issue by tom-wa** [ElektraInitiative/libelektra#1499]
it seems like the spec plugin currently only gets called after all normal (validation) plugins were called which doesn't make much sense because  the validation plugins need the metadata copied by spec
with FOREACH everything works as expected

**Comment by markus2330** [comment]
So currently spec+validation plugins do not work together?

Is this a step towards #1291?

**Comment by tom-wa** [comment]
i think there are some issues with the placements and init/foreach/maxonce but i'm not really sure. i just noticed that by default spec gets called after all other postgetstorage plugins, with foreach before (+ after when also using postgetcleanup as placement)

**Comment by markus2330** [comment]
@mpranj Can you comment on this?

We certainly need documentation what the placements are for and test cases which specify how they should behave.

**Comment by mpranj** [comment]
I'm pretty sure there are some issues since it is unfinished. Example: `init/deinit/maxonce` doesn't exist at all for `postgetstorage` and `postgetcleanup`.

Regarding `foreach`: these plugins are called exactly like you implemented it @tom-wa. I just did some refactoring for the global plugins mounting and then extended it to support the positions/subpositions. I don't think I changed the semantics of any position that was already there.

The proposal (`doc/decisions/global_plugins.md`) does not specify the ordering of plugins inside one position. Maybe I'm misunderstanding your problem, but we could add an additional position for spec to make sure it is called before the other plugins. Alternatively we could enforce mounting spec at the first position (exploiting the list plugin).

When I `kdb global-mount timeofday` it inserts spec still at `#0` and timeofday at `#1` inside the list plugin, but I never checked which one is really called first.

Regarding the placement names and semantics, I tried to clarify that in [#677](https://github.com/ElektraInitiative/libelektra/issues/677#issuecomment-228151842). Maybe it's better to start with a short list of global positions that are very clear in their meaning. It's trivial to add positions later if you know where you need them.

If you could give me a more concrete example of what you did, what you expected to see and what actually happened I can look a bit more into it.

**Comment by tom-wa** [comment]
>Example: init/deinit/maxonce doesn't exist at all for postgetstorage and postgetcleanup.

that might be the issue, because spec gets mounted in [mount.c](/ElektraInitiative/libelektra/blob/master/src/libs/elektra/mount.c#L371) using `MAXONCE`

>The proposal (doc/decisions/global_plugins.md) does not specify the ordering of plugins inside one position. Maybe I'm misunderstanding your problem, but we could add an additional position for spec to make sure it is called before the other plugins. 

the global `postgetstorage` plugins need to be called before ( `postgetstorage` ) and after ( `postgetcleanup` ) the other (local ?) backends `postgetstorage` plugins are called

**Comment by mpranj** [comment]
Thanks! I'll add the `MAXONCE` then and check whether that fixes the problem.
