### ISSUE TITLE
Try out randoop

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1506]
With the Java binding we can try https://randoop.github.io/randoop/

**Comment by e1528532** [comment]
I can try it out, is that ok?

**Comment by markus2330** [comment]
Yes, that would be great!

**Comment by e1528532** [comment]
After messing around a bit to make it work (I'll document it soon) with our bindings, i managed to make it produce some errors. Unfortunately errors in the sense that this creates a SIGSEGV in our native code thus terminating the JVM the hard way. The bad thing: randoop didn't log the sequence then that caused this errors in case of a JVM error, as it seems to be built to log after each test case.

So I finally came up with the idea of logging whats going on in the bindings by including a logging framework and write it to a file (in the bindings), so i can see the sequence of commands invoked by randoop independent of the jvm crash (by having the logger flush after each invocation, and always logging the method before each call to the native function of elektra).

Turned out the issue was by creating a Keyset like this (so no KS_END specified either, as randoop doesn't care about such details, but it also happens when you specify it at the end of the varargs):

`KeySet * ks = ksNew (10, -1, -2);`

Its probably not intended to be called that way i know, but crashing with a sigsegv is not nice.

As randoop always runs in the same issue again and again then we should maybe think about a way to fix this. While it would normally resume upon errors, it doesn't seem to be able to deal with JVM crashes caused by native code. I bet there are much more similar errors that it will discover by invoking methods with random input then.

**Comment by markus2330** [comment]
Thanks for checking!

> Its probably not intended to be called that way i know, but crashing with a sigsegv is not nice. How should we handle such cases?

It cannot be fixed in C, but we can fix it in the Java Code. For example, always appending `KS_END` and `KEY_END`, or/and by checking if what we got is valid and throwing an exception if it is not.

> While it would normally resume upon errors to find more, it doesn't seem to be able to deal with JVM crashes caused by native code.

Maybe there is an option to spawn a new JVM for the tested code? Hopefully no other crashes will happen once you validate the vaargs, so maybe simply try that first.

**Comment by e1528532** [comment]
I see. So the arguments given to keyset are interpreted as Key pointers. And if i give a random pointer like randoop does it is going to fail. There is no real way to check if the pointer is an actual elektra key right?

It is possible to add KEY_END automatically though at least to the java bindings, if we want such behavior.

I think the best way to resume is to simply exclude this creation method with varargs from the randoop tests so it cannot create keysets with arbitrary key pointers.

I think i will alter the code a bit to be able to use the logging framework anyway, as it seems to be the only way to reconstruct the cases which cause a jvm crash. I think i'll make a separate maven project for that which extends the actual bindings, overriding each method call of the classes and adding logging that way. Basically as some kind of aspects This way we can keep the logging framework requirement and the additional logging overhead away from the bindings but use it for randoop tests.

**Comment by markus2330** [comment]
> I see. So the arguments given to keyset are interpreted as Key pointers. And if i give a random pointer like randoop does it is going to fail. There is no real way to check if the pointer is an actual elektra key right?

Why do we use `final Object... args` in the signature, we could already limit to `Key` there?

> It is possible to add KEY_END automatically though at least to the java bindings, if we want such behavior.

Sounds useful. And checks for the other cases. Crashing the JVM certainly is not the wanted behavior!

> I think the best way to resume is to simply exclude this creation method with varargs from the randoop tests so it cannot create keysets with arbitrary key pointers.

Why have `Object` as argument at all? Why are "Helper constructor" public?

Excluding methods should be last resort.

> I think i will alter the code a bit to be able to use the logging framework anyway, as it seems to be the only way to reconstruct the cases which cause a jvm crash. I think i'll make a separate maven project for that which extends the actual bindings, overriding each method call of the classes and adding logging that way. Basically as some kind of aspects This way we can keep the logging framework requirement and the additional logging overhead away from the bindings but use it for randoop tests.

I do not like logging in the binding, it is not worth the effort. makes the binding more complicated and would diverge from the behaviour of other bindings. We should rather get the interface right so that a user cannot cause crashes of the JVM.

If you want to introduce logging, please use Elektra's logger and implement them in the C layer so that every binding can profit from it.

**Comment by e1528532** [comment]
> Why do we use final Object... args in the signature, we could already limit to Key there?

Well whoever made the bindings did that. I guess its to stay completely flexible and also pass in pointers directly like you can do with the actual c library. I've added a convenience method that takes a Key array and adds the KS_END appropriately for the use with randoop now.

> Why have Object as argument at all? Why are "Helper constructor" public?

Like said, i guess this was intended to give you maximum flexibility when using the jna bindings, but i didn't initially create them. If we want to keep that, excluding them is the only option i think in order to avoid randoop passing random pointers.

> I do not like logging in the binding, it is not worth the effort.

Well i've already done it in order to analyze the issues i reported here, as i said in a way the bindings remain untouched. But basically i agree that the dangerous operations probably shouldn't be available via the jna bindings.

> Sounds useful. And checks for the other cases. Crashing the JVM certainly is not the wanted behavior!

I think i have actually detected an issue with the jna bindings. The way it used the reference counting seems wrong. It increased the reference by one for every new Key object allocated in java (makes sense), and decreases it in the finalizer (makes sense too), but it also always called keyDel immediately. Now i actually call ksGetRef and only use keyDel if there is no reference on it anymore.
Then thinking about it i came to the conclusion that in java i think you shouldn't deal with reference counting manually so i've made the methods to increase and decrease the reference counter internal (so randoop doesn't call them either - like users wouldn't be able to with that change). I've also made constructors that pass a raw Object array (which is interpreted as pointers) forbidden for the keyset. 

Now randoop was able to run for a long time without any issue. (i've let it run for 60 seconds - it tested 878 test cases executing 425588 method calls. 95 exceptions were raised. And i've done that twice! i have to check the exceptions - but the important thing - no JVM crashes anymore!!). I think this sort of speaks for the stability of elektra too.

Do you agree? I mean if you want to throw pointers around, then you probably shouldn't use java but c or c++ or something like that.

**Comment by markus2330** [comment]
> If we want to keep that

I would rather avoid a flexibility that can be used to crash the JVM. We can even keep the flexibility in a safe way by providing different constructors with different signatures.

> Well i've already done it in order to analyze the issues i reported here, as i said in a way the bindings remain untouched.

Okay, then I understood you wrong. By saying "I think i will alter the code a bit to be able to use the logging framework.." I thought you want to invest more time for the logging. If it is already done you can include it in a PR.

> Now randoop was able to run for a long time without any issue.

Perfect! I am looking forward to the PR for interface improvements. (Or at least the randoop command-line that finally worked for the docu.)
