### ISSUE TITLE
Could not get fcrypt to work

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1528]
### Describe what you wanted to do

Wanted to sign a configuration file with my gpg key:

```
kdb mount test.sign user/fcrypt fcrypt "/fcrypt/sign=MYKEY"
kdb set user/fcrypt/test x
```

### Describe what you expected

That the file is signed.

### Describe what actually happened

- [ ] The file seems to be encrypted (or at least unreadable)? (is this expected behaviour?)
- [ ] The plugin config seems to be not verified, passing wrong keys to `/fcrypt/sign` was not detected and lead to later errors. Even completely wrong keys are accepted? (`fcrypt/sign`)
- [ ] inconsistency with plugin config names: `/gpg/key`, `fcrypt/sign`, `crypto/key`. Please remove leading slashes and make the config related to the purpose, and not some implementation detail. (Maybe: encrypt/key and sign/key?)
- [ ] The tutorial does not give an example of how to work with signatures
- [ ] file seems to be rewritten after `kdb get`?

Otherwise it seems to work great: you can set+get values and corruptions of the file are properly detected. (at least in the middle, but error is: `zlib inflate problem: invalid distance too far back` so I am not sure if it is actually because of signature verification, appending characters at the end is not detected though: file is simply rewritten after `kdb get`.).

### System Information

- Elektra Version: master

**Comment by petermax2** [comment]
> The file seems to be encrypted (or at least unreadable)? (is this expected behaviour?)

GPG encodes the file into its internal format appending the signature. You can simply decode it using `gpg -d file` without any key required. GPG will then automatically verify the signature and append the verification result to the output. There is a possibility of detached signature files, however it would require us to specify the path to the detached signature file when verifying the config file. If the signature file is deleted we can not verify the integrity any more, thus weakening the security. 

> file seems to be rewritten after kdb get?

Yes, the file is decoded (see above) so that the next plugin in the backend can process it properly.

I agree on the other 3 points and will fix it within the next days.

**Comment by markus2330** [comment]
Ahh perfect, that you used the internal format of  `gpg` clears up a lot. Please add this to the docu ;)

Really nicely done but as you see sometimes a tiny bit of missing information makes it hard to understand/use a tool!

> Yes, the file is decoded (see above) so that the next plugin in the backend can process it properly.

This might be a problem for some use cases. The resigning on every `kdb get` means that you need the private key for *reading/verifying* signed files? Why not simply keep the original file and swap it in the end (still needs write access, but at least not the private key)? So to be clear what I mean:

```
gpg -d /home/markus/.config/test.sign
# gpg: signature ... 13:36:01
kdb get user/fcrypt/test
gpg -d /home/markus/.config/test.sign
# gpg: signature ... 13:38:38 (2 minutes later, so it was signed again!)
```

> I agree on the other 3 points and will fix them within the next days.

Thank you! Would love to see the thesis, too!
