### ISSUE TITLE
Code Generator in C

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1562]
Reimplement python prototype in C.

**Comment by markus2330** [comment]
@kodebach Can you describe which technology you will use here?

**Comment by kodebach** [comment]
- I am using [mustache](https://mustache.github.io/) templates that will be compiled into the `kdb` tool. 
- The templates are rendered through [this library](https://github.com/kainjow/Mustache).
- The template files are turned into static strings in a header file during `cmake`s configure phase. Firstly this ensures users can't modify the templates (which might break them). Secondly the library I use expects the templates in string form anyways.
- You can view a dummy PR for the code generation in my fork (kodebach/libelektra#1). The interesting files are `src/tools/kdb/gen.cpp` and everything in `src/tools/kdb/gen/`.
- The basic idea is that each template consists of a C++ class and a set of `.mustache` files. The class is needed to convert a given KeySet into the data format used by the mustache library and to provide the logic behind the template, because `mustache` is a logic-less template language.

**Comment by kodebach** [comment]
continued in #2680
