### ISSUE TITLE
Documentation: Non-HTTPS Links Do not Work

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1594]
# Steps to Reproduce

Open http://doc.libelektra.org/api/current/html in your favorite browser

# Expected Result

The web browser redirects to the page https://doc.libelektra.org/api/current/html

# Actual Result

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api/current/html was not found on this server.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at doc.libelektra.org Port 80</address>
</body></html>
```

**Comment by markus2330** [comment]
Thank you for reporting! I did not notice because my browser still show the page (maybe because of https anywhere or because the old redirect is still cached).

How did you end up at the broken link? (I replaced the ones in the repo, but maybe there are more.)

Btw. should we change to a different 404 page?

**Comment by sanssecours** [comment]
> How did you end up at the broken link?

The main page of the [API documentation](http://doc.libelektra.org/api/current/html) contains two links to the current and latest Doxygen documentation. One of them was – and in the homepage version still is – https://doc.libelektra.org/api/current/html.

> Btw. should we change to a different 404 page?

If you have a really good idea on how this page should look, then why not. However, I am totally fine with the current version. In my opinion 404 pages are always annoying, even if they are well designed.

**Comment by markus2330** [comment]
>  and in the homepage version still is

Yes, the homepage cannot be rebuild at the moment. Next to fixing the redirecting so that external links work, we should also update our website to only use https links.

> If you have a really good idea on how this page should look, then why not. However, I am totally fine with the current version. In my opinion 404 pages are always annoying, even if they are well designed.

I was more thinking about that it should contain some information that the site is related to Elektra and this issue tracker should be used to report the problem. If someone comes up with an design, we can use that, too. We already have a designed 404 page for errors within the homepage: https://www.libelektra.org/error/404

**Comment by markus2330** [comment]
This seems to work for me now. Please reopen if there are still problems.
