### ISSUE TITLE
kdb stash: does not remove system keys

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1601]
# Describe what you wanted to do

`kdb stash`

# Describe what you expected

`kdb ls` only lists hard-coded `system/elektra` keys

# Describe what actually happened

`system/globaltestkey` was still there.

# System Information

- Elektra Version: master

**Comment by kodebach** [comment]
You might need to execute it as root, because it's just an alias for other kdb calls that may need root permissions (e.g. `kdb rm -r system`). For some reason stderr is redirected to /dev/null (git say you wrote `kdb stash` even though the author is marked as "Thomas Waser").

Additionally (at least on my system) removing `2> /dev/null` revealed the following error message:
```
The command kdb rm failed while accessing the key database with the info:
Sorry, the error (#84) occurred ;(
Description: read only plugin, kdbSet not supported
Reason: the key system/elektra/version (value Below are version information of the Elektra Library you are currently using) was removed
Ingroup: kdb
Module: 
At: /home/klemens/data/bsc/libelektra/src/libs/elektra/plugin.c:422
Mountpoint: system/elektra/version
Configfile: 
```

**Comment by markus2330** [comment]
Thank you, obviously this cannot work. I do not know why this redirection was done, it does not seem to be useful?

Supporting --without-elektra for `kdb rm -r system` and then using umount/global-umount to unmount everything should be the most reliable way.
