### ISSUE TITLE
KDB Command to Get Binary Values

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1617]
# Proposal

A tool to retrieve binary data from the KDB could be quite handy. In the first step it would make sense that the tool writes out binary data encoded as 8 bit hexadecimal values. Let us assume we call the command `kdb get-binary`, and the binary data at the location `/test/binary` stores the ASCII string `"Hi"` (the decimal numbers 72, 105, and 0). The example below shows an invocation of the proposed command using Markdown Shell Recorder syntax. 

```sh
kdb get-binary /test/binary
#> \x48\x69\x00
```

We could also integrate the functionality to read binary data directly into `kdb get`:

```sh
kdb get -b /test/binary
#> \x48\x69\x00
```

, or even better `kdb get` could just automatically encode binary values:

```sh
kdb get /test/binary
#> \x48\x69\x00
```

. Either way the current situation is not ideal:

```
The command kdb get terminated unsuccessfully with the info:
Binary/String key mismatch, use proper getString()/getBinary() or use getValue() to get both.
Please report the issue at https://issues.libelektra.org/
```

. It might make sense to implement a `kdb` command to add binary data to the database first (see issue #1614).

**Comment by markus2330** [comment]
Seems like you already implemented it but nevertheless here an idea for future reference: We could use plugins as filter to be used for "kdb get". A filter converting binary to a hexadecimal string (enabled by default so that nobody gets the "Binary/String key mismatch" error) would then exactly do what we want.

But your implementation also has advantages (no problems with missing plugins).
