### ISSUE TITLE
restbackend: HTTP 500 on 'database' endpoint without 'sortBy'

### ISSUE THREAD

**Issue by BernhardDenner** [ElektraInitiative/libelektra#1674]
If the 'database' endpoint of the restbackend is called without an 'sortBy' option, the restbackend returns with HTTP 500 'internal server error'.

see #1673 

- Elektra Version: master
- Versions of other relevant software?

# Further Log Files and Output

**Comment by markus2330** [comment]
@Namoshek Do you have any idea about this error?

**Comment by markus2330** [comment]
The full error is:

```

Running "copy:build" (copy) task
Copied 4 files

Running "create-website-sitemap:build" (create-website-sitemap) task
>> Could not reach Backend and could therefore not create sitemap.xml!
Warning: Server responded with status code 500:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
	"http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>500 &mdash; Internal Server Error</title>
  </head>
  <body>
    <h1>500 &mdash; Internal Server Error</h1>
    <p>map::at
</p>
  </body>
</html>
 Use --force to continue.

Aborted due to warnings.
```

see https://build.libelektra.org/jenkins/job/elektra-homepage/218/console

**Comment by Namoshek** [comment]
My best guess is that it has something to do with a missing configuration parameter accessed [here](https://github.com/ElektraInitiative/libelektra/blob/master/src/tools/rest-backend/database_application.cpp#L829). Maybe the [config-specification](https://github.com/ElektraInitiative/libelektra/blob/master/src/tools/rest-backend/config-specification.ini.in) is not mounted properly? In the spec, a default for this parameter is defined. I remember we had some trouble with this default, but no idea what exactly that was though.

**Comment by BernhardDenner** [comment]
I've attached a gdb recently on it:
https://github.com/ElektraInitiative/libelektra/blob/cc373abc29532b59585960fe1591419cd43e0763/src/tools/rest-backend/database_application.cpp#L844
It seems that `SORT_ENTRY_MAP.at ('key')` throws an exception. However, this should be a "static" map, including the key ... hmm maybe I've too less cpp knowledge to understand that ;)

**Comment by markus2330** [comment]
Do you mean the string `key`, `'key'` would be an compilation error ;) Or it is with quotes embedded in the string and thus wrongly spelled and cannot be found?

Because there is no write attempt to the map, I would expect it to be a typo. We should add validation code into the spec ;)

> static

static is massively overloaded in C++. Within functions it means it should be global. But for global variables it means that they should not be a public symbol. We can move it into `DatabaseApp::processSorting`, static would have a different meaning there, but it would be correct (and the scope of the variable better limited).

Any reason the map is not const?

**Comment by markus2330** [comment]
Seems like the workaround closes this issue.
