### ISSUE TITLE
release: docset+homebrew

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1688]
What about setting up a build job that builds the docset for download? (can be added to the doc build) Would this help you?

Can you check if we can publish 0.8.20 docset+homebrew in the official channels?

**Comment by sanssecours** [comment]
> What about setting up a build job that builds the docset for download? (can be added to the doc build)

The DocSet and the normal HTML documentation use different options for output generation. This means you have to decide at configuration time if you want a good looking DocSet (no index) or good looking normal HTML documentation (with index). We could generate the documentation twice to fix this problem though. If that is okay with you, where should we put the DocSet?

> Can you check if we can publish 0.8.20 docset…

I can try.

> …+homebrew in the official channels?

I thought about this when I updated the formula. Since I already [failed once](https://github.com/Homebrew/homebrew-core/pull/7850), I leave the second try to another person. The stuff Mike mentioned in [my PR](https://github.com/Homebrew/homebrew-core/pull/7850) should be fixed in the [current version of the formula](https://github.com/ElektraInitiative/homebrew-elektra).

**Comment by markus2330** [comment]
> We could generate the documentation twice to fix this problem though. If that is okay with you, where should we put the DocSet?

If it needs to be compiled differently, a new build job makes more sense.

>  I can try.

Do. Or do not. There is no try.

> Since I already [failed once](https://github.com/Homebrew/homebrew-core/pull/7850)

It was a concrete and constructive critique. You fixed the issue. I do not see a reason to be  discouraged here.

**Comment by sanssecours** [comment]
I opened a pull request for the DocSet [here](https://github.com/Kapeli/Dash-User-Contributions/pull/1635).

> If it needs to be compiled differently, a new build job makes more sense.

I think we already have enough build jobs as it is 😊. Building the DocSet should be [easy enough](https://github.com/sanssecours/Dash-User-Contributions/blob/fc4cf961980a9f9c7ef475082c566dcab12f3121/docsets/Elektra/README.md). I think we can just do it by manually for each release. Especially, if we need to open a [pull request](https://github.com/Kapeli/Dash-User-Contributions/pulls) for new versions of the DocSet anyway.

**Comment by markus2330** [comment]
Thank you for submitting the DocSet! Looks great and the build passed!

> I think we already have enough build jobs as it is

I agree that the build jobs are not well arranged. We might want to introduce pipelines and/or more views. In the release process there are still quite some manual jobs. Ideally, nothing needs to be done manually and we can simply repeat the release until no errors are detected. This helps to get more sleep :-)

> Especially, if we need to open a pull request for new versions of the DocSet anyway.

This can be automated, too: https://developer.github.com/v3/pulls/

But I agree that there are more important things to automate (see #160). If you can do the homebrew formular+docset for the next releases, that would be great!

**Comment by sanssecours** [comment]
> I do not see a reason to be discouraged here.

I see some reasons [especially](https://docs.brew.sh/Acceptable-Formulae.html):

> We frown on authors submitting their own work unless it is very popular.

. Since we already have a [tap](https://github.com/ElektraInitiative/homebrew-elektra) installing is as easy as:

```
brew tap ElektraInitiative/homebrew-elektra
brew install elektra
```

. Inclusion in Homebrew would only mean that we do not need the first line. Using taps is not that uncommon either. Some of them are quite popular. For example, I use [`beeftornado/homebrew-rmtree`](https://github.com/beeftornado/homebrew-rmtree) and [`buo/homebrew-cask-upgrade`](https://github.com/buo/homebrew-cask-upgrade).

**Comment by markus2330** [comment]
> We frown on authors submitting their own work unless it is very popular.

I agree that their statements do not provide a welcoming atmosphere for such PRs. This concrete statement (imho) refers to (mostly) single-authored work, which Elektra definitely is not.

> Inclusion in Homebrew would only mean that we do not need the first line.

It also means we get visibility for people scrolling through which packages are available. And people know it went through quality control. Having Elektra in many package managers clearly is an important factor for its success.

**Comment by sanssecours** [comment]
I opened a pull request for the Homebrew formula [here](https://github.com/Homebrew/homebrew-core/pull/20461).

**Comment by markus2330** [comment]
Thank you, great work! Let us hope for the best!

The docset worked out perfectly!
