### ISSUE TITLE
KDB Import: Import of Empty System Configuration Fails

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1700]
# Steps to Reproduce the Problem

```sh
kdb export system --without-elektra dump
#> kdbOpen 1
#> ksNew 0
#> ksEnd
kdb export system --without-elektra dump | kdb import system dump
```

# Expected Result

The last command should import the empty configuration returned by `kdb export` without any problems. For example, the following command works, at least with an empty config, without any problems on my machine:

```
kdb export user dump | kdb import user dump
```

.

# Actual Result

```
The command kdb import failed while accessing the key database with the info:
Sorry, the error (#84) occurred ;(
Description: read only plugin, kdbSet not supported
Reason: the key system/elektra/version (value Below are version information of the Elektra Library you are currently using) was removed
Ingroup: kdb
Module:
At: ../src/libs/elektra/plugin.c:369
Mountpoint: system/elektra/version
Configfile:
```

# System Information

- Elektra Version: master

# Further Information

To tackle issue #1132 it would be nice to just export the whole configuration before a test and then reapply the configuration afterwards. This does not work because of the problem described above. Does anybody know a **simple** solution to reapply the configuration of the `system` namespace?

**Comment by markus2330** [comment]
Thank you for reporting!

This is a irritating error message, it says that you are trying to change the version information within system/elektra/version (because you are deleting it). But this is quite hidden within the reason and easy to overlook.

To improve usability, we should encode the information how something was exported inside the exported file (at least by default). On import we automatically apply these flags. This meta-information within the exported files is also needed for exporting cascading keys (see #51).

In your case, the "--without-elektra" needs to be added for import (not supported at the moment), then it would not try to remove the version information and the error would not occur.
