### ISSUE TITLE
API Compatibility: New Function `elektraArrayDecName`

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#1733]
# Description

Since commit 2745c0b2 Elektra contains a new function called [`elektraArrayDecName`](https://github.com/ElektraInitiative/libelektra/blob/master/src/libs/ease/array.c#L148). Since you can not use this function in an old version of Elektra, the build job [`elektra-icheck`](https://build.libelektra.org/jenkins/job/elektra-icheck) reports the following error:

```
API and ABI addition: identifier elektraArrayDecName is new
 is now defined at src/include/kdbease.h:13:
extern int elektraArrayDecName(Key * key);
```

.

How can I fix this error? Should I just move the code for `elektraArrayDecName` to the Directory Value plugin?

**Comment by markus2330** [comment]
It seems to be wanted and reasonable to add this function to the public API of kdbease.
doc/todo/API describes the protocol for API additions.

**Comment by sanssecours** [comment]
> doc/todo/API describes the protocol for API additions (or other changes).

Thank you for the information. I added information about `elektraArrayDecName` to the [release notes](https://github.com/sanssecours/libelektra/blob/🥙/doc/news/_preparation_next_release.md#libease). Can you please tell me how I can fix [`elektra-icheck`](https://build.libelektra.org/jenkins/job/elektra-icheck)?

**Comment by markus2330** [comment]
elektra-icheck is automatically reseted on every release due to changing which version it compares against (see VERSION and VERSIONCMP in Jenkins config). Till the release it usually would continue to fail. 

But you are right: due to "jenkins build all please" this situation might not be ideal. Maybe "--skip-from" helps in suppressing already fixed icheck errors. We could point "--skip-from" to a file within the source code (maybe tests/icheck.suppression or .blacklist) which contains a list of planned API changes for a release. The file is removed directly after every release.

We could also have the script calling icheck within the source code, then we would not need to have the VERSION and VERSIONCMP config within Jenkins.
