### ISSUE TITLE
API Compatibility: make elektraArrayValidateName public

### ISSUE THREAD

**Issue by e1528532** [ElektraInitiative/libelektra#1735]
For my type system i came to the requirement that i need to detect whether a key is an array key or not. As this functionality already seems to be provided by kdbease as `
int elektraArrayValidateName (const Key * key)`, but marked as internal and thus not in the header.

I'd make this function public instead so i can add bindings for it and use it in haskell instead of reimplementing this myself. Or is there an easier reliable way of determining whether a given key corresponds to the array syntax?

**Comment by markus2330** [comment]
Yes, we could make elektraArrayValidateName public within kdbease. (Also for the upcoming release because we have an API change within libease anyway). We should consider renaming it, though. What about elektraIsArrayElement?

But the function might not quite fit of what you semantically want. Can you reformulate what exactly you want to know? Are you really interested in if a key has the syntax of an array element or do you rather to know from the parent if all its siblings are array keys?

If you are interested in the latter question #182 contains a proposal.

Also of interest is a formalization of nested arrays. It is currently not even documented 😞

**Comment by e1528532** [comment]
In my case it is really detecting whether a given key is an array key. The reason is, for instance the override metakey is an array, but the underlying function in the sense of the type system (you will see that in the prototype) is obviously only created once, so whenever i encounter such an array metakey like `override/#1` i know i can strip the basename `#1` and then check for the existence of an override type function.

I have no issue with renaming, though i think validateName is not too bad. It is not actually a boolean check like IsArrayElement would imply to me. Currently it differentiates between 3 possible cases, maybe more in the future. I only need the third case for now (1 meaning its an array element). Therefore we should either leave the name like it is or find another better one, i don't really have any good idea right now.

**Comment by markus2330** [comment]
Okay, if you are happy with its semantics and its name you can make it public as-is within libease. See doc/todo/API for what to consider (next to have the declaration in the header file).

For the binding: ideally you have two separated bindings (one for core, the other for libease). @BernhardDenner already did something like this within the ruby binding (see src/bindings/swig/ruby/kdbtools.* which is a binding for libtools).

But first steps first: for this release we should get the C API right.

**Comment by e1528532** [comment]
This is already public since quite some time, thus closing this issue.
