### ISSUE TITLE
libelektra-invoke not mentioned in any release notes

### ISSUE THREAD

**Issue by haraldg** [ElektraInitiative/libelektra#1758]
Probably nothing that can be fixed now, but I figured I should mention this at least. Seems like a new file was introduced in 0.8.20, but not mentioned in the release notes.

**Comment by markus2330** [comment]
Thank you for reporting!

Yes, in the 0.8.20 release notes the info is quite hidden in the section "Compatibility" (last point). In the 0.8.21 release notes it is mentioned twice because here we added documentation and improved the API.

Sorry for any inconveniences, we should list all changes of files in the section for maintainers in the future.

It is not important, however, to actually install this particular header file, it is quite unlikely that external parties use it at the moment. Was the installation necessary for some reason (like cross-compilation)?

**Comment by haraldg** [comment]
I didn't save the build log this time, but IIRC I noticed the problem because libelektra-core linked to libelektra-invoke and thus was uninstallable without adding the new library to the same package...

**Comment by markus2330** [comment]
Ahh, I see you mean the .so, not the header file. You are right, we forgot to mention it in the release notes. Thanks for pointing that out! It is good to get feedback how to make the release notes more useful.

What you describe seems like a bug, it should not be necessary for libelektra-core to be linked against libelektra-invoke. (And on my system it does not link against it.)

Maybe it was libelektra-full or one of the plugins that need libelektra-invoke? (i.e. curlget, gitresolver, dini, blockresolver, multifile)

**Comment by haraldg** [comment]
Maybe I'm confusing package names and library names. I will recheck. However most plugins are in their own packages, so I guess it would have been one of the libraries ...

It's always a bit cumbersome to inspect cross compiled binaries before they are installed on the target system. So maybe I'll come back to this later.

**Comment by haraldg** [comment]
I couldn't reproduce the linking problem. The only "issue" is the release notes ...
