### ISSUE TITLE
Logging inside Bindings

### ISSUE THREAD

**Issue by e1528532** [ElektraInitiative/libelektra#1775]
For bindings like haskell it is complicated to use elektra's internal logging infrastructure which is based on c-macros, and printing to stdout can cause test failures. (Ab)Using warnings or errors as log messages is also not really ideal either. I had two quick ideas about it:

### Plugin/Key based approach

So i thought about using the key given to plugins to append log messages to it (e.g. using an array to have some kind of ordering), and then before the plugin is about to exit it reads the log messages from the key and logs those messages using ELEKTRA_LOG (therefore it will only be done if logging is enabled).

Ideally we'd implement this as a log plugin that you can mount globally (or locally) that implements this behavior.

### Proxy logging function

Another idea i had is having some kind of proxy function for the logging which could look like

```
void log (char* what) {
ELEKTRA_LOG (what);
}
```

and make bindings to that function. So if logging is not enabled it will do nothing. While this still creates some overhead due to leaving eventual binding runtimes and then stepping back in it even though it would do nothing if logging is disabled, the other approach also adds some overhead due to the extra metakeys.

**Comment by markus2330** [comment]
As already said, its perfectly fine if language bindings use a logging system of their own language. 

Important is that by default there is no logging at all (no output to stdout/stderr because it is a library). If any logging is needed within the binding lies within your jurisdiction (but it must be off by default). Within the plugins you most likely want a flexible way for logging but I am sure there are plenty of options within Haskell.

Elektra's macros for logging can disable logging at compile time, as discussed in doc/decisions/logging.md but this does not make sense for every language binding.

> (Ab)Using warnings or errors as log messages is also not really ideal either.

This is obviously only relevant if you actually have a warning/error. Then you can put all relevant text within the "reason" of the message. The binding or the plugin framework should give Haskell plugins a way to set an error and to add warnings.

> Ideally we'd implement this as a log plugin that you can mount globally (or locally) that implements this behavior.

This idea goes along the lines with an early suggestion of @tom-wa. Next to the effort of implementing it I would like to avoid such run-time overhead. I would say if it is not even a warning, it is not worth reporting. I documented this in 06e10ca90ea129cf0712d8fca40f8f1159616174. Do you have an example of an information within a plugin that should be reported to an *end user* and is not a warning/error? (This has nothing to do with logging needed for development.)

> Proxy logging function

There is an underlying log function `elektraLog`, so no proxy would be needed. Using haskell libraries for logging, however, will provide you much more comfort.

**Comment by e1528532** [comment]
So summing up, the decision is that bindings should take care about their own logging infrastructure or leave it up to the respective plugins, that is fine enough! Its only important to be disabled by default.
