### ISSUE TITLE
doc: enhance search documentation

### ISSUE THREAD

**Issue by s-pace** [ElektraInitiative/libelektra#1815]
👋 team,

First of all congrats for you presentation at FOSDEM 2018. It was really instructive.

I couldn't help providing you[ a nice search experience for your neat documentation](https://community.algolia.com/docsearch/):
![Demo DocSearch](https://cl.ly/0U2E3J3C0P0O/Screen%20Recording%202018-02-07%20at%2006.50%20PM.gif)

Congratulations, your search is now ready!
I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:
- Copy the following CSS/JS snippets and add them to your page
```
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />
<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '7d1e7bc1f97b53de246aaefa29484be9',
  indexName: 'elektra',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```
- Add a search input if you don't have any yet, and update the inputSelector value in the code snippet to a CSS selector that targets your input field.
- Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/documentation/)
- You can also check your configuration in the github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/elektra.json). Feel free to open pull requests!

Feel free to get back to us if you have any issues or questions regarding the integration.
We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it.

Have a nice day :)

**Comment by markus2330** [comment]
Thank you so much, this is *really* a much requested feature we often discussed (but could not do because of the effort)! It is like you read our mind 👍 

> I've successfully configured the underlying crawler and it will now run every 24h.

That's great. In the long term we should self-host it to not burden you with this on your infrastructure.

> Add a search input if you don't have any yet,

We have one but it is only for snippets. It looks like as if the search field is implemented in
https://master.libelektra.org/src/tools/rest-frontend/public/pages/main/users/search.html

> Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/documentation/)

This redirect seems to be wrong, in my browser it leads to a 404 on https://community.algolia.com/docsearch/documentation/documentation/docsearch/introduction/

The link works after removing one of the duplicate "documentation" in the URL.

> Feel free to get back to us if you have any issues or questions regarding the integration.

 We will check how we can provide both searches (for snippets and docu).

@vanessaNWK @waht @Namoshek Do you have an idea how to integrate this so that both searches work?

> We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it.

We will do once we got our part running. I already have a small feedback: Your animated picture to show how it works is really nice but wouldn't it be better if you already provide some search mask which we could directly try out? (Might be difficult to realize, though?)

In any case: a big thanks again!

**Comment by s-pace** [comment]
@markus2330 

Glad to see I read in your mind 👁 

Regarding the website, we were working on it and we hat a small redirection issue. It is fixed now:
https://community.algolia.com/docsearch/.

We do provide analytics on the search too if you are interested.

Thank you for the feedback. It is something we are working on :)

**Comment by s-pace** [comment]
👋 @markus2330 @vanessaNWK @waht @Namoshek,

I have tailored and updated your DocSearch index: algolia/docsearch-configs@82305a5. It is live

Let us know if you need any help or if you have any feedback.

Cheers

**Comment by markus2330** [comment]
Thank you for the update! Where can we find the live version?

Unfortunately, we did not have time to integrate the search but we did not forget about it :+1:

**Comment by s-pace** [comment]
I have bootstrap a quick example (copy and paste ~2 secs)
http://elektra-docsearch.surge.sh/

**Comment by hesirui** [comment]
Thanks for assigning, I will work on that.

**Comment by markus2330** [comment]
Thank you for working on this issue!

**Comment by markus2330** [comment]
Finally done!

**Comment by s-pace** [comment]
🎉 Champagne, or Beer ;)
