### ISSUE TITLE
Web 1.2 use cases

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1857]
For some use cases I did not find out how to do it:

- [ ] drag and drop
- [ ] undo/redo

The usual shortcuts and mouse actions did not work for me.

**Comment by omnidan** [comment]
@markus2330 drag and drop works as you would expect - you drag any key (with subkeys) to another key and it puts it there. There might be an issue with this on Firefox ESR: It is too slow for me to be able to drag & drop, or maybe it is simply not supported yet? I think the drag & drop api is a html5 standard.

Undo/redo is not implemented right now. I thought this would be a "low hanging fruit" but it turned out to be really complicated, especially when dealing with external changes and keeping state in sync. I think in the future when we have better node.js bindings (#1317) and a way to listen to kdb changes this would be a great feature though.

**Comment by markus2330** [comment]
Okay, I'll try with another browser if drag&drop works there.

The elektrad implementation of undo/redo can be done with the elektrad reimplementation. But undo/redo also needs to be implemented in webd (to undo whatever a user did). This should be part of the user study. It does not, however, need to be part of the 1.2 PR.

**Comment by markus2330** [comment]
copy&paste also does not work for me in Chromium

I incorporated the issue in #1865, please feel to reopen.
