### ISSUE TITLE
check for home in testscr_check_resolver

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1881]
## Steps to Reproduce the Problem
make sure `pwd` is a checkout of libelektra
```sh
docker build doc/docker/debian/stretch/. -t buildelektra-stretch
docker run -it -u 29295:29401 -v `pwd`:/app/src buildelektra-stretch
export HOME=/tmp/home
mkdir -p $HOME
export WORKSPACE=/tmp/workspace
cp -R /app/src $WORKSPACE && cd $WORKSPACE
mkdir build && cd build
cmake -DBINDINGS=ALL -DPLUGINS=ALL -DKDB_DB_SYSTEM=/tmp/home/.config/kdb/system -DKDB_DB_SPEC=/tmp/home/.config/kdb/spec  -DCMAKE_INSTALL_PREFIX=$WORKSPACE/system -DBUILD_DOCUMENTATION=OFF $WORKSPACE
make -j 2
make run_all
```
## Expected Result

Tests should pass

## Actual Result

The following tests are not passing:
- testscr_check_resolver
  seems like some file can not be found/opened
- testshell_markdown_tutorial_validation
  ```
  ERROR - STDOUT:
  “/tmp/home/.config/tutorial.dump”
  does not match
  “/(home|Users)/.*/\.config/tutorial\.dump”
  ```

## System Information

- Elektra Version: master
- Dockerfile from #1866

## Further Log Files and Output
[Full Log on Build System](https://build.libelektra.org/jenkins/job/elektra-jenkinsfile/43/execution/node/63/log/?consoleFull)

**Comment by markus2330** [comment]
> testscr_check_resolver

The tests demand that the user has a home directory in /etc/passwd. (Content itself should be irrelevant.)

We could write an if around the test cases that do not work without home directory but I think its strange to use a user ID that does not exist on a system. Why doesn't docker add such an entry in /etc/passwd?

> testshell_markdown_tutorial_validation 

Yes, that is a wrong assumption, should be fixed now (be3787c4d0c265e68e55d26aeaf1314529e8bca6). (The test case worked for me with your docker commands.)

> Dockerfile from #1866

We could add something like this in the GitHub template so that people always try to reproduce it with Docker.

**Comment by markus2330** [comment]
>   Docker does not do anything on it's own. We could hardcode userid's and provide an apropriate /etc/passwd if we have to

We could also fill /etc/passwd with random home directories for the pool of randomly selected user UIDs.
(Assuming that the random UIDs actually improve test case coverage or are otherwise useful.)

But it is a good question what we should assume from the environment. It actually also makes a lot of sense that Elektra testcases also run on a completely unmodified docker env (at least the nokdb ones). I opened #1888 so that we can gather all these assumptions so that you do not have to trap into each of them. And so that all assumptions are handled equally (test cases check for them and disable themselves if they are not fulfilled) we should add a check in the beginning of "testscr_check_resolver". Or maybe it is even useful to support such systems. But I do not know which home directory the resolver can assume if it cannot gather any information from the environment. `/tmp` would be a very dangerous default.

Btw. did you try to run everything as root?

>> We could write an if around the test cases that do not work without home directory

> Sadly I can't see where the /etc/passwd is read in the tests, can you point me towards it?

The resolver itself "reads" /etc/passwd via glibc. See filename.c which uses the method `getpwuid_r`.

**Comment by ingwinlu** [comment]
> We could also fill /etc/passwd with random home directories for the pool of randomly selected user UIDs.
(Assuming that the random UIDs actually improve test case coverage or are otherwise useful.)

I just found out that they are not random, I only assumed so because openshift does so for security reasons and I noticed that they were different in the logs. However it is just the userid:groupid of the jenkins user on whatever machine the container gets run on

The bad thing about this is that it does not provide the security benefits. Nor can the solutions be applied that are used to handle openshifts behaviour.

What should work is providing an entryscript with the docker image that adds a line to /etc/passwd for the user that executes it.

**Comment by markus2330** [comment]
> What should work is providing an entryscript with the docker image that adds a line to /etc/passwd for the user that executes it.

Yes. But we should also have the detection code to turn off the test case because some people might run docker without having the entryscript.

Btw. what about changing the baseimage instead of writing entryscripts?

**Comment by markus2330** [comment]
> would it make sense to just provide a passwd file with the tests and let the tests overwrite where to search for the file?

It is not possible, we use a glibc method getpwuid_r  which opens /etc/passwd for us. What we could do is to mock the getpwuid_r with LD_PRELOAD but I think that is not worth the trouble and it is unclear what we are actually testing then. I think our best options are:

1. Keep having the assumption that every UID has a passwd entry but disable the test if the assumption is invalid but make sure within docker that the assumption holds, so that all tests can run.
2. Fix the test case to work without the assumption (Problem: In some situations we might test less without telling the user)
3. Fix the resolver to work without the assumption  (Problem: What is a reasonable default for a home directory?)

> Maybe we should even consider filing a cr with jenkins to get a more openshift like behaviour for id's but I doubt we would see that merged anytime soon.

I need more details here: where do we get our baseimage from, what does openshift,... If you can decide yourself and want to write about it in the thesis, you do not have to answer here.

**Comment by ingwinlu** [comment]
i only really like nr 3

https://linux.die.net/man/3/getpwuid_r
```
The pw_dir field contains the name of the initial working directory of the user. Login programs use the value of this field to initialize the HOME environment variable for the login shell. An application that wants to determine its user's home directory should inspect the value of HOME (rather than the value getpwuid(getuid())->pw_dir) since this allows the user to modify their notion of "the home directory" during a login session. To determine the (initial) home directory of another user, it is necessary to use getpwnam("username")->pw_dir or similar.
```
this states that getuid()->pw_dir should only be used if HOME is not set by the user. would it be acceptable to change resolver to behave this way or would it defeat the point of having this as a plugin?

**Comment by markus2330** [comment]
That is exactly how the default resolver (fm_hpu_b) works, first home (h), then passwd (p), then /home+$USER (u).

The "problem" is that there are test cases which have neither HOME nor USER set.

**Comment by ingwinlu** [comment]
Sorry I should have looked more closely at the code first before commenting.

If there is no way to satisfy the need to *resolve* a home directory, wouldn't it make sense for the resolver to just fail? And change the test cases accordingly?

**Comment by markus2330** [comment]
> If there is no way to satisfy the need to resolve a home directory, wouldn't it make sense for the resolver to just fail?

That is exactly what happens, it fails because it is unable to resolve. From the log above (see Description of warning `#83`, the error is directly caused because of this warning. I agree that these error messages could be improved. But it is a relatively rare error, I suppose?):

```
error: could not mount root using: /home/jenkins/workspace/elektra-jenkinsfile@2/build/bin/kdb mount --resolver resolver_fm_ub_x a dir/test/script dump
The command kdb mount failed while accessing the key database with the info:
Sorry, 3 warnings were issued ;([0m
[1m[35m Warning (#83):[0m
[1m	Description: [0mresolver was not able to resolve a filename
[1m	Ingroup: [0mplugin
[1m	Module: [0mresolver
[1m	At: [0m/home/jenkins/workspace/elektra-jenkinsfile@2/src/plugins/resolver/filename.c:306
[1m	Reason: [0muser resolver failed at step 4, the configuration is: hpu
[1m	Mountpoint: [0m
[1m	Configfile: [0m
...
```

Btw. can you install the color plugin from Jenkins to get rid of the color characters?

> And change the test cases accordingly?

That would be option nr 2), to fix the test cases.

**Comment by ingwinlu** [comment]
Just to let anybody who might have started working on this know:
We will probably have to add a jenkins user to the docker images anyway to make dbus work so this should also resolve this issue.

**Comment by markus2330** [comment]
Perfect! I added the limitation of the resolver in bfff305f6c272ee2aedf42c7f4149d1a506c0568

With an existing user the error should not occur, if it still does (for example empty string as home directory in /etc/passwd?) please open an issue.

**Comment by ingwinlu** [comment]
@markus2330 I think this can be closed as it is a non issue anymore

**Comment by markus2330** [comment]
Thank you! The only left-over is the documentation in TESTING.md as described in  #1888
