### ISSUE TITLE
rest-frontend: npm warnings

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#1930]
## Steps to Reproduce the Problem

Build rest-frontend according to docs.

## Expected Result

Install succeeds without warnings / errors

## Actual Result

npm shows warnings:
```
npm WARN deprecated angular-ui-router@0.4.3: This npm package 'angular-ui-router' has been renamed to '@uirouter/angularjs'. Please update your package.json. See https://ui-router.github.io/blog/uirouter-scoped-packages/
npm WARN deprecated http2@3.3.7: Use the built-in module in node 9.0.0 or newer, instead
npm WARN deprecated connect@2.4.6: connect 2.x series is deprecated
npm WARN deprecated minimatch@0.0.5: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! rest-frontend@1.0.0 postinstall: `./node_modules/grunt-cli/bin/grunt install`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the rest-frontend@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins/.npm/_logs/2018-04-19T11_56_07_908Z-debug.log
```

## System Information

- Elektra Version: master
- nodejs: v9.11.1
- npm: 5.6.0

## Additional logs
- [npm log](https://cloud.heroicdebugging.biz/s/SaRbspLH8Koc4yi)

**Comment by markus2330** [comment]
Thank you for reporting the problem!

Can you please post the mentioned log and which version of nodejs you used?

Nodejs as present in Debian is unfortunately way to old, the version should be >6 (npm version > 3.10)

**Comment by ingwinlu** [comment]
updated op with the wanted information

**Comment by markus2330** [comment]
According to https://stackoverflow.com/questions/44845335/npm-elifecycle-error/44847242 it might be that the port is already used.

@Namoshek Do you have an idea what the error above means or how to fix it?

Btw. if you want you can take a look at #1929

**Comment by Namoshek** [comment]
Actually, neither of the logs are giving a good hint on the issue. My best guess would be that the grunt task `create-website-sitemap` fails [here](../blob/master/src/tools/rest-frontend/resources/grunt-tasks/grunt-create-website-sitemap.js#L83) because of the backend not being online.

Of the warnings, only the first one is a direct dependency. The other ones are dep-dependencies and would probably require the direct dependencies to be updated (if the dep-deps are updated in a newer version, which isn't necessarily the case). But as this can also break things quite easily, I wouldn't suggest to do so.

Btw. if someone is willing to try, it would probably be an idea to switch from npm to yarn...
