### ISSUE TITLE
shellrecorder tests should only require POSIX

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1938]
## Steps to Reproduce the Problem

As reported in #1936 

## Expected Result

The test should disable itself. Elektra should compile and have a complete successful test run on every POSIX 2008 System with cmake 3.0.

Non-POSIX languages like ruby are not part of such a system. Basically only sed+awk can be used.

## Actual Result

As reported in #1936, the test seems to run nevertheless (and fails without error message as described in #1936)

## Further Information

@ingwinlu @sanssecours Do you know which test cases are affected?

**Comment by sanssecours** [comment]
> Elektra should compile and have a complete successful test run on every POSIX 2008 System with cmake 3.0.

I think requiring **only** POSIX 2008 compatibility for testing is too restrictive. For example, `bash` is [not part of the POSIX standard](http://pubs.opengroup.org/onlinepubs/9699919799.2008edition/) as far as I can tell. If we are serious about this issue we would have to rewrite the [Markdown Shell Recorder](https://master.libelektra.org/tests/shell/shell_recorder/tutorial_wrapper) using only `sh`. While that is certainly possible, I think doing that would be neither fun nor worth the time, as the mainstream desktop Unix systems (macOS, Linux) ship with Bash anyway. Another option would be to disable all Markdown Shell Recorder tests on systems without Bash.

> Do you know which test cases are affected?

I only used `ruby` in the Markdown Shell Recorder test of YAML CPP, since the `sh` version of `printf` does not support hexadecimal escape values (`\x…`). I do not know other places where I used non-POSIX commands, although there might be some locations where I might have used non-standard functionality of POSIX tools.

I opened a new PR that should fix the issue concerning the Ruby requirement [here](https://github.com/ElektraInitiative/libelektra/pull/1939).

**Comment by markus2330** [comment]
Yes, actually I wanted shell recorder to use `sh` from the beginning. @tom-wa added some features which required bash. I am afraid now there would be considerable effort nobody to get rid of this.

Anyway, without having tests on our build server that check if everything works without bash we would soon get regressions.

So we should take one step after the other:

1. What we should tests is if Elektra works with a minimal Debian. (Which has bash but no ruby.)
2. Then we should try to get all tests running on OpenWRT (Which does not have bash.)

**Comment by ingwinlu** [comment]
it is not just bash, but currently a lot of utils are used with nonposix features required.
I already fixed some in #2063 but stuff like `grep --text` will probably problematic on non gnu systems (busybox based systems, bsd, ...).

The markdown shell recorder heavily uses `<<<` which in itself is not a problem if you want to replace it, but it also uses globals a lot that are not playing nice with subshells needed by typical alternatives.

I too feel like patching it in its current state is out of the question. A rewrite would be necessary.

for alpine (again busybox) I will disable all shell recorder tests for now, which is a shame as they provide good coverage.

**Comment by markus2330** [comment]
Thank you for getting so far!

Can you mark these places you have found with TODOs?

Is it maybe possible to run the shell recorder with a subset of features? (comparing output/stderr and return codes should already cover most of the test cases) I am afraid that a rewrite is not going to happen anytime soon.

**Comment by markus2330** [comment]
The shellrecorder now is fixed.
