### ISSUE TITLE
Possibility to retrieve namespaces as std::vector<string> without key

### ISSUE THREAD

**Issue by 0003088** [ElektraInitiative/libelektra#195]
AFAIK, it is only possible to get the namespace of a key object, but not to list all available namespaces without a key. If this possibility would exist however, the gui could automatically adapt if new namespaces come into existence or are abandoned.

**Comment by markus2330** [comment]
0003088 wrote:
> AFAIK, it is only possible to get the namespace of a key object, but not to
> list all available namespaces without a key. If this possibility would
> exist however, the gui could automatically adapt if new namespaces come
> into existence or are abandoned.

It would be easy to list all available namespaces, but it is not possible to 
list all relevant namespaces.

E.g. proc is reserved for command-line arguments (or other per-process 
configuration) and does not really make sense in the GUI. It would always be 
empty and all changes would lost after exiting the GUI.

So a per-application mapping is needed and  this can be done with 
keyGetNamespace(). An example is given in examples/namespace.c.

This switch-style approach has the advantage that when new namespaces are 
added clients get a warning that a new namespace exists. Then they can add 
support for it or just add it in a do-nothing branch.

Abandoning of namespaces is not possible without breaking compatibility, so 
this can only happen in the 1.0 release.

For the gui currently relevant are: spec, user, system.

dir will be relevant later, but it is not fully functional and won't be 
advertised in the release, so its better to leave it out for now.

Supporting cascading names would be very nice, but that would be a completely 
new feature because it works different. (The application would have to do a 
ksLookup for every key in spec)

**Comment by 0003088** [comment]
Thank you, I thought *all* namespaces should show up in the gui. Closing.
