### ISSUE TITLE
improve dev env

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#1956]
I started writing a small script that allows devs to use Elektra from the build directory without installing Elektra (or without interfering with the already installed version).

To make everything work, there are some further tasks, though:

- [x] move man pages to subdirectories (man1 and man7) to make MANPATH work
- [x] allow multiple paths for KDB_EXEC_PATH (in list-tools, and external.cpp, related to  #1912)
- [ ] src/libs/tools/src/plugindatabase.cpp only lists compiled-in path for plugins (and not LD_LIBRARY_PATH)
- [ ] scripts/include-common cannot be sourced from zsh because `which` in zsh returns something unexpected, to be fixed with #1958

**Comment by markus2330** [comment]
@sanssecours can you try to run ". scripts/run_dev_env ~build" with #1958?

Afterwards the `kdb` commands, plugins and so on from the build directory should be used.

**Comment by sanssecours** [comment]
> @sanssecours can you try to run ". scripts/run_dev_env ~build" with #1958?

The command fails with the message

```
bash: ./include-common: No such file or directory
```

on my machine, If I use `bash`. I am not sure about `~build` in the command you provided. As far as I know `~build` should expand to the home directory of the user `build`. The following text shows the output of `. scripts/run_dev_env build`:

```
bash: ./include-common: No such file or directory
readlink: illegal option -- f
usage: readlink [-n] [file ...
```

. If I run `. ./run_dev_env` from within the `scripts` directory everything seems fine. However, in this case `PATH` contains the wrong directory:

> …Elektra/scripts/bin

instead of

> …Elektra/build/bin

. I think the command `source` (aka `.`), which sets `SCRIPTS_DIR` to `.` instead of `scripts`, is the problem. If I use 

```sh
bash scripts/run_dev_env build
```

inside the root of the repository instead of 

```sh
source scripts/run_dev_env build
```
everything seems to work correctly. I assume the command `source` does not set the value of `$0` to the path of the executed script (`scripts/run_dev_env`).

**Comment by sanssecours** [comment]
> What do you think about the usefulness of this script?

It might be useful for a Bash user, especially if you add the `MANPATH` functionality. I do not think I will use the script, since

- I use [`fish`](http://fishshell.com),
- my `config.fish` already adds `build/bin` to `PATH` if it exists, and 
- setting `LD_LIBRARY_PATH` does not work on macOS (anymore), if [SIP](https://en.wikipedia.org/wiki/System_Integrity_Protection) is enabled

.

**Comment by sanssecours** [comment]
> Should we move the man pages?

I think that make sense, if setting `MANPATH` works correctly afterwards.

**Comment by markus2330** [comment]
> I use fish,

Is there no chance that the script may work with fish?

> config.fish already adds

Doesn't this hide your installed Elektra?

>   I think that make sense, if setting MANPATH works correctly afterwards.

When setting the MANPATH *only* the Elektra man pages are shown (and no other man pages work). So it might not be your definition of "correctly".

**Comment by markus2330** [comment]
> if in fish

okay, seems like we need a different script for fish.

> You are definitely right, I still would like to read the man pages of the other tools installed on my machine blush.

Yes, thus the idea to have a separate dev env which changes everything in a way so that Elektra from the build directory is used.

MANPATH could mostly be fixed by adding commonly used man directories. But we cannot easily replicate everything as present in /etc/manpath.config

What I would be interested is if the changes in include-common still work for Mac OS X with #1958?

**Comment by sanssecours** [comment]
> What I would be interested is if the changes in include-common still work for Mac OS X with #1958?

If you talk about the `readlink` replacement, I think that code still works on macOS:

```sh
readlink -f '/tmp'
# STDERR: readlink: illegal option -- f.*
cd scripts
source include-common
readlink -f "/tmp"
#> //private/tmp
```

.
