### ISSUE TITLE
qt-gui: qt-gui configuration display/behaviour

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#199]
When I change the in-editor colors (btw. why is there a double-click needed?) the "user" tree view still stays empty. Only after a restart I see the keys below sw/libelektra.org/qt-gui/#0. Or even more strange, when I have some changes and press on "Sync", I only see user/sw even though the other keys are there (as seen when restarted). Expected behaviour: show them correctly when Sync is pressed.

Additionally, it would be enough if only changed colors are stored. When the settings dialoge is only visited once (and nothing is done or "Reset to defaults" is pressed) a full storage of all colors is triggered. Suggestion: Make "Reset to defaults" a button next to close which removes user/sw/libelektra.org/qt-gui/#0.

**Comment by 0003088** [comment]
This was actually a view-update problem. The keys were there, you just could not see them because the green triangle did not appear. Unfortunately the treeView does not update itself automatically like the native views, you always have to take care that everything looks as it should. Its a PITA really. They appear now correctly after synchronizing.
