### ISSUE TITLE
parallelize tests/kdb

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2024]
The tests in tests/kdb are some of the longest running tests in the repository. They currently have to be run serial as they all modify the key database.

Can we create a tmpdir for each of those tests with a new key database for each of the test suites?
This would shave some time of the more expensive test runs.

**Comment by markus2330** [comment]
Thank you for reporting the problem!

> Can we create a tmpdir for each of those tests with a new key database for each of the test suites?

Tests write into the system and spec namespaces, which are paths fixed at compile-time. So it would only be possible:

1. if we recompile Elektra for every test (or parts of tests).
2. fix the race tests #137 and the semlock plugin #1399 which would completely serialize all KDB accesses to avoid any conflict. Then parallel access would not matter, except if the very same key is overwritten which should not happen because we use /tests/testname as prefixes.
