### ISSUE TITLE
crypto plugins do not test for gpg availability

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2076]
## Steps to Reproduce the Problem

* build elektra on alpine
* gpg is not available when installing a minimal set of requirements
```
apk add --no-cache \
    build-base \
    cmake \
    git \
    file \
    curl
```

After the finished build run ctest and fcrypto obviously fails as gpg is not available. The others are excluded by cmake as their additional libs are not available.

## Expected Result

crypto modules check their requirements during cmake

## Actual Result

crypto modules at least miss checking if gpg is available

## System Information

- Elektra Version: master
- alpine:3.7

## Further Log Files and Output

will be added once https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2063/52 ran through

**Comment by markus2330** [comment]
Thank you for reporting the problem! And it is absolutely great that you try Elektra on other distros!

Removing the modules is not the right choice because gpg is not a build dependency. It is only an installation/testing dependency. But here you are right, the tests should disable themselves if no gpg can be found.

@petermax2 Do you have time to fix this?

**Comment by petermax2** [comment]
> Removing the modules is not the right choice because gpg is not a build dependency.

Fully agreed!

> Do you have time to fix this?

I guess I can spare a few minutes. The code to check if gpg is available is already lounging around in `gpg.c` somewhere, so in theory it is quite simple to disable the tests if `gpg` is not available.

I will have a look at it in the evening.
