### ISSUE TITLE
Outdated Link for Coverage

### ISSUE THREAD

**Issue by ingwinlu** [ElektraInitiative/libelektra#2096]
https://github.com/ElektraInitiative/libelektra/blob/master/README.md has a coverage link at the bottom that refs https://doc.libelektra.org/coverage/latest.

This should be replaced with https://doc.libelektra.org/coverage/master/debian-stable-full/ or the directory above.

**Comment by markus2330** [comment]
Thank you, fixed in af9bcfd622b5b98ddcf6a90ef744aa06c744c72e

You can push such minor things (typos, wrong URLs, etc.) directly into master.

The coverage view contains very long file names like "libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA/". I think we had a script to get rid of the common path. Do you know why this does not work anymore?

**Comment by ingwinlu** [comment]
the script is in full effect as it is stripping /home/jenkins/workspace from all paths. that is the name of the base dir. to get rid of it we would have to modify our checkouts and the build script to not operate on the top level of the workspace.

**Comment by ingwinlu** [comment]
Or we could set COVERAGE_PREFIX from ${PROJECT_SOURCE_DIR}/.. to ${PROJECT_SOURCE_DIR}

**Comment by ingwinlu** [comment]
@markus2330 why is that not the default? should we change the default or just set it on the build server?

**Comment by markus2330** [comment]
I think the reason was that the coverage included some other libs. In this situation it was useful to see the project dir (which was called "libelektra" or similar). Then you knew if the coverage was related to Elektra's source (or to other libs/header files).

If this problem is gone, changing the default seems useful.

**Comment by ingwinlu** [comment]
resolved via #2098
