### ISSUE TITLE
Writing a Plugin README.md

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2145]
I want to write an appropriate README for a potential new plugin.

I found a documentation [here](https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/plugins.md) but it does not state what should all be included and how it should look like.

Specifically I want to propose a new Checker plugin and the Maintainer @markus2330 also wants to have Relax NG in it but I cannot find a section where it describes where and how it should be used.

Is there any source of information which gives a more detailled explanation?

**Comment by markus2330** [comment]
Thank you for writing the question here!

> I found a documentation here but it does not state what should all be included and how it should look like.

Can you please more specific about what is missing? What do you mean with "should be included" and "should look like". Obviously it depends on what the plugin should do. I tried to clarify that in #2135. (Sorry for mixing so much stuff into one PR.)

> Specifically I want to propose a new Checker plugin and the Maintainer @markus2330 also wants to have Relax NG in it but I cannot find a section where it describes where and how it should be used.

[Relax NG](http://www.relaxng.org/) is not part of Elektra but a separate project. I mentioned it because what we plan with recursive specifications is already solved in Relax NG quite nicely.

> Is there any source of information which gives a more detailled explanation?

https://book.libelektra.org explains the contract (README.md) in more detail.

**Comment by Piankero** [comment]
> Can you please more specific about what is missing?
Maybe we are talking about different things here? I would like to propose a new plugin idea and how it could look like, eg. syntax, functionality, examples, etc. The [plugin documentation](https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/plugins.md) gives already implementation specific requirements and details.

I was more like asking for some sort of "template" like you have in here for submitting a bug ticket.

> Relax NG is not part of Elektra but a separate project. I mentioned it because what we plan with recursive specifications is already solved in Relax NG quite nicely.

I have taken a look into Relax NG but I am still a bit confused how I can use it to solve recursive specifications. Do you mean be mapping keys into an Relax NG XML schemata and checking for errors there?

**Comment by e1528532** [comment]
We have a template for plugins in src/plugins/template that you use via the script ../../scripts/copy-template if you mean that

**Comment by markus2330** [comment]
> Maybe we are talking about different things here?

I am not yet talking about something because I did not understand your initial sentences :wink: 

For which plugin do you have which question?

> I was more like asking for some sort of "template" like you have in here for submitting a bug ticket.

We only have templates of plugins not doing anything like Armin explained. It is also mentioned in the tutorial.

> Do you mean be mapping keys into an Relax NG XML schemata and checking for errors there?

Generating an Relax NG out of Elektra's specification and actually using Relax NG would be a possibility. But I was more thinking about that you have a look of how they specify data. I am afraid we won't be able to use it 1:1 because key/value and semi-structured data has some important differences: key/value allows holes, which are not allowed in semi-structured data.

You might also have a look at the struct checker. I maybe already does most of what we need. The recursive check is not implemented but it is obvious of how it can be added.

**Comment by Piankero** [comment]
I want to try to implement a rekursion plugin which checks for endless loops or configuration settings which are not existent. You required me to write a Plugin "README.md" for that and also want me to look at Relax NG.

So I am questioning what at all I have to write and how it relates to Relax NG. 
[This](https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/plugins.md) does not help at all as it already deals with the implementation itself. I want to show you my basic idea of the plugin so you can tell me if it is a good idea/ better options/ etc. 

Again, your plugin template and documentation is just useful for me, when I already know what I want to accomplish with a new plugin , not beforehand.

Maybe give me an example README.md?
When I look at the [enum plugin](https://github.com/ElektraInitiative/libelektra/tree/master/src/plugins/enum) for example, is this a README you actually want?

**Comment by markus2330** [comment]
Relax NG is only related work. I only asked to look at it. You do not have to use it. Please open separate issues for separate questions, otherwise the threads get confusing.

The tutorial obviously cannot cover how to write plugins that were never written before, so it is unclear to me what you expected. Please tell us about your expectations so that we can improve the tutorial.

Writing the README.md beforehand is to not lose time in implementation when the idea was flawed to begin with. My goal is  to promote documentation-driven/test-driven development in a way that the tests and docu can actually be used afterwards.

You can use any of the README.md as example, they are rendered more nicely here: https://www.libelektra.org/plugins/readme
I think you will easily see which of the README.md do not have good quality :smile: 
Any improvements of documentation are very welcomed.

**Comment by Piankero** [comment]
Ok, I think the best is that I give you an example of what I expect.

The best example for me is the bitcoin environment. If users want to improve the blockchain technology they first have to provide a sort of README which says what they want to improve and how could it look like.

Take [https://github.com/bitcoin/bips/blob/master/bip-0009.mediawiki](this) as an example. It states the Motivation, implementation possibilities, etc.

Your documentation says something more like this to me: "If you want to implement a plugin, this is how you do that. Implement interface A,B,C and you are done" (just with way more detail but I hope you get my point).

**Comment by markus2330** [comment]
I see. Do you really want such a detailed description of what to do? Implementing such a detailed proposal does not really sound like that there is any creativity involved.

I also sometimes give such detailed descriptions (e.g. in form of design decisions) but only if somebody cannot come up with a solution or multiple persons are involved. So my idea was that you draft such a document (in the form of README.md so that we do not have to discard it afterwards) and I'll check if it sounds plausible, is consistent with others and so on.

**Comment by Piankero** [comment]
> I see. Do you really want such a detailed description of what to do?

Yes and no. Just some minor guidelines would be helpful at least so you can be assured to have all the necessary information to judge about the new plugin/proposal/etc.

I will though now take any of your already present README.md's from the plugins directory and try to stick to this approach.

Thank you for your help!
