### ISSUE TITLE
Improve email notifications

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2146]
The first email I got was:
```
Build libelektra/master:159 failed with null.
> https://build.libelektra.org/job/libelektra/job/master/159/ <
```

There is some room for improvement:
- [ ] Do not send emails for aborted jobs (which happen if commits on master are too frequent)
- [ ] send git SHA1
- [ ] The message "null" is not really informative

I'll ask next meeting who is interested in getting (improved) email notifications from Jenkins.

**Comment by ingwinlu** [comment]
> send git SHA1 

not easily possible as at the point in time we send the mail we do not have a repo checked out (only the checkout process adds the GIT variables to the environment)

> Do not send emails for aborted jobs (which happen if commits on master are too frequent)

Initially I thought that would be easy. As it turns out we can not reliably determine the reason for the abort (neither exception type nor build status is set correctly at the time we have to handle the mail send). We could match on the abort message but that feels hacky.

I also tried the mail-ext plugin (which offers triggers similar to travis) but could not get it to work with pipelines.

**Comment by markus2330** [comment]
Isn't the SHA1 available? How does Jenkins knows which commit to build? When clicking on the link the SHA1 is immediately visible, I was hoping that I do not need to click on the link for that.

> We could match on the abort message but that feels hacky.

Why? We do the exec.interrupt ourself so it is not wrong to match using this string. Because it is the same file no duplication of that string is needed.

**Comment by ingwinlu** [comment]
> sha1

jenkins knows because it processes it before going into the pipeline sandbox. in the sandbox we have the scm object (which can be of the GitSCM class). Usually the git environment variables are set from the scm object during the checkout. 

I have not confirmed it yet but before the checkout there should not be a hash available as that is determined after checkout via the supplied refspec.

**Comment by markus2330** [comment]
What also would be important for future Jenkinsfile maintenance: Which parts can be modified easily and at which parts there might be dragons? (Like important environment variables missing.)
