### ISSUE TITLE
cpptemplate: unit tests hangs

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2160]
## Steps to Reproduce the Problem

Install Debian Packages and run `kdb testmod_cpptemplate`

## Expected Result

Either success or failure (because cpptemplate plugin is not installed)

## Actual Result

The tests hangs with 100% CPU on one core:

```
--- running testmod_cpptemplate ---


Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from cpptemplate
[ RUN      ] cpptemplate.basics
/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/plugins/cpptemplate/testmod_cpptemplate.cpp:29: Failure
Value of: plugin != __null
  Actual: false
Expected: true
Could not open cpptemplate plugin
```

## System Information

- Elektra Version: master

## Discussion

Is it useful to have the cpptemplate to be compiled by default? Iirc "template" does not get compiled because of its infos/status.

**Comment by sanssecours** [comment]
Since I do not use Debian I tried to reproduce the bug using the following commands:

```sh
ninja install
rm /usr/local/lib/elektra/libelektra-cpptemplate.so
kdb testmod_cpptemplate
```

. The last command produces the following output on my system:

```
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from cpptemplate
[ RUN      ] cpptemplate.basics
../src/plugins/cpptemplate/testmod_cpptemplate.cpp:29: Failure
Value of: plugin != __null
  Actual: false
Expected: true
Could not open cpptemplate plugin
fish: 'kdb testmod_cpptemplate' terminated by signal SIGSEGV (Address boundary error)
```

. As you can see the test process does not stall but fails with a segmentation fault. I opened [a pull request that should fix the problem](https://github.com/ElektraInitiative/libelektra/pull/2165) described above:

```
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from cpptemplate
[ RUN      ] cpptemplate.basics
../src/plugins/cpptemplate/testmod_cpptemplate.cpp:29: Failure
Value of: plugin != __null
  Actual: false
Expected: true
Could not open cpptemplate plugin
```

. I hope this update also works for you. Can you please check, if the updated code does indeed fix your problem too?

> Is it useful to have the cpptemplate to be compiled by default?

Probably not. I added the tag `experimental` to the plugin status in PR #2165.

**Comment by markus2330** [comment]
Thank you!

**Comment by markus2330** [comment]
The hang might be caused by #2170
