### ISSUE TITLE
Evaluate Stack for Haskell Builds

### ISSUE THREAD

**Issue by e1528532** [ElektraInitiative/libelektra#2204]
Since the builds with cabal seem very unstable, evaluate whether using stack makes sense.
Stack seems to be much more focussed on stability, reproducability and long-term support: https://docs.haskellstack.org/en/stable/GUIDE/
As far as i understood it completely sandboxes ghc / cabal / alex and everything instead of using system packages, locked to a fixed set of packages to avoid regressions, i think it makes sense because we just have too many issues otherwise. It would also help with issues where e.g. xenial provides too old ghc packages.

**Comment by markus2330** [comment]
Thank you for looking into it!

Having a completely separate ghc/cabal/alex, however, also has disadvantage and distributions like Debian would never package Elektra this way. So we should still support to use the system ghc/cabal/alex.

If stack resolves the problem @Piankero has (it most likely does) it is a great additional option for distributions that do not maintain ghc/cabal/alex.

**Comment by markus2330** [comment]
If stack supports the system ghc and still works without problems it sounds like a very good thing. I also had troubles running your plugin but I would not go as far as installing a new ghc.

> Building debian packages with stack doesn't seem impossible though

not impossible != acceptable effort

The haskell parts are not in the Debian package anyway but we might make it more difficult if someone tries. But I cannot really tell, I do not have any experience in packaging Haskell programs. I only mentioned it so that you are aware. Making the developers lives easier (automatic downloading of random packages from the Internet) often implies making the package maintainers life a lot harder.

**Comment by e1528532** [comment]
Ultimately i think i've managed to make it compatible with lts-7.24 now as debian stretch was the "lower bound" for haskell before.
Still in case one uses e.g. xenial we need to link the appropriate haskell runtimes or ship them with elektra anyway cause we can't use the system ones. So ultimately i think there is no real way around that.

**Comment by markus2330** [comment]
@e1528532  Are you still working on this?

Seems like the building of haskell is now broken, see #2585

**Comment by markus2330** [comment]
We do not use Haskell anymore.
