### ISSUE TITLE
resolver: testmod_resolver missing

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#2226]
The problem seems to be related to using plugin variants. When plugin compile variants are used, `add_plugintest` does not seem to build the test. Resolver is one of the affected plugins.

## Expected Result

`testmod_resolver` is built.

## Actual Result

`testmod_resolver` is **not** built.

## System Information

- Elektra Version: master

**Comment by ingwinlu** [comment]
Can you tell us what you passed to cmake so that we can replicate what configuration you were trying to build?

If you did only set some plugins during configuration, please note that there is a set of minimal required plugins needed for elektra to build + run: https://github.com/ElektraInitiative/libelektra/blob/master/doc/COMPILE.md#plugins

**Comment by mpranj** [comment]
`add_plugintest` seems to work when linked to the same name:
```
add_plugintest (crypto_openssl LINK_PLUGIN "crypto_openssl")
```
In the case of resolver, the names do not match. The test is added for `resolver` but then linked to `resolver_fm_hpu_b`. Maybe that has something to do with it.

**Comment by markus2330** [comment]
Thank you for reporting the problems!
I see two grave problems here:

1. add_plugintest doing nothing without any error
2. testmod_resolver not being built and executed

**Comment by mpranj** [comment]
Seems this was resolved but not closed?
