### ISSUE TITLE
resolver: check if update is needed

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#2249]
The `resolver` checks the file modification time to determine whether the storage plugin needs to read the file again. Other resolvers do it similarly (using timestamps, git commit-id, ... ). This only works within one KDB instance, once the resolver(s) have populated their data (and timestamps).

For the global cache it is necessary to store the change indicators (e.g. timestamps) within the cache. We then need a way to let the resolvers check whether the timestamp of the cached data still corresponds to the timestamp of the original config file. In other words, we need a check whether the cached data is up-to-date.

In a private email @markus2330 suggested that it might be necessary to change the plugin interface and export an additional function for this purpose or to change the kdbGet() logic. He also noted, that @tom-wa might have some ideas because of his work on the multifile resolver.
According to markus, the multifile resolver solves a similar problem, but I fail to see the similarity.

The issue is open to find and document a solution, so all suggestions are welcome.

**Comment by mpranj** [comment]
My initial idea for this was not to export and additional plugin function. It should also be possible to inject such a timestamp into the resolver by adding metadata to the parentKey. That still implies that the resolvers need to implement the desired functionality.

**Comment by markus2330** [comment]
> According to markus, the multifile resolver solves a similar problem, but I fail to see the similarity.

What I mean here is that multifile uses functions (in particular the function "filename") and enums of resolver. It only uses it to resolve filenames but not to get the timestamp. Something similar could be done to get the timestamps.

Alternatively, we could change the resolvers so that they check for the mmap file during their regular execution. The string of the parentKey could contain the timestamp to compare with for that purpose. And resolvers which are already up-to-date with the cache could return 0. (They already do this now but never during the first run of kdbGet()).

**Comment by mpranj** [comment]
This was solved by adding the Global KeySet interface.

**Comment by markus2330** [comment]
Seems like the stale bot does not recognize that the manual closing means, that this issue actually was not stale (but already fixed). I removed the stale label here.
