### ISSUE TITLE
Plugins: testmod dependencies

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2265]
Is there any reason, why the `testmod_*` CMake-targets for the plugins do not depend on the target for the plugin library?

Adding the dependency would allow simply building a `testmod_*` target and executing the resulting executable to test a plugin, without having to rebuild the plugin itself. Which makes plugin development in IDEs like CLion much easier.

**Comment by markus2330** [comment]
The dependency was forgotten because the plugin library is always built anyway and it seems like nobody tried to build the testmod_ targets without building "all" first.

But you are completely right, the dependency should be there. Maybe we can simply add the dependency at one place in add_plugintest?
