### ISSUE TITLE
libgtest.so missed

### ISSUE THREAD

**Issue by beku** [ElektraInitiative/libelektra#229]
Installation of a libelektra-devel RPM fails with following text

buildinfo is broken... it says:
unresolvable: nothing provides libgtest.so()(64bit) needed by libelektra-devel, nothing provides libgtest_main.so()(64bit) needed by libelektra-devel

The reason might be that libgtest is not in the system available and the local build is not installed.  Some solutions come to mind, which I'd like to discuss.
* Disable gtest building at all in elektra's cmake build system
* remove all installed test files afterwards (not nice) or disable testing and avoid the dependency
* link a static variant of libgtest to the binaries

**Comment by beku** [comment]
oops, with "Disable gtest building at all in elektra's cmake build system" I mean, disable in case no system libgtest is provided and a static build is requested.

**Comment by markus2330** [comment]
Hello,

Thank you for reporting this issue!

Kai-Uwe Behrmann wrote:
> oops, with "Disable gtest building at all in elektra's cmake build system"
> I mean, disable in case no system libgtest is provided and a static build
> is requested.

Elektra should always use an internal copy of gtest. Only tests should use it, 
so it certainly should not influence the package libelektra-devel.

And tests should always be statically linked against gtest. Maybe 
"BUILD_SHARED_LIBS" influences the build in an unpredicted way, is it possible 
that this cmake variable is set?

If this was the problem it is now fixed in 
5934922c306b14858a998cd9ff5470111d095c6a

BUILD_SHARED_LIBS should now not be used anymore.

best regards,
Markus

**Comment by beku** [comment]
Tested and solved by your commit. 
Thanks for the quick fix
