### ISSUE TITLE
ruby plugin: compilation fails for OpenWRT

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2302]
See https://github.com/openwrt/packages/pull/7610 the compilation of the static variant of the ruby plugin fails for OpenWRT.

A possible solution is to use ONLY_SHARED which would disable the static (and full) build altogether.

@BernhardDenner What do you think?

**Comment by BernhardDenner** [comment]
I'm not really sure why the static libs are built anyway, since they use `BUILD_STATIC=OFF` as far as I see. I never could reproduce the problem.

Anyway, it seems, these problems are coming from `libruby` itself and not from our plugin. 

From my point of view, it should make sense to disable the static build for the ruby plugin, since I someone really cares about the footprint of the used libs a scripting language like Ruby will be excluded anyway ;)

**Comment by markus2330** [comment]
Thank you for the analysis! Can you add ONLY_SHARED in your PR?
