### ISSUE TITLE
qt-gui: rewrites all configuration files

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#235]
Due to internal handling in qt-gui all keys are marked as not synchronized. As such all configuration files are rewritten.

This is a major problem for many usecases, e.g. when the user of the gui does not have access permissions to all files.

Currently, workarounds exist for version, uname and constants plugins.

The first step would be to find all places where keys are changed unnecessarily. (e.g. string and meta data is reapplied even though it has not changed and places where keys are duplicated)

The solution does not necessarily only effect qt-gui, maybe we can make keys more intelligent so that they only marked as synchronized when it is really necessary. E.g. setting the same string again could be detected.

**Comment by 0003088** [comment]
Ok, I will rewrite the rename method so that only changed names,values and metadata are set to keys. But what about duplication? What exactly is the problem here?

**Comment by markus2330** [comment]
A duplicated key currently is always marked for needSync.

It works the following way:
kdbGet() -> all keys are *not* marked as needSync
if a kdbSet() is done directly afterwards, no configuration file will be written out
if a key is marked as needSync (done automatically on any changes in any key or keyset), then the involved configuration file is written using kdbSet() (others are not)

reinserting a duplicated key currently is considered as change, even if the KeySet is equal afterwards. So the currently visitor strategy would yield a new KeySet. I tried to fix that, but it was not enough: there seem to be other sources of modification, too.

Btw. inserting all Keys into another KeySet (without duplication!) should actually be equal to using the original keyset.

**Comment by markus2330** [comment]
To use ksDup() (or dup() on a keyset) does not cause any trouble: the keys won't get duplicated but only their reference counter is incremented.

To reproduce the bug, either look at the modification-time of any configuration file under Elektra's control.

Or simply mount a configuration file you do not have write-access to. Then you will see an error message even though you did not modify configuration from this particular file.

**Comment by 0003088** [comment]
Ok, I understand the problem now. You expect that nothing is written to file when the gui is started, the config is left in its default state and 'synchronize' is pushed? But that would only work if we would kdb.set() the exact same keyset that we got with kdb.get(), wouldn't it?. But that's not the case, even when I remove the dups(). The chain of events is like this:

1) the current config is parsed with kdb.get() in main.cpp and handed to the treemodel
2) the keyset is stored in GUIBasicKeySet to have a basic keyset for the threeway merge. Initially this was a deep copy, I created a new set and filled it with dup() keys. For testing purposes I changed it to a shallow copy for the moment.
3) the original keyset is then handed to createNewNodes(). Every key is looked at and the hierarchy is created. Initially I duped every key, but I removed this for the moment as well. The original keyset is discarded after this.
4) When synchronizing, the current config is collected (initially via dup, changed it ftm) to have an 'ours' set. The 'theirs' set is fetched with kdb.get() and the basic keyset is the copy of the original keyset. Then the sets are merged and an entirely new fourth keyset is the one that is written back with kdb.set(). Since the merged keyset is not the same we got initially, every key is written back to the file (at least that is my understanding, maybe you can clarify one thing or another). 

BR

**Comment by markus2330** [comment]
So the only left-over problematic part is the merging? @fberlakovich is it possible that 'ours' keys are copied unchanged (without duping) when no actual merging occurs?

Btw. Why is merged used every time? Basically, you only need to merge if kdbSet() failed.

**Comment by 0003088** [comment]
> So the only left-over problematic part is the merging?

I have not tested if anything is broken  but in general: yes

> Btw. Why is merged used every time? Basically, you only need to merge if kdbSet() failed.

I was not aware of the fact that merging poses a problem when I wrote the code. It's an easy fix though.

**Comment by markus2330** [comment]
You can easily test it by just fixing the merging (only merge when kdbSet() returned an error). The left-over problem then (rewriting everything in the case a real conflict happened) is *much* less severe and only effects the merging code.

Can you do the fix and create a merge request?

Thanks for your investigations!

**Comment by 0003088** [comment]
Sure. Won't be today I'm afraid but tomorrow or monday.
