### ISSUE TITLE
KDB_DB_SPEC vs KDB_DB_SPEC_REAL

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2352]
I know `KDB_DB_SPEC_REAL` is the value of the `-DKDB_DB_SPEC` option from CMake and `KDB_DB_SPEC` is `${CMAKE_INSTALL_PREFIX}/${KDB_DB_SPEC_REAL}`.
So it seems `KDB_DB_SPEC` should only be used if `KDB_DB_SPEC_REAL` is a relative path.

The problem is the `resolver` plugin (the only usage of `KDB_DB_SPEC_REAL`) always uses it like this:
```c
if (KDB_DB_SPEC_REAL[0] == '~')
{
	char * oldPath = handle->relPath;
	char * path = elektraMalloc (filenameSize);
	strcpy (path, KDB_DB_SPEC_REAL);
	strcat (path, "/");
	strcat (path, handle->relPath);
	handle->relPath = path;
	elektraResolveSystemPasswd (handle, warningsKey);
	elektraFree (path);
	handle->relPath = oldPath;
}
else
{
	char * path = elektraMalloc (filenameSize);
	strcpy (path, KDB_DB_SPEC);
	strcat (path, "/");
	strcat (path, handle->relPath);
	handle->fullPath = path;
}
```
This code breaks if CMake is called with an absolute path for `-DKDB_DB_SPEC`.
Calling CMake with `-DKDB_DB_SPEC="/home/kodebach/.config/kdb/spec"` results in Elektra using the folder `/usr/local/home/kodebach/.config/kdb/spec`.

The question now is shouldn't there be another case in the code above like this:
```c
else if (KDB_DB_SPEC_REAL[0] == '/')
{
	char * path = elektraMalloc (filenameSize);
	strcpy (path, KDB_DB_SPEC_REAL);
	strcat (path, "/");
	strcat (path, handle->relPath);
	handle->fullPath = path;
}
```
Alternatively we could handle this case in CMake and not use `CMAKE_INSTALL_PREFIX`, if `-DKDB_DB_SPEC` is already an absolute path. Using CMake to fix this would be preferable, because `tests/shell/include_common.sh.in` uses the values from CMake as well. Although currently no test actually uses the `SPEC_FOLDER` variable.

**Comment by markus2330** [comment]
Yes: we should either fix this or reject path names starting with /. In your concrete case you could also use `~.config/kdb/spec` but maybe sometimes an absolute path is useful.

Please feel free to create a PR for the CMake fix so that KDB_DB_SPEC does not get CMAKE_INSTALL_PREFIX prefixed if it is already absolute. But this most likely will also require some improvements in the test cases. See also #1000 and #1001 for very much related problems in the test cases.
