### ISSUE TITLE
Problems with the `spec` plugin

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2389]
## Steps to Reproduce the Problem

Mount a specification, in which `spec/tests/example/somearray/#` has the `default` metakey set to some value.

## Expected Result

Calling `kdb get /tests/example/somearray/#0` should return the default value (unless we already set a different value.

## Actual Result

Depending on the rest of the configuration either the Key itself or the metakey aren't found. 

## Further Log Files and Output
see also [#2374](https://github.com/ElektraInitiative/libelektra/issues/2374#issuecomment-461837307)

**Comment by markus2330** [comment]
Thank you for reporting the problem! Can you give a complete example in shell recorder syntax which demonstrates the problem?

**Comment by kodebach** [comment]
The same problem also occurs for `_` instead of `#`. It is the reason, why both of the new examples in #2498 are somewhat broken.

Here is a shell recorder script for the version with `#`.

### Setup
```sh
cat <<-EOF > test.ini
	[]
	mountpoint = example.conf
	
	[testkey/#]
	default = 0
EOF

sudo kdb mount test.ecf spec/tests/specbroken
sudo kdb import spec/tests/specbroken ni < test.ini
sudo kdb spec-mount /tests/specbroken
```

### Expected
```sh
kdb get "/tests/specbroken/testkey/#0"
#> Did not find key '/tests/specbroken/testkey/#0'

kdb setmeta user/tests/specbroken/testkey array "#0"

kdb get "/tests/specbroken/testkey/#0"
#> 0
```
Possible the first `kdb get` should also return `0`, depending on whether array bounds are enforced or not.

For the version with `_`, I would expect that:
```sh
kdb get /tests/specbroken/testkey/something
#> 0

kdb get "/tests/specbroken/testkey/#0"
#> Did not find key '/tests/specbroken/testkey/#0'
```
### Actual
```sh
kdb get "/tests/specbroken/testkey/#0"
#> Did not find key '/tests/specbroken/testkey/#0'

kdb setmeta user/tests/specbroken/testkey array "#0"

kdb get "/tests/specbroken/testkey/#0"
#> Did not find key '/tests/specbroken/testkey/#0'
```

The following also happens, but is definitely wrong:
```sh
kdb get "/tests/specbroken/testkey/#"
#> 0
```

This also happens with `_`:
```sh
kdb get "/tests/specbroken/testkey/_"
#> 0
```

**Comment by markus2330** [comment]
Thank you for the detailed description of the problem.

I tagged it now as enhancement as it is not so clear what a default of a non-existing array should be.

Another problem (which is a bug) is that the array-specifications (that are supported by the spec plugin) are not documented at all. And as you described, that `kdb get "/tests/specbroken/testkey/#"` returns the default. Can you create a new bug report for this problem?

I think we can also argue that the default of a non-existing array is an empty array. Then not getting these elements would be expected behavior. If you want a non-empty array as default, you would need to specify something like:

```sh
cat <<-EOF > test.ini
	[]
	mountpoint = example.conf
		
	[testkey]
        array=#2 ;TBD
	default =#2 ;TBD

	[testkey/#]
	default = 0
EOF

sudo kdb mount test.ecf spec/tests/specbroken
sudo kdb import spec/tests/specbroken ni < test.ini
sudo kdb spec-mount /tests/specbroken
```

Then `kdb get /testkey/#2` could return 0, as the default array is specified to have 3 elements (`#0` to `#2`)

**Comment by kodebach** [comment]
I agree that an array should be empty by default, unless specified otherwise.

Setting `default = #2` on `testkey` is not in line with our decision, that the `array` metakey defines the size of an array.

Also both solutions (`default` and `array`) don't work, if the array size should be determined by the user. The spec plugin is mounted globally and executed last anyway, so it should just query the KeySet for the array size and then set the default for keys up to that size.

**Comment by markus2330** [comment]
> Setting default = #2 on testkey is not in line with our decision, that the array metakey defines the size of an array.

The array metakey currently, unfortunately, has two meanings: in spec it is the size specification of an array, otherwise it says that something is an array and gives the length. This should be fixed. (Maybe call the validation of arrays `check/array.)

> so it should just query the KeySet for the array size and then set the default for keys up to that size

Sounds good. In the example above, `array=#2` (in the spec) would be copied to `/testkey`. If the spec then also creates the default array with two entries, we do not need `default` in `[testkey]`. I udpated the example.
