### ISSUE TITLE
Homepage: Markdown Links to Anchors Do Not Work

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#2450]
# Steps to Reproduce the Problem

1. Search for the text “see also Data Types” in [this webpage](https://www.libelektra.org/tutorials/high-level-api). 
2. Click on the link “Data Types”.

# Expected Result

The browser scrolls to the header “Data Types”

# Actual Result

The browser tries to open 

>    https://github.com/ElektraInitiative/libelektra/tree/master/src/libs/high-level-api#data-types

, which does not exist.

# Additional Information

The problem does not occur on GitHub. If you retry the procedure from “Steps to Reproduce the Problem” [here](https://github.com/ElektraInitiative/libelektra/blob/master/src/libs/highlevel/README.md), everything will work as expected.

**Comment by markus2330** [comment]
Thank you for this beautiful description of the problem! Seems like the markdown parser for our webpage behaves differently than the one from GitHub.

@Namoshek Do you know if this problem might be caused by parts written by you (iirc you implemented some logic to handle external links vs. links to GitHub?) or by the markdown parser we use?

A solution to this problem would also be to find some other way to specify anchors which work for every markdown parser we use.

**Comment by Namoshek** [comment]
~The problem is most likely cause by this code:~

https://github.com/ElektraInitiative/libelektra/blob/55cfab8693aa654b8bf84a0882f3990b29f5fe18/src/tools/rest-frontend/resources/grunt-tasks/grunt-copy-website-content.js#L155-L167

~The snippet is invoked when the website content is built (pre-processed), i.e. links are rewritten to match our needs. I'm not sure, why it doesn't work though. Might be the markdown parser received an update that broke the anchor-links. As I don't really remember everything about the code, I can only say that the snippet obviously handles anchor tags on line 157.~

---

Ok, during writing the above, I realized I'm on the wrong path. The file fetched by the website in the background contains a link like this `[Data Types](#data-types)`, so it must be the frontend doing something wrong:

https://github.com/ElektraInitiative/libelektra/blob/55cfab8693aa654b8bf84a0882f3990b29f5fe18/src/tools/rest-frontend/resources/assets/js/config/marked.js#L26-L45

I guess a special case for anchor tags is required. Probably below line 31.

**Comment by markus2330** [comment]
Thank you so much for pointing out so fast where the problem is and how to solve it!
