### ISSUE TITLE
"setmeta fallback" on keys doesn't resolve default values

### ISSUE THREAD

**Issue by egoexpress** [ElektraInitiative/libelektra#247]
I set a default value for a key using _setmeta_. This seems to work as expected:

```shell
> kdb get /test1
Did not find key
> kdb setmeta spec/test1 default "default_value"
> kdb get /test1
default_value
```

Now I try look up __/test2__ which doesn't exist yet. Also looking good.

```shell
> kdb get /test2
Did not find key
```

Now I set __spec/test1__ to be the _fallback_ key for __spec/test2__. I expected this to yield the default value set above when I query __/test2__. Instead I get an empty string.

```shell
> kdb setmeta spec/test2 fallback/#0 spec/test1
> kdb get /test2

> kdb get /test1
default_value
```

Using __user/test1__ as _fallback_ I get "Did not find key".

```shell
> kdb setmeta spec/test2 fallback/#0 user/test1
> kdb get /test2
Did not find key
> kdb get /test1
default_value
```

This looks a bit inconsistent to me as there doesn't seem to be any info that metadata isn't supported in the fallback case.

**Comment by markus2330** [comment]
Thank you for your report!

The idea is that only the default-specification of the key itself will be considered. The lookup works recursively, but deeper nested defaults will not be considered, because otherwise other defaults and not the most specific default would be preferred.

Override/Fallback to spec-keys will interpret spec-keys as normal keys. For example:
```
> kdb setmeta spec/test1 default "default_value"
> kdb setmeta spec/test2 fallback/#0 spec/test 
> kdb set spec/test my_fallback
Create a new key spec/test with string my_fallback
> kdb get /test2
my_fallback
> kdb get /test1
default_value
```

Maybe you wanted instead:
```
> kdb setmeta spec/test2 fallback/#0 /test 
```

Then the specification of /test (=spec/test) will be used, with the exception of the default value: only the default of the key itself will be used. So if the looked-up key does not have a default, you might not find any key at all.

see also the testcase
test_lookupDoubleIndirectDefault in tests/ctest/test_spec.c


Which behaviour would you expect?

P.s. I plan to provide a -d (debug or describe) option for "kdb get".

**Comment by egoexpress** [comment]
I expected the recursion to consider default values of override/fallback keys as well. As you explained this is not the intended behaviour, so thanks for this clarification.

However, I'm still a bit baffled why I get an empty string as a return value in the example I showed [above](https://github.com/ElektraInitiative/libelektra/issues/247#issue-100304143). If the default value isn't used here, shouldn't I get a _Did not find key_  as a result?

**Comment by markus2330** [comment]
default values: when recursive default values would be considered, which would be the correct one? 

the empty string: setmeta needs to create a key (with an empty value) in order to attach the metadata to it.

Will adding following sentence

			"When a key does not exist, it will automatically created\n"
			"with an initial empty value\n"

in --help of kdb setmeta clear up the situation?

**Comment by egoexpress** [comment]
Thinking about it, I understand the issue regarding the selection of the "correct" default value when using recursion.

Adding the sentence you proposed should clear up the situation regarding the empty string.
