### ISSUE TITLE
qt-gui: any packages available? 

### ISSUE THREAD

**Issue by mhaberler** [ElektraInitiative/libelektra#251]
or is this a 'must compile from source' only feature?

**Comment by markus2330** [comment]
Thanks to @pinotree in Debian Testing 0.8.12 packages are available, but unfortunately without qt-gui.

@pinotree do you have plans to add qt-gui to the package? Maybe waiting for 0.8.13 is useful, because #235 can be very annoying. But @0003088 is working on it.

**Comment by mhaberler** [comment]
as a followup question and related to #254:
 
has any thought been given to running the qt-gui on a different host than the elektra instance - I would assume this being a common scenario?

**Comment by pinotree** [comment]
> @pinotree do you have plans to add qt-gui to the package?

After both:
- #235 is solved (possibly with a release carrying the fix)
- the GCC 5 transition currently ongoing in Debian unstable is over

**Comment by markus2330** [comment]
It was not necessary to address this especially in the GUI, because any 
Elektra-network bridge and implementation of Elektra API using the protocol of 
the bridge in question would automatically make the qt-gui network aware.

This would, however, involve some setup. So a web-gui might be easier for such 
use-cases. If you want to configure many nodes a full-blown configuration 
management tool (e.g. cfengine, puppet) is preferable anyway (using Elektra 
for a unified view).

**Comment by markus2330** [comment]
Packages are now available in Debian Unstable Elektra 0.8.14
