### ISSUE TITLE
jni: support attaching to existing JVMs

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2510]
See src/plugins/jni/jni.c line 201 we currently do not check if a JVM has already been started. If it was already started, the already running JVM should be used.

**Comment by dmoisej** [comment]
Hello,

I have encountered a lot of issues while trying to resolve it. 

Firstly, I tried to make a test testmod_jni but with no success. The problem is, that my IDE CLion doesn't include this test into the target builds. I added jni plugin as it is described in the documentation: 
`cmake -DPLUGINS="ALL;-EXPERIMENTAL;jni" /path/to/libelektra`. I did it but with some additional effort, cause there were some issues with the finding of jna.h. I resolved it with removing some code from the CMakeList.txt. But it is not the issue. The issue is, that I need to run JNI plugin and to check if there is already existing JVM. I believe, in order to check it, I need to run jni tests, so testmod_jni. 

I have very small experience with C and I also tried somehow to copypaste the CMakeList.txt from other plugins but still no success, that I can run this test. Can you give me some kind of advice please?

Secondly, what does Java Plugin means? It is written in the documentation, that in order to write plugins in Java, I can use JNI plugin. I have looked into the HelloElektra.java file and I saw, that there is such plugin on Java like Echo, which extends Plugin class. Does this mean, that in order to write a plugin in Java I should create the class, which inherits from the Plugin class?

**Comment by markus2330** [comment]
> Firstly, I tried to make a test testmod_jni but with no success.

It is rather complicated to start Java from a C program. It is easier, to write a Java application which reads/writes to a KDB with a predefined mountpoint, e.g., by having a shell recorder script which mounts a Java plugin and then runs the Java application.

> cause there were some issues with the finding of jna.h

Please report and fix the bug also for others (it will be a separate issue).

> I have very small experience with C and I also tried somehow to copypaste the CMakeList.txt

CMakeLists.txt is in CMake, another programming language which has nothing to do with C (except of the similarity of the name).

> Secondly, what does Java Plugin means?

An Elektra plugin implemented in Java.

> I can use JNI plugin

Exactly, JNI is currently the only way to implement plugins in Java.

> Does this mean, that in order to write a plugin in Java I should create the class, which inherits from the Plugin class?

Exactly. And the plugin  should return something to the Java application, so that you can overall verify that everything works (that the Java plugin can speak to the Java application).

I hope you see now why I insisted that the test needs to be a separate issue. It is not trivial.

**Comment by dmoisej** [comment]
Thank you very much for the info. The thing is, that I could execute the Echo plugin even without JNI Elektra plugin enabled, so that is a little bit strange for me.

**Comment by markus2330** [comment]
What do you mean with "execute"? Maybe you are using an installed `jni` plugin and you are only disabling it for your build folder?

**Comment by dmoisej** [comment]
I mean, I try to run HelloElektra.java file. HelloElektra uses Echo java class, which is a plugin. But as a result, HelloElektra.java is successfully executed with all outputs in the console. 

> What do you mean with "execute"? Maybe you are using an installed jni plugin and you are only disabling it for your build folder?

I am not sure about that. I will look at this issue more.

**Comment by markus2330** [comment]
> I mean, I try to run HelloElektra.java file. HelloElektra uses Echo java class, which is a plugin.

It instantiates Echo and calls a few functions but this is not the normal way how plugins should be used (actually this is only for unit tests). Instead they should be mounted (via the jni Plugin).

**Comment by dmoisej** [comment]
Okay, now I understand that much better. Just one more thing. 

> Instead they should be mounted (via the jni Plugin).
Is this the section "Plugin Config" here https://www.libelektra.org/plugins/jni?

**Comment by dmoisej** [comment]
I mean there is an example of how to mount the plugin but is there an example how to mount the plugin jni and mount via jni the java plugin?

**Comment by markus2330** [comment]
Yes, exactly! This shows how to mount a Java plugin.
