### ISSUE TITLE
Proposal: More verbose help message for configure-home script

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#2525]
The documentation (https://www.libelektra.org/devgettingstarted/testing) recommends the script configure-home to avoid issues when running all tests.

The error message says that I must create a new directory. However, I do not know why or where. My attempts were followed by "does not appear to contain CMakeLists.txt".

Help would be greatly appreciated. I'd additionally suggest to make the hints more verbose.

**Comment by markus2330** [comment]
Thank you for creating the issue!

> recommends the script configure-home to avoid issues when running all tests

Yes, it is one of four possibilities.

You do not need to run the script, it is enough to call "ccmake" and reconfigure these paths.

> The error message says that I must create a new directory. 

Which error message?

> I'd additionally suggest to make the hints more verbose.

Did you follow https://www.libelektra.org/docgettingstarted/compiling?

**Comment by kodebach** [comment]
Looking at `configure-home`, I would highly recommend against using it, because it also sets the default storage plugin to `ini`. This could cause its own problems and means you are no longer executing the same code the build server would execute.

Instead I would just recommend adding `-DKDB_DB_SYSTEM="~/.config/kdb/[name]/system" -DKDB_DB_SPEC="~/.config/kdb/[name]/spec" -DKDB_DB_USER=".config/kdb/[name]/user"  -DCMAKE_INSTALL_PREFIX=install -DINSTALL_SYSTEM_FILES=OFF` to your CMake command (`[name]` has to be replaced by a unique name for this build directory)

This ensures that even if you use multiple build directories (e.g. for Debug and Debug with ASAN) they cannot come into conflict with each other and because everything is in your home folder, there shouldn't be permission problems. Also by setting the install prefix to `install` and disabling `INSTALL_SYSTEM_FILES` a call to `make install` will not touch your system and work without `sudo`. Everything will be installed into the `install` folder in your build directory.

As far as I can tell plugins and external tools should also be recognized correctly inside of the `install` directory.

We may want to add this "guide" somewhere prominent, because in my mind, it is the best way to test Elektra without any modifications to your system.

**Comment by markus2330** [comment]
> sets the default storage plugin to ini

Thank you for pointing this out!  I changed it. 1c7be76080fbf943725c480b8bd51711ff2c48c9

> ... adding .... to your CMake command 

This is also how the sentence was meant to be interpreted. I improved the sentence  913821563090d8046da48087a6df490c6e0b9277

> We may want to add this "guide" somewhere prominent, because in my mind, it is the best way to test Elektra without any modifications to your system.

I agree it works well for developres. The problem is, that is only useful for single-user systems, because "system" and "spec" namespaces are then actually not system-wide.

**Comment by markus2330** [comment]
Btw. this config also works well in practice, it is used on the lab computers at the TU Wien. It is useful if a user is not admin of a system but wants to use Elektra as-if.

If you are admin of your system, you can simply give your write-permissions of the system and spec paths.

**Comment by Chemin1** [comment]
I wanted to try it with the script because thats what we talked about in the meeting.

> Which error message?

>> I'd additionally suggest to make the hints more verbose.

> Did you follow https://www.libelektra.org/docgettingstarted/compiling?

When I'm in `scripts` I get into the following situation
```
./configure-home
# You seem to be in the scripts directory, create a new directory and run /home/dominic/programming/libelektra/scripts/configure-home there
```
Now I do not know where to create a new directory. Is it `mkdir here` or `mkdir ../here` or `mkdir ~/here`? Making that more clear writing "create a new folder _in directory xyz_ and run".

**Comment by markus2330** [comment]
It is similar to the problem "press any button to continue", which one is "any"? But you are right, a concrete command what should be done helps, I added it.

**Comment by Chemin1** [comment]
> It is similar to the problem "press any button to continue".

This became clear to me after I got the same result with the newly provided example as with any of the ones I thought about before:

```sh
mkdir ../build && cd ../build && ../scripts/configure-home
# CMake Error: The source directory "/home/dominic/programming/libelektra/build" does not appear to contain CMakeLists.txt.
```

In the meanwhile I got it running using the cmake options only.

**Comment by markus2330** [comment]
This is now a different problem: the `configure-*` scripts need the source directory as parameter. I will add a message to indicate the problem.

Please reopen if there are further problems.
