### ISSUE TITLE
notification: meaning and status?

### ISSUE THREAD

**Issue by mhaberler** [ElektraInitiative/libelektra#253]
there seems to be some confusion over what 'notification' actually means

src/plugins/README.md says:

Send out all changes to configuration to:
- [dbus](dbus)
- [journald](journald)
- [syslog](syslog)

That is logging in my understanding.

What I consider notification, and would need:  using code which retrieves a key with kdbGet() can optionally have a callback/event notification that the value of a particular key has changed because some other thread/process did a kdbSet() on that key, giving using code the option to retrieve the updated value.

Is that possible?

**Comment by markus2330** [comment]
Yes, thats possible with higher-level frontends, e.g. the kdbthread.hpp allows you to pull changes from other threads by running syncLayers() (and also layer changes, hence the name). The explicit synchronization points yield the advantage that accessing the configuration value has absolutely no overhead compared to use native variables like `int`.

Of course other application architectures might want to have different behaviour (and e.g. prefer synchronized values to speed or need no such synchronization because no threads are used). So we decided to put it in a higher-level frontend to give applications this choice.

For journald and syslog you are right, their use is actually logging. (Lets keep this issue open for the renaming tasks)

But dbus is called notification because it is intended to be used in following way: The plugin is added to mountpoints where notifications should be sent. (in future, with global plugins, it will also work for all mountpoints) Applications write listener code, which runs kdbGet() when notification is retrieved. For dbus this is nearly trivial, e.g. see src/plugins/dbus/receivemessage.c (in qt and many other frameworks it would be implemented differently, but still is trival).

Cross-process notification of individual changes is currently not implemented, but it would be trivial (except for notification of removed keys). Do you need it for dbus?

**Comment by mhaberler** [comment]
We will not ever touch dbus in any shape or form for purposes of interprocess communication; if to be usable for us, it must work without dbus

for change notification, is it required to use C++? so far I assumed core features require C only

can you refer me to an an actual usage example? - like fetch key, subscribe to change notifications, get updated value?

**Comment by markus2330** [comment]
There are limitless ways in how to do such notifications. So dbus is a plugin and obviously any other messaging system can be used, too. Of course, you can also build thread-synchronization of values in C. For existing applications it might be wise to reuse the synchronization and notification you already have and use Elektra just as a storage.

Can you point be to the places where you intend to use it?

And which interprocess communication system do you want to use?

**Comment by mhaberler** [comment]
I am looking at notification being a basic C-level function of libelektra, so from the using perspective I don not care what is used internally, and I do not want to know (except as long it does not pull in a dependency on dbus), except that it MUST be integratable with existing event loops AND I want to know if this is local-only or works across different hosts.

For example, an API could be to associate a key handle with a callback function which gets called on key change.

To be integrated sanely into existing event loops, all you can assume at the library level is that a file descriptor can be registered with an existing loop, and associated with a library internal function which eventually issues the callback. That would work with pretty much any event loop - libev, libevent, zloop, gobject, boost:asio, all the web frameworks I know of - basically anything what can be added to poll(2)/epoll(2).

Other than that I do not see how such a functionality has any business to know or rely on what transport is being used in using code if any. You can expect an filedescriptor-based event loop being available. That is about as much as libelektra should know, and require. If internally sockets, eventfd, inotify or whatever is used is unrelated to using code. 

The basic question I see is if notification is going to be intra-host or includes a remote scenario.

That said, if you are considering a remote scenario I would strongly suggest to abstain from any homegrown socket handling and consider zeroMQ publish/subscribe as a vehicle (which can be made to integrate into fd-based event loop client-side just fine, and there should be no API impact if a particular library incarnation is local-only or supports remote).

**Comment by mhaberler** [comment]
how does one do change detection in elektra?  `grep -ri change .|grep -i det` comes up empty.

is there some key or tree generation serial number which gets bumbed on updates and can be monitored?

**Comment by markus2330** [comment]
You got the point: dependencies like dbus can be undesired. So ideally, you exactly state the IPC you think is best suitable (e.g. performance, integration in event loop,...) so that we get good input what should be implemented next. It seems like ZeroMQ is the way to go?

I am afraid notification is not an internal ("you do not have to care") topic exactly because of the integration of event loops but also because of external tools. qdbusviewer obviously won't work with a ZeroMQ notification. It obviously also determines how well intra-host works.

Change detection then works by listening to what gets notified.

**Comment by markus2330** [comment]
Btw. using fd-based notification is very attractive but fails when cross-node notification is needed.

But I agree that it should be available.

**Comment by mhaberler** [comment]
huh?  a fd not being "cross-node" - you mean network? what about a socket fd?

at end the transport dont matter

what matters is the notification is fd-based, that is the lowest-common denominator

everything else is not going anywhere because it does not integrate into poll/epoll/select/kqueue based event loops

**Comment by markus2330** [comment]
I have no doubt about that fd-based approaches are the most useful ones on POSIX systems.

Using socket-fd, however, seems to me only practical in a centralized system, not for a distributed multi-node system.

Nevertheless, if I understand you correctly you want something like:

    kdbNotify(int fd, void (*callback) (Key* newKey, void *callbackdata), void *callbackdata)

which does a read(2) on fd, constructs a Key for every notification it gets and calls the callback.

So the simplest usage example would be:

    void callback(Key* newKey, void *ks) {
        ksAppendKey((KeySet*)ks, newKey);
    }
    ...
    kdbNotify(0, callback, ks);

see also [the old suggestion](https://github.com/ElektraInitiative/libelektra/blob/master/doc/todo/FUTURE) which had a way to specify keys of interest and a diffMask. Which operation is happening might also be interesting. Maybe kdbNotifyValueChange(),... are better then?

**Comment by markus2330** [comment]
Development for internal notification is happening in #828

**Comment by markus2330** [comment]
This is now implemented, if you are interested in reviewing the last PRs, see #1835 #1850.
