### ISSUE TITLE
Improve Naming Schemes for KDB Commands

### ISSUE THREAD

**Issue by iandonnelly** [ElektraInitiative/libelektra#265]
You are completely right!
This was outlined in [issue #260](https://github.com/ElektraInitiative/libelektra/issues/260) by Markus but I wanted to separate this into it's own issue for clarity.

From Markus:

> I would suggest to use a hierarchical naming schema:  
> kdb-plugin (no real command, just general info about plugins)
> kdb-plugin-check
> kdb-plugin-info
> kdb-plugin-list (or kdb-plugin-ls?)
> 
> To be discussed if this also applies to meta and/or mounting:    
> 
> kdb-meta (info about meta data)
> kdb-meta-ls
> kdb-meta-set
> 
> and for future spec, global mounts:    
> 
> kdb-global-mount
> kdb-global-unmount
> 
> kdb-spec-mount
> kdb-spec-unmount
> 
> I agree we should have aliases to not break scripts.

**Comment by markus2330** [comment]
Thanks for opening a new issue! I removed the text from #260. One line was missing:

We should also hide some less important commands from --help (and give them to list-tools), e.g. fstab, test, vset is hardly used.

**Comment by markus2330** [comment]
Any progress here?

**Comment by markus2330** [comment]
As mentioned in #1188 we should also get rid of `kdb fstab` but use a generic way to set multiple keys at once.

**Comment by markus2330** [comment]
As mentioned in #876, `mountpoints-info` might be renamed to `info`, after `info` is renamed to `plugin-info`.

**Comment by markus2330** [comment]
As discussed in #2150 `kdb check` should be a check for the KDB, and for plugins there should be `kdb plugin-check`.

**Comment by markus2330** [comment]
See #2388, @kodebach suggested:

> Regarding improving kdb for array manipulation and in general: Once kdb has better support for sub-commands (using elektraGetOpts?) I think we should move to a hierarchical system would be a good idea. So kdb would for example have the subcommands array and meta, while each of those have subcommands called get, set and rm (and more), meaning kdb array set, kdb meta get and kdb array rm would all be commands.

Yes, that would be very nice.

We already have something like this with the external executor, for example `kdb elektrify-getenv getenv`.

Ideally, we would also unify how the external commands work. So `kdb umount all` instead of `kdb umount-all`. 

Let us see if @ulschaef wants to work on this.

**Comment by PhilippGackstatter** [comment]
@markus2330 
This seems like a very broad issue. Is there something concrete I can work on?

**Comment by markus2330** [comment]
The first step would be the renaming of plugin commands: `kdb list` -> `kdb plugin-list` and so on.

**Comment by kodebach** [comment]
> Regarding improving `kdb` for array manipulation and in general: Once `kdb` has better support for sub-commands (using `elektraGetOpts`?) I think we should move to a hierarchical system would be a good idea. So `kdb` would for example have the subcommands `array` and `meta`, while each of those have subcommands called `get`, `set` and `rm` (and more), meaning `kdb array set`, `kdb meta get` and `kdb array rm` would all be commands.
-- https://github.com/ElektraInitiative/libelektra/issues/2388#issuecomment-462038150

I think it wouldn't be wise to start renaming stuff now, if we might decided to implement the hierarchical command structure in the future.

---

On a separate note: Since we decided (in #2983) to expose metakeys as a normal KeySet. It might make sense, to support (more or less) all `kdb` commands for metadata as well. This could be done via a command-line option. Lets assume this option is `-X`. If `kdb op -X /some/key /other/key` is given, we could either do the operation `op` on the meta key `/some/key` of `/other/key`, or the other way round (with `/other/key`) as the metakey. Which key is the metakey doesn't really matter.

Alternatively we could create some syntax to specify key and metakey in one string e.g. `/some/key[/meta]`.

On example of using this would be e.g. `kdb rm -r -X gen /some/key`, to remove all `gen/**` metadata from key `/some/key` (`kdb rm -r -X /some/key gen` and `kdb rm -r /some/key[gen]` in the other syntax versions)

This should allow us to cleanup the code a bit. Of course this assumes, that all the `kdb` operations are actually possible to do on metadata with the new `keyMetaData` function.

**Comment by markus2330** [comment]
> I think it wouldn't be wise to start renaming stuff now, if we might decided to implement the hierarchical command structure in the future.

The way external commands and man pages are implemented conflict with hierarchical commands. I also do not see advantages compared to the pseudo-hierarchical-commands we have now with -.

> On a separate note:  Since we decided (in #2983) to expose metakeys as a normal KeySet. It might make sense, to support (more or less) all kdb commands for metadata as well

I really appreciate your thoughtful ideas but please do not drop them into completely different discussions. Yes, keyMetaData can bring opportunities to implement `kdb rm` and `kdb meta-rm` in the same way but this is unrelated to this issue.

Here it is only about how we want to rename the commands so that they are more consistent and grouped together (in this pseudo-hierarchical-structure).

**Comment by kodebach** [comment]
> compared to the pseudo-hierarchical-commands we have now with -

Whether it is `meta rm` or `meta-rm`, doesn't matter much to me, but `rmmeta` seems odd.

External commands could still work with the proper hierarchy.
Lets take the example `kdb -r com -f sub -x meta -y abc`:
- `kdb` consumes option `-r` and calls `com -f sub -x meta -y abc`
- `com` consumes option `-f` and calls `sub -x meta -y abc`
- `sub` consumes option `-x` and calls `meta -y abc`
- `meta` consumes option `-y` and calls `abc`
- `abc` executes

Now the same example, but assume that `meta` is not a subcommand `sub`:

- `kdb` consumes option `-r` and calls `com -f sub -x meta -y abc`
- `com` consumes option `-f` and calls `sub -x meta -y abc`
- `sub` consumes option `-x` and **tries to call** `meta -y abc`
- `meta` is not a subcommand
- `sub` reports to `com` that it doesn't know `meta`
- `com` reports to `kdb` that it doesn't know `sub meta`
- `kdb` looks for external command `com-sub-meta`

But like I said, `meta-rm` should be fine to.

> Here it is only about how we want to rename the commands so that they are more consistent and grouped together (in this pseudo-hierarchical-structure).

I brought up the idea in this issue, since I thought it relevant. If we change how metadata commands (option instead of separate command) work, the renaming would be needless work.

**Comment by markus2330** [comment]
> Whether it is meta rm or meta-rm, doesn't matter much to me, but rmmeta seems odd.

Exactly, this is the main reason why this issue exists. (Ironically, the source files are already called metaremove.*)

> But like I said, meta-rm should be fine to.

Good :+1: It is much more simple.

> I brought up the idea in this issue, since I thought it relevant. If we change how metadata commands (option instead of separate command) work, the renaming would be needless work.

Of course this is relevant but it has nothing to do with the renaming. I only asked for creating new issue so that we do not have so many sub-discussions. In this case concretely it confused @PhilippGackstatter who thought that we currently do not know if we want to rename the commands. But it is common sense to bring all the commands to the same structure.

The renaming should be a quite small job (some `git mv`, fixing factory.hpp at least for the lesser-used commands). But to reimplement the commands to be hierarchical or to use keyMetaData is a much bigger task.

**Comment by PhilippGackstatter** [comment]
> As mentioned in #876, `mountpoints-info` might be renamed to `info`, after `info` is renamed to `plugin-info`.

Does `mountpoints-info` exist? I suppose this is now what `kdb mount` does without arguments?

> As discussed in #2150 `kdb check` should be a check for the KDB, and for plugins there should be `kdb plugin-check`.

> As mentioned in #1188 we should also get rid of `kdb fstab` but use a generic way to set multiple keys at once.

Are these two still relevant and if so, should I work on these?

**Comment by markus2330** [comment]
> Does mountpoints-info exist?

Of course, scripts/mountpoint-info but it should be moved to scripts/kdb/. I would not rename it right now, `info` might be too generic (and confusing).

> I suppose this is now what kdb mount does without arguments?

No.  It has docu doc/help/kdb-mountpoint-info.md

>  Are these two still relevant and if so, should I work on these?
> As discussed in #2150 kdb check should be a check for the KDB, and for plugins there should be kdb plugin-check.

Yes, `plugin-check` is definitely better. Please rename it.

> As mentioned in #1188 we should also get rid of kdb fstab but use a generic way to set multiple keys at once.

Yes, please remove the `fstab` functionality. It is only confusing and is not used anymore.
