### ISSUE TITLE
Tests for old kdb gen (pythongen)

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#2671]
In #2498 I turned the `check_gen` (renamed to `check_pythongen`) test into an external test (therefore now named `check_external_pythongen`), because the Makefile used for the tests uses `pkg-config` and therefore requires an installed instance of Elektra.

This is a bad solution, because (as noted in #2523) the source folder may not be available (or not under the original path). Instead we should either install all the files needed for the test (like I proposed in #2523), or change the tests to not require `pkg-config`.

If we still want to support the old gen stuff (the new code-generation is not a full replacement yet, and never will be a drop-in replacement), we need to update it to Python 3 anyway, as Python 2.7 is EOL starting 2020. That's why I just did the quick workarround.

**Comment by markus2330** [comment]
Thank you for creating this issue!

I think it is okay that it is an external test (it was an external test already before because it compiled sources while executing tests). Of course it would be better if everything is compiled during the make run and "make test" only runs the binaries. But then the Makefile needs to be ported to CMake.

> the new code-generation is not a full replacement yet

Mainly man and html are missing. The contextual values is a nice research prototype but afaik it was never used by someone, so we do not necessarily need to port this part to make your new code-generation a full replacement.

> we need to update it to Python 3 anyway,

The main dependency (cheetah) was not available for Python 3 for a long time. It is now available, so it should now be possible to port to Python 3. The question is if we want this or better exclusively switch to your new "gen" tool.

Btw. I like the name check_pythongen.

**Comment by kodebach** [comment]
Closing this because `pythongen` is going to be removed soon
