### ISSUE TITLE
arrays with natural sorting

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2698]
As discussed in #182 and #2388 we could avoid the `_` for array numbers if we internally escape `#<nr>` to `#_..<nr>` (elektraUnescapeKeyName):

> As already discussed shortly, we could also extend the escaping logic for key names and avoid the _ prefixes. So it would be #10, and the (internally) unescaped version (see keyUnescapedName) would be #_10 for correct sorting.

Then the sorting would be still correct and the user would not be bothered by `___` (as mentioned recently in #2685)

Furthermore, we maybe should change the character for arrays to not be `#` as `#` is a shell comment (see #2388).

**Comment by kodebach** [comment]
> elektraEscapeKeyNamePart

Not sure that is the right place to add this. It is only called in `keySetBaseName` and `keyAddBaseName` as far as I can tell. Shouldn't it be done in `elektraFinalizeName` (or one of the unescape functions called from there)?

> as # is a shell comment

It is also an INI comment which always makes for confusing code highlighting.

---

Also, if someone implements this: I think `elektraUnescapeKeyName` can be optimized by adding something like:

```patch
--- a/src/libs/elektra/internal.c
+++ b/src/libs/elektra/internal.c
@@ -715,6 +715,19 @@ size_t elektraUnescapeKeyName (const char * source, char * dest)
 
 	ELEKTRA_ASSERT (sp != NULL && dp != NULL, "Got null pointer sp: %p dp: %p", (void *) sp, (void *) dp);
 
+	if (strpbrk (sp, "\\%.") == NULL)
+	{
+		strcpy (dest, sp);
+		char * last = dp;
+		while ((dp = strchr (dp, '/')) != NULL)
+		{
+			*dp = '\0';
+			++dp;
+			last = dp;
+		}
+		return last - dest + strlen (last) + 1;
+	}
+
 	if (*sp == '/')
 	{
 		// handling for cascading names
```
I think this will improve performance, because it copies the string in one go and just skips to the chars that need replacing, if no real unescaping is needed.
Just by looking at how much code there is for the key name unescaping, I suspect more optimizations may be possible.

**Comment by markus2330** [comment]
Thank you for looking into the details and giving the implementation hints! You are right, it would be 
elektraUnescapeKeyName (or elektraUnescapeKeyNamePartBegin to check if it is an array and elektraUnescapeKeyNamePart to unescape the array).

>  It is also an INI comment which always makes for confusing code highlighting.

Thanks for the hint. So which character would be best?

**Comment by kodebach** [comment]
> So which character would be best?

Maybe `^`. I can't think of a case where that would cause problems. In any case changing the character would be major change requiring huge effort.

**Comment by markus2330** [comment]
> Maybe ^. I can't think of a case where that would cause problems

Yes, ^ is quite nice. It may cause minor problems with "deadkeys" on some keyboards (that you need to press the button twice).

> In any case changing the character would be major change requiring huge effort.

Of course.

**Comment by markus2330** [comment]
`echo ^hello` seems to have a special behavior. But actually no starting character is needed if we have natural sorting. We can simply escape the number by starting with `\`. This was also discussed (offtopic) in  #2388.

**Comment by kodebach** [comment]
I dislike the idea of having no starting character for arrays in general. At least in the unescaped name there should be one. My reasoning is this:

1. Our escape character is `\`. Therefore in an escaped name `\` means take the next character literally and in an unescaped name `\` is taken literally as a backslash and cannot have any other special meaning.
2. There has to be a way to distinguish between key parts that are array indices and other array parts. There are many reasons why this necessary, but the best is that our specifications have an array globbing `/#/` feature to match all elements of an array.
3. Reasoning about key names/parts (e.g. is this an array element?) should be done in the unescaped name. This is because detecting key part borders in the escaped for is hard, which is one of the reasons we have the unescaped name in the first place. Iterating key parts in the unescaped for, however, is trivial.
4. If we convert (escaped -> unescaped) `/1/ -> /1/`, `/10/ -> /_10/` and use a leading `\` to prevent this behaviour, how do we distinguish between `/1/ -> /1/` and `/\1/ -> /1/` or between `/_10/` -> `/_10/` and `/10/` -> `/_10/`. One is an array index, the other is not, but both have the same unescaped form. In both cases we would have to look at both the escaped and the unescaped name at the same time. (°)

Therefore I propose:

ALL escaped (canonical) key parts (of length `n`) that consist ENTIRELY or digits will be prefixed with a special character `#` or `^` as well as `n - 1` underscores `_` during unescaping.

This automatically means that escaped key parts starting with a backslash, but otherwise consisting of just digits, are not treated this way (they do not consist entirely of backslashes). The special character in the unescaped name allows us to distinguish array elements from other key parts.

---

(°) The inverse problem occurs during the escaping that takes place in `keySetBaseName` and `keyAddBaseName`. What is the escaped for of `/1/` and  `/_10/`?

**Comment by markus2330** [comment]
> I dislike the idea of having no starting character for arrays in general.

Ok, then which character to pick? Maybe §? Or +, then it would like a positive number (but people might think then there are also negative numbers).

**Comment by kodebach** [comment]
> Ok, then which character to pick?

I think we can keep `#`, it (probably) breaks the least existing code and, if it only appears in unescaped names, it doesn't matter that `#` is commonly used for comments. Any text based storage format and the command line use the escaped key names, which would not use `#` for array indices.

**Comment by markus2330** [comment]
Yes, if it only appears in unescaped names it does not matter.

**Comment by kodebach** [comment]
After thinking about it some more, I think we need additional restrictions:

For escaped names:
1. If a key part starts with a digit, it must only contain digits.
2. If a key part starts with `0` nothing may follow, i.e. the whole part must be `0`.
3. If a key part starts with `#` nothing may follow, i.e. the whole part must be `#`.
4. There is no escaping mechanism for 3, i.e. key parts may NOT start with `\#`.

(3 and 4 are required for the rule below)

For unescaped names:
1. If a key part starts with `#`, either the whole part is `#` or it is a valid prefixed array index, i.e. a single digit or n underscores followed by 1 non-zero digit followed by n digits (n >= 1).

I know, you want to allow as many key names as possible in some way or another, and this prohibits all parts of the form (regex) `#.+`, but it has one crucial advantage. Detecting array elements becomes trivial, both for escaped and unescaped key name parts.

In the unescaped for any key part of length > 1 and starting with `#` is guaranteed to be a valid array element. In the escaped form all key parts starting with a digit are guaranteed to be valid array elements.

**Comment by markus2330** [comment]
> I know, you want to allow as many key names as possible in some way or another,

You misunderstood. It is perfectly fine to restrict the names as much as possible. This has been a goal in the previous escaping but I think this was a mistake as it was very complicated without clear benefit.

What is important is that every possible character string must be codable within the key name parts. This is needed, e.g., if you want wlan SSID identifiers within key names.

So `keyNew`, `keyAddName` can (and should!) fail in all the cases you mentioned. It never was a good idea to allow e.g. broken array key names.

But whatever is given `keyAddBaseName` or `keySetBaseName` should lead to some internal representation that will give the same `keyBaseName` as was given during creation. One (easy) representation is the same string but starting with `\`. (Or by escaping all the annoying characters).

**Comment by kodebach** [comment]
> But whatever is given `keyAddBaseName` or `keySetBaseName` should lead to some internal representation that will give the same `keyBaseName` as was given during creation. One (easy) representation is the same string but starting with `\`. (Or by escaping all the annoying characters).

This is exactly the problem. Any key `B` that is created by calling `keyAddBaseName` (or `keySetBaseName`) on an existing key `A`, MUST also be creatable through a single call to `keyNew`, namely `keyNew (keyName (B), KEY_END)`.

In other words, if `keyAddBaseName` and `keySetBaseName` should accept ALL possible strings, we MUST allow all possible strings (prefixed with a valid namespace and NUL separator) as unescaped key names. Therefore EVERY conceivable C string, MUST have an escaped representation.

That means, my rules above would be to restricting, as `keyAddBaseName (key, "#abc")` would not work.

However, ...

> What is important is that every possible character string must be codable within the key name parts. This is needed, e.g., if you want wlan SSID identifiers within key names.

If the goal is only that every possible string can be PART OF a unescaped key name part, there is no problem. You could just add a prefix before passing your weird string to `keyAddBaseName` or `keySetBaseName`. To take the problematic example from before, instead of `keyAddBaseName (key, "#abc")`, you would call e.g. `keyAddBaseName (key, "\#abc")`.

---

Other solutions require lifting at least one of the following conditions (AFAICT):
- `keyBaseName` returns the last part of the unescaped name. In other words:

   ```c
   *(keyBaseName (key) - 1) == '\0' && strchr (keyBaseName (key), '\0') == (char*) keyUnescapedName (key) + keyGetUnescapedNameSize (key) - 1
   ```
- `keyBaseName` after a (successful) `keyAddBaseName` returns the same string as given to `keyAddBaseName`.
  
   ```c
   keyAddBaseName (key, s) <= 0 || strcmp (keyBaseName (key), s) == 0
   ```

Lifting the first condition would allow adding some sort of indicator between parts.
Lifting the second condition allows some sort of automatic "escaping" (needs a different name because it is done to unescaped names).

---

Note: "string" above means sequence of `char`s excluding `'\0'`. This does not apply to IEEE 802.11 SSIDs, which may contain NUL characters (they are an arbitrary sequence of bytes up to 32 bytes long).

**Comment by kodebach** [comment]
Also concerning your SSID example:

```c
const char * ssid = "1"; // unlikely, but valid
keySetBaseName (key, ssid);

const char * index = "1";
keySetBaseName (key, index);
```

Should we make the SSID case easier and say the result is a key whose escaped name ends with `/\1` or the array index one and let the resulting key's escaped name end in `/1`?

If we make SSID easier,

**Comment by markus2330** [comment]
The whole point of keyAdd/SetBaseName is that users do not need to care about such issues and simply can set any arbitrary byte sequence (except of null bytes).

So this prefixing/encoding must be done internally. There are many ways to do it, and some of them are quite trivial like prefixing with `\` (this is identical like your proposed `ssid=` example, only that the prefixing happens internally).

What we could do is to not support keyAdd/SetBaseName for now and add it after this PR or even after 1.0. If we keep enough special characters, we can think of such an escaping later. Most of the keyAdd/SetBaseName we have now actually do not need any escaping.

**Comment by kodebach** [comment]
> this is identical like your proposed ssid= example, only that the prefixing happens internally

Please read my comment again, I outlined why exactly this is not the case. In short to allow this kind of internal prefixing, something about the relationship `keyAddBaseName` and `keyBaseName` must change.

> What we could do is to not support keyAdd/SetBaseName for now and add it after this PR or even after 1.0.

No, this is not possible both are widely used and are very hard or impossible to replace.

**Comment by markus2330** [comment]
> Please read my comment again, I outlined why exactly this is not the case.

Can you please highlight for me your comment or copy the text again?

> In short to allow this kind of internal prefixing, something about the relationship keyAddBaseName and keyBaseName must change.

Which relationship? The only important relationship is that keyBaseName returns whatever the user gave to keyAdd/SetBaseName.

**Comment by kodebach** [comment]
> Can you please highlight for me your comment or copy the text again?

Nevermind, I found a better explanation. See below.

> Which relationship? The only important relationship is that keyBaseName returns whatever the user gave to keyAdd/SetBaseName.

As said one of these two guarantees/conditions/whatever-you-want-to-call-it have to be broken: 

> * `keyBaseName` returns the last part of the unescaped name. In other words:
>   ```c
>   *(keyBaseName (key) - 1) == '\0' && strchr (keyBaseName (key), '\0') == (char*) keyUnescapedName (key) + keyGetUnescapedNameSize (key) - 1
>   ```
> * `keyBaseName` after a (successful) `keyAddBaseName` returns the same string as given to `keyAddBaseName`.
>   ```c
>   keyAddBaseName (key, s) <= 0 || strcmp (keyBaseName (key), s) == 0
>   ```

And there is another one that becomes important below:

`keySetBaseName (key, keyBaseName (key));
```

If you know a solution that keeps both, I am open to suggestions...


---

I'll give a clear example, where no single solution exists (that I know of):

Assume we have no restrictions on the arguments of `keyAddBaseName` and therefore no restrictions on the characters inside a single unescaped key part (except that no `'\0'` is allowed of course).

Assume further that, as decided above, escaped array indices are just numbers like `10` and unescaped array indices are something like `#_10`. Since that terminology is a bit backwards, I will call `10` unprefixed and `#_10` prefixed.

We look at two use cases. In the first one we want `keyAddBaseName` to add a name with no meaning (lets say it is an SSID), in the second one we want to explicitly to add an array index. Of course to add an array index, we need to give `keyAddBaseName` the prefixed form, because `keyAddBaseName` expects unescaped stuff.

Now, what happens if our SSID is #_10 in the first case and in second case we want to add the array index 10? Both times we call `keyAddBaseName (key, "#_10")`. So there is clearly a problem.

We definitely don't want our SSID to be treated as an array index. In that case we expect the escaped name to end in `/#_10`.

At the same time our array index should be treated as such. The escaped name should end in `/10`.

So is the function expected to magically know the difference?

Well, we could use `keyAddName (key, "10")` to add the array index instead. But then

**Comment by kodebach** [comment]
> Can you please highlight for me your comment or copy the text again?

Nevermind, I found a better explanation. See below.

> Which relationship? The only important relationship is that keyBaseName returns whatever the user gave to keyAdd/SetBaseName.

As said one of these two guarantees/conditions/whatever-you-want-to-call-it have to be broken: 

> * `keyBaseName` returns the last part of the unescaped name. In other words:
>   ```c
>   *(keyBaseName (key) - 1) == '\0' && strchr (keyBaseName (key), '\0') == (char*) keyUnescapedName (key) + keyGetUnescapedNameSize (key) - 1
>   ```
> * `keyBaseName` after a (successful) `keyAddBaseName` returns the same string as given to `keyAddBaseName`.
>   ```c
>   keyAddBaseName (key, s) <= 0 || strcmp (keyBaseName (key), s) == 0
>   ```

And there is another one that becomes important below:

The call `keySetBaseName (key, keyBaseName (key))` should obviously be a no-op.

If you know a solution that keeps all these, I am open to suggestions...

---

I'll give a clear example, where no single solution exists (that I know of):

Assume we have no restrictions on the arguments of `keyAddBaseName` and therefore no restrictions on the characters inside a single unescaped key part (except that no `'\0'` is allowed of course).

Assume further that, as decided above, escaped array indices are just numbers like `10` and unescaped array indices are something like `#_10`. Since that terminology is a bit backwards, I will call `10` unprefixed and `#_10` prefixed.

We look at two use cases. In the first one we want `keyAddBaseName` to add a name with no meaning (lets say it is an SSID), in the second one we want to explicitly to add an array index. Of course to add an array index, we need to give `keyAddBaseName` the prefixed form, because `keyAddBaseName` expects unescaped stuff.

Now, what happens if our SSID is #_10 in the first case and in second case we want to add the array index 10? Both times we call `keyAddBaseName (key, "#_10")`. So there is clearly a problem.

We definitely don't want our SSID to be treated as an array index. In that case we expect the escaped name to end in `/#_10`.

At the same time our array index should be treated as such. The escaped name should end in `/10`.

So is the function expected to magically know the difference?

Well, we could use `keyAddName (key, "10")` to add the array index instead. Then we could make `keyAddBaseName (key, "#_10")` add `#_10` to the escaped and the unescaped name, i.e. ignore that `#_10` is an array index. But that has the huge problem that `keySetBaseName (key, keyBaseName (key))` after calling `keyAddName (key, "10")` (°) modifies the key. It turns the last escaped key part from `10` into `#_10`.

Okay, next try make `keyAddBaseName (key, "#_10")` add `#_10` to the escaped name and `\#_10` to the unescaped name. This doesn't work either, to make this work `keySetBaseName (key, "\#_10")` would have to set the escaped base name to `#_10` and the unescaped base name to `\#_10`. So what if our SSID was `\#_10`?We would want the escaped name to end in `\#_10` after `keyAddBaseName (key, "\\#_10")`. And we are back at the beginning...

I just don't see a way how we could ever get around this, without restricting the arguments to `keyAddBaseName` and `keySetBaseName`. Like I said before, we could introduce a `keyAddToBaseName` (name debatable) that has unrestricted arguments. Then for the SSID we would first add a safe prefix with `keyAddBaseName` and then add the SSID with `keyAddToBaseName`. The only condition there would be that characters other than `/` and `\` could only have special meaning at the start of a part.


---

(°) `keySetBaseName (key, keyBaseName (key))` then is `keySetBaseName (key, "#_10")`, i.e. the same as `keySetBaseName (key, NULL); keyAddBaseName (key, "#_10")` to make the problem very explicit.

**Comment by markus2330** [comment]
> keyBaseName returns the last part of the unescaped name.

You are right, this cannot be like this. keyBaseName will need to skip the prefix if it's there.

> We look at two use cases. In the first one we want keyAddBaseName to add a name with no meaning (lets say it is an SSID), in the second one we want to explicitly to add an array index. Of course to add an array index, we need to give keyAddBaseName the prefixed form, because keyAddBaseName expects unescaped stuff.

We should only support the first use case. For array index an `keyAddArrayIndex(Key * key, size_t index)` is better suited. (Can be added post-1.0)

> So is the function expected to magically know the difference?

No, it should only support the first use case.

> Well, we could use keyAddName (key, "10") to add the array index instead.

Yes, exactly.

> But that has the huge problem that keySetBaseName (key, keyBaseName (key)) after calling keyAddName (key, "10") (°) modifies the key.

Yes, but this would only happen once. And I would not call it a "huge problem". The guarantee is only in one direction: after keySetBaseName you get the same in keyBaseName, not the other way round. Round-tripping is usually only defined in one direction, and not bidirectionally.

> So what if our SSID was `\#_10`?

`\` also needs to be escaped, so the unescaped name would be `\\#_10` but keyBaseName would return `\#_10`.

> keyAddToBaseName

This we do not need to worry about now. Let us make the most out of the current Name functions. If there are some limitations people are unhappy with, we can add something like `keyAddBinaryName` and `keyGetBinaryName`, which could even allow null characters. But this can be done post-1.0.

**Comment by kodebach** [comment]
> Can be added post-1.0

This is only true, if no part of Elektra uses `keyAddBaseName` or `keySetBaseName` to for array indices. I doubt this is the case.

> The guarantee is only in one direction: after keySetBaseName you get the same in keyBaseName, not the other way round. Round-tripping is usually only defined in one direction, and not bidirectionally.

But the other direction is much more intuitive and many users won't even check the docu whether it is true. In general, I expect calling `setY (x, getY (x))` to not change the value `Y` of `x`.

**Comment by markus2330** [comment]
> This is only true, if no part of Elektra uses keyAddBaseName or keySetBaseName to for array indices. I doubt this is the case.

This is actually a good argument for not allowing to do this.

> But the other direction is much more intuitive and many users won't even check the docu whether it is true. In general, I expect calling setY (x, getY (x)) to not change the value Y of x.

Why is this direction more intuitive? Is there code that relies on this?

**Comment by kodebach** [comment]
> This is actually a good argument for not allowing to do this.

I don't understand...

My argument was:
If there is currently some part of Elektra that does `keyAddBaseName (key, "#_10")` and expects the resulting key to be an array element, we need a solution for 1.0 and cannot wait until later.

A quick search reveals that at least `elektraMetaArrayAdd` expects this behaviour.

> Why is this direction more intuitive?

In general, I expect that `getX()` returns the value of `X`. I also expect that `setX (a)` sets the value of `X` to the value `a`.

I also understand, if there is some processing and `setX (a)` actually sets `X` to a value derived from `a`. But `getX ()` should then return this derived value, and passing that back to `setX` should not change it any more. Otherwise the name `setX` seems wrong to me, it is not a pure setter function any more.

> Is there code that relies on this?

I can't say. I do not know the whole code base and searching for something like this is basically impossible, since the calls to `keyBaseName` and `keySetBaseName` might be quite far apart.

**Comment by markus2330** [comment]
I added this as 6629a93b2018339db39b763800704eb2e0523da7 in #3514
