### ISSUE TITLE
empty/presence type

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2705]
Does the type plugin still support empty? I could not find it in the docu of the type plugin but it is still in the description of [type] in METADATA.ini.

At least `[binary]` in METADATA.ini still uses empty.

**Comment by kodebach** [comment]
I removed `empty` because the [README of the old plugin](https://github.com/ElektraInitiative/libelektra/tree/master/src/plugins/cpptype) said it is deprecated and regex should be used. Although I already noticed that this creates an awkward situation, since the `string` type only matches non-empty values.

IMO we should probably add the `empty` type again for cases where only the presence of a key is important and also allow empty values for type `string`, because `any` would allow binary data as well.

**Comment by markus2330** [comment]
> also allow empty values for type string

Yes, without sum types we need to do that.

> because any would allow binary data as well

Yes.

For the specification, however, it would be good to have a special type which indicates the presence of a key. While "any" would be okay, it somehow does not reflect the purpose. Or alternatively: we get rid of these presence keys and make the boolean (with "false" as default on absence).

**Comment by kodebach** [comment]
> For the specification, however, it would be good to have a special type which indicates the presence of a key.

Do you mean for the specification of an applications config, or for our METADATA.ini specification?

**Comment by kodebach** [comment]
For application specification there technically is this:

https://github.com/ElektraInitiative/libelektra/blob/4a3c1634be7a732b00aacc9c5ed6dc46d33652c2/doc/METADATA.ini#L611-L623

Although even there it is stated that the status is unclear....

Fixing/implementing `require` in `spec` is something I might do, since it would be useful for LCDproc. Also I would like to add a `constant` metakey that has the same functionality as `default`, but also marks the key as read-only.

**Comment by markus2330** [comment]
> Do you mean for the specification of an applications config, or for our METADATA.ini specification?

Ideally, the types for specifications and meta-specifications (METADATA.ini) are the same. Until now this was the case for the CORBA types. It seems like they are now out-of-sync, hence this issue.

> Although even there it is stated that the status is unclear....

In this issue, I did not want to raise the problem how to require a key (we already have #1024 for this. It would be great if you can clean this mess up. I am not sure if we need it for LCDproc, though. I think it would be better to have defaults everywhere.)

Instead, it is about to find the proper CORBA type to indicate that (meta-)keys are empty and only the presence of the (meta-)key is relevant.

> Although even there it is stated that the status is unclear....

> Fixing/implementing require in spec is something I might do, since it would be useful for LCDproc. Also I would like to add a constant metakey that has the same functionality as default, but also marks the key as read-only.

`readonly` metadata already exists. What are you missing there? (Please create a new issue for discussion.)

**Comment by kodebach** [comment]
> readonly metadata already exists. 

I can't find it in METADATA.ini

**Comment by markus2330** [comment]
I answered it in #2706.

So maybe migrating everything to boolean is the best way? "kdb setmeta" needs a meta-value anyway. And configuration files are of course free to render the booleans differently (also without values).
