### ISSUE TITLE
support restrict/*

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2706]
As said in  #2705:
>   I can't find it [readonly] in METADATA.ini

It is called: "restrict/write" (there are a few more "restrict/*"). They are already implemented in WebUI.

The old code-generator still uses "readonly" but this should be updated to "restrict/write". Maybe this can be updated with the following diff (I did not test it):

```diff
diff --git a/src/tools/gen/support/context.py b/src/tools/gen/support/context.py
index 679fa863a..b48ec263c 100644
--- a/src/tools/gen/support/context.py
+++ b/src/tools/gen/support/context.py
@@ -26,7 +26,7 @@ class ContextSupport(NestedSupport):
                return name.lower().replace('#','n')
 
        def readonly(self, info):
-               return "readonly" in info
+               return "restrict/write" in info
 
        def typeof(self, info):
                """Return the type for given parameter"""
diff --git a/src/tools/gen/tests/lift.ini b/src/tools/gen/tests/lift.ini
index bf10091ba..290eb45cb 100644
--- a/src/tools/gen/tests/lift.ini
+++ b/src/tools/gen/tests/lift.ini
@@ -27,7 +27,7 @@ see=/test/lift/emergency/delay
 [/test/lift/emergency/action/stops]
 type=boolean
 default=true
-readonly
+restrict/write=1
 explanation=if emergency button stops the lift
 rationale=REQ1331 needed for material lifts
 accessibility=systems_engineering
```

**Comment by kodebach** [comment]
Where should we support this? In the `spec` plugin or somewhere else?

**Comment by markus2330** [comment]
I would not stuff more features into the spec plugin but rather get a new restrict plugin.

Furthermore, the restrict/write can also be used in the code generator (not allow to call a setter at compile-time if it has restrict/write"). This is low-priority, though.

**Comment by kodebach** [comment]
> I would not stuff more features into the spec plugin but rather get a new restrict plugin.

A second question then: Should the `restrict/write` metadata be added to keys in the spec namespace and prevent writing values to the same key in other namespaces, or should the metakey prevent changes to between kdbGet and kdbSet to the key that actually is marked with the metadata?

> Furthermore, the restrict/write can also be used in the code generator (not allow to call a setter at compile-time if it has restrict/write"). 

We can't fully disallow setter calls at compile-time (since in the end everything boils down to strings being passed to the highlevel API), but we can skip the generation of the tags and the associated methods for keys with `restrict/write`.

For this spec

```ini
[some/key]
type = string
restrict/write =
```

`elektraSet (elektra, ELEKTRA_TAG_SOME_KEY, value, &error)` and `elektraSetSomeKey (elektra, value, &error)` would be a compile time error, while `elektraSetString (elektra, "some/key", value, &error)` would only produce an error at runtime (and only if the `restrict` plugin is mounted).

Additionally we could also add `restrict/read` to do the same for getters (don't know if there is a use case), but that could not really be enforced in the plugin. Unless we just remove all keys with that metakey.

**Comment by markus2330** [comment]
> A second question then: Should the restrict/write metadata be added to keys in the spec namespace and prevent writing values to the same key in other namespaces, or should the metakey prevent changes to between kdbGet and kdbSet to the key that actually is marked with the metadata?

I was originally thinking about the first use-case. But the Web-UI also allows you to directly append the restrict/write metadata to any key and refuses any write attempts that still have the metadata. After removing the metadata, writing attempts again succeed.

> would be a compile time error,

This would be perfect.

> Additionally we could also add restrict/read to do the same for getters (don't know if there is a use case)

I do not see such use case.
