### ISSUE TITLE
cache: namespaces and dirs are in one folder

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2708]
## Steps to Reproduce the Problem

```sh
cd .cache/elektra/backend
ls
```

## Expected Result

That I only see namespaces or the first path of cascading namespaces.

## Actual Result

```sh
dir/     lehre/   spec/    system/  test/    tests/   user/
```

Which might create problems when doing something like `kdb ls /user`. Or how does it work?

## System Information

- Elektra Version: master

**Comment by mpranj** [comment]
The cache always uses the mountpoint (key name) as the path. There it will store a `cache.mmap` file.
Any key starting with "`/`" resolves to the default mountpoint, so _any_ cascasing cache would be exactly in a single file: "`~./cache/elektra/default/cache_cascading.mmap`".

Using the parentkey was not really an option, since there are "inifinitely" many possible parentkeys, but they always resolve to a finite set of backends (i.e. mountpoints).

**Comment by mpranj** [comment]
In other words I don't think this introduces any bugs. In addition to the path, the cache also stores quite a bit of additional information. For instance, it stores the parentkey used when kdbGet was invoked (and thus when the cache was created). When the cache is loaded, we always check that the parentkey is the same or below the parentkey used with the last kdbGet.

In fact, the cache should work when using a single file too. It would just not be fast, as it would **always** overwrite it.

**Comment by markus2330** [comment]
Thank you for the quick intro of the logic.
