### ISSUE TITLE
cache: how to (de)activate?

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2709]
How to activate the cache after 5732f1b603bbe65ace3dee181c57351e1c537e71?

I did it now by reverting 5732f1b603bbe65ace3dee181c57351e1c537e71 and recompiling. Is this needed?

**Comment by mpranj** [comment]
Yes, that is needed if you want to change the default config.
Otherwise, if you already have a global config you can simply toggle it with:

Enable:
```
kdb set system/elektra/globalplugins/postgetcache cache
kdb set system/elektra/globalplugins/pregetcache cache
```

Disable:
```
kdb set system/elektra/globalplugins/postgetcache
kdb set system/elektra/globalplugins/pregetcache
```

It won't work like this if the global config (system/elektra/globalplugins and below) has not yet been written to a config file. Then it is overridden by the default config and changes would be lost.

**Comment by mpranj** [comment]
As I already mentioned, I'll add this to the kdb tools later (`kdb cache enable`, `kdb cache clear` and `kdb cache disable`).

**Comment by markus2330** [comment]
Thanks for the info! Yes, it would be great to have these tools.
