### ISSUE TITLE
Statistics of Errors

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#2767]
Do you have some statistics of how often which error is used now? (Simple grep should help.)

This might give us indications that some groups are too heavy. E.g. it might make sense to split installation errors into errors caused by binaries and errors caused by KDB manipulations.

**Comment by Piankero** [comment]
Installation: 100
Resource: 151
Out of memory: 50
Internal: 49
Interface: 20
Plugin Misbehavior: 38
Conflict: 12
Validation Syntactic: 138
Validation Semantic: 87
---
Sum: 645

> This might give us indications that some groups are too heavy

Honestly this is not the correct approach imo just to split or merge a group if there are too few or too many errors. It should only be splitted or merged once a different reaction makes sense. And differentiating between binary or kdb manipulations does not make a lot of sense to me. The user has to investigate the message no matter what to fix the problem. Just because it is in a different category will not help him. Nonetheless I added the statistics because it is interesting for you to know. I think by the way that the statistics fit very well in what elektra does (eg. lot of parsers -> many validation syntactic errors, etc.)

**Comment by markus2330** [comment]
Thank you for the stats, they are most likely also useful for your thesis.

> The user has to investigate the message no matter what to fix the problem.

Of course, annotating correct solutions is much more helpful than moving the errors between categories.

> I think by the way, that the statistics fit very well in what elektra does (eg. lot of parsers -> many validation syntactic errors, etc.)

I fully agree. The errors are quite good balanced.

**Comment by Piankero** [comment]
@markus2330 did you remove a considerable amount of plugins?

Rerunning my script now shows the following statistics:

            RESOURCE: 128
       OUT_OF_MEMORY: 5
        INSTALLATION: 41
            INTERNAL: 34
           INTERFACE: 9
  PLUGIN_MISBEHAVIOR: 24
   CONFLICTING_STATE: 6
VALIDATION_SYNTACTIC: 93
 VALIDATION_SEMANTIC: 77

Sum: 417
