### ISSUE TITLE
3-way merging ignores conflicts

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#290]
Somehow the code in the qt-gui (src/treeviewmodel.cpp) seems to misuse the 3-way merge API such that it never comes to conflicts.

So even if ours and theirs modify the same key or introduce a new key, no conflict is reported.

I also wonder about the `KeySet discard` in src/libtools/examples/merging.cpp. Doesn't it contain the desired keys (below `resultRoot`)?

Can you take a short look? Otherwise, it might be better to disable 3-way merging for this release.

**Comment by fberlakovich** [comment]
Yes for sure, I will have a look. Regarding the example: as far as I can tell the discard KeySet contains those keys that would possibly collide with the merge result (i.e. are below the Key where the merge result will be written to). That's why step 2 suggests bailing out if such keys or found or alternatively overwriting them.

**Comment by markus2330** [comment]
It seems like that, in the example, AutoMergeConfiguration and OneSideMergeConfiguration are confused.
