### ISSUE TITLE
Array recognition for opts.c

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#2920]
In `opts.c` on lines 833 there is 
```c
bool isArray = strcmp (keyBaseName (keyWithOpt), "#") == 0;
```
and something similar on 962.

From a quick glance this seems to be responsible for [command line arguments](https://www.libelektra.org/tutorials/command-line-options#introduction). Something like that should generally be refactored into a new method in my opinion. This way nobody can edit (hopefully improve) the one array recognition line but not the other.

There even seems to be an appropriate solution already available: ` int elektraArrayValidateName (const Key * key)`in `array.c` could be used.

In case I overlooked why we should not use this method from `array.c` we might want to add a comment into `opts.c`.

**Comment by markus2330** [comment]
Thank you for the suggestion!

In general it is very good to find common functionality and put it into one of the libs (e.g. libease or libmeta).

> There even seems to be an appropriate solution already available elektraArrayValidateName

It would not do the same, currently it checks if the baseName is `#`, and elektraArrayValidateName checks if the baseName is any array name (e.g. `#0`).

> In case I overlooked why we should not use this method from array.c we might want to add a comment into opts.c.

One reason might be that for a trivial functionality you do not want to pull in a dependency.

@kodebach: was there a specific reason?

**Comment by kodebach** [comment]
> It would not do the same

AFAIK `elektraArrayValidateName` does use a different return code for `#` (which technically is not a valid array index).

> One reason might be that for a trivial functionality you do not want to pull in a dependency.

The required dependency is already there in this case.

> was there a specific reason?

The reason is just that I didn't think about it. It is dead simple to do a `strcmp` on the basename, if you want to identify array spec keys.

IMO not using the library function also makes the code easier to understand. Everybody knows what `strcmp` does.

Lastly, `elektraArrayValidateName` does a lot of unnecessary work, if the key actually is an array element (e.g. `/#__100`). If we really want to use a library function we would need to create a new one that literally only does this one line.

**Comment by markus2330** [comment]
So, I will close this issue. Conclusion: the code is trivial and does not need to be put in a support library.

@Chemin1 if you find other occurrences, please open new issues. In general we first create methods within the plugins/libs and only if we see that multiple plugins/libs have similar methods we refactor the methods to a common library. Feedback on duplicated code is highly appreciated.
