### ISSUE TITLE
keyIsBelowOrSame

### ISSUE THREAD

**Issue by PhilippGackstatter** [ElektraInitiative/libelektra#3048]
`keyIsBelowOrSame` is part of the public API, and should thus be documented on the [libelektra.org documentation](https://doc.libelektra.org/api/current/html/group__keytest.html), but it isn't. 

Before we find out why it's not displayed, we should figure out if we still need this function, as it can easily be replaced by `keyCmp` and `keyIsBelow`.

**Comment by markus2330** [comment]
Thank you for reporting the issue. I am in favor of removing it.

Bindings that already have this function can keep it and call keyCmp || keyIsBelow,

**Comment by kodebach** [comment]
I'm against removing `keyIsBelowOrSame`, since `keyIsBelow` actually uses it. Also `keyCmp || keyIsBelow` would need two `memcmp`s of the full key name to find out that the key is below, when actually just one would be enough.

Also, `keyCmp || keyIsBelow` is actually not quite the same as `keyIsBelowOrSame`, because `keyIsBelowOrSame` has some handling for cascading keys that `keyCmp` (and also `keyCompare`) doesn't have. IMO the handling of the cascading keys is weird and could be removed, but the fact remains that  `keyCmp || keyIsBelow` != `keyIsBelowOrSame`.

A better idea might be to consolidate the functions `keyIsBelow`, `keyIsDirectlyBelow` and `keyIsBelowOrSame` into one and use multiple return values, e.g.

```
0 - not below
1 - same
2 - directly below
3 - below, but not directly
```

Then you could use `keyIsBelow > 0` for below or same, `keyIsBelow > 1` for below and `keyIsBelow == 2` for directly below. Also you get `keyIsBelow == 1` for is the same and `keyIsBelow > 2` for below but not directly.

**Comment by markus2330** [comment]
Yes, I agree that the comparison functions need some cleanup. `keyRel` tried something similar your propose but it didn't work out so well (is luckily already gone). Let us see which new ideas the API review will bring.
