### ISSUE TITLE
order of namespaces in KeySet

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3084]
Currently keys are added in alphabetical order, thus the namespaces would be in following order:

1. default
1. dir
1. proc
1. spec
1. system
1. user

More logical, however, would be to have the keys in order of preference:

1. spec
1. proc
1. dir
1. user
1. system
1. default

This could be implemented similar to #2698: Within the unescaped key names there could be some prefix that brings the keys to the desired order.

**Comment by kodebach** [comment]
We already have an `enum` for all the namespaces. Why don't just use that as the first byte of the unescaped name. For example the key `spec/foo/bar/key` would become `\4\0foo\0bar\0key\0`. That would also simplify `keyGetNamespace`.

IMO we should strive to make `elektraUnescapeKeyName` more efficient, so we should really think hard before adding stuff to it. And more importantly everything we add has to be benchmarked first, since `elektraUnescapeKeyName` is called a lot.

In this case there shouldn't be performance hit, since we already have to check the namespace when creating a key. We might have to move the check somewhere else, to avoid checking twice, but it should be possible to do efficiently.

**Comment by markus2330** [comment]
> We already have an enum for all the namespaces. Why don't just use that as the first byte of the unescaped name. For example the key spec/foo/bar/key would become \4\0foo\0bar\0key\0. That would also simplify keyGetNamespace.

Excellent suggestion! I like this idea very much!

> IMO we should strive to make elektraUnescapeKeyName more efficient, so we should really think hard before adding stuff to it. And more importantly everything we add has to be benchmarked first, since elektraUnescapeKeyName is called a lot.

I think the most expensive stuff is already implemented, the ordering and array escaping should be cheap compared to what we already have.

**Comment by kodebach** [comment]
I will implement this and look into possible optimizations as well. I think I found some minor problems already.

**Comment by markus2330** [comment]
Thank you sooo much :sparkling_heart:
