### ISSUE TITLE
get rid of kdbprivate.h in bindings/tools

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3162]
- [ ] src/tools/kdb/get.cpp:#include <kdbprivate.h>
- [ ] src/tools/kdb/mount.cpp:#include <kdbprivate.h>
- [x] src/bindings/glib/gelektra-keyset.c:#include <kdbprivate.h>
- [x] src/bindings/glib/gelektra-key.c:#include <kdbprivate.h>
- [ ] src/bindings/intercept/fs/intercept.c:#include <kdbprivate.h>

@manuelm can fix the glib bindings and @PhilippGackstatter the others?

**Comment by manuelm** [comment]
>  src/bindings/glib/gelektra-key.c

The glib object model is splitting object creation and initialization. That's why glib is calling the private `keyVInit`. I can remove the call, but every call to `gelektra_key_new` will in fact create two keys. One empty keyNew that gets immediately freed again. And the second keyNew-call with the actual arguments. It's not possible to work around this.

>  src/bindings/glib/gelektra-keyset.c

Doable. But one `gelektra_keyset_new` call will result in multiple realloc. One for every key to append. It's calling `ksResize` internally.

Shall I proceed? I also don't quite understand why it's suddenly forbidden to call private methods for *shipped* bindings.

**Comment by markus2330** [comment]
> One empty key that gets immediately freed again.

Isn't there some rule that init needs to be called after new? So why not simply doing nothing in new and create the key in init?

If something like this is not possible, it is mostly about documentation, it should be easy to understand which parts of Elektra needs which internals and why.

There are several ways to fix this:

1. we write a design decision about keyVInit (why it is needed for GLib)
2. we document the need directly next to kdbprivate.h header inclusion
3. we create a new header kdbbinding.h which includes ref counting, locking, and keyVInit (if needed)

If it is possible, however, it would be better to not have keyVInit as it is some additional maintenance burden. Every additional symbol in the core has some cost, both in maintenance as in library size (I would be interested how much the difference is, maybe you can find out in your thesis).

> But one gelektra_keyset_new call will result in multiple reallocs. 

Without benchmarks it is hard to say if this is a relevant issue or not.

>  I also don't quite understand why it's suddenly forbidden to call private methods for shipped bindings.

Distributions, afaik, always ship all binary package of one source package together. So the bindings will match the core version. But from the architecture/maintenance point of view it is much better if modules do not depend on internals of other modules.

**Comment by manuelm** [comment]
If you want to drop va_args for glib, I expect you also drop va_args for libelektra itself. Then the bindings don't have to mimic and workaround the argument passing anymore.

I've created a PR which drops kdbprivate. Feel free to merge it or close it.

**Comment by markus2330** [comment]
> If you want to drop va_args for glib, I expect you also drop va_args for libelektra itself.

Unfortunately, this change is too big.

> Then the bindings don't have to mimic and workaround the argument passing anymore.

Some bindings found quite elegant solutions for that. But of course, the va_args do not help the bindings but are rather a source for trouble.

**Comment by PhilippGackstatter** [comment]
For the intercept plugin, I think I can't remove the dependency on `kdbprivate.h`. 

The only need for the header is here

https://github.com/ElektraInitiative/libelektra/blob/cc2a31416836c1bff91eb9d9d5f2dd4ad29bb418/src/bindings/intercept/fs/intercept.c#L261-L264

But removing the header results in `pointer to incomplete class type is not allowed` in line `264` and since the `_Plugin` type is defined in `kdbprivate.h`, I don't think we can remove it.

**Comment by markus2330** [comment]
Yes, we would need to replace this call with libinvoke. As the intercept plugin is very experimental it is maybe not worth the effort.
