### ISSUE TITLE
[CM P0] implement external iterators

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3171]
As written in  #2991 we want to switch to external iterators. Which bindings do still make use of the internal iterators (ksNext and friends?). They should be removed/deprecated and an external iterator provided instead.

- [x] #4281
- [x] Java (remove internal)
- [X] Rust
- [X] Go
- [X] GLIB
- [ ] #4280
- [x] #4279

---

The functions that will be removed are:

```c
int ksRewind (KeySet *ks);
Key *ksNext (KeySet *ks);
Key *ksCurrent (const KeySet *ks);

elektraCursor ksGetCursor (const KeySet *ks);
int ksSetCursor (KeySet *ks, elektraCursor cursor);

int keyRewindMeta (Key *key);
const Key *keyNextMeta (Key *key);
const Key *keyCurrentMeta (const Key *key);
```

**Comment by manuelm** [comment]
Both python and lua are using the CPP iterators. So if you remove them you are also removing them from python+lua.

**Comment by Piankero** [comment]
The java implementation already uses an [external iterator](https://github.com/ElektraInitiative/libelektra/blob/38fc1a4046449d36b6007f70ede8395b4fac36c8/src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeySetIterator.java#L9)

Once ksNext() is removed, [this](https://github.com/ElektraInitiative/libelektra/blob/c4c31f047428a77c60d68cbcff52dbd2d7fa1c68/src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeySet.java#L256-L258) line should also be removed.

**Comment by manuelm** [comment]
@Piankero I assume `ksRewind`, `ksNext`, `ksCurrent`

@markus2330 You should add Ruby. It's actually wrapping all three and also using them in the ruby iterator implementation

**Comment by markus2330** [comment]
Thank you for the hint, I added Ruby (@BernhardDenner).

@Piankero can you fix Java, it should be quite easy for you to write an iterator?

**Comment by Piankero** [comment]
> @Piankero can you fix Java, it should be quite easy for you to write an iterator?

There is already an external iterator written as I have written in the upper comment.

**Comment by Piankero** [comment]
@manuelm @markus2330 Are you sure about the ksRewind? If I remove [this](https://github.com/ElektraInitiative/libelektra/blob/9c33d843cf3074b4c5825ccb94d7bc77466a9499/src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/NativePlugin.java#L88) line I receive test failures in the integration tests of jna.

**Comment by markus2330** [comment]
Yes, the tests also need update.

**Comment by Piankero** [comment]
> Yes, the tests also need update.

I already have updated some test cases but the set/get methods seem to need a rewinded keyset. what should I do if I cannot rewind it anymore?

**Comment by markus2330** [comment]
Thank you this is really a good point. I am afraid we need to fix all plugins that use the internal cursor to properly rewind before using the iterator.

We also need some docu (in the release notes) how to use the external iterator and how to migrate away from the internal iterator:

1. we only use external iterator from now on.
2. after 1.0 release we slowly start replacing usage of internal iterator (to use external iterator instead)

**Comment by markus2330** [comment]
ksGet/SetCursor is also a friend of ksNext, I opened #3189 for that.

**Comment by Piankero** [comment]
This issue is unrelated to visible error messages.
As discussed in the Elektra meeting I may unassign myself.

**Comment by markus2330** [comment]
@Piankero this would be a quite simple Java task.

**Comment by Piankero** [comment]
Yes it is an easy task but I cannot remove the deprecated iterator because the tests use plugins that expect a rewinded keyset and I cannot rewind them any longer. Until those plugins are fixed I could not do that anyhow. 

Nontheless we discussed that only error message specific tasks are prioritized because of time constaints so this will have to be done by someone else unfortunately. :(

**Comment by kodebach** [comment]
At least some of the internal iterator functions exposed by the C++ API are not use at all (or only by test cases) and could therefore be removed right now without breaking anything (in our repo).

**Comment by markus2330** [comment]
The iterators need more thought, I do not think it is suitable for CM.

Only @tucek could look into it for Java. (Removing ksNext, ksCurrent and so on.)

**Comment by tucek** [comment]
So what functions are you planning to remove exactly?
- [ ] ksRewind
- [ ] ksNext
- [ ] ksCurrent
- [ ] ksGetCursor
- [ ] ksSetCursor
- [ ] ksAtCursor
- [ ] anything else?

**Comment by kodebach** [comment]
I think you've got most of it. But `ksAtCursor` needs to stay and just be renamed to `ksAt`. It doesn't use the internal cursor, but takes an external cursor value. Also `elektraKsPopAtCursor` should replace the current `ksPop`. See also #3189.

IMO, the end goal would be to remove `Key * cursor` and `size_t current` from `struct _KeySet`. So anything that uses it and doesn't serve another purpose (e.g. `ksLookup` sets the cursor, but clearly has a different purpose) should be removed. Anything that uses it, but has another purpose needs to be modified.

**Comment by tucek** [comment]
@markus2330 @kodebach
- i currently cannot rename `Elektra::ksAtCursor` to `Elektra::ksAt`, since it is not yet renamed in the native library. Regarding the JNA binding, it does not really matter anyways, because it already features the method with signature `Key KeySet::at(Pointer, int)`...
- i've removed `Elektra::ksNext`, `Elektra::ksCurrent`, `Elektra::ksGetCursor`, `Elektra::ksSetCursor`, `KeySet::next`, `KeySet::current`, `KeySet::rewind`, `KeySet::getCursor`, `KeySet::setCursor`
- i've deprecated `Elektra::ksRewind`, since it is needed to rewind the a `KeySet` before handing it to a native plugin via `NativePlugin::set`, `NativePlugin::get` and `NativePlugin::error`

btw. i'm getting the following output for some test in master (test are not failing):
```
Running org.libelektra.GOptsTest
Invalid name:  (in keyVNew at src/libs/elektra/key.c:238)
Invalid name:  (in keyVNew at src/libs/elektra/key.c:238)
Invalid name:  (in keyVNew at src/libs/elektra/key.c:238)
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.038 sec
```
```
Running org.libelektra.GOptsTest
Invalid name:  (in keyVNew at src/libs/elektra/key.c:238)
Invalid name:  (in keyVNew at src/libs/elektra/key.c:238)
Invalid name:  (in keyVNew at src/libs/elektra/key.c:238)
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.038 sec
```

I've also noticed that `KeySetIterator` is yet missing tests.

see draft PR #3706

**Comment by kodebach** [comment]
> * i've deprecated `Elektra::ksRewind`, since it is needed to rewind the a `KeySet` before handing it to a native plugin via `NativePlugin::set`, `NativePlugin::get` and `NativePlugin::error`

I haven't looked that closely at the Java Binding, but could you call `Elektra::ksRewind` inside the `NativePlugin` methods and make it package-private to essentially remove it? Or is that not possible?

> btw. i'm getting the following output for some test in master (test are not failing): [...]

The "Invalid name: " messages are log messages, these will not cause test errors automatically. However, if you are not explicitly testing for invalid key names, then there shouldn't be any such messages.

In this case something tries to call `keyNew ("", KEY_END)` (possible with more arguments before `KEY_END`). You can tell that this happens, since the full log message should be `Invalid name: <KEYNAME> (in keyVNew at src/libs/elektra/key.c:238)`. So in this case `<KEYNAME>` must be an empty string.

Normally, to debug this, I would suggest adding a breakpoint at `src/libs/elektra/key.c:238` and looking at the call stack, to find the problem. But I don't think adding breakpoints to the native code is easily possible with JNA, so you'll have to manually check where the invalid key name comes from. If it only happens in the `GOptsTest` it shouldn't be hard to find, just check the parts of the binding that are only used there.

**Comment by tucek** [comment]
> > * i've deprecated `Elektra::ksRewind`, since it is needed to rewind the a `KeySet` before handing it to a native plugin via `NativePlugin::set`, `NativePlugin::get` and `NativePlugin::error`
> 
> I haven't looked that closely at the Java Binding, but could you call `Elektra::ksRewind` inside the `NativePlugin` methods and make it package-private to essentially remove it? Or is that not possible?
I could only make the `Elektra` interface as a whole package private. This would also require the `NativePlugin` class to be moved to the same package as the `Elektra` interface. In my opinion this would not make things better. Explicitly annotating the `Elektra::ksRewind` as 'deprecated for removal' should suffice imho.

> > btw. i'm getting the following output for some test in master (test are not failing): [...]
> 
> The "Invalid name: " messages are log messages, these will not cause test errors automatically. However, if you are not explicitly testing for invalid key names, then there shouldn't be any such messages.
> 
> In this case something tries to call `keyNew ("", KEY_END)` (possible with more arguments before `KEY_END`). You can tell that this happens, since the full log message should be `Invalid name: <KEYNAME> (in keyVNew at src/libs/elektra/key.c:238)`. So in this case `<KEYNAME>` must be an empty string.
> 
> Normally, to debug this, I would suggest adding a breakpoint at `src/libs/elektra/key.c:238` and looking at the call stack, to find the problem. But I don't think adding breakpoints to the native code is easily possible with JNA, so you'll have to manually check where the invalid key name comes from. If it only happens in the `GOptsTest` it shouldn't be hard to find, just check the parts of the binding that are only used there.

I've debugged the affected Java tests. the only thing i can see so far is, that it happens after `kdb.set` operations `GOptsTest.java:55` and `KDBTest.java:44`.

Anyways i cannot see an adverse effect regarding the tests and since this was already an issue in master i would deem it out of scope of #3171.

**Comment by kodebach** [comment]
> Anyways i cannot see an adverse effect regarding the tests and since this was already an issue in master i would deem it out of scope of #3171.

If you don't fix it, please create a separate issue, so we don't forget to fix it later

**Comment by tucek** [comment]
> > Anyways i cannot see an adverse effect regarding the tests and since this was already an issue in master i would deem it out of scope of #3171.
> 
> If you don't fix it, please create a separate issue, so we don't forget to fix it later

I've created #3710 to address this issue.

**Comment by tucek** [comment]
@kodebach Was the Java binding the last to be updated and we can now close this issue?

**Comment by kodebach** [comment]
I'm not sure, let's keep the issue open for now. But your part is done, so I unassigned you...

**Comment by markus2330** [comment]
@kodebach can you write a new issue about rewriting the parts that still use ksNext/ksRewind etc.? In particular rewriting the plugins would be quite suitable for CM.

**Comment by kodebach** [comment]
> @kodebach can you write a new issue about rewriting the parts that still use ksNext/ksRewind etc.? In particular rewriting the plugins would be quite suitable for CM.

I created #4279, #4280, #4281. Please label them with the appropriate points for CM.
