### ISSUE TITLE
Cirrus timeout

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3211]
My [last bulid](https://cirrus-ci.com/task/5783213456228352?command=tests#L667) on Cirrus timed out after 45 minutes.

```sh
run_all RESULTS: 160 test(s) done 0 error(s).
output="$(cmake --build "$BUILD_DIR" --target uninstall 2>&1)" || printf '%s' "$output"
cmake --build "$BUILD_DIR" --target uninstall 2>&1
Timed out!
```

I just restarted it, but we should do something about it if this happens more often. Has somebody already had similar problems?

**Comment by markus2330** [comment]
I think there is little we can do, unfortunately external providers always have some arbitrary constraints which you need to live with. I personally think we should migrate as much as possible to Jenkins, where we do not have any constraints (except of the hardware).

@sanssecours already fixed many similar issues, usually by reducing something not to be built/tested. But I am not sure what the actual problem is here.

**Comment by markus2330** [comment]
Please reopen if further problems occur.
