### ISSUE TITLE
update elektra-glossary.md

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3240]
Following is not explained in doc/help/elektra-glossary.md

- [ ] key name
- [ ] key base name
- [ ] key name part

@kodebach can you do this within #3115 once it is settled?

**Comment by kodebach** [comment]
Will do

**Comment by kodebach** [comment]
See #3596. Note: I did not add "empty base name", because I don't think it's important enough to be included in the glossary. Without going into details about key name structure and escaped vs. unescaped name, empty key name parts also can really be explained.

In general I think, we should try to compact and slim down our documentation and **not** duplicate information. Elektra's documentation is already harder to navigate than some of the code base. Adding small pieces of information everywhere doesn't help users find what the are looking for.

**Comment by mpranj** [comment]
> In general I think, we should try to compact and slim down our documentation and not duplicate information. Elektra's documentation is already harder to navigate than some of the code base. Adding small pieces of information everywhere doesn't help users find what the are looking for.

I agree that this is an important point.

**Comment by markus2330** [comment]
Yes I agree, if we already have such pieces of information somewhere else (like in the key name docu) it is better to only refer to the place.
