### ISSUE TITLE
Avoid calling the new merge "cmerge"

### ISSUE THREAD

**Issue by Chemin1** [ElektraInitiative/libelektra#3254]
@markus2330  When mentioning [this](https://github.com/ElektraInitiative/libelektra/pull/3236#discussion_r347518825)

> I really recommend you (again) to avoid using the word "cmerge". It will be a lot of work to rename all of this. 

I assume you were referring to [this](https://github.com/ElektraInitiative/libelektra/issues/3132#issuecomment-547795797)
> Btw. it is good if we can get rid of the name "cmerge" as fast as possible (and use "merge" everywhere).
 
I initially thought "as fast as possible" included removing the old merge but now it seems you meant something else? We could, for example, replace all occurences of the name "cmerge" in `doc/tutorials/cmerge.md` (`merge.md` is already taken btw) that are not used in the shell recorder tests with "merge" -- but wouldn't it be confusing to have two different names for the same thing in the same document?

**Comment by markus2330** [comment]
Thank you for creating the question! As you already created the PRs introducing the tools, you can also create a PR which gets rid of the old merge libraries.

> merge.md is already taken btw

This file will also be replaced with content about your merge.

Somehow we need to find good timing so that every release either still has cmerge/merge or only merge (which is what we call "cmerge" now). From my point of view actually one big PR which gets rid of all the old merging tooling and uses the new merging tooling instead would be not so bad. (Because it is a breaking change and merging intermediate states can lead to a situation where we cannot release.)

**Comment by Chemin1** [comment]
> From my point of view actually one big PR which gets rid of all the old merging tooling and uses the new merging tooling instead would be not so bad.

Done with #3260
