### ISSUE TITLE
qt-gui: large list of search results becomes empty when scrolling 

### ISSUE THREAD

**Issue by 0003088** [ElektraInitiative/libelektra#328]
When a search term has many hits, the listview will become empty when the user scrolls fast through the search results. This does not happen when the user scrolls slowly. Probably a bug in Qt. Will try to find a solution.

**Comment by 0003088** [comment]
Well, it turned out that this was no Qt bug after all. In fact, it was a problem that I mentioned in my very own thesis: object ownership. I do not know why exactly, but QML just deleted the model. Setting the ownership to C++ solves the issue (but leaves an object in the memory, until the app is closed). Is there a way to solve this without a smartpointer?

**Comment by markus2330** [comment]
Garbage collection would be the alternative to smart pointers.

Did you do some tests with this fix? Is the program behaviour otherwise identical? Will it cause some memory leaks within QML?

There also seem to be ways to bind the ownership for individual objects with [newQObject](http://doc.qt.io/qt-5/qscriptengine.html#newQObject).

Btw. Felix will fix the merging, so that writing out all configuration won't happen even if a merge conflict occurs.

**Comment by 0003088** [comment]
I have repeatetly used the search, closed the search window, searched again, closed the gui etc. and was not able to produce a crash. So I could not find any obvious bug. With the C++ ownership the model has nothing to do with QML any more, only the  backend can destroy a model that contains search results. So I do not believe that there will be any memleaks in QML. Every time the search feature is used, there will be a model left in memory however. I do not believe that this behaviour is dramatic, since the contained nodes are not duplicated and a model alone does not use that much memory, but still...

What about a method that can be called from QML and that itself calls the model destructor? So every time the search window is closed or the model is swapped, I could call the method and destroy the old model? What do you think about that?

**Comment by markus2330** [comment]
Such swapping and deleting is a standard approach, sounds good.
