### ISSUE TITLE
Lua binding: ipairs skips first key

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#3480]
## Steps to Reproduce the Problem

Compile and run `make run_all`. (Specifically `test_keyset.lua`)

## Expected Result

Compilation and tests should be sucessful.

## Actual Result

`test_keyset.lua` fails with a nondescript error. On closer inspection, it turns out that `ipairs` (Line 66) always skips the first Key in the KeySet.

## System Information

- Elektra Version: master
- Operating System: Manjaro Stable Version, up-to-date as of 2020-09-05
- Lua Version: 5.4.0 (specifically 5.4.0-2 from the Manjaro extra repo)

## Further Information

AFAIK Lua uses indexes starting from 1. Maybe this isn't adjusted to a zero-based index somewhere.

**Comment by mpranj** [comment]
I can confirm that this happenes. I noticed it during (trying) updating our CI with Fedora 33, which introduces Lua 5.4.

What I observed is that one Lua version uses a floating point loop index that goes "1.0, 2.0, 3.0, 4.0" and the other Lua version uses integers "1, 2, 3".

@manuelm do you have any idea what's going on there? What's especially confusing is that with Lua 5.4 one Key is simply skipped/missing.

**Comment by manuelm** [comment]
Because of ` The ipairs iterator now respects metamethods and its __ipairs metamethod has been deprecated. ` (from Lua 5.3). So the internal ipairs hook which basically does `ks.at(i - 1)` no longer gets called.

The "easiest" way forward would be to add our own iterator. e.g. something like `for k in ks:ipairs() do ... end`
