### ISSUE TITLE
rename all plugins's `.so`s

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3486]
As @poldi871reported in #3472 on embedded systems (with the cmake option `TARGET_PLUGIN_FOLDER=""`) `kdb plugin-list` reports both libraries and plugins. Also by looking at the names of the `.so`s you cannot know what a plugin is.

An easy fix for both problems would be to rename the `.so`s to e.g. `libelektra-plugin-toml.so` instead of `libelektra-toml.so`. This is a bit redundancy in the case  `TARGET_PLUGIN_FOLDER!=""` but helpful in many other situations (e.g. when looking into the `lib` folder of the cmake build dir), e.g. on my system (where `kdb get system/info/elektra/constants/cmake/BUILTIN_PLUGIN_FOLDER` returns `/usr/lib/x86_64-linux-gnu/elektra4` the plugins would be called e.g. `/usr/lib/x86_64-linux-gnu/elektra4/libelektra-plugin-toml.so`.

So I propose to do this rename. Obviously it is an incompatible change: Elektra needs to be fully reinstalled as the new core would only find newly installed plugins (and not the ones with the old name). Furthermore, I propose (maybe even the bigger change in terms of work) that we drop the name "modules". Instead, only the name "plugin" should be used for plugins, even on loader level. E.g. elektraModulesLoad would be renamed to elektraPluginLoad. I also think that these 3 functions for plugin loading should be public, as they are handy in many situations (e.g. for import/export configuration).

What do you think?

**Comment by mpranj** [comment]
I agree with this proposal, and there is no better time to do this than pre-1.0. :+1:

**Comment by markus2330** [comment]
@kodebach any thoughts on this?

**Comment by kodebach** [comment]
Yes, adding a `-plugin-` part to plugin SOs is a very good idea. It would also avoid weird cases like having to call the plugin `gopts`, because `opts` would conflict with the library.

> Furthermore, I propose (maybe even the bigger change in terms of work) that we drop the name "modules". Instead, only the name "plugin" should be used for plugins, even on loader level.

Since `elektraModulesLoad` already returns a `elektraPluginFactory` that is a sensible change.

Additionally, I would also change `elektraPluginFactory` from

```c
typedef Plugin * (*elektraPluginFactory) (void);
```

to 

```c
typedef KeySet * (*elektraPluginFactory) (void);
```

where the returned `KeySet *` is the contract of the Plugin to avoid the hacky overload of the `get` function.
I think that is already mentioned in another issue. This also requires changing `elektraPluginExport` and `elektraPluginOpen`, but should be doable without any other changes.

**Comment by markus2330** [comment]
Thank you for your input!

I have split the issues: this issue is only about renaming: adding the `-plugin-` part, for the rest there is #4490.

**Comment by markus2330** [comment]
@tmakar last issue for you: spec plugin should be renamed to libelektra-plugin-spec.so (and likewise for all other plugins)

**Comment by kodebach** [comment]
@tmakar One way this issue can definitely be solved is by adding the `-plugin-` in this line:

https://github.com/ElektraInitiative/libelektra/blob/ef00c963e05307cfb5e38d9365cac522b4c80803/scripts/cmake/Modules/LibAddPlugin.cmake#L430

IMO this would be the best option, but it will probably require more changes to CMake elsewhere, since this changes the name of the CMake targets for plugins.

CMake also supports setting an [`OUTPUT_NAME`](https://cmake.org/cmake/help/latest/prop_tgt/OUTPUT_NAME.html#prop_tgt:OUTPUT_NAME) for each target independent of the name of a target. That is probably quicker to implement. I haven't looked into details, but I suspect this would only require adding one (or a few) line below this one

https://github.com/ElektraInitiative/libelektra/blob/ef00c963e05307cfb5e38d9365cac522b4c80803/scripts/cmake/Modules/LibAddPlugin.cmake#L639

to set the `OUTPUT_NAME` for the `${PLUGIN_NAME}` target.

**Comment by tmakar** [comment]
> @tmakar One way this issue can definitely be solved is by adding the `-plugin-` in this line:
> 
> https://github.com/ElektraInitiative/libelektra/blob/ef00c963e05307cfb5e38d9365cac522b4c80803/scripts/cmake/Modules/LibAddPlugin.cmake#L430
> 
> IMO this would be the best option, but it will probably require more changes to CMake elsewhere, since this changes the name of the CMake targets for plugins.
> 
> CMake also supports setting an [`OUTPUT_NAME`](https://cmake.org/cmake/help/latest/prop_tgt/OUTPUT_NAME.html#prop_tgt:OUTPUT_NAME) for each target independent of the name of a target. That is probably quicker to implement. I haven't looked into details, but I suspect this would only require adding one (or a few) line below this one
> 
> https://github.com/ElektraInitiative/libelektra/blob/ef00c963e05307cfb5e38d9365cac522b4c80803/scripts/cmake/Modules/LibAddPlugin.cmake#L639
> 
> to set the `OUTPUT_NAME` for the `${PLUGIN_NAME}` target.

Thanks for the details!!

**Comment by tmakar** [comment]
@markus2330  PR exists in #4919.
