### ISSUE TITLE
TOML spacing

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3490]
I played around with the new TOML plugin and must say it works beyond expectations, it is definitely superior to ini. The only things I noticed so far are some texts in error messages:

- [x] we should not expect people to know what rhs or lhs is

and spacing:

- [ ] a practical problem is that some INI parsers (in particular everything related to shells) do not accept spaces around `=`, see also #2065. Ideally, the parser would remember what spaces are around `=` and restore it as it was.
- [ ] a cosmetic problem is that spaces before the key name get removed. Probably nearly nobody would do this, if the example on https://toml.io/en/ would not promote this usage. But as it is, people quickly find out, e.g. #3472. Also here the ideal solution would be the restore it as it was.

String quoting seems to be a bit buggy (You will probably catch these things with `kdb test`):

- [x]  `path = 'C:\Users\nodejs\templates'`in a TOML file gets after roundtrip rewritten to `path = "C:\Users\nodejs\templates"` which leads to a parse error.

- [x] Some rare features like `1e06`numbers seem to be not supported. (The parser currently thinks it is a bare string.) Imho rather low priority.

Something else:

- [x] Keys with empty names seem to be currently not supported. In Elektra you can represent them by giving them an empty base name. In TOML you can represent them with
```toml
"" = "blank"     # VALID but discouraged
'' = 'blank'     # VALID but discouraged
```
(Btw. I think this example within the TOML spec is broken as another example says that multiple keys with the same name is not allowed.)

I do not think that any of these problems is urgent enough that it must be fixed for the next release. If I could choose something, I think the error messages are the most important thing. It might be good, however, that the current gaps to the TOML standard are documented in the README.md (and which version it should be compliant to.)

So in general I am very positive about this plugin, it greatly improves Elektra :sparkling_heart:  I'll remove the ini plugin, as I am very positive that soon the toml plugin will cover essentially every use case the ini plugin fulfilled but unlike the ini plugin, it will be properly maintained.

**Comment by bauhaus93** [comment]
> I played around with the new TOML plugin and must say it works beyond expectations, it is definitely superior to ini. The only things I noticed so far are some texts in error messages

Thanks, I'm glad it works so well! I will look through all error messages and make them more clear.

 > a practical problem is that some INI parsers (in particular everything related to shells) do not accept spaces around =, see also #2065. Ideally, the parser would remember what spaces are around = and restore it as it was.
a cosmetic problem is that spaces before the key name get removed. Probably nearly nobody would do this, if the example on https://toml.io/en/ would not promote this usage. But as it is, people quickly find out, e.g. #3472. Also here the ideal solution would be the restore it as it was.

I can look into preserving the correct amount of spaces for those. I think I've already an idea on how to solve this without inflating the bison grammar too much/at all (which was my reason for not doing it in the first place). 

> String quoting seems to be a bit buggy (You will probably catch these things with kdb test)

Yes, strings are currently only written as basic strings. I'll look into this issue in the default storage PR #3478, since the unexpected escaping is causing problems there also.
For solving this, I currently consider 2 possible solutions:

- Introduce a metakey which hints that the string contains escape sequences. Only write a basic string, when the metakey is present (making literal strings the default for writing). The metakey would be set by the plugin on the reading of basic strings or manually by the user.
- On writing, check what the "best" type of string would be. Eg. check if the string contains any `'` or `"` characters. Additionally, check if the string contains only valid escape sequences (or none at all). Then, with this parameters, derive the most appropriate type of string. The problem here would be, that if a string contains only valid escape sequences by accident,  it may falsely be seen as a basic string (eg. a file path of `C:\tmp\name`).

> Some rare features like 1e06numbers seem to be not supported. (The parser currently thinks it is a bare string.) Imho rather low priority.

I'll look into this issue as well, this should already have been supported.

> Keys with empty names seem to be currently not supported. In Elektra you can represent them by giving them an empty base name. In TOML you can represent them with

I'll check this out too. I don't think this case is currently handled at all.


I will look through all this issues, prioritizing the error messages and mentioning the current gaps to the TOML standard in the readme.

**Comment by markus2330** [comment]
@bauhaus93 can you update the top-post? Which of these issues are now resolved via the PR that was merged?

**Comment by bauhaus93** [comment]
@markus2330 I've updated the top post

**Comment by markus2330** [comment]
@kodebach is the point " path = 'C:\Users\nodejs\templates'in a TOML file gets after roundtrip rewritten to path = "C:\Users\nodejs\templates" which leads to a parse error." already fixed?

**Comment by kodebach** [comment]
It should be fixed in #3935. I'll try to finish the PR this week.

The code is already there, if you wanna test it. Documentation and tests are still missing, and the handling of comments will change again.

We do also validate all string values before writing, so that we never create an invalid TOML file. In the case mentioned here, you will get the literal string `'C:\Users\nodejs\templates'`. If you remove the `tomltype` metakey that is used to remember the kind of string, you will get a correctly escaped basic string `"C:\\Users\\nodejs\\templates"`.

Without a `tomltype` we default to basic strings (or multiline basic strings, if there are 2 or more `\n`), because those can be used for any valid UTF-8 string. If the string is not UTF-8, we will replace invalid sections with the Replacement Character (U+FFFD) and emit a warning.

If you wanna know more take a look [at the code](https://github.com/ElektraInitiative/libelektra/blob/91eadccda858e16359677e80a5dc36906c065752/src/plugins/toml/write.c) or wait for me to finish the docs.

**Comment by markus2330** [comment]
@kodebach which issues here are still open? I remember you fixed many problems with quoting?

**Comment by kodebach** [comment]
I'd have to check again, but I know `toml` definitely doesn't (fully) support metadata. Also https://github.com/ElektraInitiative/libelektra/blob/master/src/plugins/toml/toml/checks_toml_1_0_0/roundtrip.toml still contains some commented out test-cases with `TODOs`. Finally, from looking at some of the text files in VSCode, it seems we support some positions for comments that are maybe not allowed by the TOML spec e.g.

```toml
[[table_array]] # error in VSCode, but valid in Elektra
```

**Comment by markus2330** [comment]
> I'd have to check again for the full details

Thank you! Is it maybe possible to work on these issues for FLOSS or is the whole lexer/parser too complicated for a new-comer?

> it seems we support some positions for comments

I think this is okay.

**Comment by kodebach** [comment]
I think if someone has prior experience with flex/bison parsing (not unreasonable, considering there are other courses for that), then working on this should be possible. The code is pretty readable IMO and on the TOML side there is a good spec and many examples to show what is allowed and what isn't. There are even some GitHub repos with lots of TOML files for testing parsers.

**Comment by markus2330** [comment]
@kodebach this issue is for everything that is not #2330 (further features etc.)

**Comment by kodebach** [comment]
#2330 is closed, did you mean #3910 or maybe #4466?

**Comment by markus2330** [comment]
I mean https://github.com/ElektraInitiative/libelektra/issues/3910.

So actually only the spacing issues are left-over here. I don't think this is crucial for having toml as default storage.

**Comment by flo91** [comment]
@markus2330 Maybe an issue for the FLOSS course?

**Comment by markus2330** [comment]
It is a bit difficult to implement and has much lower priority than #3910.
