### ISSUE TITLE
make simpleini/mini provide storage/properties

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3516]
As mini correctly states: "maybe this is not INI" we might want to correct "infos/provides" to "storage/properties".

The same is true for simpleini. In simpleini, however, there is a severe bug that empty values do not work. So probably we need to remove simpleini anyway. (Didn't look into the details, I only noticed it yesterday in an export/import.)

@sanssecours What do you think?

**Comment by kodebach** [comment]
Is there any reason to keep both, if they both achieve the same thing? Seems like unnecessary maintenance effort.

What about renaming the result to `properties` to make the whole thing less confusing?

**Comment by markus2330** [comment]
> Is there any reason to keep both, if they both achieve the same thing?

Simpleini has a unique feature, it allows you to define the format the properties are parsed/written out. But probably exactly this feature causes the problem with empty values, as the format has the implicit assumption that every property has a key and a value.

> What about renaming the result to properties to make the whole thing less confusing?

As `kdb mount ... properties` would work anyway, I think the funny name MINI: “Maybe this is not INI” is okay :wink:

**Comment by kodebach** [comment]
> Simpleini has a unique feature, [...]

Then we should fix simpleini and keep that.
I think it supports multiple formats, because Java Properties also support multiple key-value separators.

> I think the funny name MINI: “Maybe this is not INI” is okay 😉

It's a funny name, but IMO it makes the codebase needlessly confusing. 

At the very least we also need to add a note to `src/plugins/README.md` that `mini` is for properties files. Otherwise people will just assume there is no properties plugin and not even try `kdb mount ... properties`.

**Comment by sanssecours** [comment]
> @sanssecours What do you think?

I opened pull request #3573, which changes the default format for both `simpleini` and `mini`.
