### ISSUE TITLE
escaping library

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3526]
To start with @kodebach's proposal of a storage library #3496 I would suggest to add (un)escaping which is a rather urgent issue as the code plugins (like ccode) do not work well (they only escape values and not names or meta-data) and its best if we get rid of them.

The first question is: do we already have suitable code for escaping/unescaping?

- hexcode seems to be quite suitable: already has simple API and also the code is trivial. It can be used to escape any chars as needed.
- DoEscape in src/plugins/ni/nickel-1.1.0/src/io.c is more advanced but entangled with the rest of the code.
- As bauhaus said in #3491 the TOML code seems to only contain unescaping but not escaping.
- The ccode plugin is in C++ and thus not so suitable
- @sanssecours do we have a general (un)escaping code in the YAML plugins?

Any other? Which one do you prefer?

**Comment by kodebach** [comment]
In general, however, I'm not sure this is a good fit for the storage library. The functions would have to be very general to accommodate different kinds of escaping. Some storage formats (e.g. TOML, JSON, XML) have pre-defined ways for encoding special characters. These encodings can be quite different. Not just the set of special characters that have be encoded or the escape character itself, but the whole encoding.

A general function probably wouldn't be very usable either. Instead I suggest, we write a guide with tips on how to implement escape sequences. e.g. In decoding use `strchr` (or `strpbrk`) to find escape characters and copy everything else with `memcpy` or `strncpy` (see `elektraKeyNameUnescape` in #3447).

If we still want to provide a function, the function `escapeString` from the `c` plugin might be a good candidate [1] as an encoding function. [2] The decoding function should probably support the full set of C-style escape sequences and not just the subset that `escapeString` produces.

However, there is the further complication some formats (e.g. TOML) are explicitly based on UTF-8. So ideally we wouldn't encode every non-printable ASCII character and all non-ASCII bytes, but only those bytes that are invalid UTF-8 or need to be escaped for other reasons. Otherwise for example we might read a file with the string `"© 2011 John Smith"` and write it back as `"\u00a9 2011 John Smith"`.

---

[1] `escapeString` has a small bug. For example the bytes `C2 AE 31 32` (UTF-8 for `®12`) are encoded as `\xc2\xae12`, but according to [Wikipedia](https://en.wikipedia.org/wiki/Escape_sequences_in_C#Table_of_escape_sequences) `\x` sequences have no length limit, so this is decoded as `C2` and an implementation defined character based on the hex value `ae12`. So any hex digit following the `\xHH` escape sequence must also be encoded as an escape sequence. We could also switch to octal escape sequences those have a max of 3 digits, so we could just encode everything zero-padded to 3 digits to avoid problems.

[2] We might want to add an option to use `\u` escapes instead of `\x` escapes, since some formats (e.g. TOML, JSON) don't support the `\x` syntax. However, I'm not sure if `\xHH` is always the same as `\u00HH`. It could be the case that `\u00HH` assumes UTF-8 and that e.g. `\u00ae` is actually the same as `\xc2\xae`. This might also differ from format to format.

**Comment by markus2330** [comment]
Thank you for this great input!

To clarify the goal: My intention was not to change the escaping/unescaping code of any plugin that already has escaping/unescaping, so TOML, YAML, ni and so on should stay as they are. Also for new plugins that implement some standard it will be not relevant. It is about having some escaping mechanism that works well if there are no constraints how to do escaping are given by the underlying format.

Thank you for pointing out escapeString, this is actually perfect. It is more or less what ccode does but written much more simple.

So the plan would be:

- [ ] to extract the function into a library
- [ ] fix the bug @kodebach pointed out
- [ ] write an unescaping for it
- [ ] write test cases for it
- [ ] use these functions in all plugins that need it (currently depend on code plugin):
   - [ ] c
   - [ ] mini
   - [ ] simpleini
- [ ] remove the code plugins:
   - [ ] hexcode
   - [ ] ccode

Anything I forgot? Any volunteers?

**Comment by sanssecours** [comment]
> @sanssecours do we have a general (un)escaping code in the YAML plugins?

Nope. YAML CPP just uses the [`yaml-cpp`](https://github.com/jbeder/yaml-cpp) library, which should offer support for both escaping and unescaping. The other YAML plugins do not support unescaping (Yan LR) or escaping (YAML Smith) at all.
