### ISSUE TITLE
Make OPMPHM work with zero bytes

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3548]
`opmphmHashfunction` clearly takes both a `const void *` and a `size_t`. So the hash function has no problem with zero bytes.

The other parts of `opmphm.c` are tailored to non-zero strings AFAICT, but I also think we just need to make two small changes:

https://github.com/ElektraInitiative/libelektra/blob/5ebc9a4ba5215950f990f7dca948ce310f764079/src/libs/elektra/opmphm.c#L32-L54

Here we need to pass the size of the key name so we don't have to call `strlen`.

https://github.com/ElektraInitiative/libelektra/blob/5ebc9a4ba5215950f990f7dca948ce310f764079/src/libs/elektra/opmphm.c#L164

https://github.com/ElektraInitiative/libelektra/blob/5ebc9a4ba5215950f990f7dca948ce310f764079/src/libs/elektra/opmphm.c#L182-L191

Here we need to add a `getNameSize` field to `OpmphmInit` to avoid `strlen`.

Both these changes should be pretty simple. Apart from benchmarks/tests these functions are only called in one place each:

https://github.com/ElektraInitiative/libelektra/blob/a5b8684ed10a939b94597e587730ae5b26b09128/src/libs/elektra/keyset.c#L2226

Here we can simply pass the name size.

https://github.com/ElektraInitiative/libelektra/blob/a5b8684ed10a939b94597e587730ae5b26b09128/src/libs/elektra/keyset.c#L2176-L2186

Here we should create a function `elektraOpmphmGetStringSize` similar to `elektraOpmphmGetString` and set in the `OpmphmInit init`.

**Comment by markus2330** [comment]
@KurtMi ping

**Comment by kodebach** [comment]
I checked the source code and it's not as simple as switching `keyName` to `keyUnescapedName`, but is pretty simple to make the hashmap work with zero-bytes. (details below)

Even if we don't remove the escaped name, we should make this update, because it would avoid the unnecessary `strlen` calls. We already know the size of all key names.

---


`opmphmHashfunction` clearly takes both a `const void *` and a `size_t`. So the hash function has no problem with zero bytes.

The other parts of `opmphm.c` are tailored to non-zero strings AFAICT, but I also think we just need to make two small changes:

https://github.com/ElektraInitiative/libelektra/blob/5ebc9a4ba5215950f990f7dca948ce310f764079/src/libs/elektra/opmphm.c#L32-L54

Here we need to pass the size of the key name so we don't have to call `strlen`.

https://github.com/ElektraInitiative/libelektra/blob/5ebc9a4ba5215950f990f7dca948ce310f764079/src/libs/elektra/opmphm.c#L164

https://github.com/ElektraInitiative/libelektra/blob/5ebc9a4ba5215950f990f7dca948ce310f764079/src/libs/elektra/opmphm.c#L182-L191

Here we need to add a `getNameSize` field to `OpmphmInit` to avoid `strlen`.

Both these changes should be pretty simple. Apart from benchmarks/tests these functions are only called in one place each:

https://github.com/ElektraInitiative/libelektra/blob/a5b8684ed10a939b94597e587730ae5b26b09128/src/libs/elektra/keyset.c#L2226

Here we can simply pass the name size.

https://github.com/ElektraInitiative/libelektra/blob/a5b8684ed10a939b94597e587730ae5b26b09128/src/libs/elektra/keyset.c#L2176-L2186

Here we should create a function `elektraOpmphmGetStringSize` similar to `elektraOpmphmGetString` and set in the `OpmphmInit init`.
