### ISSUE TITLE
make namespace enum more future proof

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3567]
At the moment the namespaces are consecutively numbered, which creates problems when we want to introduce new namespaces with the priority somewhere in between. As the enum is an int and as such the is a huge space of numbers we should also use that space to be more future proof.

We could simply append three zeros to every value, then there is space for plenty of namespaces to be introduced in between:
```
    CASCADING = 1000
    META = 2000
    SPEC = 3000
    PROC = 4000
    DIR = 5000
    USER = 6000
    SYSTEM = 7000
    DEFAULT = 8000
```

or the better/more future proof decision would be to divide the whole space of (positive?) ints. The numbers might be a little weird and difficult to remember then, though.

**Comment by mpranj** [comment]
Sounds like a good idea to me too. I would suspect that we do not want to add 999 further namespaces between e.g. cascading and meta. So I think there will be diminishing returns for dividing up the int space equally.

**Comment by kodebach** [comment]
In general, I'm not sure we need this. I can't really think of a situation where we would add a new namespace and need to have it sorted between other namespaces, without causing any breaking changes. And as soon as we have a breaking change, we might as well change the namespace numbers...

---

If want to change it anyway:

The namespace is stored as a single byte in the unescaped name. Therefore the values for the namespaces MUST be in the range `1-255` (0 is reserved for `KEY_NS_NONE`).

Multiplying all values by 10 or 20 should be fine. Also `KEY_NS_CASCADING = 1` should be kept. I don't think a namespace with higher "ranking" makes sense. Also casacading keys shouldn't be inserted into `KeySet`s so the number doesn't really matter. Cascading isn't even really a proper namespace. `KEY_NS_CASCADING` rather indicates the absence of a namespace and the need to resolve the key. So a special value makes sense.

I would propose e.g.:

```
    CASCADING = 1
    META = 10
    SPEC = 30
    PROC = 50
    DIR = 100
    USER = 150
    SYSTEM = 200
    DEFAULT = 250
```

---

If you think this is not enough space between namespaces and we need more range than `1-255`, then I have to say: I won't implement it. I have nothing against the change, but finding and fixing the bugs that are caused by such a change was among the hardest parts of #3555. I really don't want to do that again...

**Comment by markus2330** [comment]
>  I would suspect that we do not want to add 999 further namespaces

It is not really space for 999. Actually, for every added namespace you might use half of the space, so it might be after 9 additions that the space is exceeded.

> I can't really think of a situation where we would add a new namespace and need to have it sorted between other namespaces

This already happened several times in the past, e.g. adding the `dir` namespace. It was completely compatible, so it is possible. Actually it was quite "simple", as the compiler gives you even a warning for all the missing branches in the switch statements.

> The namespace is stored as a single byte in the unescaped name. Therefore the values for the namespaces MUST be in the range 1-255 (0 is reserved for KEY_NS_NONE).

Yes, I agree! I simply forgot about that constraint, I think you mentioned it already.

> I would propose e.g.:

Maybe we should keep the special ones (not part of ordering) together (as it does not matter which number they get), and other one later, what do you think about:

```    
    CASCADING = 1
    META = 2
    SPEC = 3

    PROC = 40
    DIR = 80
    USER = 120
    SYSTEM = 160
    DEFAULT = 200
```

Now I see, I came up with nearly the same as you, so yours is fine, too :wink: The only advantage of mine is that there is plenty of space for very high&low priority namespaces. And my feeling is that these will be more important than somewhere between.

**Comment by kodebach** [comment]
> Now I see, I came up with nearly the same as you, so yours is fine, too  The only advantage of mine is that there is plenty of space for very high&low priority namespaces.

I don't really care either way, but a namespace with lower priority (i.e. higher number) than `DEFAULT` makes very little sense. That's why I put it at `250` (there is space for a few more, if something very unlikely comes up).

**Comment by markus2330** [comment]
If we make special fallback keys (for performance during lookup) and "global defaults" (when there is both a `_` specifier and a concrete default) we already need two more namespaces with lower priority. Of course nobody knows which namespaces will be really needed in future but I would have a better feeling with more space at the ends.

**Comment by kodebach** [comment]
I just tried again to change the values in #3596, but I stumbled upon a few problems. We need to discuss a few more things before this can be implemented.

1. Using values bigger than 127 leads to some annoying errors at first. This because the unescaped name is still a `char *`, so sometimes casts are necessary to avoid the compiler warnings. This could also be solved by using e.g. -56 instead of 200 (I think that's the right conversion)
2. The bigger problem: Some of these values are not valid UTF-8 (see below). That doesn't matter in C, but some bindings (I encountered it in Java) expect valid UTF-8. I think the main problem here is the way the name iterators work in most bindings. They expect that each key name part is a string, but the first part in the unescaped name is the namespace, which is not a string.

The original values had the advantage of being ASCII non-print/control characters. On top that they were ASCII control characters that don't have much effect under most circumstances. The only exception is `KEY_NS_DEFAULT` which is backspace in ASCII, but that is also mostly ignored in non-interactive contexts.

The new values are interpreted as follows:
```
    CASCADING = 1     0x01 -> ASCII/UTF-8 control character "Start of Heading"
    META = 2          0x02 -> ASCII/UTF-8 control character "Start of Text"
    SPEC = 3          0x03 -> ASCII/UTF-8 control character "End of Text"

    PROC = 40         0x28 -> ASCII/UTF-8 for '('
    DIR = 80          0x50 -> ASCII/UTF-8 for 'P'
    USER = 120        0x78 -> ASCII/UTF-8 for 'x'
    SYSTEM = 160      0xA0 -> non-ASCII, invalid UTF-8 (only valid as second, third or fourth byte of sequence) 
    DEFAULT = 200     0xC8 -> non-ASCII, invalid UTF-8 (would start a 2 byte sequence, but is followed by 0x00 in unescaped key name, which is not valid)
```

---

There are now two solutions:

1. Change the arguable wrong key name iterators. Two options:
    1. The iterators return byte arrays (or the language equivalent) as elements instead of string. Technically the "correct" solution, but inconvenient in most situations.
   2. Name iterators no longer return the namespace as the first element. Only the "path" is returned. This way using string should still mostly work, but of course in theory a key name must not be valid UTF-8 (or whatever encoding).
2. Only use ASCII bytes for `elektraNamespace`. The easiest, but arguably worst solution.

**Comment by markus2330** [comment]
> This because the unescaped name is still a char *

We can change to `unsigned char *`. As it is unspecified if `char` is signed or unsigned and we now actually interpret a byte of it as number, it is not an ideal situation anyway.

> This could also be solved by using e.g. -56

Not really, some compilers interpret `char` as `unsigned` and you will get warnings/errors on these compilers then.

>  Some of these values are not valid UTF-8 in Java binding

We should rather change the type in the Java binding. It is perfectly valid that key names contain non-UTF-8 bytes or sequences also at any other place. It seems like the test suite simply never covered this. At the moment, the unescaped key name does not seem to be exposed in Java anyway, so I wonder which error you got.

What we could consider, however, is if we want to have an UTF-8-valid **escaped** key name. You are probably the best to decide if this makes sense and how difficult the escaping would be to implement. I only noticed that we already have places where something like this is done, e.g. in the TOML plugin. Then the escaped key name could be a `String` in Java/Python and other languages that require unicode encoding in their strings. Only the unescaped names (and BaseName) would need to be a non-string/buffer/. I think this would fit more to the expectations of programmers in such languages. Of course it is a very strategic decision if we want to do something only to please such languages.

> Change the arguable wrong key name iterators. The iterators return byte arrays (or the language equivalent) as elements instead of string. Technically the "correct" solution, but inconvenient in most situations.

If we do the UTF-8-valid escaped key names as proposed above, we could probably have both kind of iterators. If someone requests a UTF-valid-`String`, the iterator could escape the current key part name using our escaping code.

It looks to me we soon need a 3rd round of decisions.

**Comment by kodebach** [comment]
> We can change to unsigned char *. 

Don't like the idea. It probably means changing a lot of code to get rid of compiler warnings. And like you said in C `char *` is just fine for binary data. If anything we should change it to `unit8_t *`.

> We should rather change the type in the Java binding. It is perfectly valid that key names contain non-UTF-8 bytes or sequences also at any other place. It seems like the test suite simply never covered this.

The thing is, in Java you would have to use `byte []` as the type (or better some wrapper so that `equals`/`hashCode` works properly). And like you said, the key name can contain invalid UTF-8 anywhere, so this would have to be done for the escaped name as well. But that makes the API super hard to use in Java. Since Java's `String` type uses UTF-16, you can't really operate  on invalid UTF-8 data and just ignore the invalid bytes. For example, if you just want to compare the key name to a String literal, you either need to validate and convert the key name to UTF-16 or convert the String literal to UTF-8 bytes first.

> At the moment, the unescaped key name does not seem to be exposed in Java anyway, so I wonder which error you got.

It is exposed as key name parts via the `KeyNameIterator` and I only got errors, once I tried to expand the tests to use more than just cascading names.

> What we could consider, however, is if we want to have an UTF-8-valid escaped key name. You are probably the best to decide if this makes sense and how difficult the escaping would be to implement.

A good idea, but I need to look into what the best way would be to do that while preserving the 1:1 mapping.

> If we do the UTF-8-valid escaped key names as proposed above, we could probably have both kind of iterators.

We could but I would do something else (see below).

> It looks to me we soon need a 3rd round of decisions.

Yes, but "soon" probably means next year.

---

I think the best way make a Elektra more usable in other languages would be to do the following:

1. The escaped key name MUST be valid UTF-8.
2. Introduce some mechanism to escape non-UTF-8 (non-zero) byte sequences in the escaped name.
3. Name iterators DO NOT return the namespace as a first item.
4. Name iterators ALWAYS return valid UTF-8 as key name parts, i.e. the escape the non-UTF-8 parts (but do not apply any other escaping like empty name, dot-dot, etc.)
5. Key values of string keys MUST be valid UTF-8. (otherwise we have the same problem again)

Optionally, we could provide an iterator that doesn't do the UTF-8 escaping. But I don't think that is needed. In general the UTF-8 will be used for storage plugins, etc. If you do need the raw key name parts, it's pretty easy to split the unescaped name yourself. This would also be very low-level operation so it makes sense to not provide much support. I don't think there will be many use-cases that are not UTF-8.

**Comment by kodebach** [comment]
Alternatively, we could do this:

1. Every key name part (on its own) MUST be valid UTF-8.
2. Name iterators DO NOT return the namespace as a first item.
3. Key values of string keys MUST be valid UTF-8.
4. We DO NOT validate any of the UTF-8 constraints. If the developers uses non-UTF-8 values things may break silently and unexpectedly.

This would be much simpler to implement, since non-UTF-8 would essentially be undefined behaviour. Like I said, I don't think there are many use cases for non-UTF-8 key name parts. For the few uses cases that exist, the developer will have to find their own escaping mechanism (e.g. just encode all potentially non-UTF-8 key name parts in Base64).

Mandating that "String Key" now means valid UTF-8 not just "doesn't contain zero bytes", is not a problem, since already have binary keys as a solution. Because C doesn't care about UTF-8 and you can read any String Key as a Binary Key anyway, there wouldn't even be a lot of problems, if someone ignores the "String Key = UTF-8" rule.

**Comment by markus2330** [comment]
>  Don't like the idea. It probably means changing a lot of code to get rid of compiler warnings. And like you said in C char * is just fine for binary data. If anything we should change it to unit8_t *.

What about to have one uint8_t for the namespace (maybe directly in struct `_Key`?) and the `char*` for the rest of the name? 

Btw. did you consider or even implement the optimization to not allocate key names for keys that are exactly `/` (which are many as this is used everywhere)?

> It is exposed as key name parts via the KeyNameIterator and I only got errors, once I tried to expand the tests to use more than just cascading names.

I see.

> A good idea, but I need to look into what the best way would be to do that while preserving the 1:1 mapping.

Yes, please. It would more or less combine the benefits of both proposals.

>   Yes, but "soon" probably means next year.

Yes. It is a tough decision, I am not yet sure what I like more. The problem with the "MUST be valid UTF-8" proposal is that I definitely do not like "things may break silently and unexpectedly".

**Comment by kodebach** [comment]
> What about to have one uint8_t for the namespace (maybe directly in struct _Key?) and the char* for the rest of the name?

We could do that yes, but it would be another **huge** and very complicated change.

> Btw. did you consider or even implement the optimization to not allocate key names for keys that are exactly `/` (which are many as this is used everywhere)?

I did consider it but I haven't implemented it. I wanted to produce something that worked first.

> The problem with the "MUST be valid UTF-8" proposal is that I definitely do not like "things may break silently and unexpectedly".

We could of course valid that it is UTF-8. I'm sure we can find a reasonably fast implementation of the logic with an acceptable license somewhere. Of course, if we validate the UTF-8 it is no longer the case that `keySetBaseName` accepts anything. That's why I suggested the "undefined behaviour" solution.

---

We can also extend the guarantees to:

> There is only limited support non-UTF-8 for key name parts. The core C API and the C++ binding fully support such parts. However, using another binding may result in errors or unexpected behaviour. There is also no guarantee that all storage plugins support non-UTF-8 key name parts (in fact most will not). The `dump` and `quickdump` plugins support all key names.

Essentially non-UTF-8 key name parts are like the `®` reserved ones: Theoretically it can work, if you are careful, but practically you should avoid it.

This solution also requires no implementation work (apart from either moving the namespace value or changing name iterators). It would just mean adding a new section to `doc/KEYNAMES.md`.

**Comment by markus2330** [comment]
>  We could do that yes, but it would be another huge and very complicated change.

Yes, I was afraid so. Maybe simply keeping the highest bit reserved for future use is the easiest way. So something like:


```    
    CASCADING = 1
    META = 2
    SPEC = 3

    PROC = 32 // space
    DIR = 50  // 2
    USER = 69  // E
    SYSTEM = 83 // S
    DEFAULT = 100  // d
```

>  I did consider it but I haven't implemented it. I wanted to produce something that worked first.

:+1: 

> This solution also requires no implementation work

If you do not find a solution how to universally escape non-UTF-8 chars, we will have to do something like this anyway. I would prefer that we fix the bindings, though (probably doing some language-specific escaping there). If you are already on it, you could also check how to escape null bytes, then we would have a truly universal key name where base names could be any byte sequence.

I would optimize towards beautiful and short escaped key names, not towards fast (un)escaping.

Would be interesting if we are the first who ever implemented something like this. With a proof that the key names actually fulfill the properties it could be even worth a paper.

**Comment by kodebach** [comment]
> a solution how to universally escape non-UTF-8 chars

The best thing I came up with is using e.g. `\xC0` to encode the byte `C0` (must never occur in UTF-8). But there are only 13 byte values that cannot ever occur in UTF-8 (`C0`, `C1` and `F5`-`FF`). All other bytes in the range `80`-`FF` sometimes valid and sometimes not. This is problem, because to preserve the 1:1 mapping only those escape sequences that are needed must be allowed. That means people need intimate knowledge of UTF-8 encoding to properly understand the escaped key name escape sequences. I don't think that would be a good idea.

> I would optimize towards beautiful and short escaped key names, not towards fast (un)escaping.

Since we want to move to using the escaped name only for user interfaces, speed doesn't matter. However, I would add simplicity as a goal. And that seems to not be possible for the UTF-8 stuff.

> you could also check how to deal with null bytes (if it is possible)

This will never be possible. Zero bytes **cannot** occur in (unescaped) key name parts _ever_. We use `\0` as a separator so. Escaped `\0` bytes in the unescaped name e.g. as `\x00` could work, but would just unnecessarily complicate things.

If it truly is a goal to have any byte sequence as key name parts, We need to store key names differently (i.e. store the length of each part). This would be another huge change on the level of or bigger than #3555 (external API changes would be needed as well).

> we would have a truly universal key name where base names could be any byte sequence.
> Would be interesting if we are the first who ever implemented something like this. With a proof that the key names actually fulfill the properties it could be even worth a paper.

It may be an interesting research question. But AFAICT the goal of Elektra is shifting from a research project to something practically useful (Gnome, KDE). We should think about what is practical and what most users will need. We should **NOT** invest huge amounts of time to implement a feature for a handful of users, just so we can say "Look we can do this super-duper niche thing that nobody else can do".

To cut this debate short: I won't implement any UTF-8 escaping. If somebody else wants to do it, go ahead. But I think non-UTF-8 values are so rare that most people won't even notice they are not fully supported.

---

> Maybe simply keeping the highest bit reserved for future use is the easiest way. So something like: [...]

I'll check how much work it would be to not return the Namespace as the first element of name iterators. If that's too complicated I'll use the new values.

**Comment by markus2330** [comment]
> But AFAICT the goal of Elektra is shifting from a research project to something practically useful (Gnome, KDE).

Yes, I see it the same way :sparkling_heart: 

> I won't implement any UTF-8 escaping.

Probably you are right and the time is invested better somewhere else.

> I'll check how much work it would be to not return the Namespace as the first element of name iterators. If that's too complicated I'll use the new values.

If the problem is only in the Java binding: We have someone working on Java and he can look into a solution that also non-utf sequences have a more user-friendly behavior.
