### ISSUE TITLE
[new-backend] mountpoint-info broken

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3578]
```
Version: 0.9.3
Mountpoint: user:/sw/elektra/dq/#0
File: dq.ini
        config:
sed: -e Ausdruck #1, Zeichen 36: Unbekannte Option für »s«
sed: -e Ausdruck #1, Zeichen 36: Unbekannte Option für »s«
sed: -e Ausdruck #1, Zeichen 36: Unbekannte Option für »s«
         = 23
sed: -e Ausdruck #1, Zeichen 36: Unbekannte Option für »s«
         = 3B
sed: -e Ausdruck #1, Zeichen 36: Unbekannte Option für »s«
         = 3D
sed: -e Ausdruck #1, Zeichen 36: Unbekannte Option für »s«
         = 5C
sed: -e Ausdruck #1, Zeichen 36: Unbekannte Option für »s«
         = dq.ini
getplugins:
        #0#resolver
        #5#mini#mini#
        #9#ccode#ccode#
setplugins:
        #0#resolver
        #1#ccode
        #5#mini
        #6#sync#sync#
        #7#resolver
errorplugins:
        #5#resolver_fm_hpu_b#resolver#
```

**Comment by kodebach** [comment]
I'm not sure, whether this is the issue but this line in `mountpoint-info.sh` is definitely wrong (`:` is missing):

https://github.com/ElektraInitiative/libelektra/blob/7cba2f97152ce272307a14fe95232394b80b181d/scripts/kdb/mountpoint-info#L18

The `sed` error is probably from the second `sed` in this line (no other `sed` command could be 36 characters long):

https://github.com/ElektraInitiative/libelektra/blob/7cba2f97152ce272307a14fe95232394b80b181d/scripts/kdb/mountpoint-info#L75

I think the problem is that `:` is used as the `sed` "separator" and then `sed` is confused by the occurrence of `:` in the key name.
Not sure what the best solution here is... Maybe `awk` makes it easier than `sed`...

**Comment by markus2330** [comment]
In sed you can use (nearly) any character as "separator". Unfortunately, every character can also be in the key name. Maybe we use `^` or something like this this would probably enough for this kind of script (which is not so much used).

**Comment by kodebach** [comment]
> In sed you can use (nearly) any character as "separator".

I know. It's also not easy to escape the chosen separator in a shell script. That's why I suggested `awk` using its `match` or `gsub` function might work better, since you don't need a separator.

**Comment by markus2330** [comment]
I think for this script is it fine to have some small fix. It does not need to work better than before. It is only unfortunate that it is completely broken now.

**Comment by markus2330** [comment]
Probably we should simply remove the script for now as it will get completely broken with #3693

**Comment by kodebach** [comment]
The script definitely needs to be updated for `new-backend`, if we want to keep it at all. Since different backends can have different positions, I think we should just remove the script.

**Comment by markus2330** [comment]
Yes, please remove the script in the new-backend branch. The functionality can be reintroduced later. It better should be on top of @flo91's API.
