### ISSUE TITLE
Scope of implementation work done within FUSE Thesis

### ISSUE THREAD

**Issue by dev2718** [ElektraInitiative/libelektra#3599]
## Added by Markus

- [x] `cd ~/mount/47/proc: && cd ../54` yields "Input/output error" instead of "No such file or directory"
- [ ] no example given in Docker container where proc: is actually used and cascading case is interesting
- [x] maybe use `sleep infinity` instead of `sleep 9999999`
- [X] `rm dir:/dirkey` does not work (still present in FUSE afterwards, after several invocations it works though)
_Reply_: Observe that there is masking going on in the example. Before the first delete, the contents of `dirkey` are "Key from /root/dirkeys/a", afterwards its "Key from /root/dirkeys", after yet another rm `dirkey` is gone.

- [X] `--dir_file_special_name ®elektra/value --xattr_kdb_file ®elektra/file` broken (leads to input/output errors when accessing). I still do not think that it is a good idea to offer such options. I am fine with `@elektra.value` if `@elektra/value` does not work (and let us forget about ® if it leads to problems in practice): let us decide on something and update doc/KEYNAMES.md accordingly.
_Reply_: In `KEYNAMES.md` we already have "Any key name containing the key name part `®elektra`:" (is reserved). I removed the command line option; `®elektra.value` and `®elektra.file` are now used.

- [x] Bug: `cd mount/1; ls; ls` hangs endless
- [x] Implement `proc:` using #3651 (pass env+argc of process to )
- [x] Write semantics for cascading writes or disable cascading writes
- [x] ```cd /home/testuser; kdb set dir:/info "test user, I am here"; cd ~/mount/47``` ls fails, dir: is broken, ~/mount/47/cascading does not contain `...I am here`.

_Reply_: The reason for this is a permission problem: In the example, `/home/testuser/.dir/default.ecf'` is created by the root user with restrictive permissions, so testuser cannot see nor change the value of `dir:/info`. Therefore the fix is to deal with the permission exception, but in this precise scenario testuser will not have access to the key.

- [x] `kdb set user:/info/@elektra.value` creates two files called `@elektra.value`. You could use `®elektra` which is reserved (see KEYNAMES.md).
- [x] get file name of underlying file?
- [ ] put the whole README.md into shell recorder format to automatically check the behavior? (I am not sure if docker in docker works on our build server, though)
- [x] Access related errorcodes not yet implemented (e.g. normal user tries to write to system:/) (defaulting to read only fs - error)
- [ ] Everything that is labelled as `TODO` in the source.

## Define reasonable semantics of write-access to the cascading namespaces:
- Core requirement: “Read after write” reads what was written
- Port that semantic to kdb

## Mounting of ‘system:’, ‘user:’, ‘spec:’ as FUSE file system
- Prototype functional (https://github.com/dev2718/elektra-fuse)
- Feedback appreciated

## Possible mechanisms of mounting the cascading namespace in FUSE
- Option A: the context used to evaluate cascading lookups is static and is either
inherited from the mount-script or set as command line option. The cascading
namespace could then be made accessible under the mount point like ...
mountpoint/cascasing/.
- Option B: like option A, but pseudo-files are used to modify the context at
runtime.
- Option C: using a structure similar to the /proc file system of unix-systems, for
each process, its view of the cascading namespace can be made available.
- Further options: open to suggestions

This is a first draft and therefore any additional suggestions are appreciated.

**Comment by markus2330** [comment]
Thank you for creating the issue! My idea was more that you list what the tool should offer to an admin, without going into details how it will be done. E.g. "enable to investigate the namespaces of a running process". The implementation details are then found after we have a full list of requirements.

Imho Option C is the most elegant one. Did you already investigate the feasibility?

**Comment by dev2718** [comment]
Okay, I will rephrase my issue.

#### Regarding the feasibility of option C:
First, it would need to be established precisely what conditions the cascading-lookup depends on. My findings are that the current working directory and process user id should suffice for all namespaces but 'proc:'.
A simple way, without duplicating any logic, could then be to have a process that mocks the to be inspected process in these regards, and to perform all lookups using this process-context.

The 'proc:' namespace seems more difficult, since Elektra reads from '/proc/self' to construct (at least part) of it. It could be feasible to intercept fopen system calls (e.g. by attaching gdb) and swap 'self' for the proper pid. 
On the other hand, since 'proc'' is read-only, it would be possible to duplicate all logic regarding this namespace, but that would hardly be clean and disconnect the fuse tool from the core.

**Comment by markus2330** [comment]
> First, it would need to be established precisely what conditions the cascading-lookup depends on.

This is very simple question to answer, as every namespace is designed to be dependent on exactly one condition.

- system: the root filesystem of a node. Can be changed by chroot
- user: the user executing the process. Can be changed by setuid and so on
- dir: the working directory of the process. Can be changed by chdir
- proc: the command-line args&environment. Can be changed via setenv

Where did you try to find that information? (At this place we should add the info.)

> It could be feasible to intercept 'open' system calls (e.g. by attaching gdb) and swap 'self' for the proper pid.

We should avoid intercepting syscalls or using gdb in the FUSE implementation. Latter is already done by the bindings in src/bindings/intercept and is a very fragile option. Instead simply change your process so that Elektra does what you want. So e.g simply read the contents from `/proc/<pid>/environ` and set it to the global variable `environ` (before doing kdbGet).

**Comment by markus2330** [comment]
I added some tasks in the top post which I stumbled upon during the review.

**Comment by markus2330** [comment]
@dev2718 Can you tick the tasks you fixed?

For cascading writes I created #3742 to make this issue less confusing.

**Comment by dev2718** [comment]
Thanks for adding the tasks.

I will tick them when they are finished but most of them are still in discussion/implementation

**Comment by markus2330** [comment]
I added

- [ ] `cd ~/mount/47/proc: && cd ../54` yields "Input/output error" instead of "No such file or directory"
- [ ] no example given in Docker container where proc: is actually used and cascading case is interesting
- [ ] maybe use `sleep infinity` instead of `sleep 9999999`
- [ ] `rm dir:/dirkey` does not work (still present in FUSE afterwards, after several invocations it works though)
- [ ] `--dir_file_special_name ®elektra/value --xattr_kdb_file ®elektra/file` broken (leads to input/output errors when accessing). I still do not think that it is a good idea to offer such options. I am fine with `@elektra.value` if `@elektra/value` does not work (and let us forget about ® if it leads to problems in practice): let us decide on something and update doc/KEYNAMES.md accordingly. (It would be a shame to officially say something and in reality do something else.)

@kodebach can you help with the examples for proc:?

**Comment by kodebach** [comment]
> let us forget about ® if it leads to problems in practice

We could also do the following:
- Key name parts starting with `@elektra` are reserved
- The exact key name part `®elektra` is reserved
- If possible, `®elektra` should be preferred (e.g. inside of storage file that use UTF-8 like TOML). However, if an ASCII name is needed `@elektra` can be used. Similarly, using a proper hierarchy should be preferred over a dotted named (i.e. `@elektra/value` over `@elektra.value`).

My reasoning is that (assuming a compatible encoding) `®elektra` should be far less likely to cause collisions with existing syntax. On the other hand it is quite feasible that some storage format or application attributes some special meaning to names starting with `@`.

> can you help with the examples for proc:?

I'm not sure what exactly you want to see. If you just want an example where a program that uses `gopts` is running so you can inspect the keys it uses via FUSE, then the easiest way would be to modify `examples/gopts.c`. Just add a `getchar()` (or similar) before the `kdbClose()` so it waits for user input. Start the program via e.g. `bin/gopts -rv abc &` and then you should be able to see it's KDB via FUSE.

I don't really have time right now to create a full working example, but if I understood the idea correctly, this hint should help a bit.

**Comment by markus2330** [comment]
> We could also do the following [reserve both]

If `@elektra` gets reserved (or even everything starting with `@elektra`), there is no need for `®elektra`, as its only advantage is that it is even less likely to collide as `@elektra`.

At the moment we only have a single use case of `@elektra`, which is the FUSE tool. So we will reserve exactly the minimum needed for the FUSE tool. If it really needs "everything starting with `@elektra`", then let us reserve that. Then probably the requirement to only reserve `@elektra` was too strict. Good that we found out now.

> If you just want an example where a program that uses gopts is running so you can inspect the keys it uses via FUSE

Exactly.

> then the easiest way would be to modify 

Isn't the python program even easier (at least for @dev2718)?

> this hint should help a bit

@kodebach The hint does not state all the requirements: the FUSE tool will only work if the specification is also available in `spec:`?

**Comment by kodebach** [comment]
> So we will reserve exactly the minimum needed for the FUSE tool.

That is not the point for reserved names. You are confusing "reserved key name" and "key name with special meaning". The latter is a subset of the former.

The whole idea of reserving key names is that we do not break existing stuff, if we need to create new "key names with special meaning" in the future. If don't do that any time a new "key name with special meaning" is added (e.g. `@elektra/meta`), it would be breaking change.

We _reserve_ (as in "we reserve the right to use") all key names that contain a key name part equal to `@elektra`. But for now only those key names where the second last part is `@elektra` and the last part is `value` (i.e. `.../@elektra/value`) do actually have a special meaning.

> there is no need for `®elektra`, as its only advantage is that it is even less likely to collide

It is a bit redundant, yes.

---

> Isn't the python program even easier

Yes, the Python version should work as well. It doesn't really matter how you achieve it. The only thing you need is a process that calls `kdbOpen()` with a gotps contract and then keeps running until it receives some termination signal (user input or otherwise).

> The hint does not state all the requirements: the FUSE tool will only work if the specification is also available in `spec:`?

I'm not sure, what exactly you mean, but `gopts` also only works, if the specification is actually read from the `spec:/` namespace in `kdbGet()`. That's why all the examples write their spec via `kdbSet()` before the actual example, and remove it again afterwards.

**Comment by markus2330** [comment]
> You are confusing

Please avoid personal accusations. E.g. with a statement "If don't do that any time" a response can be: "a noun is missing in the sentence", and definitely not "You are confusing nouns with verbs".

My previous answer holds: we reserve for now what has a special meaning in FUSE. Of course we can reserve more (e.g. `@elektra.*` instead of `@elektra.value`). I have trust in @dev2718 that he will find a good balance. If you find some use case that is not covered by this reservation or think we reserved too much, we can discuss this later, i.e. after the PR from @dev2718. We cannot expect everyone to participate in endless discussions.

> I'm not sure, what exactly you mean, but gopts also only works, if the specification is actually read from the spec:/ namespace in kdbGet(). That's why all the examples write their spec via kdbSet() before the actual example, and remove it again afterwards.

I mean that the FUSE tool might not find the spec: of these tools if they immediately remove it. So the pausing needs to be done at the correct place. Maybe obvious, but imho worth mentioning as there are many kdbClose in the file (and not only in line 239).
