### ISSUE TITLE
keyCompare

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3604]
@kodebach wrote:
> I wrote:
> > keyCompare is internal, so no worries.
>
> `keyCompare` is not internal. It is exported via `kdbease.h`.
> https://github.com/ElektraInitiative/libelektra/blob/f4392e92dcb9cb77a6e13573f4b275e443fe50a3/src%2Finclude%2Fkdbease.h#L27
> 
> And is also declared as a public API symbol:
> https://github.com/ElektraInitiative/libelektra/blob/d27fb630a4da8718e76cb6bd3a47693bdbe84ac3/src%2Flibs%2Felektra%2Fsymbols.map#L30

Thanks for the hint. Seems like things are messed up around keyCompare:

- in Doxygen it is marked as internal
- the header file implies it should be in libease
- it seems to be in the core

**Comment by kodebach** [comment]
Not directly related to this issue, but there are also `keyCmp` (not internal), `keyCompareByNameOwner` (internal), `keyCompareByName` (internal) and `keyCompareByOwner` (internal).

First, we should probably remove the "owner" stuff, since the concept of a key owner doesn't exist anymore.

Second, the fact that both `keyCmp` and `keyCompare` exist as public functions with wildly different purposes could lead to confusion.

**Comment by markus2330** [comment]
> First, we should probably remove the "owner" stuff, since the concept of a key owner doesn't exist anymore.

I fully agree. Which points are to be done to get rid of the "owner" stuff?

> Second, the fact that both keyCmp and keyCompare exist as public functions with wildly different purposes could lead to confusion.

Yes, this is definitely something we need to fix within the API reviews.

**Comment by kodebach** [comment]
> Which points are to be done to get rid of the "owner" stuff?

`keyCompareByOwner` has to be removed, `keyCompareByNameOwner` has to be removed and calls have to be replaced with `keyCompareByName`.
