### ISSUE TITLE
remove search of "dir:" namespace

### ISSUE THREAD

**Issue by dev2718** [ElektraInitiative/libelektra#3614]
## Steps to Reproduce the Problem

```sh
mkdir /testdir
mkdir /testdir/subdir

cd /testdir
kdb set dir/value "In testdir"

cd /testdir/subdir
kdb set dir/value "In subdir"

cd /testdir
kdb get dir/value

```

## Expected Result

"In testdir"

## Actual Result

"In subdir"

## System Information

- Elektra Version: Release 70 (https://build.libelektra.org/job/libelektra-release/70/artifact/artifacts/ubuntu-focal/ubuntu-focal-release.tar.gz)
- Docker container (ubuntu:focal)

**Comment by markus2330** [comment]
Thank you for reporting the problem! It is indeed a tricky one.

The problem is that, even when we are in /testdir/subdir the config folder of /testdir is still used for writing.

For reading this behavior might be okay but for writing we need to always write to the current directory, even if we read from another one. This, however, contradicts to the static context Elektra had up to now.

So we can:

- live with the current behavior and explain it in the docu
- remove the feature to search for upper directories, and always read&write to the current directory
- have different reading and writing config files (static: determined once like now)
- dynamically always re-search which config file to use, for writing use the current working dir

Dropping the feature is probably the best idea, as we also have another bug in this code: #1455

**Comment by markus2330** [comment]
The goal of this issue to get rid of loop in elektraResolveDir, in src/plugins/resolver/filename.c
Instead simply always use the current working directory.
