### ISSUE TITLE
keynames link broken

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3646]
As reported by Ferdinand Thommes, the link to KEYNAMES.md in the release notes as rendered by the website is broken. I think this is because this is not a page automatically indexed nor manually added in the website structure. (Subfolders of doc are added, but not files in the doc folder itself.)

Fix: move the file to `doc/dev`, as initially suggested by me but unfortunately this breaks the link on GitHub release pages, where it works now... I hope we can avoid such special cases in the future.

@kodebach do you have time to fix it?

**Comment by markus2330** [comment]
Ideally we should teach our link checker that such files actually do not work...

Btw. I wrote to Ferdinand Thommes to use https://github.com/ElektraInitiative/libelektra/blob/0.9.4/doc/KEYNAMES.md so at least in this case we can move the file safely. Probably we should use version specific links in the future...

**Comment by kodebach** [comment]
Ideally we would fix the website so that it supports the same links that Github does.

To me it is very clear that this is a bug with the website. The link to `keynames.py` works fine and both links have a very similar structure: `[key name documentation](../KEYNAMES.md)` vs `[Python reference implementation](../../scripts/keynames.py)`
If `../../` works, but `..` doesn't, clearly something is broken.

BTW in the Github release neither of the links works: https://github.com/ElektraInitiative/libelektra/releases/tag/0.9.4. That however is easy to fix, since it is entirely separate from everything else.

@markus2330 are the actual Github release notes inserted manually or is there some automated process that needs to be fixed as well?

**Comment by markus2330** [comment]
I agree that it could be interpreted as a bug in the website but I do not think we should invest time in fixing this as it helps us avoiding a big mess directly below `doc`. The few pages we really need below `doc`, can be added manually to the structure (src/tools/website/resources/structure.json.in).

I am open to make an exception here now, as the KEYNAMES.md document is arguable very important and https://linuxnews.de/2021/02/elektra-0-94-erscheinen/ (after all) links to KEYNAMES.md in master :wink: 

> are the actual Github release notes inserted manually

I think @mpranj did this manually, which would also favor adding KEYNAMES.md to the structure (and not moving it). At least until the dust about the release settles, and then we can think again about how we want `doc` structured.

**Comment by kodebach** [comment]
> which would also favor adding KEYNAMES.md to the structure (and not moving it). At least until the dust about the release settles

If this the Github release notes were inserted manually, it doesn't matter one way or the other, since you have to edit all relative links to fix this anyway.

The most permanent solution would probably be to use **only** absolute links using the domain `libelektra.org` (Files that aren't part of the website have to be linked via `git.libelektra.org`) in the release notes. Then they should work everywhere and as long as we have control of `libelektra.org`.

**Comment by kodebach** [comment]
@markus2330 should be fixed in #3647
