### ISSUE TITLE
ni: metadata: namespace

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3697]
Is it on purpose that ni files now contain `meta:` in front of every metakey?

E.g.

```sh
kdb meta-set /sw/app/current/#0/server/port type short
cat `kdb file spec:/sw/app/current/#0`
```

now yields:

```ini
server/port = 

[server/port]
 meta:/type = short
```

In earlier versions of Elektra it was simply `type = short`.

Btw. in the slides I use `:=` to make more clear that it is metadata, maybe we should also adapt the ni plugin to do so?

**Comment by kodebach** [comment]
The `ni` uses a 3rd party ini library. I'm not sure how easy it would be to change the key value separator from `=` to `:=`.

Regarding the `meta:/` prefix. We could easily strip it since it everything already works fine, if you write the file manually without the prefix. In future this may require adding the prefix back when reading files. For 1.0 the `keyGetMeta` function should only accept valid meta key names including the namespace to avoid some edge cases in the current implementation.

For `ni` we should also define, one way of doing it. Either with or without the namespace.

**Comment by kodebach** [comment]
@markus I think this could be a good FLOSS issue. Stripping the `meta:/` prefix when writing and adding it when reading should be pretty simple.
