### ISSUE TITLE
Simplify memory management of functions that copy into a buffer

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3731]
Currently the way functions like `keyGetName()` work is by passing a buffer with a maxSize and if the buffer is large enough, the value gets copied into the buffer. This leads to the user having to write a lot of surrounding boilerplate code, checking for the size of every value / name they want to copy into a buffer.

A possibility of alleviating this problem has been discussed in an API review. Instead of passing the buffer and the maxSize directly, the user passes a `** char|void returnPointer`. The function then allocates the exact amount of needed memory and writes the pointer into `returnPointer`. The function then returns the size of the stored value. This would cause the user to not have to worry about the amount of memory he needs to allocate for every call to a function that stores values in a buffer.

Downsides to this approach would include a loss of flexibility. If the user wants to only allocate a certain amount of memory, the function would not allow for this flexibility. One possibility would be reintroducing a `maxSize` parameter, but this cuts into the upsides of changing the function in the first place. If the user doesn't care about the `maxSize` he would still have to pass it as an argument, or we would have to do some macro magic, to make it work.

Changing the API of a lot of functions in such a fundamental way, could pose a big problem. One idea would be to add those functions additionally as convenience functions, that could just alias the existing functions. A downside of this would be cluttering of the public API, where users are confused by the big amount of functions available to them.

Candidate functions for this change would include:
- `keyGetName()`
- `keyGetUnescapedName()`
- `keyGetBaseName()`
- `keyGetString()`
- `keyGetBinary()`

**Comment by markus2330** [comment]
The first question is: do we really need these functions? Isn't it easily possible to avoid all of them via strndup? E.g. something like strndup (keyValue(), keyGetBinarySize());

**Comment by lawli3t** [comment]
Yes, although this probably would pose some discoverability issues. 

`keyGetUnescapedName` and `keyGetBaseName` are probably also not trivially replacable, because they extract the respective parts from the name.

**Comment by kodebach** [comment]
> The first question is: do we really need these functions?

IMO we don't. I know about all these functions and I think have never used any of them. A simple `strndup (keyValue(), keyGetBinarySize());` only works for string values (so not for binary key values and unescaped names), but there is `elektraStrNDup` (which should be called `elektraMemDup`, see #3110). That would work for binary values too.

If we keep the functions, I think they should work more like `strcpy` or `memcpy` (and many others) and just always copy as many bytes as the user requested and return the number of bytes copied. But then again, the user could just call the `memcpy` themselves.

> keyGetUnescapedName and keyGetBaseName are probably also not trivially replacable, because they extract the respective parts from the name.

I don't see how these are any different from the other functions. They both have `keyUnescapedName` and `keyBaseName` counter parts that returns pointer from which the user could copy the data.

**Comment by lawli3t** [comment]
> I don't see how these are any different from the other functions. They both have `keyUnescapedName` and `keyBaseName` counter parts that returns pointer from which the user could copy the data.

I see, I was working off the top of my head here, and apparently I misremembered. I should have just looked, sorry :smile:

**Comment by lawli3t** [comment]
So it seems to be the best bet going forward will be removing those functions. On the way to this goal, should we remove / deprecate the functions altogether or make the transition period longer and temporarily rewrite them using `strndup` / `memcpy`?

**Comment by markus2330** [comment]
There is no deprecation or transition period needed. The purpose of 0.9 series is the preparation of 1.0 and we didn't make any promises of compatibility for 1.0. So better we break hard and pointed and remove everything which can be removed.

> strndup / memcpy

We have elektraStrNDup and elektraMemcpy in our helpers API. Their purpose is to allow people to change to other memory allocators. There was already discussion if we should remove these APIs. I think it is not worth the effort and they have some (small) benefits, like adding assertions.

@kodebach I wonder a bit why the helpers API is not private. E.g. elektraLog is also private and all plugins actually use this symbol.

**Comment by kodebach** [comment]
> Their purpose is to allow people to change to other memory allocators.

I would not call that their main purpose. There are better ways to change the allocator (e.g. `LD_PRELOAD`).  IMO the only benefit are the assertions and even there the benefit is not that clear. The log message from `elektraAbort` is nice, but I'm not sure that's worth using non-standard functions. Most of the time you have to attach a debugger anyway to find out where the `NULL` came from. With a debugger, the log message is mostly useless.

The main disadvantage of using these functions is that compilers have lots and lots of optimizations for `strdup` et al. The compiler may spot that `elektraStrDup` basically is `strdup` in release mode. (Last I checked, it actually does detect that the weird implementation of `elektraStrLen` is actually just `strlen` and replaces the `strchr` stuff with a `strlen` call) But I don't think the compiler will apply any optimizations to call-sites of e.g. `elektraStrDup` (at least not those that are in a different library), because at that point it can't guarantee that `elektraStrDup` will always behave like `strdup`.

If I had to decide, I would say we remove `elektraMalloc`, `elektraCalloc`, `elektraFree`, `elektraStrDup` and `elektraStrLen`. The functions `elektraRealloc` and `elektraMemDup` (renamed from `elektraStrNDup`) can stay, because they are an improvement upon the libc.

Anyway to answer your question:
- `elektraLog` is used by plugins, yes, but it is not something an application or even a plugin outside our repo should necessarily use. In fact it can't (easily) be used outside the repo, because `kdblogger.h` is not shipped/installed with Elektra. That's why it is declared in the `libelektraprivate_1.0` part of the symbol versioning files. 
- `elektraFree` has to be public, because there are some public functions that return pointers allocated with `elektraMalloc`/`elektraCalloc`. It therefore shouldn't be in `libelektraprivate_1.0`, because those symbols are not supposed to be used externally. For consistency's sake, `elektraMalloc`/`elektraCalloc` are also public.
- The other functions could technically be in `libelektraprivate_1.0`.

**Comment by markus2330** [comment]
I agree that they provide little benefit. But removing them also provides little benefit and a lot of effort. Making them private is imho the best option. It seems like there is no way around a decision here, as we already discussed this many times.

> There are better ways to change the allocator

I don't know of any if you want to change the allocator **only** for Elektra. There are many libraries providing similar mechanisms, e.g. [libltdl](https://www.gnu.org/software/libtool/manual/html_node/Using-libltdl.html) or glyphy (IIRC, project seems to be gone now) or even implement their own allocator, e.g. [harfbuzz}(https://github.com/harfbuzz/harfbuzz/blob/c39ab82c90479341dcf28eaa8174af6f08c0d7ae/src/hb-pool.hh)

> elektraFree has to be public, because there are some public functions that return pointers allocated with elektraMalloc/elektraCalloc. 

These are probably bugs, as our API design says that for every (public) function allocating something there needs to be a function freeing it. If you mean, e.g., elektraFormat: of course it needs to be as private as elektraMalloc/elektraFree.

**Comment by mpranj** [comment]
> The function then allocates the exact amount of needed memory [...] user to not have to worry about the amount of memory [...]

> The first question is: do we really need these functions?

I would be a fan of `keyGetName()` just allocating everything and returning a `char *` (similarly for the other functions). To me this would be much simpler than the current API.

The current API is more flexible (e.g. you could re-use a buffer instead of multiple allocs), but even that argument is weak as the buffer might be too small. Either way we currently need much boilerplate code and have little benefit compared to the simplified function.

**Comment by markus2330** [comment]
I think this is a very good idea for bindings and higher-level APIs. Exclusively providing such an API, however, would lead to double allocations in all bindings that have a string-type on its own (like C++).

**Comment by kodebach** [comment]
> I would be a fan of `keyGetName()` just allocating everything and returning a `char *` (similarly for the other functions). To me this would be much simpler than the current API.

That would be easier, yes but it would just be the same as `strdup (keyName (k))`. I don't see the point of having a separate function for that.

---

I moved the discussion about `elektraMalloc` to #3750

**Comment by markus2330** [comment]
Are these functions already removed or will you create a new issue? Otherwise we probably should not close the issue.

**Comment by lawli3t** [comment]
i have created a new issue here https://github.com/ElektraInitiative/libelektra/issues/3975
