### ISSUE TITLE
Current status of function ksRenameKeys

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3733]
`ksRenameKeys()` currently pops up in the [KDB Section](https://doc.libelektra.org/api/latest/html/group__kdb.html#ga1ba80a565f54490f362df95f401bcb29) of the documentation, but isnt a part of `kdb.h.in`. Is this function even still available via the elektra library? Several functions still seem to use it, might it be only available internally? We should either remove it from the documentation or move it to the correct section and add it to kdb.h.in.

**Comment by markus2330** [comment]
Thank you for reporting this problem! Yes, it should not be in the docu as it is only a private function (src/include/kdbprivate.h).

**Comment by kodebach** [comment]
It is listed in the relevant `symbols.map` so it is technically available to external callers, but it is marked as a private symbol so not currently public API.

https://github.com/ElektraInitiative/libelektra/blob/5702ce0496823fdd12c4e1e6ff9d6d1ca1b71a40/src/libs/elektra/symbols.map#L161

The function probably appears in the KDB section, because it is implemented in `kdb.c` and part of `libelektra-kdb`. I suspect it was originally a static function and then someone needed it in other file...

PS. Ideally all calls to `ksRenameKeys` would be replaced with calls to the new `ksRename`. This new function is better optimized and has a more general API.

**Comment by lawli3t** [comment]
Should I open a PR for this?

**Comment by markus2330** [comment]
For our own sanity there should be as little categories in the API as possible, e.g.:

1. public API (within kdb.h.in, within API docu and in public field of symbols.map)
2. private API (not in kdb.h.in but in kdbprivate etc., not in API docu (only in internal, which we disable by default) and in private field of symbols.map)
3. really internal, i.e., static functions (not in any header, not in API docu, not in symbols.map.)

Both 2+3 simply structure our code and are not supposed to be used by anyone outside of our repo.

I think we should avoid other categories, except of maybe the aliases if they have really promising advantages (as we already discussed).

In general, functions should be as hidden as possible. So if we can make a function really internal (a static function), it would be best. If there are users (and there seem to be for ksRenameKeys) moving to a private header is the second-best option.

Yes, please make a PR making it private in the same way as the other private APIs (removing it from the docu).

**Comment by markus2330** [comment]
Please also write about these "API categories" in our guidelines doc/DESIGN.md (if you think we already have more, write about it).

**Comment by lawli3t** [comment]
I will add them to the design, I might need to consult you for the content though. I'm not sure im a 100% aware of the use cases of the functions contained in the different categories. I'll draft it up for you to review.

I hope I can finish up my PRs for the documentation issues this week, so I can focus on this (and other issues).
