### ISSUE TITLE
Error handling and return codes for errors are inconsistent across the public API

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#3737]
Currently, a lot of functions return the error value, regardless of error. These poses some problems, for instance authors of bindings, where it is hard to tell which error exactly occured. A big improvement to this would be returning different error codes for different types of errors, in order to be able to provide better information in cases of errors. Some functions also make use of an `errorKey`. While this seems like a decent approach, to provide additional informations in cases of error, it is currently very badly documented. It is not really transparent for the users of the function, what kind of information is included in the `errorKey` and even which messages could possibly be returned.

The first step would be to find an approach that is unified across all functions for error handling. This could mean changing the return types of every function to be more specific, or to include error keys into more functions. The second approach seems very impractical and would break basically the whole API. Changing return types would be a lot easier and more practicable. One can generally check for errors by `returnValue < 0`, and check for specific error cases via comparison.

Changing the return values of functions would also pose a good possibility of unifying return values for similar errors. So null pointers always return the same error code, read-only errors always return the same error code, etc. These error classes could also be implemented via an enum, which could in turn be documented. This would add a section to the documentation where all errors are documented in one single place.

Examples of function having "kitchen-sink" error codes:
 - [keyAddBaseName](https://doc.libelektra.org/api/master/html/group__keyname.html#gaa942091fc4bd5c2699e49ddc50829524)
 - [keyGetBinary](https://doc.libelektra.org/api/master/html/group__keyvalue.html#ga4c0d8a4a11174197699c231e0b5c3c84)

**Comment by markus2330** [comment]
Thank you for reporting this problem! I agree this can be annoying. Maybe it is only a documentation problem because usually all error codes but one are actually wrong API. So if you can exclude the possibility of wrong API use (properly check preconditions), the errors are actually not so ambiguous as you might think. Afaik #3029 is the only case where two different non-API error conditions exist. The other cases could be improved by docu: telling the user what are the real errors and which cases actually should have been checked before calling the API, e.g. giving examples of how to check preconditions.

But nevertheless I agree, that also for "wrong API use" some guidance is useful, as "always the same error code" can be frustrating in development. So I am open to suggestions. A return value does not always work as some functions return pointers. Did you find a situation where we need to report an error and the return value is a pointer?

**Comment by markus2330** [comment]
Btw. probably we can leave this issue to be post-1.0 because a thread-local variable for error handling can also be introduced in 1.X.

**Comment by kodebach** [comment]
Yes, the `errorKey` (sometimes also `parentKey`) way of returning errors is not really documented in the code. It is, however, already a  well thought-out and well documented system. The documentation can be found [here](https://github.com/ElektraInitiative/libelektra/blob/master/doc/dev/error-categorization.md), [here](https://github.com/ElektraInitiative/libelektra/blob/master/doc/dev/error-message.md) and [here](https://github.com/ElektraInitiative/libelektra/blob/master/doc/dev/error-handling.md).

Basically AFAIK the `error` metadata approach is used in the KDB part of the API, while simpler return values are used in the lower level `Key` and `KeySet` parts. There it wouldn't make sense to use a key for reporting errors (sometimes it wouldn't even be possible, e.g. `keyNew`).

I see your point that in Bindings that could throw different exceptions or use a Rust-like `Result` approach it would be nice to have detailed error codes. But it using the same error codes everywhere would be quite annoying for development. We basically would need a giant enum with all possible errors, many of which would only be used in a single function. And then that enum would somehow have to be compatible with many different return type. I don't see how that would work. The only solution would be creating our own `errno` and I'm really not a fan of that.

AFAICT we use `error` metadata, if there could be an error that should be reported to the user (i.e. the human in front of the PC). But if the error code is only relevant to the developer writing the code (e.g. "wrong API use", i.e. NULL pointer passed, key is locked etc.) then we use basic return values.

Like Markus said, for the most part with basic return values it is almost always 1 value for "wrong API use" and then a few others for more specialized error cases. Of course it is hard to decided what is "wrong API use" and what isn't (e.g. is an invalid key name for `keySetName` "wrong API use" or should it get a different error code than "NULL pointer passed"). The way I decide this is normally: Can this error generally be avoided by writing the code in a certain way? e.g. NULL pointers can normally be avoided, same goes for passing locked keys. If so, then I classify the error as "wrong API use". If the error could only be avoided by doing some check every time before the function is called than it gets a special error code. I can't think of a concrete example right now, but a hypothetical example would be, if a function requires to keys `A` and `B` and `A` has to be below `B`. That condition would be a bit to advanced for me to say "this can be ensured by writing the code properly".

**Comment by markus2330** [comment]
> There are several cases, for instance kdbOpen. Here the error gets outputted to the errorKey parameter. Those are usually poorly documented. I have not been able to find any descriptions on how the error gets stored there (I have only looked at the API-documentation). Also the functions usually do not indicate the different errors that could be inserted into the errorKey.

Yes, you are right, the errors of the `kdb*` functions are not properly documented from within the API docu, this is a must-have for 1.0. The links @kodebach mentioned are actually included in the API docu but nearly impossible to find:
https://doc.libelektra.org/api/master/html/md_doc_decisions_error_codes.html
https://doc.libelektra.org/api/master/html/md_doc_decisions_error_message_format.html
https://doc.libelektra.org/api/master/html/md_doc_decisions_error_semantics.html

Another problem of the API docu is that many documents are simply called README:
https://doc.libelektra.org/api/master/html/pages.html

**Comment by kodebach** [comment]
> Another problem of the API docu is that many documents are simply called README:

Is there maybe a way to tell doxygen to use a different name for these files (e.g. the name of the folder they are in)?

But probably we should exclude all the `.md` files from doxygen. IMO doxygen should only contain the API docs, i.e. what is written in comments in code files. All other docs should just be part of the homepage.

**Comment by tucek** [comment]
> Like Markus said, for the most part with basic return values it is almost always 1 value for "wrong API use" and then a few others for more specialized error cases. Of course it is hard to decided what is "wrong API use" and what isn't (e.g. is an invalid key name for `keySetName` "wrong API use" or should it get a different error code than "NULL pointer passed"). The way I decide this is normally: Can this error generally be avoided by writing the code in a certain way? e.g. NULL pointers can normally be avoided, same goes for passing locked keys. If so, then I classify the error as "wrong API use". If the error could only be avoided by doing some check every time before the function is called than it gets a special error code. I can't think of a concrete example right now, but a hypothetical example would be, if a function requires to keys `A` and `B` and `A` has to be below `B`. That condition would be a bit to advanced for me to say "this can be ensured by writing the code properly".

From my point of view, it is imperative for the developer experience to enable the caller to differentiate between the different possible causes for "wrong API use". Whether null or an invalid key name is being passed, mostly is a result of completely different mistakes (by the caller) upstream.
I would also refrain from general error code enums, but what about a kind of namespacing for error codes? (i.e.: -1[0-9] .. wrong API usage, -2[0-9] ... other errors , ...)

**Comment by kodebach** [comment]
> I would also refrain from general error code enums, but what about a kind of namespacing for error codes? (i.e.: -1[0-9] .. wrong API usage, -2[0-9] ... other errors , ...)

Again you also have to consider that many parts of the API very constrained in what values they can use for error codes. If a function returns a pointer the only possible error value by definition is `NULL`.

I would also like to see a good example, of where these distinct error codes would provide a clear benefit. There are examples above, but they don't really do it for me. 

With `keyAddBaseName` we have
https://github.com/ElektraInitiative/libelektra/blob/5702ce0496823fdd12c4e1e6ff9d6d1ca1b71a40/src/libs/elektra/keyname.c#L1537-L1540

1. `if the key had no name` this is just outdated docs, this is no longer possible unless someone circumvented the API
2. `on NULL pointers` okay that's always there, but checking for `NULL`s is easy and doesn't really warrant a separate error code
3. `if key was inserted to a keyset before` this is something you might have to consider, if you call `keyAddBaseName` with a `Key *` you received from another caller. But you can just pass on the precondition that the key cannot be in a keyset to your caller. If you want to manipulate the key name the key cannot be in a KeySet. This is just a general requirement and if you don't have control over the key you cannot do anything about this anyway. In this case it wouldn't even make sense to call `keyDup` because then you would manipulate the name of a different `Key`.
4. `on allocation errors` I'm not sure this is even checked. In any case it is almost impossible to recover from allocation errors and even more impossible to ensure nothing is corrupted to crashing the process is probably the best solution anyway.

So other than the broken docs, I don't really see a problem here.

Then there is `keyGetBinary`.
https://github.com/ElektraInitiative/libelektra/blob/5702ce0496823fdd12c4e1e6ff9d6d1ca1b71a40/src/libs/elektra/keyvalue.c#L397-L401

I admit in this case the error codes are quite bad. But the `keyGetBinary` API is quite bad in general. For one, why is there an upper limit for `maxSize`? It just has to be bigger than `key->dataSize`, beyond that we don't care. The other requirements for `maxSize` could also be removed by using `min (key->dataSize, maxSize)` instead of `key->dataSize` (both for the `memcpy` and the return value). Which only leaves the "is string not binary" error (ignoring the `NULL` pointers). That one is matter of opinion, but we are just calling `memcpy` here. So there really is no technical reason not to allow string values too.

I checked most of the `key*` and `ks*` functions and the only somewhat plausible example I found was `keyGetString` (same arguments as with `keyGetBinary`, but in this case we actually need the string vs. binary type check). But like `keyGetBinary`, the whole function might be removed (#3731). Most functions either have only one or two very basic error cases other than `NULL` pointers (e.g. locked key) or return `ssize_t` or a pointer and therefore cannot use multiple error values.

**Comment by markus2330** [comment]
> But probably we should exclude all the .md files from doxygen. IMO doxygen should only contain the API docs, i.e. what is written in comments in code files. All other docs should just be part of the homepage.

As written in the main README.md, our current approach is that the same documentation is rendered in different formats:

- [on the Website](https://www.libelektra.org)
- [in the API docu](https://doc.libelektra.org/api/master/html/doc_help_kdb_md.html)
- by using `man kdb`
- by using `kdb --help` or `kdb help <command>`
- [on GitHub](https://master.libelektra.org/doc/help/kdb.md)

Having different subsets at different places might make everything more confusing. There are several documents that are very strongly linked to the API docu, like the error docu, so imho it makes sense to make them available within Doxygen (and link it properly).

@kodebach thank you for the analysis, I hope it will help @lawli3t to find a good solution. Once all the docu problems are fixed, it should be more clear how to move forward.

**Comment by kodebach** [comment]
> our current approach is that the same documentation is rendered in different formats: [...]

The manpages and the docs provided by `kdb --help`/`kdb help` do not contain all the information that e.g. the website contains. The website also doesn't contain any of the docs generated by doxygen AFAIK (it only links to the API docs site).

GitHub of course contains all the information, but that's just because you can view the whole repo, which is the only source of information.

So actually, only the API docs contain everything. IMO this may be a nice idea in principle, but the way doxygen renders some of the files is not ideal. I think we should use the appropriate tools for the job. That is, use doxyen only for API docs, use man pages to document the `kdb` tool and use the Website with our custom setup for other documentation (including the man pages here is also an option). GitHub will of course always contain everything.

Having docs in multiple places will only lead to problems with rendering or links, etc.

**Comment by kodebach** [comment]
PS. of course all docs should link to each other when appropriate

**Comment by markus2330** [comment]
>  The manpages and the docs provided by kdb --help/kdb help do not contain all the information that e.g. the website contains. The website also doesn't contain any of the docs generated by doxygen AFAIK (it only links to the API docs site).

Is there something relevant you miss? Doxygen also creates man pages, so also from the API there can be man pages.

> So actually, only the API docs contain everything. IMO this may be a nice idea in principle, but the way doxygen renders some of the files is not ideal.

They constantly improve their Markdown renderer. (At least they fixed the problems I was involved with.) And we have several Markdown rendererers anyway (qt-gui also uses another one), so we are limited to "common" Markdown anyway.

> I think we should use the appropriate tools for the job. That is, use doxyen only for API docs, use man pages to document the kdb tool and use the Website with our custom setup for other documentation (including the man pages here is also an option). GitHub will of course always contain everything.

I agree that everything as man pages is too much. But why would you want to limit what the website&API docu (besides rendering issues) contains?

**Comment by kodebach** [comment]
> But why would you want to limit what the website&API docu (besides rendering issues) contains?

Because Elektra's docs are complicated enough to navigate already. It doesn't really help if we duplicate everything. IMO there should be exactly one place (apart from the git repo), where each piece of documentation lives. Think of it as a "single source of truth" kind of thing.

Having the docs in multiple places, just seems like super unnecessary maintenance effort.

**Comment by markus2330** [comment]
> It doesn't really help if we duplicate everything.

Afaik relative links will only resolve if these pages are included. Only the website has some fallback logic to link to GitHub, which is also not ideal: better is if you can stay in the website.

> Think of it as a "single source of truth" kind of thing. Having the docs in multiple places, just seems like super unnecessary maintenance effort.

As all of them are generated, we have a single source of truth and only marginal additional maintenance effort (only if one of the  renderers makes weird things we have additional work).

**Comment by kodebach** [comment]
> Afaik relative links will only resolve if these pages are included. Only the website has some fallback logic to link to GitHub, which is also not ideal: better is if you can stay in the website.

Yes, the website should ideally be self-contained in terms of markdown. Relative links to code files linking to GitHub is fine IMO.

The API docs (if they really need such a link) should just link to the website (libelektra.org) IMO. Then the link is always unambiguous, even if you just opened the file in an editor. It also saves us the trouble of checking for relative links in the docs before moving code from one file to another.

**Comment by lawli3t** [comment]
Even though I agree with the sentiment that there should be one place only for each piece of documentation, I think adding the error codes to the Doxygen documentation would prove very beneficial. They are part of the API in my opinion. Another possibility would be linking to the respective parts in the documentation, which would also be fine in my opinion, although I would prefer them being contained in the Doxygen documentation as well.

I agree with @markus2330 that with the current setup it shouldn't be hard to realize, although such judgements are kinda hard for me to make with the little experience I have with the project.

**Comment by markus2330** [comment]
> I think adding the error codes to the Doxygen documentation would prove very beneficial.

Yes, I think it is a must-have.

> Another possibility would be linking to the respective parts in the documentation

The more detailed information can be provided by a link (inside or outside of Doxygen) but I think the basics about the errorKey must be directly in the API docu.

**Comment by lawli3t** [comment]
resolved by implementing #3972
