### ISSUE TITLE
Meta functionality in ini could be solved via keytometa

### ISSUE THREAD

**Issue by fberlakovich** [ElektraInitiative/libelektra#377]
@markus2330 @tom-wa 

If anyone is interested in implementing this: I think the meta functionality of ini could also be achieved with keytometa and glob by making these simple extensions:

* extending glob to allow matching metakeys (we could match on ```ini/section``` according to the new pull request)
* extending keytometa to allow dynamic target meta names (for example based on the keyname of the converted key). Currently the target meta name is configured via a simple MetaKey.

This seems like a more natural separation of responsibilites to me. In addition, other plugins might beneift from these extensions as well. Both improvements shouldn't be to much work and we could simplify the ini plugin again. 

What is your oppinion on this?

**Comment by markus2330** [comment]
I like the idea that every storage plugin could be transformed to a meta-storage. I think, however, we should avoid matching for `ini/section`, do you have another idea how we could match every key?

**Comment by tom-wa** [comment]
what about a special mountpoint to mount metadata.ini + a global plugin that copys the needed keys to the actual plugin(s). that way we could easily change every plugins configuration whenever we want.

**Comment by markus2330** [comment]
To clarify: obviously it cannot work in a fully generic way, otherwise the distinction between meta data and data would be useless.

I am more thinking about a convention, for example null keys, are interpreted as sections and everything below such sections markers is meta data for the section.

Or, alternatively, we could simply use meta data `section`, but then we would need section support for every storage plugin, unless we have another transformer from null keys to meta data `section`...

**Comment by markus2330** [comment]
@tom-wa good idea! The "special mountpoint" is already the namespace `spec`. Its explicitely designed to contain the meta data for all other namespaces.

This namespace does not, however, solve the problem of meta data storages. And obviously the plugin you mentioned (that copies the meta data from `spec` to the other namespaces) is also missing.

**Comment by markus2330** [comment]
But we are not far from this goal. Nevertheless, I would prefer to release 0.8.14 as quickly as possible and delay this proposal for 0.8.15.

**Comment by fberlakovich** [comment]
I agree with delaying it. The ```ini/section``` glob match example was only an example for the ini plugin. The challenge basically is that the glob plugin would need to identify all Keys that are to be converted to MetaKeys for this proposal to work. In the case of the augeas plugin the glob plugin can simply use the key name (*#comment*). The proposed way of matching all keys that DO NOT have the ```ini/section``` MetaKey was just one thinkable possibility.

**Comment by markus2330** [comment]
@fberlakovich It seems like that there is a major flaw with this approach. @tom-wa noted that there might be name collisions. E.g. in `CONTRACT.ini` there is:
```
[infos]
description = Indicate ...
[infos/description]
```
Thus we need special handling of the parsing code with meta anyway, even with `keytometa` afterwards.

So I am afraid there is no way around to providing metastorages next to non-meta storages. Do you have another idea how to deal with such collisions nicely in the parser and in keytometa?

**Comment by fberlakovich** [comment]
Ok, maybe someone can explain to me what the meta functionality of ini does. I thought currently it would only convert all non section keys to meta keys and append them to their corresponding section key. My proposal referred only to replacing this builtin functionality with keytometa + glob. In your example this would mean the key ```infos``` would receive a ```description``` MetaKey. As the key ```infos/description``` has no keys below it it would receive no MetaKeys. 

Could it be that we are talking about different topics? I was not actually thinking about turning every storage plugin into a metastorage plugin (although this idea is also appealing).

**Comment by markus2330** [comment]
@fberlakovich Thats exactly what the meta functionality of INI does.
But without the meta functionality, INI collapses above "description" into the same key, thus render it impossible for `keytometa` to know which key is meta and which is not.

This would not happen if we do not collapse them and mark one of them as section and the other not, but then we need to invent a new name for either meta or non-meta `infos/description`.

**Comment by fberlakovich** [comment]
Ok, I see the problem now. However, I think this is not strictly related to this proposal, is it? It is again a general issue with the ini section handling. In my proposal I suggested matching on the MetaKey ```ini/section``` which implies that ini would tag section (or non-section keys) in any way. However, this is also not very nice). But the issue at hand seems to be the collapsing itself, not the the meta functionality in specific, do you agree?

**Comment by markus2330** [comment]
Yes, I agree. I would be interested about which syntax used in practice would work without a problem (thus my followup question addressing the flaw: maybe its even possible with an INI dialect or simply with a different interpretation of how section should be mapped to keys).

Your generalized proposal is that we tag keys that syntactical differ in order to use that tag later to collapse all other data below them as meta data to the key which has a tag. I really like the idea, because it allows any storage plugin that has syntactical distinguished places to serve as meta data storage.

That said, back to INI:
```
[infos]
description = Indicate ...
[infos/description]
```
In the above situation we would like to have the description key with the value "Indicate ..." to be a meta data of `infos`.

The question is what we would like to have here:
```
infos/description = value, not meta data??
[infos]
[infos/description]
```

So we would need someone to think this through, especially also for other syntax (for INI-only it would not really pay off). The required keytometa changes also do not seem to be trivial. I don't think that @tom-wa will pick this up, because the feature is already implemented in INI.

**Comment by markus2330** [comment]
I will close it for now until someone picks it up again.

Adding ideas here is always possible, though.
