### ISSUE TITLE
Uninstall: target fails without failed CI runs

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#3777]
I noticed on cirrus (🍎 FULL), that the uninstall tests are failing without the build to fail/turn red.

See build log [here](https://cirrus-ci.com/task/4825555225804800), "Run tests" section.

I don't know since when this is happening.

**Comment by markus2330** [comment]
Thank you so much for reporting this! It is important that we have a look if our tests are actually testing what we think they do.

**Comment by kodebach** [comment]
@mpranj Is this still happening?

**Comment by mpranj** [comment]
Yes, [it is](https://cirrus-ci.com/task/4788134348062720).

**Comment by kodebach** [comment]
Based on the way the `uninstall` command is written in `.cirrus.yml`, it will never fail.

https://github.com/ElektraInitiative/libelektra/blob/5ebc9a4ba5215950f990f7dca948ce310f764079/.cirrus.yml#L202

The command basically says: Run the `cmake` command and only if it fails, print the output. But that also means this build step only fails, if `printf` fails.

What we want is probably something like:

```sh
output="$(cmake --build "$BUILD_DIR" --target uninstall 2>&1)"; ret=$?; if [ $ret != 0 ]; then printf '%s' "$output"; exit $ret; fi
```

But I'd just go with the much simpler:

```sh
cmake --build "$BUILD_DIR" --target uninstall 2>&1
```

Because it doesn't really matter, if the CI jobs produces some unless output
