### ISSUE TITLE
kdb.get returns key of wrong namespace when used with kdb.goptsContract

### ISSUE THREAD

**Issue by dev2718** [ElektraInitiative/libelektra#3799]
## Steps to Reproduce the Problem

```python3
import kdb

config = kdb.KeySet(0)
contract = kdb.KeySet(0)
kdb.goptsContract (contract, [], [], kdb.Key(), config)
db = kdb.KDB(contract)

ks = kdb.KeySet(0)
k = kdb.Key("user:/")

db.get(ks, k)

assert 'proc:/elektra/gopts/help' in ks
# a key of namespace proc: does not belong here.
```

## Expected Result

The assertion should fail. We asked for `user:` keys and did not expect a `proc:` key.

## Actual Result

The key `proc:/elektra/gopts/help` is returned.

## System Information

- Elektra Version: 0.9.4, https://debs.libelektra.org/focal focal-unstable main
- Operating System or Docker Container? docker container 
- Versions of other relevant software? -

**Comment by mpranj** [comment]
Thank you for reporting!

Is there any guarantee/statement regarding that in the docs? The core [C API docs](https://doc.libelektra.org/api/latest/html/group__kdb.html#ga28e385fd9cb7ccfe0b2f1ed2f62453a1) state for `kdbGet()` that you may get more keys than you requested (i.e. keys that are not below `parentKey`). Thus the assumption that everything is below `parentKey` does not hold in general.

If your code relies on such an assumption, you can use `ksCut()` to work only on specific keys. Remember to append the keys back to the keyset before calling `kdbSet()` if they should not be removed permanently. Another variant to work on a subset of a keyset is `ksFindHierarchy()` (it is unfortunately private API).

It might sound unusual at first, but some use cases actually even require such a relaxation. It is possible that you would need to return a keyset together with its specification (`spec:/`) and also allows us to do some optimizations etc.

Other than that: maybe @kodebach knows why the `proc:/elektra/gopts/help` key ends up in the keyset. It might be that its a bug, but only for this specific case.

**Comment by kodebach** [comment]
The fact that `proc:/elektra/gopts/help` is returned is fully expected. You used a `gopts` contract to create the `KDB` instance. Therefore, the `gopts` plugin will be called and the plugin always adds the `proc:/elektra/gopts/help` key. Even if it doesn't do anything else, because there is no specification present.

> Is there any guarantee/statement regarding that in the docs?

AFAIK there shouldn't be. In #3693 the explanation of what `kdbGet()` returns, is a bit more strict, but in the current master I think we don't guarantee anything.

> If your code relies on such an assumption, you can use `ksCut()`

Yes, it might be better for your code in general, to always use a cascading key as the parent for `kdbGet()` (and `kdbSet()`) and then use `ks.cut()` to get the part you actually want. That way you always get the same data from `kdbGet()` (using a non-cascading key may limit the plugins that run). It may also improve cache performance, if the parent key is always the same (@mpranj would know better).

**Comment by mpranj** [comment]
> It may also improve cache performance, if the parent key is always the same (@mpranj would know better).

In short: Yes, always using the same parent key can improve performance.

In detail: The cache will store everything below the mountpoint of the parent key. In simple terms it stores everything you wanted, but maybe a little bit more than you wanted. This reflects exactly what `kdbGet()` would do anyway. If you can give a more specific parent key (e.g. `user:/my/interest` instead of `/`) it means you may get less keys and more performance. There are some optimizations though: e.g. if you use different parent keys in the invocation, but all resolve to the same mountpoint, there will effectively be no difference.

**Comment by markus2330** [comment]
Thank you for giving these answers. I agree but still I see valid criticism about the docu and suggest #3803
