### ISSUE TITLE
Notifications from storage backends

### ISSUE THREAD

**Issue by machinekoder** [ElektraInitiative/libelektra#386]
Is there a way for a storage back-end to notify elektra about changes?

What I am thinking about was either watching for changes on the file system, e.g. when a user modifies a configuration file in a text editor. Or for example a redis database plugin that is synced with another remote or cloud database (e.g. to sync two ROS masters). It would be required for the back-end to notify elektra about a change in order to inform subscribers to elektra (e.g. via dbus plugin) about changes.

**Comment by markus2330** [comment]
There are at least two very nice ways to allow administrators to use their favourite text editor and still have proper validation and notification.

1. "etckeeper-ng": Let Elektra read from git and not directly from configuration files. Modifications of files themselves are not relevant anymore and a commit will trigger Elektra (validation, notification and everything else). Changes from gui+web would also be tracked nicely in commits per change. @tom-wa already expressed interest in doing something like that.
2. "visudo-ng": Resurrect `kdb edit` which generates files in the favourite syntax of the administrator. When quitting the editor (of administrators choice), Elektra will import the changes (again with validation, notification and everything else).

**Comment by strahlex** [comment]
Changing INI files on the drive are not really are requirement but would be nice to have. However the redis database scenario is something that has to be kept in mind. It means that the data behind elektra can change without calling kdb or changes from a user. The database needs a way to notify elektra that somehting has changed and elektra needs to notify subscribers about changes. 

One way to achieve that would be create a elektra client (e.g. in Python) rather than a plugin that calls kdb set when keys change, but I was looking for a more elegant solution.

**Comment by markus2330** [comment]
Obviously, its not the most controlled circumstance if something changes behind your back. Validation cannot be enforced anymore. Why not simply use a redis storage plugin?

To understand your use case better: Which configuration data is in redis, why is it there and who changes it?

**Comment by markus2330** [comment]
@waht I assigned it to you to read more about the users perspective. Nothing particular to do here.

**Comment by markus2330** [comment]
redis seems to not support hooks, so it seems to be impossible to anything here.

Please reopen if redis has hooks.
