### ISSUE TITLE
reference counting

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3869]
## Unexpected Behavior:

- locking is not reset when ref counting again gets 0 (adding to keyset and pop again) #2202
- C++ API for KeySet and Key has unexpected differences: also use ref counting for KeySets (also suggested in #1332)

## Proposals/for Discussion:

- make ref counting thread safe (probably useful for JNI)
- start with 1 for reference counting and let keyDecRef do keyDel (remove ksDel&keyDel; or remove keyDecRef, rename keyIncRef to keyBorrow (or similar) and keyDecRef to keyDel) #1332

**Comment by kodebach** [comment]
> make ref counting thread safe

Making just the ref count thread safe would be odd, when the rest of the API isn't thread safe at all.

> (probably useful for JNI)

The Java binding already uses a lock to prevent race conditions.

> start with 1 for reference counting

Starting with 1 is more logical, but doesn't really change anything.

> let keyDecRef do keyDel (remove ksDel&keyDel; or remove keyDecRef, rename keyIncRef to keyBorrow (or similar) and keyDecRef to keyDel)

I prefer to think of it the other way around. `keyDel` should do a `keDecRef`, if the `refCount > 0` and if `refCount` then hits zero (i.e. it was 1), it actually frees the memory. Otherwise, it just returns after decrementing `refCount`.

Instead of renaming `keyIncRef` to `keyBorrow`, I would do this:
```c
/**
  * @return a new reference to k
  */
Key * keyBorrow (Key * k) {
   keyIncRef (k);
   return k;
}
```

`keyIncRef` and `keyDecRef` would be internal/private/static (whatever fits). The same `ks*` functions should exist for `KeySet`.

The end effect is basically the same. Users should
- use `keyNew` and `keyCopy`/`keyDup` to create entirely new `Key *` that don't have any links to other `Key *`.
- use `keyBorrow` to create a new `Key *` that is a reference an existing `Key *`.
- use `keyDel` to dispose of a `Key *` (whether the `Key *` comes from `keyNew`, `keyCopy`/`keyDup` or `keyBorrow`).

The fact that there is a reference counter would be an implementation detail.

---

**Possible, but work-intensive extension**
We could also do this:
```c
typedef KeyRef Key *

Key * keyBorrow (KeyRef k) {
   keyIncRef (k);
   return k;
}
```

Then we could have the convention: "If you receive a `Key *` you must call `keyDel`, if you receive a `KeyRef` you must not." That would however require going through the entire code base and replacing `Key *` with `KeyRef` where appropriate.

The nice thing here is that the signature of `keyBorrow` shows that calling it creates the need for an additional `keyDel` call.

---

PS. I think we should convert this issue into a discussion (there is a button for this in the sidebar).
