### ISSUE TITLE
docker elektra/elektra not in released version?

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3885]
## Steps to Reproduce the Problem

```sh
docker pull elektra/elektra
docker run -it elektra/elektra
kdb --version
```

## Expected Result

0.9.6

## Actual Result

0.9.5

## System Information

- Elektra Version: master

**Comment by mpranj** [comment]
This should be automated, but as the release pipeline (partially) failed I think it did not get published.

I updated this specific image manually now. We can re-test the automation with the next release soon. :smile:

**Comment by markus2330** [comment]
Thank you for manually uploading it! Did the pipeline succeed at all in this release? I thought once it was successful and then you did small updates?

Is there maybe some way that @robaerd can do improvements that partial publishing is less likely? (or at least more clear what did (not) get published) But obviously the goal is that the release pipeline is successful. Probably we always should do a release when we change something in the release pipeline.

**Comment by kodebach** [comment]
Is it possible that our Alpine Linux builds are somehow broken? 

There clearly are images that are built and pushed to Docker Hub that have the new 0.9.9 version (e.g. [`elektra/elektra:0.9.9-6-bionic`](https://hub.docker.com/layers/elektra/elektra/0.9.9-6-bionic/images/sha256-1187310c9837fb745613abfa4587b72bd3c3a492301dbb43777496d89e6b4ad6?context=explore)). You can tell, because the `exports` for the `dump` plugin are `serialize`/`unserialize` and not the old `serialise`/`unserialise`.

```
elektra@280d2d97b27b:~$ kdb ls system:/elektra/modules/dump/exports
system:/elektra/modules/dump/exports
system:/elektra/modules/dump/exports/fserialize
system:/elektra/modules/dump/exports/funserialize
system:/elektra/modules/dump/exports/get
system:/elektra/modules/dump/exports/serialize
system:/elektra/modules/dump/exports/set
system:/elektra/modules/dump/exports/unserialize
```

However, the `elektra/elektra` seems very broken. It's not just that the `latest` tag isn't updated. According to the SHA256 digests `elektra/elektra:latest` is currently an alias for `elektra/elektra:0.9.9-6-alpine`. And that image simply also contains the old `0.9.8` build, no idea how that happend.

**Comment by mpranj** [comment]
Seems that I made an error in the release scripts. I tried to automate the version bump for the alpine builds. It worked but the change was not reflected in the release build, due to not fetching the git changes.

I'll take a look into it. Thank  you for reporting.
