### ISSUE TITLE
diff of installed files for releases

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3900]
In previous releases we created diffs of which files are going to be installed. It basically worked by

```
DESTDIR=d make -j 5 install
find d > list-of-files-in-current-release
diff  list-of-files-in-current-release list-of-files-in-previous-release
```

Can we include this in the automatic release notes #3899 (or later)  please?

**Comment by robaerd** [comment]
I am currently a bit unsure on how to implement the access to the _installed-files_ file of the previous version.
Following would be the possible options (sorted by best fit):

1. Add the _installed-files_ file to git. Creating a seperate directory in the [ftp repo](https://github.com/ElektraInitiative/ftp) would fit well.
2. Load the previous _installed-files_ file from the artifacts of a previous release-pipeline run. 
   - This could be implemented automatically by looking for the latest successful run
   - and/or by adding a parameter with which we could specify the build number of the last release-run, we want to copy the artifacts from
3. Rebuild and install the previous release based on the released tarball and generate the _installed-files_ file.
   - Increases build time
   - Possibility that previous release can not be build/installed anymore due to dependency issues (package upgrades or other reasons)

@markus2330 what is your opinion on this?

**Comment by markus2330** [comment]
> Add the installed-files file to git. Creating a seperate directory in the ftp repo would fit well.

Exactly, there where we have other logs and so on from every release.

**Comment by markus2330** [comment]
For the previous release you can create the file manually so that the script will start working :rocket:

**Comment by markus2330** [comment]
Btw. for the ABI tests we will also need the possibility to refer to the previous release.

**Comment by robaerd** [comment]
> > Add the installed-files file to git. Creating a seperate directory in the ftp repo would fit well.
> 
> Exactly, there where we have other logs and so on from every release.

Currently we do not have any logs from the release under git, only an archive that can be downloaded from our Jenkins UI. However, adding these logs to git would actually be a good idea.

> Btw. for the ABI tests we will also need the possibility to refer to the previous release.

My current approach for the ABI tests would be to use the previously published `elektra-test` packages, install them and run the tests again. This would remove the need to ever compile the previous release in the release pipeline. 
Please correct me if I misunderstood the ABI test procedure.
