### ISSUE TITLE
highlevel: do not fail without any spec

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3938]
@haraldg reported a usability problem of the highlevel API.

While it is important that we fail with an inconsistent/wrong spec during `kdbOpen` it is not a good design choice that `elektraGet` calls fail because of a missing type in the spec. Let us assume following example program:

```c
#include <stdio.h>
#include <elektra.h>

int main () {
        Elektra *elektra = elektraOpen("/sw/test/elektraHighLevel/", NULL, NULL, NULL);

        const char *output = elektraGetString(elektra, "output");

        printf("%s", output);

        return 0;
}
```

## Expected Behavior

It is fine to fail if there is no config nor spec:

```
kdb rm /sw/test/elektraHighLevel/output
./a.out
# RET: 1
```

## Unwanted Behavior

It is weird to fail if there is no spec and there is a valid value:

```
kdb set /sw/test/elektraHighLevel/output "Hello World"
./a.out
# RET: 1
```

## Guidelines

In general, we should try to fail within `elektraOpen` if possible (specs without defaults or value, without types). At run-time we should only fail if there is an unrecoverable error/inconsistency. (e.g. other type specified than asked for, value not according the type and so on...). Not having a spec is neither an error nor an inconsistency.

**Comment by markus2330** [comment]
Btw. the situation drastically improves if the TOML plugin is in use, then we have:

```
sudo kdb mount test.toml /sw/test/elektraHighLevel toml
kdb set /sw/test/elektraHighLevel/output "Hello World"
kdb meta-get /sw/test/elektraHighLevel/output type
#> string
./a.out
#> Hello World
```

**Comment by kodebach** [comment]
First of all, it is not recommended to use the highlevel API without code-generation. This is clearly stated in the [tutorial](https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/highlevel.md).


> it is not a good design choice that `elektraGet` calls fail because of a missing type in the spec.

It may not be the best choice, but it was the choice we made. Therefore, I see this issue as a proposal for an API change, enhancement or new feature, i.e. a low-priority issue considering the other issue we are working on right now. If you see it differently, feel free to implement the change yourself.

> It is weird to fail if there is no spec and there is a valid value:

The highlevel API by design requires a complete (see also below) specification to be present and correctly mounted. This is why it is highly recommended to only use the highlevel API **with** code-generation. It is far to easy to build something that looks like it might work but actually doesn't, if you write the code by hand.

> At run-time we should only fail if there is an unrecoverable error/inconsistency. (e.g. other type specified than asked for, value not according the type and so on...)

The highlevel API only considers `spec:/` keys with a `type` metakey part of the specification. This was a design choice and is reflected in documentation, code-generation and tests. For example, the code-generator ignores als keys that don't have a `type` metakey and doesn't generate a `ELEKTRA_TAG_*` macro.

Since the highlevel API is designed with a complete specification in mind, it is designed `elektraGet` will fail when a non-specified key is used. As stated, keys without `type` are considered non-specified and therefore `elektraGet` fails by design.

The reasoning behind this is also very simple: If we call e.g. `elektraGetShort (elektra, "foo")` we want the guarantee that not only the key `foo` contains a `short` value, but **also** that `foo` is supposed to contain a `short` value, i.e. that is is specified as `type = short`.

> In general, we should try to fail within `elektraOpen` if possible

While in theory this is a nice idea, any check that is done explicitly in `elektraOpen` (and not indirectly by `kdbGet`, e.g. because of a plugin), has to be replicated `elektraSaveKey` (the function behind `elektraSet*`). So the nice idea of a big one time initial cost, becomes a big cost initially **and** every time you update a value. If the notification API is used (not possible right away) you need to do the same checks, every time you get a notification. Basically every time you cal `kdbGet` you need to check **everything**, even though you may not access any of it.

**Comment by markus2330** [comment]
I don't think we should have such an attitude toward reported usability problems.

1. It is not so clearly said in https://github.com/ElektraInitiative/libelektra/blob/master/src/libs/highlevel/README.md
2. It seems to work without type set in spec: (see what I wrote in the second message)

**Comment by kodebach** [comment]
> It is not so clearly said in [...]

True, the documentation could be better. At the very least, it should mention the [tutorial](https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/highlevel.md) should be read first. 

> It seems to work without type set in `spec:` (see what I wrote in the second message)

Yes, the high-level API (without codegen) doesn't care about `spec:`. It needs the `type` on the actual config keys. The `toml` plugin generates a `type`, so everything works fine.

---

What would be your suggestion how we handle this situation instead? There isn't really any way of knowing in e.g. `elektraGetLong` whether there is no spec at all, this particular key is missing the spec, or whether just `type` is missing.

Should we just say if `type` is missing we try to convert it and if it succeeds it succeeds, if it fails it fails?

**Comment by markus2330** [comment]
> True, the documentation could be better. At the very least, it should mention the tutorial should be read first.

Could you please update the flow how to read the docu as @qwepoizt is currently trying to understand the high-level API.

> Should we just say if type is missing we try to convert it and if it succeeds it succeeds, if it fails it fails?

Let us see what @qwepoizt says.

**Comment by qwepoizt** [comment]
I am not sure if I fully understand the issue in all its details, but I believe that if :

1. the high-level API must not be used without code generation
2. and the reported issue does not occur when code generation is used

then

1. the above should be clearly stated in the documentation
2. and the reported issue can be fixed by using code generation

I hope that helps :)

**Comment by haraldg** [comment]
I'm actually a big fan of code generation, yet I believe it shouldn't be mandatory.

I think, when evaluating elektra people want to write a quick hello world example and see how it works. Maybe strace it or profile it or whatever they consider an useful evaluation. Then in the next step, they will rewrite the hello world example to evaluate the code generator. Then decide, whether they want to use elektra with code generation or without or not at all.

If the first step fails without good reason, it will just drive away potential users. (And probably rightly so, as a project where people argue over being right instead of solving problems surely isn't a good base to build upon.)

**Comment by kodebach** [comment]
First of all, if it came across as me arguing that I'm right, then I'm sorry. That was not my intention. My main argument was that a single report of a small usability problem, should not be reason enough to immediately change an already implemented design decision.

The design decision here was: The high-level API works only for specified keys and the minimum specification is a `type`.

In the actual high-level API this is reflected as an error/abort, if the users tries to read an unspecified key. In the code-generation part we simply ignore spec:/ keys without a `type` and don't generate tags or accessor functions for them.

The reason behind this decision was that the high-level API is meant for "real" applications and those should have a specification. Anything that doesn't have specification (e.g. tools like `kdb`), should continue using the low-level `kdbGet`/`kdbSet` API directly. (Note: the [conversion APIs `elektraKeyTo*`](https://doc.libelektra.org/api/latest/html/conversion_8c.html) used by the highlevel API can also be used with the low-level API)


The code-generation is **not** mandatory. It doesn't generate anything you couldn't write by hand. You probably wouldn't write code exactly the way it is generated, but there is nothing special in the code generator. The reason we do highly recommend using the code generator is that without it, it is very easy to write something that doesn't work.

I also recognise that experimenting with the high-level API without a full spec may be a valid use case. However, I don't think it is as easy as "if there is no `type` just try converting and hope for the best". This would completely invalidate the idea that only specified keys can be read. Instead a propose a configurable approach.

Via the `contract` given to `elektraOpen`, we could provide an option to define whether or not keys without a `type` can be read. By default we would allow reading keys without a `type`, but the code-generation would override this. That way the basic example in this issue would work, but when you use the code generator you still have the guarantee that everything you read is properly specified.

This change may take some time to implement, so in the meantime the documentation should be updated to clearly state a `type` is required for the high-level API.

**Comment by haraldg** [comment]
I agree, that this issue is not urgent as an easy workaround (just add the specification) is available.

Still I strongly recommend to change this before 1.0 for two reasons:
a) The current behavior is just embarrassing

**Comment by kodebach** [comment]
@qwepoizt Since you are working with the highlevel API right now, and have already updated some of the documentation, could you maybe also add somewhere in the [README](https://github.com/ElektraInitiative/libelektra/blob/master/src/libs/highlevel/README.md) that `type` is required even without the code-generator. You've probably read the docs more recently than I have, so you'll know better where this information fits best.

**Comment by qwepoizt** [comment]
@kodebach Okay, I'll take care of it and add a reference to this issue to my commit/PR.

**Comment by markus2330** [comment]
> small usability problem

I would not play it down. If you are new to Elektra and don't know anything about namespaces, meta-set and so on it can be challenging to do the right thing in this case. A small usability problem would be, e.g., that we do not provide alloca variants in the high-level API.

> a) The current behavior is just embarrassing
> b) I can't think of any case where the current behavior would actually be helpful.

I fully agree. We should fix the issue and only fail on incompatible types. Not having any spec should be allowed.

**Comment by markus2330** [comment]
@kodebach can you describe what needs to be changed to fix this issue?

**Comment by kodebach** [comment]
I **think** we just need to change this part

https://github.com/ElektraInitiative/libelektra/blob/5ebc9a4ba5215950f990f7dca948ce310f764079/src/libs/highlevel/elektra_value.c#L55-L63

if `keyGetMeta` returns `NULL` we should `return resultKey`.

I'm not sure, if other changes are needed, but it should be pretty simple to use an example like the one you provided and step through it with the debugger. More specifically, adding a breakpoint in `elektraFatalError` should be enough, since that should be the only way for the highlevel API to fail.
