### ISSUE TITLE
package gsettings

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3955]
Is there some progress in packaging fuse and gsettings? Would be nice to have it so that people (including me) can install it easily.

Probably we should not support current Debian stable, as the next stable will hopefully be released soon.

**Comment by dev2718** [comment]
https://github.com/ElektraInitiative/libelektra/pull/3996 introduces packaging for the FUSE tool.

**Comment by markus2330** [comment]
Bullseye packages (0.9.7-5.5491) of Elektra still do not contain libelektra5-fuse? What went wrong?

**Comment by dev2718** [comment]
This is because `python3-elektra` does not get built on bullseye, therefore `libelektra5-fuse` isn't as well.

**Comment by markus2330** [comment]
Is there a bug preventing python3-elektra from being built? Or are just deps missing?

**Comment by dev2718** [comment]
I investigated this and I think I found the culprit:

- The bullseye Dockerfile uses swig4.0 (in constrast to the other debian distros, except sid)
- The python binding does get built successfully in the full build "debian-bullseye-full"
- But **not** in the packaging job, because for everything that is not Fedora, swig3.0 is hardcoded here:

https://github.com/ElektraInitiative/libelektra/blob/e9d0afa7821b82b44940ffe5bfc271f2c69bc663/scripts/packaging/package.sh#L61

**Comment by markus2330** [comment]
Thank you for looking into it! This swig3.0 was needed for buster. As buster is now oldstable we can get rid of it. Not having python3 for buster (or even having no buster packages at all) shouldn't be a big problem anymore.
