### ISSUE TITLE
Keyname validation does not detect all invalid names

### ISSUE THREAD

**Issue by dev2718** [ElektraInitiative/libelektra#3989]
## Steps to Reproduce the Problem

In C++:
```cpp
kdb::Key broken ("systemx:/hello", KEY_END); // no exception thrown
kdb::Key broken2 ("usx:/hello", KEY_END); // no exception thrown
kdb::Key broken3 ("usxx:/hello", KEY_END); // exception thrown
```

This also manifests in the kdb tool where
```sh
kdb set systemx:/hello x
```
fails silently, but
```sh
kdb set usxx:/hello x
```
produces a proper error message.

## Expected Result

All three keynames should produce exceptions.

## Actual Result

Only the last keyname produces an exception.

## System Information

- Elektra Version: master
- Operating System or Docker Container? Docker

**Comment by markus2330** [comment]
Is this a problem in the C++ binding or is it also present directly with keyNew?

**Comment by markus2330** [comment]
elektraKeyNameValidate seems to be the problem: it does not return false on the keyname `ystemx:/hello`

**Comment by JakobWonisch** [comment]
[FLOSS H1]

The issue is in `elektraReadNamespace` in [`/src/libs/elektra/internal.c`](https://github.com/ElektraInitiative/libelektra/blob/master/src/libs/elektra/internal.c) which actually checks if the namespace is valid:

```c
elektraNamespace elektraReadNamespace (const char * namespaceStr, size_t len)
{
	if (len == 0) return KEY_NS_NONE;
	if (strncmp (namespaceStr, "system", len) == 0) return KEY_NS_SYSTEM;
	if (strncmp (namespaceStr, "user", len) == 0) return KEY_NS_USER;
	if (strncmp (namespaceStr, "dir", len) == 0) return KEY_NS_DIR;
	if (strncmp (namespaceStr, "proc", len) == 0) return KEY_NS_PROC;
	if (strncmp (namespaceStr, "spec", len) == 0) return KEY_NS_SPEC;
	if (strncmp (namespaceStr, "meta", len) == 0) return KEY_NS_META;
	if (strncmp (namespaceStr, "default", len) == 0) return KEY_NS_DEFAULT;
	return KEY_NS_NONE;
}
```

This function gets passed the length of the name in `namespaceStr` before the first ":" character. As `strncmp` only checks at most `len` characters the input dictates how much of the string is actually checked and therefore all names that are only a part of the valid namespaces are returned as valid.

Compounding that issue there is also 1 being subtracted from the intended length in `elektraKeyNameValidate`'s call to `elektraReadNamespace`, which means "usx" does not fail as namespace, because the program only checks that the first two characters match the first two of "user". Only when another character is added ("usxx"), the program compares "usx" to "use" (again, only the first three letters) and throws an exception.
