### ISSUE TITLE
problems with specload

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4032]
@kodebach is there somewhere a summary which problems specload has?

- [ ] codesize: redshift has 88K instead of 79K (the installed version without Elektra), so it might not be a big deal for desktop applications
- [ ] exitForSpecload is needed: this mechanism probably can also be useful for other introspection mechanisms, #3888 
- [ ] changing of the spec does not seem to be allowed anyway? I could not even change the description:

```
kdb meta-set spec:/sw/redshift/#0/current/mode description x
 Sorry, 11 warnings were issued ;(
        Sorry, module sync issued the warning C01100:
        Resource: Could not open config file sw_redshift__0_current.overlay.spec.eqd. Reason: No such file or directory
Sorry, module specload issued the error C01100:
Resource: This kind of change is not allowed
```

**Comment by kodebach** [comment]
> is there somewhere a summary which problems specload has?

I don't think so, but I think you covered most of it. To me the main problem was that we completely failed to achieve the main goal. Initially the idea was to guarantee that the spec matches was the application developer intended it to be, while allowing safe modifications by system admins. This turned out to be far to complicated.

> codesize [...] might not be a big deal for desktop applications

Agreed, for most modern desktop systems even going from 100kB to 1MB probably wouldn't be a problem. However, the size change will depend on the size of the spec, so we probably shouldn't make embedding the spec the default, if we even keep the option at all.

> changing of the spec does not seem to be allowed anyway? I could not even change the description:

Not sure, what happend there. I won't waste time looking into it unless we really want to keep `specload`.

**Comment by markus2330** [comment]
> Initially the idea was to guarantee that the spec matches was the application developer intended it to be,

Was the first goal achieved?

> while allowing safe modifications by system admins. This turned out to be far to complicated.

Probably because of #3983, we made the `type` too much overloaded. In the initial concept every additional metadata only restricted the types more and more. In this case, adding new metadata would be always safe, so specload simply would need to prohibit changing existing metadata, which should be fairly easy to check.

**Comment by kodebach** [comment]
> Was the first goal achieved?

Yes, I would say so. `specload` requests the specification from the application itself. Therefore, if the spec doesn't match the application developers intentions, it is their own fault.

However, as stated before, this could be achieve with a much simpler design as well. Especially, once the new backend plugin stuff is done (then we don't need to pretend that there is a file somewhere).

> In this case, adding new metadata would be always safe

It's hard to say anything in general, because in theory adding a new metakey could trigger some plugin to do something the application does not expect. We would at least need to restrict it to "adding new `check/*` metadata", since a `check/*` metakey should only trigger a check, but not add/remove/change keys via a plugin.

I don't really see a lot of use in `specload` anymore. At least not in the current version. IMO it is best to deprecate and remove it. If we want something like `specload`, we should design something new with the insights we gained.

**Comment by markus2330** [comment]
>Yes, I would say so. specload requests the specification from the application itself. Therefore, if the spec doesn't match the application developers intentions, it is their own fault.

So the remaining problem is if spec-mount was executed.

> However, as stated before, this could be achieve with a much simpler design as well. Especially, once the new backend plugin stuff is done (then we don't need to pretend that there is a file somewhere).

Do you remember what the behavior was when you passed the overlay file to the resolver?

> It's hard to say anything in general,

Obviously it will only follow the rules we make but...

> because in theory adding a new metakey could trigger some plugin to do something the application does not expect.

Would imho be an insane behavior = bug. New metakeys might reject a key but should never allow a key that was rejected before.

> I don't really see a lot of use in specload anymore. At least not in the current version. IMO it is best to deprecate and remove it. 

It is up to @qwepoizt.

> If we want something like specload, we should design something new with the insights we gained.

Can you please summarize the insights?

**Comment by kodebach** [comment]
> Do you remember what the behavior was when you passed the overlay file to the resolver?

Not of the top of my head.

> Would imho be an insane behavior = bug. New metakeys might reject a key but should never allow a key that was rejected before.

Yes, I agree. I was thinking more along the lines of adding a metakey, which triggers the generation of an entirely new key, which in turn might cause unexpected behaviour in the application. For example:

1. The application expects that key `X` and `Y` are both integers. This is enforced via the `type` plugin.
2. I now add a metakey `meta = value` to key `X`.
3. This triggers a plugin `P`, which generates key `Y` with value `value`.
4. The `type` plugin should reject key `Y`, but currently there isn't a good way to ensure that `type` runs after `P`. Therefore we may get an unexpected value in the application.

This is example, is not really problem with `specload` in itself, but more a limit of the plugin ordering mechanism. However, it illustrates that a correct `specload` is very complicated to do and probably not worth anybody's time right now.

> Can you please summarize the insights?

Currently, more less what is already discussed here. But I meant, we should abandon `specload` for now and in the future when we want to try again, we will hopefully have _new_ insights that will help us.

**Comment by kodebach** [comment]
see #4444
