### ISSUE TITLE
API for accessing parts of the Key name

### ISSUE THREAD

**Issue by lawli3t** [ElektraInitiative/libelektra#4102]
Currently it is very hard to access specific parts of the name. While it shouldn't be too common a task, the following snippet from the GSettings bindings might be evidence that some kind of helpers for accessing specific parts of the name might be needed:

```
gchar * gsettingskeyname = g_strdup (g_strstr_len (g_strstr_len (gelektra_key_name (gkey), -1, "/") + 1, -1, "/"));
```

I have thought about several ways to implement this properly but every option I see has some serious drawbacks, that disqualify them from getting put into practice:

## Variant 1

```
elektraGetNameParts(key)
elektraGetNamePartCount(key)
```
There are some practical issues with this solution. The user has to know the allocated size for every part of the array. If there is a big element in the key hierarchy, then there is lots of unneeded space. There also needs to be a way to convey the size of the array, so that the user can actually work with it. Also the user needs to handle memory management of the array, putting another responsibility on the invoker of the function.

## Variant 2
```
elektraGetNamePartAt(key, position)
elektraGetNamePartCount(key)
```

If I wanted to iterate over the name parts, then I would have to repeatedly call the function. If the function splits and returns the respective element at `position` every time it is called, then this has huge performance issues when used in loops.

Another option would be storing the name in an already split form so only the respective parts get returned, but this uses way too much memory for too little gain.

## Variant 3 - External Iterator

We could implement an external iterator, as we did with KeySets. This is a lot of added stuff for 'just' iterating over the name parts, but would probably be the best solution I could come up with so far. The question is if the implementation effort is worth the ability to iterate over name parts?

### Open questions

- Do you think this would be a worthwhile addition? Is this something other Elektra users could benefit from?
- Do you see any other possible implementation options?
- Are there possibly any internal implementations / APIs for this that I am not aware of? We probably would need something like that internally I would suppose.

**Comment by markus2330** [comment]
> Currently it is very hard to access specific parts of the name.

Do you mean escaped or unescaped parts?

> If the function splits and returns the respective element at position every time it is called, then this has huge performance issues when used in loops.

From previous benchmarks we learned that mostly the key creation is a performance problem.
In general, memory overhead is currently a much bigger problem than performance.

> Another option would be storing the name in an already split form so only the respective parts get returned, but this uses way too much memory for too little gain.

Actually we would like to store **only** the unescaped name, see #3521.

>  Do you think this would be a worthwhile addition? Is this something other Elektra users could benefit from?
>  Do you see any other possible implementation options?

I think best would be to only store unescaped name and implement #3902. Then iteration should be easy enough that no API in C is needed. (In languages that have iterators, we provide them already.)

> Are there possibly any internal implementations / APIs for this that I am not aware of? We probably would need something like that internally I would suppose.

keyNameGetOneLevel (but we actually thought it is not a good idea to provide such an API).

> What you didn't mention is the current correct solution (using the C API)

Thank you :sparkling_heart: very good to have these examples. Please let us add this to the API docu.

**Comment by kodebach** [comment]
> Do you mean escaped or unescaped parts?

I'd say it doesn't matter much. Accessing escaped parts is almost impossible (unless you take an unescaped part and re-escape it), while unescaped part not hard to acess but, the method is not very intuitive. So clearly there is room for improvement in both cases.

> From previous benchmarks we learned that mostly the key creation is a performance problem.

I think people may have avoided code that needs to access individual key name parts, because it is so difficult. Therefore, previous benchmarks may be biased. Also I think the main point here was that `elektraGetNamePartAt(key, position)` could imply `O(1)` runtime, when it is in fact `O(position)` (or worse). This would simply be a bad API.

> > Another option would be storing the name in an already split form [...]
>
> Actually we would like to store only the unescaped name

I have thought about storing indices to the unescaped parts, but it is too expensive, unless we limit the length of an unescaped to part to e.g. 255.

> [Implement #3521 and #3902] Then iteration should be easy enough that no API in C is needed.

Even then I would still add `keyGetNextPart` to `libelektra-ease`. I think it makes the code more readable compared to the direct `strlen` stuff. In the internal code it doesn't matter, because people that read that code should know about the unescaped name structure. But in plugins or application code `keyGetNextPart` would certainly be an improvement.

> keyNameGetOneLevel

The fact that this is a function within a plugin (`yajl`) demonstrates very well, why adding `keyGetNextPart` to `libelektra-ease` would make sense.

I would also make `elektraKeyNameEscapePart`  a public symbol or at least add a public wrapper. Then you can get the escaped name from an unescaped part (e.g. for display in a UI).

**Comment by markus2330** [comment]
> I'd say it doesn't matter much.

I was asking to keep this issue focused. I agree in both cases there is room for improvement.

> Even then I would still add keyGetNextPart to libelektra-ease.

 I don't have objections against adding it to libelektra-ease. It is only that it does not bring us closer to 1.0.

>   The fact that this is a function within a plugin (yajl) demonstrates very well, why adding keyGetNextPart to libelektra-ease would make sense.

Yes,  it is good if functions added to libelektra-ease are used from the beginning

> I would also make elektraKeyNameEscapePart a public symbol or at least add a public wrapper. Then you can get the escaped name from an unescaped part (e.g. for display in a UI).

If we get rid of the escaped key name in Key, a function like this will be required anyway.

**Comment by kodebach** [comment]
I suggest adding `keyGetNextPart` to the newly proposed `libelektra-operations` (see https://github.com/ElektraInitiative/libelektra/pull/4223/commits/26e66b64cf3f44e7fa7c94b0e576ecef17d2bbb0).
