### ISSUE TITLE
cache: disabled due to `procgetstorage` check

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#4104]
The cache has been effectively disabled in 6525b71fe535f54d136f9b63fab101d619bd4b68 with this check:
https://github.com/ElektraInitiative/libelektra/blob/9a14f67a9f3edb393daf41346f3d4f3b781b6b60/src/libs/elektra/kdb.c#L1279-L1288

As `procgetstorage` is always filled by the list plugin in the **default** configuration, the cache is loaded but ignored currently.

**Comment by kodebach** [comment]
A few things upfront:
- I will consider "`procgestorage` plugins" and `gopts` to be the same, since `gopts` is currently the only thing that uses this position.
- In the #3693 the plan is that there are no more generic positions for global plugins. We just call `gopts`, `spec`, `internalnotification`, `cache`, etc. exactly how and when needed.
- At least in #3693 it would be possible to mount a backend to a `proc:/foo/bar` mountpoint. This is different from `gopts`. These backends must also be excluded from the cache, but because they are isolated, we can simply process the whole backend after loading the cache. I'm not sure, if such backends are possible right now, so let's ignore this for now.

---

> Unfortunately `procgetstorage` and `cache` were developed roughly at the same time, so we could not take the other into the design.

I know, but the `proc:/` namespace existed already and caching `proc:/` keys never makes sense, because they are by definition specific to one single process. This fact is something _we all_ overlooked when the cache was initially designed.

> Calling all `postgetstorage` plugins twice sounds problematic and erroneous.

I agree. Something like this may work, if we more clearly separated into plugins that only validate and plugins that might modify, but currently calling any plugin twice should be considered an error.

> Isn't it possible to basically cache everything except the `proc:/` namespace and then a new cleanup/postprocessing position that only affects `proc:/`?

In theory, yes. But ...

> So the order would be: `PROCGETSTORAGE; PREGETCACHE; PROCPOSTPROCESS`

... not like this. `gopts` must be called **after** the other keys are loaded, because it reads `spec:/` keys to determine what to do.

I think it may be possible, to do:
1. load cache
2. call `gopts`
3. call `spec`, but only with `spec:/` and `proc:/` keys
4. call all `postgestorage` plugins for `proc:/` keys

Steps 3 and 4 could be limited to the case, where `gopts` actually did something. For that `gopts` needs to be adapted to return `ELEKTRA_PLUGIN_STATUS_NO_UPDATE`, when appropriate.

Also step 3 and 4 only make sense, if it is possible to have a `postgestorage` plugin (e.g. `type`) for `proc:/` keys. This might be possible via a cascading mountpoint from `kdb spec-mount`. We need to call these plugins to e.g. check that a command line argument is an integer and not a string.

If `postgestorage` isn't called for `proc:/` anyway, then this whole issue boils down to: "Call `procgetstorage` after loading the cache". And the rest is only relevant with #3693.
