### ISSUE TITLE
"kdb --help" is inconsistent

### ISSUE THREAD

**Issue by nikonthethird** [ElektraInitiative/libelektra#421]
`kdb qt-gui --help` launches the GUI, but `kdb --help qt-gui` displays the help.

This applies for all tools listed in `kdb list-tools`, but some of them have no manual entry anyway.

KDB version is: 0.8.14

**Comment by markus2330** [comment]
Thank you for reporting it! Please reopen if you find further issues regarding unified --help or -H usage.

The -V or --version is not unified on purpose because I think we should give external commands a chance to report their own version information. And if some command is unable to report a version, I think the usability will not suffer too much if you need to retype `kdb -V`.
