### ISSUE TITLE
[CM P0] LDIF Storage Plugin

### ISSUE THREAD

**Issue by eiskasten** [ElektraInitiative/libelektra#4295]
# LDIF Storage Plugin

LDIF is the file format which is used by LDAP to exchange data. Mainly, this format is used to exchange user records for services with a large amount of users. Furthermore, this format is used by OpenLDAP in order to configure it.

As no storage plugin for LDIF already exists, we want to introduce it. Our approach is to use the `libldap` which includes an API which is able to read and write the LDIF file format.

The LDIF format is defined [here](https://datatracker.ietf.org/doc/html/rfc2849).

## Scope

* Reading LDIF files
* Writing LDIF files

## Team
The team consists of the members @bhampl and @Eiskasten.

**Comment by markus2330** [comment]
This is an excellent idea!

Which programming language do you want to use?

Please give more details about the scope (also depends on what libldap supports):

- comments in `comment/#`?
- remember order?
- see also doc/tutorials/storage-plugins.md for information what might be important for the plugin.

Please also say at which milestone you want to do which task. You probably also want to do the T2 task related to your LDIF Storage Plugin. Then also add as tasks which kind of validations you want to implement.

Please do not forget to also add non-trivial test cases (some real world configs, more complicated than the examples in the standard).

Related work is missing: which alternatives to libldap would be possible?

Btw. you can have check boxes for your individual tasks: `- [ ]`, then you/I see more easily how many tasks you already did.

**Comment by Eiskasten** [comment]
In order to avoid using bindings for two libraries, we will use C to implement the ldif storage plugin.

To answer you questions about the scope:
* we do not plan to implement comments as the `libldap` does not have any support deserializing them from the ldif format
* as ldif files are order sensitive in general, the plugin will remember the order
* besides from the order and comments, there exist no further meta data in ldif which answers the question about support additional meta data
* as the ldif format is multi valued per key, supporting arrays is mandatory
* supporting "holes" does not seem to be possible in this case, as in ldif, every parent key of a key is always a valid key too and at least contains the `dn` attribute
* this also applies to the topic with the empty keys in some way, as in ldif only attributes but not keys can be empty
* supporting values inside non-leaf keys is mandatory as this is the essence of directory services an respectively the ldif format

While there exist the `ldaptive` library for java and the `ldap3` crate for rust, the crate has not received a stable release yet and does not seem to be widely used. The `libldap` is developed within OpenLDAP which exists since 1998 and is used in basically every client application on Linux which requires ldif support. So using it allows us using C and a library which is installed on the vast majority on Linux systems.

I hope this clarifies most of your questions?
