### ISSUE TITLE
[CM T0] Sort Plugin

### ISSUE THREAD

**Issue by Gratla** [ElektraInitiative/libelektra#4303]
My collegue @mandoway and I propose a checker plugin which validates the sorting of its items (for [CM T2]).
In detail the plugin should check, whether the values in an array are sorted (valid) or not (invalid).
The reformatting of existing configuration settings is not considered within this issue!
To setup the plugin, there are some meta-keys needed for its configuration which are set for the array:

The enable key is `meta:/sorted`. It is used to activate the plugin on an array.
The value of this key determines which sub-value of the array should be used for sorting.
If it is empty, the plugin assumes, that the array consists of primitive types (i.e. number or string).

For the direction, the key `meta:/sorted/direction` is used.
Also, two directions can be implemented:

- ascending (default)
- descending

We want to write this plugin either in Java or in Kotlin depending on the implementation of the Kotlin binding (#4294).

### Example Primitive Types
Valid:
```
/#0 = a
/#1 = b
/#2 = c
```

Invalid:
```
/#0 = a
/#1 = c
/#2 = b
```

### Example Complex Array
Sort by permission value.
Valid:
```
/#0/name = admin
/#0/value = 999
/#1/name = user
/#1/value = 800
/#2/name = guest
/#2/value = 700
```

Invalid:
```
/#0/name = admin
/#0/value = 999
/#1/name = guest
/#1/value = 700
/#2/name = user
/#2/value = 800
```

The usecase for this example would be, that one could always query the first entry of the array and it is asured, that the role with the highest permission value is returned.

**Comment by kodebach** [comment]
Please provide more infos on how this plugin would work. What `meta:/` keys would it use? What do you mean by "its items"?

If you're unsure what to describe, take a look at the [references plugin](https://github.com/ElektraInitiative/libelektra/tree/master/src/plugins/reference). It doesn't have to be this detailed, but please provide a rough overview before you start with the implementation. Otherwise, you may go down a wrong path because you misunderstood something.

**Comment by markus2330** [comment]
I assume that this plugin is for T2. Then a pure checker is enough, so simply fail if the values are not sorted in the wanted directions.

As already said, many details of how the validation should work are missing. Do you want to check if a KeySet is sorted per keys, e.g.:
```
/#0/a
/#1/b
/#2/c
```

or that its values are sorted?
```
/#0 = a
/#1 = b
/#2 = c
```

Important is that you find a clear use case (example) for what this plugin should be used.

**Comment by Gratla** [comment]
I added some more details to the description above 👍

**Comment by kodebach** [comment]
The plugin idea looks good. But I would use `meta:/sorted` instead of `meta:/sort`, because you mark arrays that _are sorted_ but don't instruct the plugin _to sort_ the array. Additionally, for the direction `meta:/sorted/direction` should be used. With Elektra we always prefer a hierarchical structure when possible.
