### ISSUE TITLE
default preferred over fallback

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4329]
## Steps to Reproduce the Problem

```
kdb meta-set spec:/fallback default default
kdb meta-set spec:/fallback fallback/#0 /something
kdb set user:/something something
kdb get /fallback
```

## Expected Result

something

## Actual Result

default

## System Information

- Elektra: master

~The problem was probably introduced in keyname overhaul d9a8478478b0009971a070d2990af0b310abfd7e  src/libs/elektra/keyset.c with this change:~

```diff
diff --git a/src/libs/elektra/keyset.c b/src/libs/elektra/keyset.c
index 379602421..793df64fa 100644
--- a/src/libs/elektra/keyset.c
+++ b/src/libs/elektra/keyset.c
@@ -1731,14 +1673,18 @@ static Key * elektraLookupBySpecDefault (KeySet * ks, Key * specKey)
        Key * ret = 0;
        const Key * m = 0;
 
-       ret = ksLookup (ks, specKey, KDB_O_NOCASCADING);
+       keySetNamespace (specKey, KEY_NS_DEFAULT);
+       ret = ksLookup (ks, specKey, 0);
+
        if (ret) return ret; // return previous added default key
 
        m = keyGetMeta (specKey, "default");
        if (!m) return ret;
-       ret = keyNew (keyName (specKey), KEY_CASCADING_NAME, KEY_VALUE, keyString (m), KEY_END);
+       ret = keyNew (keyName (specKey), KEY_VALUE, keyString (m), KEY_END);
        ksAppendKey (ks, ret);
 
+       keySetNamespace (specKey, KEY_NS_CASCADING);
+
        return ret;
 }
```

This does change the logic a bit, but it is not relevant. See below.

**Comment by kodebach** [comment]
> The problem was probably introduced in keyname overhaul [d9a8478](https://github.com/ElektraInitiative/libelektra/commit/d9a8478478b0009971a070d2990af0b310abfd7e) src/libs/elektra/keyset.c with this change:

Nope, that's not the issue. The function `elektraLookupBySpecDefault` is only called here

https://github.com/ElektraInitiative/libelektra/blob/f2b9d555a2de6da944781bd9edb4a2a877cd3c35/src/libs/elektra/keyset.c#L2060-L2091

and this clearly happens, _after_ we checked `fallback`.

I haven't verified this, but I rather suspect that the `default:/` namespace is picked up during the normal cascading resolution, before `fallback` et. al. are checked. If there is no special handling for `default:/` keys, we probably just return that key since we found a match for the cascading one.

**Comment by markus2330** [comment]
@kodebach Does new-backend influence how this issue can get solved? Further input is required so that this can be a FLOSS issue.

**Comment by kodebach** [comment]
No this is purely in `ksLookup`. The "new backend" changes should have no effect here.

I just checked and the problem is very simple and also easy to find, once you add a test case with a `default:/` key and `meta:/fallback` to `test_spec.c` (which should exist anyway). Then just attach a debugger and step through `ksLookup`.

@markus2330 I think this is easy enough for FLOSS that I shouldn't reveal the details, but if you want me to I can reveal where exactly things go wrong.

**Comment by markus2330** [comment]
What you already know on the top of your head, please say. We do not need to make bugs artificially difficult.

**Comment by kodebach** [comment]
Since the FLOSS course should be a learning experience, I wasn't sure, how much I should reveal.

The issue is that `elektraLookupBySpecNamespaces` is called before we check the `fallback` key:

https://github.com/ElektraInitiative/libelektra/blob/930673f511c864ffd6233b7ab3e1a438c5a9b378/src/libs/elektra/keyset.c#L1996-L2004

Within `elektraLookupBySpecNamespaces` we call `elektraLookupByCascading` again, but with `KDB_O_NODEFAULT`:

https://github.com/ElektraInitiative/libelektra/blob/930673f511c864ffd6233b7ab3e1a438c5a9b378/src/libs/elektra/keyset.c#L1955-L1958

This is what returns the `default:/` key, because this 
https://github.com/ElektraInitiative/libelektra/blob/930673f511c864ffd6233b7ab3e1a438c5a9b378/src/libs/elektra/keyset.c#L2075-L2079
doesn't respect the `KDB_O_NODEFAULT` option.

**Comment by markus2330** [comment]
Thank you for helping here!

> Since the FLOSS course should be a learning experience, I wasn't sure, how much I should reveal.

You can always reveal everything you know and help in any way that people ask you about. Obviously you won't be able to completely help everyone in everything as you cannot possibly do the work of N other people. Admittedly your N is quite high, though. :wink:  Also applying a ready-made patch is a learning experience. Simply don't disguise anything, the FLOSS course should be as realistically as possible. The only thing is that all the information flow must happen openly, giving help via different channels obviously would be cheating.
