### ISSUE TITLE
[DOC] How to change default system: and user: locations

### ISSUE THREAD

**Issue by Kochise** [ElektraInitiative/libelektra#4349]
I'd like to change `Elektra` default locations from `/etc` and `~` to some other locations.

Mostly because working from RAM in a `Docker` lost when shutting down unexpectedly.

Hence those default locations should be redirected to flash storage that is more "persistent".

I've seen about :

https://github.com/ElektraInitiative/libelektra/blob/master/src/include/kdbconfig.h.in

https://www.libelektra.org/manpages/elektra-bootstrapping
https://www.libelektra.org/manpages/elektra-namespaces
https://www.libelektra.org/tutorials/contributing-with-clion#setting-up-the-project

Can `KDB_DB_SYSTEM` be loaded from a configuration file and/or changed at runtime ?

Thank.

**Comment by markus2330** [comment]
The resolver_fm_xhp_x accepts the environment variables HOME and XDG_CONFIG_DIRS, this should do what you want? (There are also other variants, e.g. resolver_fm_xp_x doesn't accept HOME but accepts XDG config dirs.)

**Comment by Kochise** [comment]
That indeed looks like it. Can all the "locations" be changed as well ? Even `spec:` ?

**Comment by markus2330** [comment]
spec: (schemata) isn't included in the XDG standard, so there isn't a env var for it, see #734

`kdb change-resolver-symlink` might be useful for you to change the resolver for all mountpoints.

> Btw, what's the difference between resolver_fm_xhp_x and resolver_fm_hpu_b ?

In very short: The one accepts XDG env vars, the other only HOME and USER.

See [doc/COMPILE.md](https://www.libelektra.org/compiling/compile) for the description of all flags. I agree this should actually be in the resolver's README.

**Comment by Kochise** [comment]
What is the difference between those resolver :

```
resolver_fm_b_b
resolver_fm_pb_b
resolver_fm_hb_b
resolver_fm_hp_b
resolver_fm_ub_x
resolver_fm_xb_x
resolver_fm_xp_x
resolver_fm_xhp_x
resolver_fm_uhb_xb
resolver_fm_hpu_b # default
```

**Comment by markus2330** [comment]
> /workdir # export XDG_CONFIG_DIRS=$HOME/.config;/etc/kdb
> /bin/sh: /etc/kdb: Permission denied

Quoting is incorrect here.

> /workdir # kdb change-resolver-symlink resolver_fm_xp_x

Are you sure this resolver exists on your system?

> How to configure the XDG_CONFIG_DIRS environment variable to behave the same way than using the resolver_fm_hpu_b resolver ?

That is not possible. Only the resolver with x understands the [XDG variables](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html).

Isn't the better option to recompile Elektra so that paths suitable for your system are used? XDG environment variables are only a compatibility feature for people who want XDG support. In many situations they need special considerations (different shells, at, cron, sudo, ...).

**Comment by Kochise** [comment]
Seems like that's what I was looking for, yet didn't quite understood their configuration and usage.

Could you provide a quick functional example ?

**Comment by markus2330** [comment]
I gave an example:

```sh
kdb mount --resolver resolver_fm_xhp_x somefile /somewhere
XDG_CONFIG_HOME=/someplace kdb file user:/somewhere
XDG_CONFIG_DIRS="/otherplace:/fallback" kdb file system:/somewhere
```

What are you missing?

**Comment by Kochise** [comment]
```bash
kdb mount -W --resolver resolver_fm_xhp_x note.xml user:/sw/myorg/toto/#0/current/ xml
XDG_CONFIG_HOME=/root kdb file user:/sw/myorg/toto/#0/current/
XDG_CONFIG_DIRS="/var/tmp:/fallback" kdb file system:/sw/myorg/toto/#0/current/
```

Like that ?

**Comment by markus2330** [comment]
I don't know which paths you want but it could be like that :rocket:

**Comment by Kochise** [comment]
Ok, thank you, I just wanted to be sure about the syntax being right :)

**Comment by h-s-evbox** [comment]
@markus2330 I'm following up the question by @Kochise 
I tried the following and it works 
`
kdb mount -W --resolver resolver_fm_xhp_x note.xml system:/sw/myorg/toto/#0/current/ xml
XDG_CONFIG_DIRS="/var/tmp" kdb file system:/sw/myorg/toto/#0/current/
`
Then to write to the file in `/var/tmp/note.xml`:
XDG_CONFIG_DIRS="/var/tmp" kdb set system:/sw/myorg/toto/#0/current/path2/KEY2 "test"
`
We have to provide the env variable, `XDG_CONFIG_DIRS="/var/tmp"` 

is there an equivalent way to do it (pass this variable) via the API, i.e elektraSetString(..) such that the string gets saved under `/var/tmp/note.xml`? (this is what we want to accomplish, save in a specific location)

**Comment by markus2330** [comment]
If your goal is actually to get "note.xml" from different folders, the `dir:` namespace might be what you want! Then it simply gets the config file from the current working directory, e.g.:

```sh
kdb mount -W /note.xml dir:/sw/myorg/toto/#0/current/ xml
kdb set dir:/sw/myorg/toto/#0/current/sthg value
cd /var/tmp
kdb set dir:/sw/myorg/toto/#0/current/sthg value
```

Programmatically you would use chdir within the program (before you use kdb commands).

**Comment by h-s-evbox** [comment]
Thanks for the response!
We would like however to still be able to specify the directories for the user: and system: namespaces. 
So much like we do with the kdb command:
`XDG_CONFIG_DIRS="/var/tmp" kdb set system:/sw/myorg/toto/#0/current/path2/KEY2 "test"`

we want through the API to do the same. We can try to compile libelektra ourselves, are there compile flags/modifications we can do to accomplish that?
thanks!

**Comment by markus2330** [comment]
One of Elektra's goals is to abstract from configuration sources, i.e. syntax and location of configuration files. So it cannot have a direct way for applications to choose which configuration file they want to use as this would be violation of the abstraction. It is like when you could choose where on your block device some specific file is written, it would violate the abstractions file systems provide.

So I need to need to know more about your use case to help you: What exactly do you want to achieve? Why do you want different config files in different situations? What are these situations? Why do you think it needs to be `user:` and `system:` and not `dir:`? The purpose of `dir:` is to give configuration files from different directories depending on something. The something could be where the application was started (like in .git) or which files are returned (like .htaccess).

As workaround you could use setenv for XDG_CONFIG_DIRS before doing `kdbOpen`. Maybe it is also possible that you require your favorite resolver via contract (@kodebach can you answer that?). But this doesn't sound like a proper solution as it destroys the XDG conformity.

**Comment by kodebach** [comment]
> Maybe it is also possible that you require your favorite resolver via contract

AFAIK this isn't possible right now. It would also go against the idea of separate backends/mountpoints.

To me it seems like Elektra really is not at all a good fit for your use-case. Why do you want to use Elektra?

**Comment by Kochise** [comment]
Maybe a "symlink" of `/etc/kdb` and `$home/.config` would do it, though...

**Comment by kodebach** [comment]
> Here the question is "just" how to change Elektra default user: and system: paths at runtime, while keeping its regular behavior.

Changing the paths at runtime is not really possible, because it is not the intended use-case of Elektra. The idea is that user have a consistent experience of where the config files are. If every application could define it's own paths the, whole thing would be chaos again.

> I don't think `dir:` is suitable in the current scenario, as using `Elektra` in a RAM mounted FS makes it prone to data loss in case of system or power failure. That's why the idea is to redirect `user:` and `system:` paths to a FLASH memory, yet without having to do a specific `Elektra` compilation/package.

This sounds more like you want to have a custom version of Elektra that uses different paths and not like you need your app to set the paths for `user:/` and `system:/` at runtime. So you just want to set the paths once, and not use potentially different paths every time. For that compiling Elektra manually is probably the best option ...

> Maybe a "symlink" of `/etc/kdb` and `$home/.config` would do it, though...

... but, yes using symlinks to replace the standard folders should also work. Since you mentioned different file systems, you could also mount (as in [`mount (8)`](https://linux.die.net/man/8/mount)) the file system directly at those locations.

Of course this will then apply to the whole system not just one application. But if this is okay, then that's the way to go.

Finally, I just saw that you mentioned Docker. If the only problem is that by default, the data inside Docker container is lost, when the container restarts. Then you should really look into Docker volumes. You can simply mount docker volumes at each of the locations that will be used by Elektra.

**Comment by Kochise** [comment]
Well, not the way it works currently, the Docker is ran in RAM in an embedded system yet persistent storage is present in the form of FLASH memory. So the idea is not to use the default/traditional `user:` and `system:` paths in RAM but redirect them into the FLASH storage. It's not trying to mess with the "intended" use-case of `Elektra` as I perfectly understand the "user's consistent experience of where the config files are", which is generally assumed to be located on a persistent storage already, but to adapt to a more "specific" use-case, embedded here, hence perhaps the use of `XDG_CONFIG_DIRS` to perform this gracefully. Or the "symlink" of those specific locations to trick `Elektra`...

**Comment by kodebach** [comment]
Like I said, if you want to change the paths that Elektra uses, it would be easiest if you compiled it yourself. There are CMake variables for the paths you just need to configure them.

If you are developing for an embedded system (where I would assume some constraints on available storage size), I would suggest compiling a custom version of Elektra anyway. There are some plugins/libraries/bindings in the default packages you may not need. There is no need to include these and their dependencies if you don't need them.

**Comment by kodebach** [comment]
Yes, it's not well documented (since the feature is mostly used for testing/during development). It is briefly mentioned in the [docs for compiling](https://www.libelektra.org/compiling/compile). It also comes up in various other tutorials, but isn't explained well and there is also a partial explanation in [the README](https://www.libelektra.org/plugins/resolver) for the `resolver` plugin (this is where we should actually explain it better).

The CMake variables `KDB_DB_SYSTEM` (default `/etc/kdb`) and `KDB_DB_SPEC` (default `/usr/share/elektra/specification`) define the location of `system:/` and `spec:/` files respectively. You should use absolute paths for these. The variable `KDB_DB_DIR` (default `.dir`) is resolve relative to the current working directory when looking up `dir:/` keys.

Keys in `user:/` are a bit more complicated. The location is resolved in two steps. First we need to find the current users home directory. By default the `resolver` (actually `resolver_fm_hpu_b`) plugin will use the `$HOME` environment variable, if that is not available it will use the `/etc/passwd` file, and only if that is also not available will it take the `KDB_DB_HOME` (default `/home`) CMake variable and append the `$USER` environment variable (if that is not set, it fails). Once the home directory is resolved, it appends the CMake variable `KDB_DB_USER` (default `.config`, canbe empty) to get the location of `user:/` keys.

So to get the behaviour you want, `$HOME` would need to be unset and `/etc/passwd` unavailable/unreadable. Since this is unlikely, I would suggest compiling the resolver differently as well. If you set `KDB_DEFAULT_RESOLVER=resolver_fm_u_b` in CMake, the resolver will directly try the `KDB_DB_HOME`+`/`+`$USER`+`/`+`KDB_DB_USER` variant.

We do it this way, to get a different directory (and therefore possible different config) for every user. In a single user system, where you just need a single directory for the `user:/` keys, you an also use `KDB_DEFAULT_RESOLVER=resolver_fm_b_b`. Then the resolve will use `KDB_DB_HOME`+`/`+`KDB_DB_USER` (without adding the username in between). You can then set `KDB_DB_USER=""` and just set `KDB_DB_HOME` to the path you want for your `user:/` files.

> Using symlinks to trick elektra throws an error.

Could you post the error that was thrown? (Maybe in a separate issue) AFAIK there is no reason for symlinks to cause problems.

**Comment by Kochise** [comment]
Or just creating a resolver that can accept user path ?

**Comment by kodebach** [comment]
Yes, creating a custom resolver is also an option, but that is a much bigger task than just re-compiling Elektra.

**Comment by Kochise** [comment]
But then in what should it be any different than `resolver_fm_xhp_x` ?

**Comment by h-s-evbox** [comment]
The attempt to "trick" libelektra using symlinks, I tried the following:

```
# ln -s /var/config/key /etc/kdb/default.ecf

# ls -l  /etc/kdb/default.ecf 
lrwxrwxrwx    1 root     root            15 May 30 09:15 /etc/kdb/default.ecf -> /var/config/key

# kdb set system:/sw/org/toto/#0/current/path2/KEY2 "test"
Sorry, module resolver_fm_hpu_b issued the error C01100:
Resource: No configuration file was there earlier. Now configuration file '/etc/kdb/default.ecf' exists
```

**Comment by markus2330** [comment]
You need to symlink the whole directory.

As the plugin "resolver" needs to rewrite and rename the file to be safe on concurrent writes, symlinking only the file does not work for you. It might work with the plugin "wresolver" but I wouldn't use it as it is much less reliable (e.g. on computer crashes you might have half-written config files). 

best regards

**Comment by Kochise** [comment]
> You can simply mount docker volumes at each of the locations that will be used by Elektra.

Never ever forget to "prune" the volumes upon Docker rebuilding, otherwise the changes are not taken into consideration.
