### ISSUE TITLE
PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP is not portable

### ISSUE THREAD

**Issue by haraldg** [ElektraInitiative/libelektra#439]
While musl libc supports recursive mutexes, the initaliziation macro appears to be specific to glibc, causing a build error:
```
/home/lambda/olinuxino/openwrt/build_dir/target-arm_arm926ej-s_musl-1.1.11_eabi/elektra-0.8.15dev/src/plugins/resolver/resolver.c:52:49: error: 'PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP' undeclared here (not in a function)
```
See this link for the same issue on an other project: https://github.com/Itseez/opencv/issues/5476

**Comment by markus2330** [comment]
Thank you for reporting!

@petermax2 already wrote a solution for that problem (that exists in OS X <= 10.6, too). Later we reverted it, even though we knew it is actually not portable, because we thought it would not effect us anymore.

@petermax2 Can you add your same code again with a `#ifndef PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP`?

**Comment by petermax2** [comment]
I'll check the history and I'll try to resolve this issue.

**Comment by markus2330** [comment]
Thank you! It would be ideal if you try to compile Elektra with `CC=musl-gcc  ./scripts/configure-debian ~e` to see if the problem is gone for musl.

@haraldg You can easily avoid the issue by removing all resolver variants that contain `m` (for mutex).

**Comment by haraldg** [comment]
markus2330 writes:
> @haraldg You can easily avoid the issue by removing all resolver variants that contain `m` (for mutex).

I tried it with:
        -DKDB_DEFAULT_RESOLVER=resolver_l_h_b \
        -DPLUGINS="DEFAULT;-resolver;resolver_l_h_b"

but got an error:
CMake Error at cmake/ElektraCache.cmake:338 (message):
  selected default resolver (resolver_l_h_b) is not selected in PLUGINS,
  please change KDB_DEFAULT_RESOLVER or PLUGINS

**Comment by markus2330** [comment]
@haraldg: Sorry, the workaround does not work as I thought it would. First I will tell you a workaround that works, then I will go into the details why the other one did not work.

A solution that compiles  is to use `wresolver` instead of `resolver`:

`cmake ~e -DKDB_DEFAULT_RESOLVER=wresolver -DPLUGINS="dump;error;wresolver"`
or longer as I tried it:
`CC=musl-gcc CXX=g++ cmake -DKDB_DEFAULT_RESOLVER=wresolver -DPLUGINS="dump;error;wresolver" -DBUILD_TESTING=OFF -DBUILD_FULL=OFF -DBUILD_STATIC=OFF`

which will use the wresolver, a very poor substitute for the real resolver (has no conflict handling and cannot create files or directories, but works even on non-POSIX systems), but should be enough until @petermax2 has fixed the `resolver` for musl.

The problems were:

1.) You cannot combine special markers as DEFAULT together with other plugins, it is only possible to substract plugins (as you did with -resolver).
2.) Currently it is not possible to remove the resolver "resolver" if you want other variants of the resolver. Cmake wont consider any of the resolvers in the folder "resolver".

I updated the docu to better reflect this behaviour (48df1f220ab2b5ac7b649aaba794e5a7efc73ff9). Hopefully, we can improve it for the next release.

**Comment by petermax2** [comment]
@markus2330 the code sequence is already within an `#ifdef`

    #if defined(__APPLE__) && defined(__MACH__)
    static pthread_mutex_t elektra_resolver_mutex = PTHREAD_RECURSIVE_MUTEX_INITIALIZER;
    #else
    static pthread_mutex_t elektra_resolver_mutex = PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP;
    #endif

The problem is that `PTHREAD_RECURSIVE_MUTEX_INITIALIZER` is also not available when compiling with `musl-gcc`. Should we make this section dependent on `#ifdef ELEKTRA_LOCK_MUTEX`? Because all the usages of `elektra_resolver_mutex` within resolver.c are guarded by `#ifdef ELEKTRA_LOCK_MUTEX`.

**Comment by markus2330** [comment]
Yes, it should also be dependent of `ELEKTRA_LOCK_MUTEX`. But if  `PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP` exists should be also checked. The check with __APPLE__ and __MACH__ is not useful (or since 10.7 even wrong).

So it should be:
```
#if defined (ELEKTRA_LOCK_MUTEX) // do we need a lock at all?
#if defined (PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP) // is _NP available?
static pthread_mutex_t elektra_resolver_mutex = PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP;
#else
static pthread_mutex_t elektra_resolver_mutex = PTHREAD_RECURSIVE_MUTEX_INITIALIZER;
#endif
#endif
```

Thanks for your quick response on the weekend!

**Comment by petermax2** [comment]
@haraldg I provided a PR ( #442 ) but you will still need to compile the resolver without the `ELEKTRA_LOCK_MUTEX` variant.

**Comment by haraldg** [comment]
Peter Nirschl writes:
> @haraldg I provided a PR ( #442 ) 

Ok, I will try to test it.

> but you will still need to compile the resolver without the `ELEKTRA_LOCK_MUTEX` variant.

How do I do that?

$ rgrep ELEKTRA_LOCK_MUTEX doc

turns up nothing and as @markus2330 wrote yesterday, removing the m resolvers
from the plugin list is not done easily.

Silly question time:
Since musl actually supports recursive mutexes, wouldn't it be better
to just do mutex initialization the posix way (whatever this would be)?
(See the link to the other project having had the same issue, that I
added to the original post of this issue.)
Is it actually necessary to use *recursive* mutexes? - Maybe the code
could be cleaned up instead ...

I'm in no hurry with openwrt packaging - can't submit the package
before 0.8.15 is released anyway.

**Comment by petermax2** [comment]
@haraldg I am not so familiar with the internals of the resolver and I'm not sure if recursive mutexes are necessary and why.
@markus2330 can you please answer the questions? =)

**Comment by markus2330** [comment]
Yes, within resolvers, recursive locking is necessary. Within a single `kdbGet/kdbSet` multiple resolvers with the same lock may participate, thus we need recursive locking.

We also want to write a global lock plugin, then there would be a single point of lock and no recursive locking would be necessary. The locking would be less granular then, so there is a use-case for both variants of locking.

> to just do mutex initialization the posix way

Yes, the previous locking implementation (from @petermax2) was to use POSIX conforming initialization of recursive locking. @petermax2 can you still add this? Because in older MacOSX and for musl it is still needed.

> can't submit the package before 0.8.15 is released anyway.

Yes, but it would be good if we can make sure that everything works smoothly with 0.8.15.

Compiling the resolver with musl *without* `m` worked for me now. (E.g. with: `CC=musl-gcc CXX=g++ cmake -DBUILD_TESTING=OFF -DBUILD_FULL=OFF -DBUILD_STATIC=OFF ~e`)

**Comment by markus2330** [comment]
or
`CC=musl-gcc CXX=g++ cmake -DBUILD_TESTING=OFF -DBUILD_FULL=OFF -DBUILD_STATIC=OFF -DPLUGINS="ALL;-resolver_fm_b_b;-resolver_fm_hb_b;-resolver_fm_hp_b;-resolver_fm_ub_x;-resolver_fm_xb_x;-resolver_fm_xp_x;-resolver_fm_xhp_x;-resolver_fm_uhb_xb;-yajl;-journald;-crypto;-dbus;-xmltool" ~e && make -j 5`
compiles, too.

BUILD_TESTING and "-yajl;-journald;-crypto;-dbus;-xmltool" was added because Debian has header files which are not compatible with musl. It might work in openwrt.

**Comment by petermax2** [comment]
@markus2330 I checked the history. Yes, I will restore the manual initialization of the recursive mutex.

**Comment by markus2330** [comment]
Thank you!

**Comment by petermax2** [comment]
The resolver compiles using `musl-gcc`with the manual setup of the recursive mutex. Do you want me to restore the CMake definition to:

	add_plugin(resolver
		SOURCES
			${SOURCES}
		LINK_LIBRARIES
			${CMAKE_THREAD_LIBS_INIT}
			${CMAKE_REALTIME_LIBS_INIT}
		COMPILE_DEFINITIONS
			ELEKTRA_VARIANT_BASE=\"\"
			ELEKTRA_VARIANT_USER=\"hpu\"
			ELEKTRA_VARIANT_SYSTEM=\"b\"
			ELEKTRA_PLUGIN_NAME=\"resolver\"
			ELEKTRA_LOCK_FILE
			ELEKTRA_LOCK_MUTEX
	)

or do you want to have no locking as default?

**Comment by markus2330** [comment]
The idea is to completely remove the resolver called "resolver" for the next release. So it should not matter much. But yes, you can restore it. Thank you!

**Comment by haraldg** [comment]
Thanks, compiles now on openwrt. As far as I'm concerned this issue can be closed.
