### ISSUE TITLE
Provide Dockerfile for Jenkins build environment

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#440]
It would be nice to have the exact state like the Jenkins build server. I often encounter errors on the build server, that I can not reproduce on my local machines. By having the same environment (package versions, path configs, etc.) we should be able to reproduce build errors on our local machines.

**Comment by markus2330** [comment]
Thank you, this is a good idea! Lets talk about it the next time. Maybe there is a jenkins plugin for that already?

**Comment by markus2330** [comment]
As workaround, you can download the workspace of jenkins already. You only need a chroot with the same debian version to run the executables.

**Comment by markus2330** [comment]
The mergerequest (and others) from now on generate a file build-information.txt that contains the list of all manually installed packages (w/o their deps) and the complete environment.

http://community.markus-raab.org:8080/job/elektra-mergerequests/ws/build/build-information.txt/*view*/

Additionally, following files are archived with every build (so that subsequent builds do not remove information relevant for you)
`build/build-information.txt, build/doc/doxygen.log, build/Testing/*/DynamicAnalysis.xml`

Please reopen #160 if you want any changes in the build server environment.

**Comment by markus2330** [comment]
What about using https://www.vagrantup.com/?

**Comment by petermax2** [comment]
This could do the job. Should I investigate?

**Comment by markus2330** [comment]
Maybe someone already has experience with vagrant? I am not sure if vagrant should be used for build server nodes, too?

**Comment by markus2330** [comment]
Seems like we already have a docker container: https://github.com/krit0n/libelektra_docker

**Comment by markus2330** [comment]
@krit0n Can you move the repo to ElektraInitiative?

**Comment by markus2330** [comment]
Thanks to @krit0n this is solved now!
