### ISSUE TITLE
libelektra 0.9.10 upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [ElektraInitiative/libelektra#4414]
## Steps to Reproduce the Problem

- cmake build against the 0.9.10 release

```
cmake
..
-DBINDINGS=cpp
-DTOOLS=kdb;
-DPLUGINS=NODEP
-DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/elektra/0.9.10
-DCMAKE_INSTALL_LIBDIR=lib
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_FIND_FRAMEWORK=LAST
-DCMAKE_VERBOSE_MAKEFILE=ON
-Wno-dev
-DBUILD_TESTING=OFF
-DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
```

## Expected Result

Test success

## Actual Result

```
$ /opt/homebrew/Cellar/elektra/0.9.10/bin/kdb plugin-list  | head -n 1
tracer: open(0x600003830420, / = ): system:/module=this plugin was loaded without a config 1

$ /opt/homebrew/Cellar/elektra/0.9.10/bin/kdb plugin-list  | head -n 5
tracer: open(0x600000540240, / = ): system:/module=this plugin was loaded without a config 1
base64
blacklist
blockresolver
c
```

## System Information

- Elektra: 0.9.10
- Operating System: macOS

## Further Log Files and Output

- relates to https://github.com/Homebrew/homebrew-core/pull/105517
build log, https://github.com/Homebrew/homebrew-core/runs/7323076958

I have detailed local build log, but dont feel it is necessary (but can provide upon request)

**Comment by markus2330** [comment]
Thank you for reporting this problem! We definitely have a regression here, I opened the issues #4415 and https://github.com/ElektraInitiative/libelektra/issues/4416.

An obvious problem from the build log is that `kdb plugin-check tracer:` shouldn't have a colon at the end. Is this from our test cases or do you have additional tests?

@[chenrui333](https://github.com/chenrui333) Do you want a patch so that you can release 0.9.10 for brew or would you prefer a new release?

**Comment by mpranj** [comment]
Tracer prints during pluginOpen() and this is shown in the output of kdb plugin-list.

**Comment by markus2330** [comment]
> Tracer prints during pluginOpen() and this is shown in the output of kdb plugin-list.

Yes, this is because of #4415 (a cascading key is used to check if the output should be done).

@chenrui333 A probably easy fix for now would be to exclude the tracer plugin. It is only for debugging/testing. So from your cmake code above the diff would be:
```diff
diff --git a/cmake b/cmake
index 227b79b..f4133cf 100644
--- a/cmake
+++ b/cmake
@@ -1,8 +1,8 @@
 cmake
 ..
 -DBINDINGS=cpp
--DTOOLS=kdb;
--DPLUGINS=NODEP
+-DTOOLS=kdb
+-DPLUGINS="NODEP;-tracer"
 -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/elektra/0.9.10
 -DCMAKE_INSTALL_LIBDIR=lib
 -DCMAKE_BUILD_TYPE=Release
```

I don't know how many other changes you would need in your build scripts, though. So a new release might be the better option.

**Comment by chenrui333** [comment]
> > Tracer prints during pluginOpen() and this is shown in the output of kdb plugin-list.
> 
> Yes, this is because of #4415 (a cascading key is used to check if the output should be done).
> 
> @chenrui333 A probably easy fix for now would be to exclude the tracer plugin. It is only for debugging/testing. So from your cmake code above the diff would be:
> 
> ```diff
> diff --git a/cmake b/cmake
> index 227b79b..f4133cf 100644
> --- a/cmake
> +++ b/cmake
> @@ -1,8 +1,8 @@
>  cmake
>  ..
>  -DBINDINGS=cpp
> --DTOOLS=kdb;
> --DPLUGINS=NODEP
> +-DTOOLS=kdb
> +-DPLUGINS="NODEP;-tracer"
>  -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/elektra/0.9.10
>  -DCMAKE_INSTALL_LIBDIR=lib
>  -DCMAKE_BUILD_TYPE=Release
> ```
> 
> I don't know how many other changes you would need in your build scripts, though. So a new release might be the better option.

Thanks for the direction, let me give it a shot.

**Comment by chenrui333** [comment]
Works for me. Thanks!
