### ISSUE TITLE
ksSearch: does not support cascading

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4415]
#4414 uncovered this problem. It is quite easy to implement if done similar to ksLookup: you basically only need to check if a key is cascading, then do elektraLookupByCascading, and then ksSearchInternal this key. (In #4039 we can take care of optimizations...)

Then there is another problem: the function is basically unable to return errors, which would be needed if no cascading key is found (and also on null ptrs). I would suggest that -1 is an error (like everywhere else) and the insertpos is -insertpos-2.

Who can take this issue? @tucek?

**Comment by kodebach** [comment]
IMO `ksSearch` should not handle the lookup of cascading keys automatically. This would confuse the two separate functionalities. To me `ksSearch` checks whether or not a _specific key_ is contained in a `KeySet` and returns it's position, or the position where it would be inserted. `ksLookup` does a full lookup of keys and resolves cascading keys if needed.

Also, a `KeySet` currently **can** contain a cascading key (*). So in a `ksSearch` a cascading key should be no different, the cascading key might be contained in the `KeySet`, and if not there is an exact position where is would be inserted. Adding an automatic lookup makes the result ambiguous. You'd need to check the key at the returned index to find out, if the cascading key was resolved or not.

Finally, this would be against the principle of minimal API. If you want to search for a cascading key with lookup, you can already do `ksSearch (ks, ksLookup (ks, key, 0))`. Changing `ksSearch` doesn't enable anything new, so it's clearly not minimal.

---

(*) and the latest plan to change that only intends to restrict `KeySet`s to either contain only cascading keys or to contain only non-cascading keys IIRC.

**Comment by markus2330** [comment]
I agree with you on the goals (minimal API) but I disagree in this case about the conclusion. With current API `ksSearch (Key*)`  allows to pass cascading keys. We cannot avoid that. At least in one case, someone accidentally (?) did so and thought it would work.

If someone passes a cascading key, we have two options:

1. immediately return an error
2. do the right thing (the cascading lookup) and only return an error if it did not work

So we need the error case anyway (-insertpos-2).

As we already know, at least one person expected "2." should happen. I don't see any reason why it shouldn't happen (If you want more argumentation about that, read #3938 again :wink:).

> ksSearch (ks, ksLookup (ks, key, 0))

Actually we could do an alias the other way round:

`ksLookup -> ksAtCursor(ksSearch())`

> and the latest plan to change that only intends to restrict KeySets to either contain only cascading keys or to contain only non-cascading keys IIRC.

No, it was KeySet should be either meta or config. Cascading can be completely prohibited, they do not make sense in KeySets anymore. (Thanks to your `default:` namespace, which is a much cleaner solution.)

Would be amazing if you could write a decision about that. IIrc we actually already agreed about it but forgot to write it down. This is why it is important to write down the decisions.

Writing down the decisions is also important so that we think about all implications. One implication we also forgot about (at least in ksSearch) is that e.g. searching meta in a config KeySet can and should also immediately fail. (And not return arbitrary positions where it actually cannot be added.)

**Comment by kodebach** [comment]
> do the right thing (the cascading lookup) 

IMO that's not the right thing, because the lookup is a behaviour of `ksLookup` and not something intrinsic to a `Key` with `KEY_NS_CASCADING`.

See also #3598 and more importantly #3597. If we have `KeySet`s with only cascading keys. Then a lookup makes no sense and `ksSearch` must simply search for the cascading key directly. It is explained in #3598, but the reason to have such `KeySet`s is when you want to use a `KeySet` as a hierarchical string-key-value structure without relation to the KDB. The `KEY_NS_CASCADING` is the best choice here, because all other namespaces have distinct meaning attached.

> at least one person expected "2." should happen. 

IMO that's a documentation issue, not a problem with the implementation. 

> No, it was KeySet should be either meta or config.

Nope, see #3598

> This is why it is important to write down the decisions.

It's more why some people say ["GitHub stale bot considered harmful"](https://drewdevault.com/2021/10/26/stalebot.html)

> One implication we also forgot about (at least in ksSearch) is that e.g. searching meta in a config KeySet can and should also immediately fail. (And not return arbitrary positions where it actually cannot be added.)

It may not have been explicitly mentioned, but I was always assuming that all operations with mismatched namespaces between `Key` and `KeySet` would immediately return an error. 

> Actually we could do an alias the other way round:
> 
> `ksLookup -> ksAtCursor(ksSearch())`

That would make more sense, yes.

----

One way of fixing this would be to introduce another namespace. I'll call it `data:/`, but it definitely needs a better name.

Then we have 3 types of KeySet:
1. `meta:/`
2. `data:/`
3. other namespaces with lookup

With these rules:
- Appending a cascading key to a keyset is always an error.
- When a keyset is empty (either after `ksNew` or when all keys are removed again), any key can be appended.
- Otherwise, `keyNamespace (key) == ksAtCursor(ks, 0)` must hold for `ksAppendKey (ks, key)` to work.
- When you search for a cascading key, in type 3 a lookup with namespace resolution is performed. In the other types, you get an error.

**Comment by markus2330** [comment]
> IMO that's not the right thing, because the lookup is a behaviour of ksLookup and not something intrinsic to a Key with KEY_NS_CASCADING.

There seems to be a misunderstanding. Cascading keys (i.e. keys from namespace KEY_NS_CASCADING) **only** purpose is  to be looked up. Also see glossary.

> as a hierarchical string-key-value structure without relation to the KDB

This sounds a bit like misuse of cascading keys and KeySet.

>> alias: ksLookup -> ksAtCursor(ksSearch())
> That would make more sense, yes.

Ok, agreed. Can you write up the decision, please?

Btw. I hope the idea with the aliases will work out. I am still not totally convinced as aliases give very severe restrictions in compatibility. They basically need to stay identical forever. Do we have a decision about the aliases?

> One way of fixing this would be to introduce another namespace

I am open to that. But I hope we agree that this is a post-1.0 thing?

**Comment by kodebach** [comment]
> Cascading keys (i.e. keys from namespace KEY_NS_CASCADING) only purpose is to be looked up. Also see glossary.

That's definitely not how they are used throughout the code base. There are many places where some data needs to be stored and a `KeySet` is used. Often with cascading names, because no other namespace really fits.

Also see [Hyrum's Law](https://www.hyrumslaw.com/).

> This sounds a bit like misuse of cascading keys and KeySet.

Well that depends. IMO since `libelektra-core` is separate and has no knowledge of the KDB at all, it is okay.

> Can you write up the decision, please?

Will to, when I find time (for this alias and aliases in general).

> I am still not totally convinced as aliases give very severe restrictions in compatibility.

That's why we need to use them very sparingly. The current examples `ksDup` and this `ksLookup` are fine. AFAICT any change that would break the alias, would be a breaking change to the underlying function anyway.

> I am open to [adding a new namespace]. But I hope we agree that this is a post-1.0 thing?

Like I said, there are already some places that use `KeySet`s with cascading keys as a data structure. If we prevent inserting cascading keys into `KeySet`s, we need a replacement. I don't see why we should misuse one of the other namespaces, if introducing a new one would be about the same amount of work.

**Comment by markus2330** [comment]
> That's definitely not how they are used throughout the code base. There are many places where some data needs to be stored and a KeySet is used. Often with cascading names, because no other namespace really fits.

Which places? It could be misuse because no other namespace was available.

> IMO since libelektra-core is separate and has no knowledge of the KDB at all, it is okay.

If it is unrelated to Elektra's goals, it is a "trying to please everyone".

>  Will to, when I find time (for this alias and aliases in general).

:partying_face: 

> That's why we need to use them very sparingly.

:+1: 

> If we prevent inserting cascading keys into KeySets, we need a replacement.

Or it simply unveils bugs/misuses.

> cascading mountpoints/backends

#4428

**Comment by kodebach** [comment]
> It could be misuse because no other namespace was available.

If you define "cascading" as "only for lookup" then it clearly is.

> Or it simply unveils bugs/misuses.

Unlikely. Using the `KeySet` as a generic key-value data structure is pretty handy. If we don't want this, we probably need a different structure (probably also based on the OPMPHM) that plugins and libraries can use. Otherwise we get lots of poorly written linked-list-like structures, since everything else is much harder in C.

However, if we introduce a pure hash-map key-value structure, we loose the hierarchical nature of the `KeySet`. 

> Which places [use cascading keys]?

With a quick search I found:

- `src/libs/opts/opts.c`: Yes, I know I wrote that code, but I didn't have anything else to use. The way `opts` works and passes data between processing steps, it definitely needs a hash map. I'm not 100% certain we need the full hierarchical structure of a `KeySet`. Maybe this use could be replaced with another hash map implementation. It is certainly easier with a `KeySet` since most data in `opts` is based around key names.
- `src/libs/pluginprocess/pluginprocess.c`: Uses `KeySet` as a basic key value structure that can be serialised and transferred to another process. Kind of irrelevant because this lib is obsolete.
- In various places, a cascading key (often `keyNew ("/", KEY_END)`) is used as an `errorKey`. I don't really have a good alternative here apart from randomly choosing another namespace.
- Many plugin tests use cascading keys for config or testdata. In most cases I don't even understand why. For example, there is a `kconfig` test that expects cascading keys to be returned from the plugins `get` function.

**Comment by markus2330** [comment]
> Using the KeySet as a generic key-value data structure is pretty handy. If we don't want this, we probably need a different structure (probably also based on the OPMPHM) that plugins and libraries can use.

I am not against using KeySet as general-purpose data-structure. I only dislike the idea of several semantics for cascading keys.

I think the easiest fix is to have an extra namespace if someone wants to use the KeySet as generic data structure and dislikes the idea of using any of the other namespaces. This namespace would be ignored by kdbGet/kdbSet and cascading lookups.

Can we then agree on ksSearch behaving like ksLookup? It would be good to get a fix in the next release to repair tracer etc.

**Comment by kodebach** [comment]
> Can we then agree on ksSearch behaving like ksLookup? 

Yes, if there will be a separate namespace e.g. `data:/` then doing a lookup in `ksSearch` is fine.
