### ISSUE TITLE
drop cascading mountpoints/backends?

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4428]
As brought up by @kodebach in #4415 we actually misuse cascading keys to do something else for cascading mountpoints. Cascading keys should have the semantics to search in one namespace after the other (i.e. cascading).

Cascading mountpoints, however, is a mountpoint for several namespaces, a feature that has nothing to do with the English word "cascading". I propose to remove cascading mountpoints in favor of explicit mounts per namespace. The implications would be:

- `kdb mount` would need to be executed for every namespace separately. This is probably even an advantage as we could drop the complicated rules what an "absolute path" and a "relative path" means and at least for dir: and system: simply resolve relative paths relative to `pwd` (where  `kdb mount` was executed) and disallow relative paths.
- `kdb spec-mount` would have several `mountpoint` specifications for each namespace, e.g.:
```
[]
mountpoint = 1 # we define a mountpoint here
user:/path = myapp.toml
system:/path = /etc/myapp/myapp.toml
dir:/path = .myapp.toml
```

@flo91 what do you think?

**Comment by kodebach** [comment]
Generally, I'm totally in favour of removing cascading mountpoints. I always found them strange a bit of a hack. The code would certainly be simpler without them.

> at least for dir: and system: simply resolve relative paths relative to pwd (where kdb mount was executed) and disallow relative paths.

Something went wrong with this sentence...

> `kdb spec-mount` would have several `mountpoint` specifications for each namespace, e.g.:

I like the idea, but not the syntax. From your proposed syntax the full key names would be `meta:/user:/path`, `meta:/system:/path`, `meta:/dir:/path`. That's just confusing.

Also using `path` is very specific to file-based backends. We need a more generic config.

I propose this scheme:
- `meta:/mountpoint` defines the backend plugin used by the mountpoint defined in the keys of the spec below.
- Below `meta:/mountpoint/system`, `meta:/mountpoint/user` and `meta:/mountpoint/dir` are the configs for `system:/`, `user:/` and `dir:/` mountpoints. The keys below `meta:/mountpoint/default` are used, in case any of the other 3 aren't provided.
- The the config in `meta:/mountpoint/*` will be the same as what the backend plugin uses in `system:/elektra/mountpoints/_/definition`. (see `doc/dev/mountpoints.md` in `new-backend` branch)
- Parts of the config (e.g. `positions`) may be inferred by the spec and don't need to be provided.

For example:

```ini
[]
mountpoint = backend
mountpoint/default/path = myapp.toml
mountpoint/user/path = myapp/config.toml
mountpoint/system/path = /etc/myapp/myapp.toml
mountpoint/dir/path = .myapp.toml
```

or for a hypothetical `postgres` backend:

```ini
[]
mountpoint = postgres
mountpoint/default/connection = postgresql://user:secret@localhost/kdb
mountpoint/system/connection = postgresql://root:bettersecret@localhost/system_kdb
```

In practice, the `kdb spec-mount` tool could then merge the `meta:/mountpoint/user` et al. sections with the `meta:/mountpoint/default` section and hand that together with the list of plugins inferred from the `meta:/` keys in the spec to `kdb mount`.

At this point `kdb mount` would call the backend plugin with the data received from `kdb spec-mount`. From this partial definition and full list of plugins the plugin would then construct it's `system:/elektra/mountpoints/_/definition` and return it to `kdb mount`. Finally, `kdb mount` creates the actual mountpoint. Then `kdb spec-mount` continues with the next namespace.

> **Note**: What I call `kdb mount` and `kdb spec-mount` shouldn't be the tools themselves, but functions in the new library used by them. That way other tools can achieve the same results.

**Comment by flo91** [comment]
I'm also in favor of removing the cascading mountpoints.
The concept can take some time for beginners to understand and with more generic backends this concept tends to get even more confusing.
For the database backend, the solution proposed by @codebach looks promising.
Besides from different credentials for different namespaces, the data can even be stored at different locations. (e.g. using a local SQLite DB for user data and a remote PostgreSQL DB for system data).


To cover the currently used namespaces:

- The `proc`-namespace is only for in-memory keys, so no new backend, esp. no database backend, should be used for that namespace.
- The `spec`-namespace can be useful for using with a database, so that the specification can also be stored in a database table instead of a specfile.
- For the `dir`-namespace, a local database (like SQLite) could be an interesting option.
If we just store the whole database in the directory, it's basically just a special case of a file-based mount.
So the semantics remain the same, the file is directly stored in the directory (or the sub-directory `.dir`).
If we want to allow other actual locations of the database (e.g. using the same local database for multiple directories or even using a database stored on a remote host), we would have slightly different semantics.
We can store the path + hostname (or ip-address) for which a key should be valid, but this is not the same as storing the information directly in the directory.
The same path on the same host can refer to different actual content at different points in time, if different volumes are mounted on the same mountpoint.
On the other hand, one volume can be mounted on different mountpoints.
So the keys in the `dir`-namespace would no longer be used based on the actual content, but on the mountpoint in the filesystem we are accessing.
Alternatively we can use a file in the current working directory where the backend-configuration is specified, so instead of placing the actual configuration-file in the directory, a backend-plugin configuration setting (e.g. giving the location of the database, credentials and table to use) is stored there. With this approach, a full backend configuration must be provided in every directory for which the `dir`-namespace should be used.
A simple solution would be to only allow the classical file-based storage plugins for the dir-namespace, but that obviously also reduces the versatility of Elektra.
But that's is a different topic and not directly related to the use of cascading mounts or separate mounts for each namespace.
Please correct me if I misunderstood or missed something here.
- Regarding the `user`-namespace, we can store the mountpoint-configuration in the home-directory (or a subdirectory), but also use a distinction based on a unique user name or id.
For the database plugin, the criteria could be `user@host`.
I would prefer that a connection string (or more generally a backend-configuration) is used to mount a database table in the `user`-namespace and this table is used for the current user, so that the user-conf is not bound to a concrete host. We also would not need to store in the database which key is valid for which user, as the mapping of the `user`-namespace to a database-table is done by the mountpoint-configuration. That would also be more similar to the behavior of file-based backends where different files are used for different namespaces and the namespaces for the keys are not specified in the actual configuration-file.
- For the `system`-namespace, a connection string that specifies a database to use is sufficient and than this database/table is used system-wide.

For now, the most promising solution seems to be using a configuration-file in the current directory for `dir` and in the home-directory for `user`, but storing a backend-configuration (e.g. connection string for databases) instead of the actual configuration like done with the file-based backends. If this was already specified or other concepts were evaluated, please inform me about it.


Another aspect I found is that in https://github.com/ElektraInitiative/libelektra/blob/new-backend/doc/dev/kdb-operations.md is stated:

> explicit default:/ mountpoints are illegal They can only exist via cascading mountpoints. This is so that default values can be checked and validated by plugins.

This would imply that if we remove cascading mountpoints, `default:/` mountpoints are also not possible anymore.

**Comment by kodebach** [comment]
> This would imply that if we remove cascading mountpoints, `default:/` mountpoints are also not possible anymore.

That's just a matter of definition. The goal was that you cannot define a custom `default:/` mountpoint. Not with tooling and not by manually editing `system:/elektra/mountpoints`. My reasoning for this was that `default:/` keys are supposed to come from the specification defined in `spec:/` keys. So the `default:/` backends should also come from the specification.

There are two basic options now:
1. Allow `default:/` mountpoints in `system:/elektra/mountpoints`, i.e. `libelektra-kdb` reads them like any other mountpoint. But don't allow them in the `kdb mount` tooling. This way it's very easy to let `kdb spec-mount` create the `default:/` mountpoint, but in theory you could also create other `default:/` mountpoints that break the link to the specification.
2. Prohibit `default:/` mountpoints in tooling and in `system:/elektra/mountpoints`, i.e. `libelektra-kdb` entirely rejects them like it does now. This enforces the link to the specification, but we'd have to find a way allows `libelektra-kdb` to infer the mountpoints from the specification.

Option 1, is IMO the better (and simpler) solution.

----

Regarding the other namespaces: I'm not sure we have this specified anywhere, but my understanding was that

- `dir:/` keys are tied to the current working directory (i.e. same output from `getcwd(3)`/`pwd(1)` means same keys)
- `user:/` keys are tied to the current user or the current home directory. This is not quite clear because it depends on the resolver, but on a normal system `$HOME`, `$USER`, etc. should be "linked" so it doesn't matter much.
- `system:/` keys are the same for the entire system.

So you don't need to store files in `$PWD` or `$HOME` for `dir:/` and `user:/` keys. Creating separate tables for every user/directory, or adding a column with the directory/user the key belongs too, should be good too. However, to protect credentials, it could make sense to create separate file to store the configuration with the appropriate POSIX permissions. But I think this should be an optional feature, something like

```
# inline password
[]
mountpoint/user/connection = postgresql://user:password@localhost/kdb

# external password
# passwordfile must be created by the user, is read by backend plugin and it's entire contents are used as the password
[]
mountpoint/user/connection = postgresql://user@localhost/kdb
mountpoint/user/passwordfile = path/to/file/with/password
```

**Comment by markus2330** [comment]
> For the dir-namespace, a local database (like SQLite) could be an interesting option.

Yes, it would be interesting, for any namespace. I am not sure if it should be put together with the "database" backend, as it is somewhat hybrid database and file-based.

@flo91 ideally create new issues for such topics, it is only vaguely related to removal of cascading mountpoints.

> Regarding the other namespaces: I'm not sure we have this specified anywhere

It is specified in https://www.libelektra.org/manpages/elektra-namespaces#elektra-namespaces7----namespaces

It can be easily found by typing "namespaces" in the search field.

@kodebach are the default: mountpoints within cascading mountpoints used for something? This is probably simply unnecessary and wrongly introduced when the default: namespace came into existence? Afaics default: should be exclusively for keys managed by the spec plugin and the keys should never be persisted.

**Comment by kodebach** [comment]
> I am not sure if it should be put together with the "database" backend, as it is somewhat hybrid database and file-based.

I'd say SQLite is clearly a database backend, because 1) it is probably accessed in a similar way to other SQL-based backends 2) the actual file handling is done by SQLite and not by Elektra.

The only thing that could be useful from the file-based backend is the "resolving part" of `resolver`, i.e. getting absolute paths from relative paths or filenames.

> > Regarding the other namespaces: I'm not sure we have this specified anywhere
> It is specified in [link to man page]

Not relevant here, but this a good example of my opinion on man pages a primary docs in #4436.

>  are the default: mountpoints within cascading mountpoints used for something? This is probably simply unnecessary and wrongly introduced when the default: namespace came into existence? Afaics default: should be exclusively for keys managed by the spec plugin and the keys should never be persisted.

To clarify: IIRC `default:/` mountpoints are not implemented (fully/correctly) yet. However, `default:/` mountpoints are what's needed to make the validation (e.g. with `type`) work for `meta:/default` values from `spec:/` keys. Which is bug/problem already discussed in various issues.

> the keys should never be persisted.

As stated in https://github.com/ElektraInitiative/libelektra/blob/new-backend/doc/dev/kdb-operations.md, not all namespaces are treated the same (search for "Influence of namespaces:"). This includes for example, not persisting `default:/` or `proc:/` keys.

**Comment by markus2330** [comment]
> The only thing that could be useful from the file-based backend is the "resolving part" of resolver, i.e. getting absolute paths from relative paths or filenames.

I disagree here.

1. It is not "only" but resolving is a lot (many variants due to many operating systems, conventions etc.)
2. Also the cache/update would be handled (i.e. if kdbGet needs to do something etc.)

About the semantic differences in conflict handling Elektra vs. SQlite we will maybe read in @flo91 thesis. This topic is quite interesting. Whatever the better approach, imho it makes sense from uniformity point of view to also use Elektra's conflict handling on databases, if possible (and imho it should be possible on single-file databases implemented as library). What the better approach is, we need an implemented conflict handling in a database plugin and an analysis thereof, so further discussions do not make sense at this point. A SQlite plugin is nice-to-have anyway.

> To clarify: IIRC default:/ mountpoints are not implemented (fully/correctly) yet. However, default:/ mountpoints are what's needed to make the validation (e.g. with type) work for meta:/default values from spec:/ keys. Which is bug/problem already discussed in various issues.

Can you please create one issue which summarizes what exactly needs to be done in the new-backend branch so that "type" works correctly?

**Comment by kodebach** [comment]
I don't disagree that it should be possible and would be nice to have an SQLite storage plugin for the existing file-based backend plugin. But I'm not sure this is the best way to spend time right now. IMO it is more important to have a proper database backend plugin to validate the idea of backend plugins. If this database plugin is SQL based and agnostic to the actual database, then SQLite should work just as well as Postgres, MySQL, etc. So it would simply be more time-efficient to focus on the database plugin first.

> what exactly needs to be done in the new-backend branch so that "type" works correctly?

That's a bit complicated. I can't say exactly what needs to be done. But the start point would be to generate `default:/` and `proc:/` mountpoints from cascading ones (i.e. the ones created by `spec-mount`). Those would then receive the `default:/`/`proc:/` keys to validate etc. From there I'd have to test and see myself what is and isn't working...

**Comment by markus2330** [comment]
> That's a bit complicated. I can't say exactly what needs to be done.

Are there test cases failing so that we cannot forget about it? Otherwise, could you please add test cases or write an issue?
