### ISSUE TITLE
yajl: remove global variable

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4467]
In yajl we unfortunately introduced a global variable (yajl/yajl_parse.c:static elektraCursor itKs;) which needs to be removed.

See also #4466.

@flo91 can you describe how it can be removed?

**Comment by kodebach** [comment]
I had a quick look and it seems `elektraCursor itKs` was a quick and dirty workaround, since `yajl` relied on the internal cursor in `KeySet`s for communication between different functions. So changing this will require reworking some of these functions. This probably means creating a custom struct to wrap a `KeySet *` and a `elektraCursor` and pass that around instead of a `KeySet *`.

**Comment by flo91** [comment]
The triage by @kodebach summarizes the issue very well.
As the parameters of the callback-functions are given by yajl,the information must be passed as part of a `void *`
