### ISSUE TITLE
[FLOSS] Switch from probot/stale to github/stale

### ISSUE THREAD

**Issue by kodebach** [ElektraInitiative/libelektra#4476]
We should switch from the current Probot based "stale issue bot" to [the one provided by GitHub](https://github.com/marketplace/actions/close-stale-issues).

Not only is the Probot based one, seemingly no longer maintained (see https://github.com/probot/stale/issues/385 and https://github.com/probot/probot.github.io/pull/376), but the GitHub one also has a lot more options. Including [one option](https://github.com/actions/stale#close-issue-reason) which allows closing issues as "not planned" instead of "completed".

**Comment by kodebach** [comment]
@markus2330 The old Probot based bot also seems to be buggy. It closed both #3318 and #1610 even though the last comment wasn't the "I mark this issue stale" from the bot.

**Comment by stefnotch** [comment]
I can confirm that probot/stale is still installed.
The config file exists at https://github.com/ElektraInitiative/libelektra/blob/master/.github/stale.yml 
And since it's an *app*, it would also have to be uninstalled.

And the improved [stale issues *action*](https://github.com/marketplace/actions/close-stale-issues) still needs to be installed.

### Installing the new stale issues action

After a fair bit of searching, I actually found the right documentation page
https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues

This can probably be done in a fork, and a pull request can be created with this.


### Uninstalling probot/stale
 
By going to https://github.com/apps/stale and pressing configure.

Then one would select libelektra
![image](https://user-images.githubusercontent.com/10220080/196413809-35507b32-0de3-4eca-a8db-d2f740eedfed.png)

And hit the x button
![image](https://user-images.githubusercontent.com/10220080/196413828-fbda9249-788e-40d4-80d3-57d7dcbdd57c.png)

And finally press uninstall

**Comment by markus2330** [comment]
Thank you for the detailed analysis. Let us first make a config file for the new one, then I'll do the steps to add the new one and remove the old one.

**Comment by Janldeboer** [comment]
Is creating the config file an appropriate  change for a pull request in T1?
It does not completely fit into any of the 3 described problems, but it it is still closely related I suppose.

**Comment by markus2330** [comment]
I uninstalled probot/stale as described above.

> And the improved [stale issues action](https://github.com/marketplace/actions/close-stale-issues) still needs to be installed.

Is there anything else to be done?

**Comment by 0x6178656c** [comment]
> > And the improved [stale issues action](https://github.com/marketplace/actions/close-stale-issues) still needs to be installed.
> 
> Is there anything else to be done?

I don't think so. I think that the only manual step needed was removing the old probot/stale.

The action has been created automatically: https://github.com/ElektraInitiative/libelektra/actions/workflows/stale.yml

**Comment by kodebach** [comment]
Is there a reason, we didn't end up using the `close-issue-reason: not_planned` option?

**Comment by markus2330** [comment]
> Is there a reason, we didn't end up using the close-issue-reason: not_planned option?

What do you mean? We switched.

**Comment by kodebach** [comment]
Yes we switched to the GitHub stalebot action. But I don't see the `close-issue-reason: not_planned` option in https://github.com/ElektraInitiative/libelektra/blob/master/.github/workflows/stale.yml. 

That means the bot still closes issues as "completed" not as "not planned". See for example https://github.com/ElektraInitiative/libelektra/issues/2991#event-7908260243, which was closed today.

**Comment by 0x6178656c** [comment]
@kodebach Thanks for pointing this out. I should have read this thread more carefully.

It seems that the option `close-issue-reason` is set automatically to `not_planned` in v6. I still added it so be explicit, though.
