### ISSUE TITLE
ksSearch: should support cascading

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4477]
#4414 uncovered this problem. It is quite easy to implement if done similar to ksLookup: you basically only need to check if a key is cascading, then do elektraLookupByCascading, and then ksSearchInternal this key. (In #4039 we can take care of optimizations...)

Then there is another problem: the function is basically unable to return errors, which would be needed if no cascading key is found (and also on null ptrs). I would suggest that -1 is an error (like everywhere else) and the insertpos is -insertpos-2.

**Comment by kodebach** [comment]
Actually, I would

1. Move the full code of `ksLookup` into `ksSearch`
2. Rewrite that code (i.e. all the functions called by `ksLookup`/`ksSearch`) to return a `elektraCursor` instead of a `Key *`.
3. Implement `ksLookup` as `ks->array[ksSearch(...)]` plus error handling

That should still be pretty simple. The functions in `ksLookup` all eventually call back into `ksLookup` with different arguments.

For the "error case", I'd actually say:

- `ret >= 0`: Key was found at position `ret`
- `ret == -1`: Key was not found and cannot be inserted into this KeySet
- `ret < -1`: Key was not found, but could be inserted at `-ret - 2`

I wouldn't call it an error, because it is a valid result for `ksSearch`. Also the `-1` case will in future apply to more cases, when we implement #3598, e.g. if you search for `user:/foo` in a keyset that contains `meta:/` keys we should return `-1`, since `ksAppendKey` would fail.
