### ISSUE TITLE
ni removes part of names using cascading export

### ISSUE THREAD

**Issue by tom-wa** [ElektraInitiative/libelektra#448]
```
% cat /tmp/test.ini
test = testval

% kdb mount /tmp/test.ini system/mytestmount ni

% kdb ls /mytestmount
system/mytestmount/test

% kdb export /mytestmount ni
;Ni1
; Generated by Nickel Plugin using Elektra (see libelektra.org).

mount/test = testval

%
```

works fine using kdb export system/mytestmount

**Comment by markus2330** [comment]
Thank you for reporting! The problem is that ni does not expect a cascading key as parent key (line 109: `keyName(cur)+parentSize`+the length calculation directly afterwards).

Related to that bug:
What about adding `keyGetRelativeName(Key, Key)` and its size pedant `keyGetRelativeNameSize(Key, Key)` that handles cascading/non-cascading names correctly?

With the event of global plugins I think we will need it in more places than "just" in storage plugins.

**Comment by tom-wa** [comment]
You are right, i've just noticed that i have the same issue with the ini plugin
want me to do it ?

**Comment by markus2330** [comment]
I think the best proceeding is to first fix it in the new INI plugin #405, and if the solution is generic and works well, we fix all other occurrences. We should add a test-case with cascading export/import in the shell-testcases.

**Comment by markus2330** [comment]
@tom-wa Any progress here, did you find a good solution in the INI plugin?

**Comment by tom-wa** [comment]
more like a workaround, but:
```
	char *name = NULL;
	if(keyName(section)[0] == '/' && keyName(key)[0] != '/')
	{
		size_t offset = strchr(keyName(key)+1, '/')-keyName(key);	
		name = (char *)keyName(key)+strlen(keyName(section))+offset+1;
	}
	else
	{
		name = (char *)keyName(key)+strlen(keyName(section))+1;
	}
```

**Comment by markus2330** [comment]
What about putting it into a elektraKeyGetRelativeName function?

**Comment by markus2330** [comment]
Does this code also handle keyName(section) == "/"? We really should put it to a library..

**Comment by markus2330** [comment]
Seems to work now! (For both ini and ni)
