### ISSUE TITLE
profile plugin: allow profile to be passed by command-line

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4481]

**Comment by kodebach** [comment]
It should already be possible to add something like this to the specification of an application (mounted at `spec:/sw/org/myapp/#0`:

```
[profile]
opt/long = profile
```

Then you can use `--profile=myprofile` and `gopts` should already set `proc:/sw/org/myapp/#0/profile = myprofile`.

That being said, I think the profile handling should be integrated into the `spec` plugin. That way it would be active by default and we don't get possible ordering problems between `spec` and `profile`.

**Comment by markus2330** [comment]
@hannes99 can you check if this works for `kdb`?

> That being said, I think the profile handling should be integrated into the spec plugin. That way it would be active by default and we don't get possible ordering problems between spec and profile.

Please refrain from off-topic suggestions. In this specific case I don't think it is a good proposal, as some applications don't want profiles and the main advantage of plugins is that you can either include or exclude them as preferred. If you think it is a good idea anyway, please create a separate issue for the proposal.

**Comment by kodebach** [comment]
> Please refrain from off-topic suggestions.

Not sure how this was off-topic, since it concerns the `profile` plugin...

> some applications don't want profiles

Could be configurable via metadata in the spec, e.g. instead of assuming `/sw/_/_/#/profile` specifies a profile, we could have a `meta:/profile` key that says "this key defines the active profile for the keys below".

>  If you think it is a good idea anyway, please create a separate issue for the proposal.

I don't think it is that important. I just thought combining with `spec` would simplify things. If `profile` is separate we need another hook for it, since it is a global plugin in the current system.

**Comment by markus2330** [comment]
>   Not sure how this was off-topic, since it concerns the profile plugin...

The topic is: "profile plugin: allow profile to be passed by command-line" not "general discussion about profile plugin". I hided the off-topic post. (And also this one.)
