### ISSUE TITLE
spec: handle metadata correctly

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4496]

**Comment by kodebach** [comment]
We should do something, but I'm not sure failing with an error is a good option. Somehow `spec` needs to now what metadata to keep and what to remove. This needs more investigation.

A problematic example:
- `spec:/foo` has both `meta:/type = unsigned_long_long` and `meta:/something = else`
- `user:/foo` does not exist in the KDB
- `user:/foo` is added between `kdbGet` and `kdbSet`
- now during `kdbSet` the metakeys are added by `spec`
- when we get to `toml` the `meta:/type` should still exist, because it influences `toml`, but if we keep `meta:/something` as well there would be an error according to this proposal

There might be no way around defining the meta keys a storage plugin supports within the contract.

**Comment by markus2330** [comment]
spec only removes what it added. So either `meta:/type = unsigned_long_long`

1. was added first by toml, then spec will only check consistency of the type but doesn't add or remove it (so toml will get the metadata again later)
2. was not added by toml, then spec will copy it and remove it before it reaches toml
3. was added by the application, then spec will not remove it and toml will get it

But I agree, careful investigation of all these possibilities must be done.

**Comment by kodebach** [comment]
Okay let me expand on my example.

In my original example, option 2 of your options would be the case. But what if the application in question is `kdb` then the example would be:

- `spec:/foo` has both `meta:/type = unsigned_long_long` and `meta:/something = else`
- `user:/foo` does not exist in the KDB
- `user:/foo` is added via `kdb set user:/foo 123`
- now during `kdbSet` the metakeys are first added by `spec` to make validation work
- then before we get to `toml` the metakeys are removed again by `spec`
- therefore `toml` doesn't think of the key as an integer, and instead assumes a string (Important note at the end)

Because of the spec, a user would expect that we get a TOML file like this:

```toml
foo = 123
```

But if `spec` simply removes everything it added, which would include `meta:/type`, then we get this file:

```toml
foo = "123"
```

Even worse, on the next `kdbGet` the `spec` plugin will complain about a mismatch of `meta:/type`, because `toml` will report `meta:/type = string`, but we expect `meta:/type = unsigned_long_long`.

> **Note** This example might not apply exactly to `toml`. I'd have to check, but I think `toml` may try to infer the TOML type from the value, if no `meta:/type` is found. There are multiple reasons why this is not the solution.
> 1. What if the spec had `meta:/type = float` instead? `toml` would still infer an integer, but the user might not care whether the config says `123` or `123.0`, but the next `kdbGet` will still have a type mismatch.
> 2. There could be other storage plugins (e.g. binary ones, or databases) where `meta:/type =  unsigned_long_long` vs `meta:/type = unsigned_long` makes a difference. If the plugin infers types, it would have to choose one. If the spec contains the other one that's a problem.


> For storage plugins, however, the situation is simple: they fail if they get something they don't understand.

I agree on that. But it only works, if we make sure that the plugin doesn't receive extra data and also receives all the data it needs.

**Comment by markus2330** [comment]
Yes, spec needs to make sure that only the right meta data ends up at the storage plugins. And the storage plugins should fail if they don't understand some of the metadata.

**Comment by kodebach** [comment]
> Yes, spec needs to make sure that only the right meta data ends up at the storage plugins.

Which is why I said

> There might be no way around defining the meta keys a storage plugin supports within the contract.

So do we now agree that just making storage plugins fail on unknown metadata is not the whole solution and that spec must have some knowledge about the storage plugin that was used?

**Comment by markus2330** [comment]
I've split the issues about spec and storage plugins.

Further discussions about spec when it is time (Tomislav starts collecting requirements for spec).

**Comment by kodebach** [comment]
This issue should not just be about `type`. The same issue can apply to other metadata, `type` is just the obvious example.

**Comment by markus2330** [comment]
If there is further metadata where such problems exist, please list them.

**Comment by kodebach** [comment]
It is impossible to list them, because this obviously depends on the storage plugins. If you want an example, there are `tomltype` and `order`. Both influence the behaviour of `toml`. It might be less common to have those in the spec, but it could still be that the TOML file needs a certain order, or something must be a table, etc.

Basically, to be on the safe side, anything that _can_ be processed by the storage plugin _should not_ be removed by spec.

**Comment by markus2330** [comment]
Exactly, we can simply solve the issue by requiring that internal/* stuff (tomltype should be there) and order is not present in spec. The question is if there is metadata that has valid use cases in spec and has meaning in storage plugins. For comments there is also no problem, as "comments" are called description in spec. So type is probably the only one, hence I used this as title.

**Comment by kodebach** [comment]
> So type is probably the only one, hence I used this as title.

probably != definitely

> tomltype should be there

The reason it's not there AFAIK is that `meta:/internal/*` is for things the user should not need to know about and also should never want to use with `kdb meta-set`. However, using `tomltype` with `kdb meta-set` makes a lot of sense, if you want a certain TOML output. The same is true for `order`.

> we can simply solve the issue by requiring that internal/* stuff (tomltype should be there) and order is not present in spec.

Did you even read my comment? I provided a case where `tomltype` and `order` might be needed and you just say "Exactly, let's forbid that"

I'll provided a more concrete example, because that has helped you understand in the past:

For `order` it could simply be the case, that the author of the spec wants the config file to be more readable, so they mandate a certain order between the keys. A similar argument can be made for `tomltype`. For example, when we expect a string to contain `"` and `\` then we may want to use `tomltype = string_literal` to avoid escape sequences. Also [this example](https://github.com/ElektraInitiative/libelektra/tree/master/src/plugins/toml#simple-tables) in the README of `toml` shows that without `tomltype` you will get something like this:

```toml
common.a = 0
common.b = 1
common.c = 2
```

In many cases using the table syntax would be more readable:

```toml
[common]
a = 0
b = 1
c = 2
```

This could be defined in the specification.

For both `order` and `tomltype` the reason could also be that there is another application that needs to read the config file, but it doesn't use Elektra. Maybe the application needs a certain order or format.


Finally, a different example is `unit/base`. For some types of number using hexadecimal or maybe binary just makes more sense.
