### ISSUE TITLE
[FLOSS] Kotlin Binding Link broken

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4525]
https://www.libelektra.org/bindings/readme the link "kotlin" is broken. Why is this not detected by the dead-link checker?

**Comment by 0x6178656c** [comment]
After taking a pretty deep dive into this, I think I know the cause for this.

Firstly, I am not sure if the external link checker is used to check links in the website at all. It might only be used to check the files in `/doc` but I am not sure of this.

The reason why the link is broken is because it refers to the wrong path (probably due to an oversight after a renaming):

https://github.com/ElektraInitiative/libelektra/blob/bef233527a5ab40a2f05cf5424f99bd8becb1dfa/src/bindings/README.md?plain=1#L21

Should read

```yaml
  - [kotlin](jna/libelektra-kotlin) Kotlin binding (based on JNA)
```

What I do not fully understand is why this is an external link in the first place. That is, why does the link not simply go to "/jna/kotlin" (in the broken version). Note that the link remains an external link even after correcting the path, although it then no longer is broken.

To understand how the structure of the website is built one would have to dive into the build process (probably): https://github.com/ElektraInitiative/libelektra/blob/master/src/tools/website/resources/grunt-tasks/grunt-create-website-structure.js

Do you think this warrants further investigation?

**Comment by markus2330** [comment]
Thank you, great investigations! There is clearly some introduction in the link checker missing! Do you want to write such a (short) introduction in doc/contrib/links.md as H2 or H3 as you are now getting more and more familiar?

> Firstly, I am not sure if the external link checker is used to check links in the website at all. It might only be used to check the files in /doc but I am not sure of this.

./doc/markdownlinkconverter gets called for the files included in Doxygen, so doc/Doxyfile controls it.

> The reason why the link is broken is because it refers to the wrong path (probably due to an oversight after a renaming):

:+1:

> What I do not fully understand is why this is an external link in the first place.

As you already found out it is because of the website. The website automatically converts links to documents that are not listed in src/tools/website/resources/structure.json.in to external links to GitHub.

There is ./scripts/link-checker but it only checks external links that are collected from the markdownlinkconverter.
