### ISSUE TITLE
[FLOSS H0] Continuous Delivery to AUR

### ISSUE THREAD

**Issue by deoknats861** [ElektraInitiative/libelektra#4544]
Hello,
I recently read about the problem that the sources on the AUR are outdated and versions conflict with cmakes' build process (#4539, #4302).
This made me think if continuous delivery of a new release to the AUR would be possible or even is considered as a next step for this project. Said in advance, I never have maintained a package in the AUR, so I do not know how many further (manual) steps are required to update the package resources. However, CD would kind of resolve the version problem and keep the repository up to date.
 
Let me know if my thoughts are feasible or if this could even be a task/project for this semester :)

**Comment by markus2330** [comment]
Thank you for reporting this problem! There are definitely tasks to be done on this topic! I don't think it is a project, though.

@Eiskasten is the maintainer of AUR, so it should be coordinated with him. He also has experience with AUR.

**Comment by Eiskasten** [comment]
First of all, there are two version of Elektra in the AUR, the one which is prefixed with "lib" is the more current version and maintained by me. This one has no git version but a release version only. In my opinion this is possible without a large effort, it should be enough to create a Docker image which just generates a PKGBUILD file with updated checksums and version from a template, run `makepkg` and pushes it to the Git repository of the AUR. Verifying the resulting PKGBUILD is mandatory in order to keep up to date and let the pipeline fail in case it results in a broken PKGBUILD. We only need an Elektra account for the AUR which is not a big deal.
