### ISSUE TITLE
[FLOSS H0] Linux Distro

### ISSUE THREAD

**Issue by Dynamichost96** [ElektraInitiative/libelektra#4546]
Hey as I am new to Elektra and Linux is there a recommended Linux distro for newbies :)

**Comment by kodebach** [comment]
Ubuntu is normally a good bet for beginners and should be well supported by Elektra.

If you are currently working on Windows you might also want to [try WSL](https://learn.microsoft.com/en-us/windows/wsl/install). We have a [tutorial](https://github.com/ElektraInitiative/libelektra/blob/master/doc/tutorials/contributing-windows.md) as well. Although I would recommend trying Visual Studio Code not the full Visual Studio as is explained in the tutorial. VS Code should be easier to set up, because it has [native support for WSL](https://code.visualstudio.com/docs/remote/wsl).

Also if you are using macOS, that should work out of the box too. There might be less tutorials, but we have a few macOS build servers so everything should work. To set things up, you need [Homebrew](https://brew.sh/). Then just you can just install the dependencies like it happens in the CI config:

https://github.com/ElektraInitiative/libelektra/blob/930673f511c864ffd6233b7ab3e1a438c5a9b378/.github/workflows/macOS.yml#L77-L117

**Comment by Dynamichost96** [comment]
I will try WSL looks very promising and easy to set up, Thank you for the fast answer :)
