### ISSUE TITLE
[FLOSS] scripts/dev/reformat-shell doesn't reformat all shell files

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4559]
example of non-included file: src/tools/qt-gui/elektra-qt-editor.in

**Comment by 0x6178656c** [comment]
## The problem

Currently `reformat-shell` leverages the built-in discovery feature of `shfmt` provided by the `-f --find` option.

Experimentally I verified that `shfmt` discovers files with an extension `.sh` and an appropriate shebang **as long as the filename of the script has no extension** (if the extension is anything else than `.sh` then `shfmt` assumes this is not a shell script). (You can also check the code: https://github.com/mvdan/sh/blob/master/cmd/shfmt/main.go)

## Finding shell scripts

I am aware of two methods to check whether a file is a shell script (essentially the same as `shfmt`'s discovery feature without the restriction on extensions)

1. Check if the file extension is `.sh`
2. Check if the first line is a shebang for a shell

I wrote a short shell script which only checks the first line of files for the shebang-check. However this is quite inefficient. It would probably be easier to simply grep the entire file and have an exclude-list for files which mention the shebang someplace else than the first line.

```sh
#!/bin/sh

elektra_dir="/libelektra"

IFS=''

files_from_shebang=$(mktemp /tmp/files_from_shebang.XXX)

find "$elektra_dir" -type f | while read file; do
	first_line=$(head -1 "$file")
	if echo "$first_line" | grep --quiet '^#!\(/bin/\|/usr/bin/env \)[a-z]*sh$'; then
		printf '%s\n' "$file" >> "$files_from_shebang"
	fi
done

wc -l "$files_from_shebang"

files_from_extension=$(mktemp /tmp/files_from_extension.XXX)

find "$elektra_dir" -type f -name '*.sh' | while read file; do
	printf '%s\n' "$file" >> "$files_from_extension"
done

wc -l "$files_from_extension"
```

I got the output

```text
152 /tmp/files_from_shebang.eDa
88 /tmp/files_from_extension.qB1
```

Now it is very interesting that no set of discovered shell scripts is a subset of the other. In Python I checked:

```
>>> len(from_extension.difference(from_shebang))
36

>>> len(from_shebang.difference(from_extension))
100

>>> len(from_shebang.union(from_extension))
188
```

## Files currently not checked

As stated above, the files not discovered by `shfmt` are those which have a shebang but a file extension other than `.sh`.

The command

```sh
cat /tmp/files_from_shebang.eDa | grep '\..\+$' | grep -v '\.sh$'
```

gives

```text
/libelektra/src/tools/qt-gui/elektra-qt-editor.in
/libelektra/src/tools/kdb/gen/templates/highlevel.mount.sh.mustache
/libelektra/src/tools/fuse/fuse.in
/libelektra/tests/shell/include_common.sh.in
/libelektra/.git/hooks/update.sample
/libelektra/.git/hooks/commit-msg.sample
/libelektra/.git/hooks/pre-applypatch.sample
/libelektra/.git/hooks/pre-rebase.sample
/libelektra/.git/hooks/pre-merge-commit.sample
/libelektra/.git/hooks/post-update.sample
/libelektra/.git/hooks/prepare-commit-msg.sample
/libelektra/.git/hooks/pre-receive.sample
/libelektra/.git/hooks/pre-push.sample
/libelektra/.git/hooks/applypatch-msg.sample
/libelektra/.git/hooks/pre-commit.sample
/libelektra/.git/hooks/push-to-checkout.sample
/libelektra/scripts/dev/run_nocheckshell.in
/libelektra/scripts/dev/run_memcheck.in
/libelektra/scripts/dev/run_nokdbtests.in
/libelektra/scripts/dev/run_all.in
/libelektra/scripts/dev/run_checkshell.in
/libelektra/scripts/completion/install-sh-completion.in
/libelektra/scripts/change-resolver-symlink.in
/libelektra/scripts/configure-firefox.in
/libelektra/scripts/randoop/randoop.in
/libelektra/scripts/change-storage-symlink.in
/libelektra/scripts/kdb/mount-java.in
/libelektra/scripts/kdb/elektrify-getenv.in
/libelektra/scripts/kdb/elektrify-open.in
/libelektra/scripts/kdb/backup.in
/libelektra/scripts/kdb/list-tools.in
/libelektra/scripts/make-source-package.in
```

(The files in the `.git` directory should probably be omitted.)

But these certainly are more than specified in the `additional_files` variable in `reformat-shell`

https://github.com/ElektraInitiative/libelektra/blob/0e2ec762d9d032f075fae22cafebf991a2c43a81/scripts/dev/reformat-shell#L35-L52

## Conclusion

The discovery feature of `shfmt` misses shell scripts which have a shebang but an extension other than `.sh`.

Since maintaining lists like the `additional_files` in `reformat_shell` is prone to errors, I suggest investigating further in efficient ways to populate a list of shell scripts.

Of course, one could simply extend the variable `additional_files` by the ones currently missing as well.

**Comment by markus2330** [comment]
Thank you, great work so far!

I agree, `additional_files` is error prone.

What about restricting to a known set of shebangs and let the CI fail for others?

**Comment by 0x6178656c** [comment]
> What about restricting to a known set of shebangs and let the CI fail for others?

I think this is the best solution. Furthermore, we should only allow `#!/bin/sh` and `#!/usr/bin/env <shell>` for maximal portability.

However, one thing I am not sure about are the scripts in `tests/shell`. Most of them start with `@INCLUDE_COMMOND@` which I guess is a preprocessor macro. For instance,

https://github.com/ElektraInitiative/libelektra/blob/d1a8f828fea2ad77c612df62009764beb397d273/tests/shell/run_all.sh#L1

If you prepend this with a shebang,

```sh
#!/bin/sh

@INCLUDE_COMMON@ 
```

then you would end up with

```sh
#!/bin/sh  # from the file

#!/bin/sh  # from the include
```

Do you think this is a problem?

Note that removing `#!/bin/sh` from [tests/shell/include_common.sh.in](https://github.com/ElektraInitiative/libelektra/blob/d1a8f828fea2ad77c612df62009764beb397d273/tests/shell/include_common.sh.in) would then lead to **that** file not being found when looking for shell-shebangs.

Perhaps for this type of special cases a list of shell scripts without shebang might be an acceptable solution too, similar to the `additional_files` in the current discovery.

TODO for me: Create list of shell scripts that don't start with a (valid) shebang.

**Comment by markus2330** [comment]
> we should only allow #!/bin/sh and #!/usr/bin/env <shell> for maximal portability.

I fully agree :+1: 

> Do you think this is a problem?

No, it is simply a comment there. We simply document that the shebang is just for file detection and the file is not meant to be executed. Same for scripts/dev/run_env etc.

> Perhaps for this type of special cases a list of shell scripts without shebang might be an acceptable solution too, similar to the additional_files in the current discovery.

Also fine by me. But if we can get rid of exceptions I would prefer it.

> src/tools/fuse/docker/build_container.sh

Here we simply replace /bin/bash -> /usr/bin/env bash

**Comment by kodebach** [comment]
`awk` should be fine, it is already used in some places. Ideally the script would be POSIX-compliant, but if it runs on all of our CI servers it should be fine. Your example seems POSIX too me, but to be sure you could check with the GNU version of awk (`gawk`) with the `--posix` option. The only thing I couldn't find any information on is the `NFS==0`.

> In the above I have used an include-list approach for the find command.

I think including everything by default makes more sense. Otherwise it is too easy to add a new file and not have it included in the check. We could just use `git` to list all files in the repo. That would already cover the obvious exclusions (`.git`, build folder, etc.).

```sh
git ls-tree --full-tree -r --name-only HEAD
```

**Comment by 0x6178656c** [comment]
> `awk` should be fine, it is already used in some places. Ideally the script would be POSIX-compliant, but if it runs on all of our CI servers it should be fine. Your example seems POSIX too me, but to be sure you could check with the GNU version of awk (`gawk`) with the `--posix` option. The only thing I couldn't find any information on is the `NFS==0`.

Thanks, that is very helpful. Indeed, `NFS` is wrong. I meant `FNR` which gives "The input record number in the current input file."  It should be `FNR==1` for the first line. I think this is then POSIX.

> > In the above I have used an include-list approach for the find command.
> 
> I think including everything by default makes more sense. Otherwise it is too easy to add a new file and not have it included in the check. We could just use `git` to list all files in the repo. That would already cover the obvious exclusions (`.git`, build folder, etc.).
> 
> ```shell
> git ls-tree --full-tree -r --name-only HEAD
> ```

That is an excellent suggestion. I agree that is is error prone to maintain either an include or exclude list, so simply using whatever Git tracks is a fantastic solution.

Putting everything together I have come up with

```sh
#!/bin/sh

git ls-tree --full-tree -r -z --name-only HEAD \
        | xargs -0 awk 'BEGIN {pattern = "^#!(/bin/sh|/usr/bin/env [a-z]*sh)$"} FNR==1 && $0 ~ pattern {print FILENAME}'
```

**Comment by markus2330** [comment]
Superb solution, thank you both! Can you put this to scripts/dev?

> if it runs on all of our CI servers it should be fine

If it can be POSIX, it is very much favored as it avoids later troubles, e.g. with FreeBSD: #4396 or several times with MacOS.  But the above script seems to be POSIX anyway.

**Comment by 0x6178656c** [comment]
> Can you put this to scripts/dev?

At first I was reluctant to create a function, since filenames can contain pretty much any character.

But since the [coding guideline](https://github.com/ElektraInitiative/libelektra/blob/master/doc/CODING.md) states

> `find . -not -regex '[/.a-zA-Z0-9_-]*'` should not find your file names

this is probably safe.

New file: https://github.com/ElektraInitiative/libelektra/blob/b9a97d96c8e1f414dd0076a373dcd9a76291e593/scripts/dev/list-shell-scripts
