### ISSUE TITLE
[FLOSS] LGTM.com deprecation

### ISSUE THREAD

**Issue by joni1993** [ElektraInitiative/libelektra#4577]
According to [this post](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/) LGTM.com will be shut down in December 2022. 
CI pipeline should be adopted accordingly - either by using GitHub code scanning (as advised in the post) or evaluating other solutions.

**Comment by markus2330** [comment]
Thank you for telling! Is GitHub code scanning easy to setup? Is there some migration help?

> evaluating other solutions.

It is not either/or. We can integrate several static analysis tools.

**Comment by atmaxinger** [comment]
On this topic, SonarCloud is free for open source projects. We could also integrate that.

**Comment by kodebach** [comment]
> Is GitHub code scanning easy to setup?

AFAICT we just have to setup a new GitHub action: https://github.com/github/codeql-action

I assume the default config, will do something similar to what LGTM does.

> SonarCloud is free for open source projects.

Seems like that can also be configured as a GitHub action. Although it's a bit more complicated, because the have separate actions for [C/C++](https://github.com/marketplace/actions/sonarcloud-scan-for-c-and-c) and [other stuff](https://github.com/marketplace/actions/sonarcloud-scan). Also for Java they want you to run the SonarQube plugin through Maven or Gradle during a normal build.

Another option would be to integrate SonarCloud into Jenkins. But I'd advise against that. SonarQube scans normally take a while to do for bigger projects and our Jenkins is already a bit overloaded as is.

**Comment by kodebach** [comment]
Seems the issue has magically solved itself: #4751
