### ISSUE TITLE
Broken artifact links failing PR builds

### ISSUE THREAD

**Issue by atmaxinger** [ElektraInitiative/libelektra#4624]
The following links in `doc/INSTALL.md` seem to no longer work. 
This breaks at least #4554 and #4574, both are rebased on the current master branch.

```
doc/INSTALL.md:178:0 https://build.libelektra.org/job/libelektra/job/master/lastSuccessfulBuild/artifact/artifacts/debian-bullseye-mingw-w64-i686/elektra.zip
doc/INSTALL.md:179:0 https://build.libelektra.org/job/libelektra/job/master/lastSuccessfulBuild/artifact/artifacts/debian-bullseye-mingw-w64-x86_64/elektra.zip
```

**Comment by flo91** [comment]
I can confirm the issue.
For now, I added the two links to the linkchecker whitelist to get the PR #4492 merged.
But of couse, the links should be fixed or adapted in the `doc/INSTALL.md` file, so that
people who read the documentation about installation get working links.

I suggest to leave this issue open until the links are fixed and removed from the whitelist.

After my PR #4492 gets merged, you should be able to merge other PRs if they are again rebased to the updated master branch.

**Comment by atmaxinger** [comment]
I think you mean #4506?

**Comment by markus2330** [comment]
I suspect we do not need to solve this issue (other then temporarily put the links to allowlist): once the javadoc issue is gone, master builds will hopefully succeed again and then these artifacts should be available again.

**Comment by markus2330** [comment]
Unless there was a Jenkins upgrade and these links actually changed, @mpranj @lukashartl?

**Comment by mpranj** [comment]
I also suspect there is nothing to do here: I think it's just that jenkins cleaned up old artifacts after _n_ builds or days and the link went gone.
As soon as a new master build is successful the links should be OK again.

**Comment by kodebach** [comment]
> I think it's just that jenkins cleaned up old artifacts after n builds or days and the link went gone.

Would be pretty weird if something called `lastSuccessfulBuild` is automatically deleted without a newer successful build. Especially, since the last successful build was only 10 hours before this issue was opened and there were only 2 failed builds between the successful build and this issue being opened. 

A separate oddity is that `doc/INSTALL.md` uses release builds/packages or even distro package repos, but for MinGW we just link to the latest `master` build. We should probably link to the [latest release build](https://build.libelektra.org/job/libelektra-release/lastSuccessfulBuild/artifact/artifacts/debian-bullseye-mingw-w64-x86_64/elektra.zip) instead (Note: this link works, even though the build is older).

Did someone maybe manually clean up space recently? I think there were some failed builds because of "no disk space left".

**Comment by markus2330** [comment]
The current setting in Jenkins is that artefacts are kept 31 days but only 5 builds. I would have expected that it is 5 successful builds but maybe it is not so?

> A separate oddity is that doc/INSTALL.md uses release builds/packages or even distro package repos, but for MinGW we just link to the latest master build. We should probably link to the [latest release build](https://build.libelektra.org/job/libelektra-release/lastSuccessfulBuild/artifact/artifacts/debian-bullseye-mingw-w64-x86_64/elektra.zip) instead (Note: this link works, even though the build is older).

I think this is a good idea. We should also add these binaries to the releases. Then we don't need the link to the latest artifacts. @mpranj what do you think?

> Did someone maybe manually clean up space recently?

I only pruned docker images.
