### ISSUE TITLE
kdb tests fail

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4642]
In https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4602/9/tests testcpp_kdb fails with following error:

```
[ RUN      ] kdb.get_set
unknown file: Failure
C++ exception with description " Sorry, 3 warnings were issued ;(
[1] Sorry, module kdb issued the warning C01320:
	Interface: Calling the kdbGet function for the backend plugin ('backend') of the mountpoint 'system:/elektra' has failed during the STORAGE phase.
	Mountpoint: system:/elektra
	Configfile: /home/jenkins/workspace/libelektra_PR-4602/config/kdb/system/elektra.ecf
	At: /home/jenkins/workspace/libelektra_PR-4602/src/libs/elektra/kdb.c:1569
[2] Sorry, module kdb issued the warning C01320:
	Interface: The STORAGE phase of kdbGet() has failed. See warnings for details.
	Mountpoint: system:/elektra
	Configfile: /home/jenkins/workspace/libelektra_PR-4602/config/kdb/system/elektra.ecf
	At: /home/jenkins/workspace/libelektra_PR-4602/src/libs/elektra/kdb.c:1588
[3] Sorry, module kdb issued the warning C01100:
	Resource: Could not open configuration file /home/jenkins/workspace/libelektra_PR-4602/config/kdb/system/elektra.ecf for reading. Reason: No such file or directory
	Mountpoint: /
	Configfile: 
	At: /home/jenkins/workspace/libelektra_PR-4602/src/libs/elektra/errors.c:189
Sorry, module kdb issued the error C01200:
Installation: Bootstrapping failed, please fix '/home/jenkins/workspace/libelektra_PR-4602/config/kdb/system/elektra.ecf'. If the error persists, please report this bug at https://issues.libelektra.org.
Mountpoint: /
Configfile: 
At: /home/jenkins/workspace/libelektra_PR-4602/src/libs/elektra/kdb.c:384
" thrown in the test body.
```

The error itself is quite unclear and could be improved.

The problem itself maybe related to tests that run in parallel and shouldn't. testcpp_kdb itself has the property kdbtests set but maybe some other new kdb test hasn't? @kodebach any idea?

**Comment by kodebach** [comment]
> The error itself is quite unclear and could be improved.

IMO that's mostly an issue of the formatting. If you remove all the debug info and just take the important information, it's much clearer:

```
Installation Error (C01200): Bootstrapping failed, please fix '/home/jenkins/workspace/libelektra_PR-4602/config/kdb/system/elektra.ecf'. If the error persists, please report this bug at https://issues.libelektra.org.

Warnings:
  - Interface Warning (C01320): Calling the kdbGet function for the backend plugin ('backend') of the mountpoint 'system:/elektra' has failed during the STORAGE phase.
  - Interface Warning (C01320): The STORAGE phase of kdbGet() has failed. See warnings for details.
  - Resource Warning (C01100): Could not open configuration file /home/jenkins/workspace/libelektra_PR-4602/config/kdb/system/elektra.ecf for reading. Reason: No such file or directory
```

The order of the warnings is still a bit weird, but that's because second "Interface Warning" would be an error outside the bootstrap process. Then it would make sense again.

> testcpp_kdb itself has the property kdbtests set but maybe some other new kdb test hasn't?

Could be. I didn't add any such tests. Maybe @atmaxinger did?

> kodebach any idea?

Well `At: /home/jenkins/workspace/libelektra_PR-4602/src/libs/elektra/errors.c:189` points to `elektraTriggerWarnings`. That suggests the `error` plugin is in use, because I don't think `elektraTriggerWarnings` is used anywhere else.

**Comment by atmaxinger** [comment]
> Maybe @atmaxinger did?

No, I didn't touch those tests.

**Comment by markus2330** [comment]
add_msr_test_plugin (and add_msr_test) adds the property kdbtests. So it cannot be src/plugins/error/README.md. Any other test using the error plugin? (I think there is but I cannot find it)

**Comment by kodebach** [comment]
> So tests/kdb/CMakeLists.txt should set the property within add_kdb_test.

Pretty sure it does:

https://github.com/ElektraInitiative/libelektra/blob/78485f055f8b62a97e59b7a9ae4848310310e54c/tests/kdb/CMakeLists.txt#L75

**Comment by markus2330** [comment]
So it must be something else, any other tests that don't have kdbtests set?

**Comment by kodebach** [comment]
1. This is once again one of those weird Jenkins runs, where tests failed, but all pipeline stage and jobs are marked as successful.
2. Because of that, can't see which of the two failed tests was run first. It could be that the other failing test (which does use the KDB) created some very broken state on disk and that broken the following test.

**Comment by markus2330** [comment]
This is very easy to check: to run one after the other and see what happens.
