### ISSUE TITLE
Permissions to re-run checks

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4669]
As reported in #4658, FLOSS participants don't seem to have the permission to re-run checks. They have the permission "triage". According to https://docs.github.com/en/rest/checks/runs#rerequest-a-check-run they "must have the checks:read permission on a private repository or pull access to a public repository". Isn't "pull access" less than "triage"?

Anyone knows how to fix this? Until then, please help retriggering checks.

(@flo91)

**Comment by markus2330** [comment]
Last year this problem didn't exist. Seems like they try to push people to GitHub Enterprise. For me it is rather one more point to restart investigating GItLab.

**Comment by kodebach** [comment]
I don't think we should discuss GitLab just because of this. Not least because many other things we can better utilise our time for.

> Last year this problem didn't exist.

I would rather assume we just missed it. Either nobody tried or people just didn't say they can't trigger reruns. I remember I did trigger a few reruns, when I reviewed PRs.

---

In any case, as a solution we could probably set up something similar to the "jenkins build libelektra please" detection.
