### ISSUE TITLE
type: check shouldn't be locale dependent

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4674]
Given `/tests/type/latitude` of type double, change user:/tests/type/latitude to 47.571217 with e.g. LANG=de_AT.UTF-8.

## Expected Result

That validation succeeds. I.e. it must ignore the locale.

## Actual Result

```
Validation Semantic: The type 'double' failed to match with string '47.571217'
At: libelektra/src/plugins/type/type.c:96
```

**Comment by kodebach** [comment]
`type` just tries to apply `elektraKeyToDouble`, which just uses `strtod`. There is some info we could provide, `strerror`/`errno` could be printed and we could print whether there are leftover characters (which is also a failure condition). However, the `elektraKeyTo*` functions don't really have a way of returning such error information.

Since the string `"47.571217"` does successfully convert with `strtod`, I can only guess that this is a locale issue. Can you try to run `setlocale(LC_ALL, "C")` before the `kdbGet` (or whatever you called)?

If your locale is set to e.g. German, `strtod` would only parse `"47"` and leave `".571217"` untouched, because it would expect a `,` instead of a `.`. That would be reported as a failure by  `elektraKeyToDouble` and therefore `type`.

**Comment by markus2330** [comment]
I was afraid so. I clarified the top-post about this bug. I cannot reproduce it with `kdb`:

```
kdb mount type.toml user:/tests/type toml type
kdb set user:/tests/type/latitude 47.571217
kdb meta-set user:/tests/type/latitude type double
```

Succeeds also with `de_AT.UTF-8`.

**Comment by kodebach** [comment]
AFAICT all C/C++ applications should start up as if `setlocale (LC_ALL, "C")` was called. So the bug would only occur in applications that explicitly change their locale.

In any case, we should change our conversion functions to not be locale-sensitive.
