### ISSUE TITLE
restyle checker problems

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4687]
> It appears to me that the restyle check always fails because of the underscore in the filename. When escaping the underscore `\_` it complained it shouldn't have the escaping backslash - now with the escaping-backslash removed (which is wrong i think) it says it should be something totally wrong (`Extend check*doc.sh to work for contrib and tutorials *(@Joni1993)\_`)

_Originally posted by @joni1993 in https://github.com/ElektraInitiative/libelektra/issues/4634#issuecomment-1313993608_

**Comment by markus2330** [comment]
Yeah, the restyler's suggestions are sometimes wrong, feel free to report this problem to prettier. I can reproduce the problem here: https://prettier.io/playground

```
- Extend check_doc.sh to work for contrib and tutorials _(@Joni1993)_
- Extend check*doc.sh to work for contrib and tutorials *(@Joni1993)\_
```

Is obviously not a good suggestion.

**Comment by kodebach** [comment]
> Is obviously not a good suggestion.

IMO this is a fine suggestion. I would prefer the following, but I assume that's an issue with prettier's parser. It probably thinks the first two `_` belong together and form an emphasised section.

```patch
-- Extend check_doc.sh to work for contrib and tutorials _(@Joni1993)_
+- Extend check\_doc.sh to work for contrib and tutorials *(@Joni1993)*
```



However, the issue is that this suggestion also happens:

```patch
-- Extend check\_doc.sh to work for contrib and tutorials _(@Joni1993)_
+- Extend check_doc.sh to work for contrib and tutorials _(@Joni1993)_
```

I don't see any reason why this should ever be suggested (why remove the escape character?), but it definitely is a problem because it causes a suggestion cycle.
