### ISSUE TITLE
Adding a storage plugin for xfconf

### ISSUE THREAD

**Issue by leo-unglaub** [ElektraInitiative/libelektra#47]
Hey,
would it be possible for you to add a dummy storage plugin that simply passes the data to the xfconf tool. This way, i a user is running Xfce, they would be able to use there default settings system if available.

![screenshot - 08112014 - 04 10 33 pm](https://cloud.githubusercontent.com/assets/734684/3876976/a80c1816-2161-11e4-8209-afd97d938e29.png)

Thanks and greetings
Leo (from Debienna)

**Comment by grindhold** [comment]
heyho @markus2330 ! i chatted you up on vala bindings this afternoon after you talk. it seems that the GI-bindings have been deprecated for some reason. However they are a necessary intermediate step in order to obtain vala bindings. now i am confused. if the GI-bindings aren't here to stay, i probably shouldn't bother generating a VAPI from them.

I already succeeded in generating a VAPI-file from the GI-files generated in master. But now comes the tough part: cleanly integrating it into cmake. Please tell me more about the GI-binding deprecation so i have a understanding whether doing the contribution is worthwile.

**Comment by markus2330** [comment]
The GI-bindings were only deprecated for python and lua because the SWIG bindings were better (especially performance). There is nothing wrong with them otherwise. There is no plan to remove them. We can relabel them if you have a better word than "deprecated" :-)

The Vala binding would, of course, not be "deprecated"! So it is definitely worthwhile and I would love to see this binding.

**Comment by markus2330** [comment]
@grindhold any update?

**Comment by grindhold** [comment]
I could post the manually generated vapi for now, but i did not yet get around to integrate stuff into CMake. I'll post the file in a Gist and paste it here.

**Comment by grindhold** [comment]
Here you go 
https://gist.github.com/grindhold/cf784de3faf8ef6c9fbcf1ce1e24e493

**Comment by markus2330** [comment]
Thank you, that is great!

How did you test it?

Did you try to copy the cmake from the other bindings? (e.g. https://github.com/ElektraInitiative/libelektra/blob/master/src/bindings/gi/lua/CMakeLists.txt)

**Comment by markus2330** [comment]
The discussion went off-topic. Please reopen new issues if you are interested in a xfconf plugin or open a PR when GI-bindings of Vala are finished (simply copy CMake of other GI-bindings should suffice, adding tests would of course be better).
