### ISSUE TITLE
deploy website for braches

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4803]
As reported in #4795, and fixed in 15332afa06038652c8fb075c240aa895d88c5764, a corrupted file [src/tools/website/resources/structure.json.in](https://github.com/ElektraInitiative/libelektra/commit/15332afa06038652c8fb075c240aa895d88c5764#diff-b6fe711e3a8436bc6febd51bc7026a23b81be7bd1b3b42a9414ff46ef3be93ed) can lead to a broken website, without breaking the build.

Wanted behavior: that "make install" fails if src/tools/website/resources/structure.json.in is broken.

**Comment by markus2330** [comment]
Maybe it is enough to add COMMAND_ERROR_IS_FATAL to line 38 of src/tools/website/CMakeLists.txt

**Comment by mpranj** [comment]
In the original problem report it was stated that Javascript throws the following error:
`Error: State 'main.dyn.installation' is already defined`

I found with grep that `main.dyn.` seems to be part of routes.js, which seems like it parses the structure.json file. for content.
I also looked at the suspected PR #4756 and have found that the "installation" reference was added. By taking a look at the file I found that it occured multiple times.

An experienced JS developer might have a better way to find this kind of problem.

**Comment by markus2330** [comment]
So there is no indication of the problem at build time at all?

**Comment by kodebach** [comment]
The first question here is: Is `routes.js` even run by `make install` or is it only executed at runtime? From #4795 it seems to me that the error only occurs when the server is started. In that case, we'd need an extra check in `make install` to avoid such duplicate entries.

However, another option might be to simply try to start the server in Jenkins and maybe even do a simple `curl | grep` check to see if the website is being served properly.

A more permanent fix would of course be to rewrite the Website and have proper testing in the CI.

**Comment by mpranj** [comment]
>  So there is no indication of the problem at build/install time at all?

None whatsoever.

As you suggested, we might need some kind of a staging page for PRs, if there will be more frequent changes to the website (wasn't really the case until now).

**Comment by kodebach** [comment]
An accessible staging page for the website would be useful. We build the full Docker images for each build anyway. I think we currently just drop them and eventually delete them (@lukashartl should know what happens, he investigated the image situation recently).

A proper staging environment (e.g. `staging-1234.libelektra.org` for PR 1234) would be nice, but probably a lot of work. For now it might be enough to push website images from every PR (one tag per PR) to the registry so that we can download them and run a local version. Then we'd just need to create a cron job to regularly remove images for closed/merged PRs, instead of a full staging environment.

Anyway, that's not what I meant with my suggested solution. IMO the easy options are:

1. Add a simple check to `Gruntfile.js` or `build.sh` that checks for duplicate entries in `structure.json.in`. That would solve the duplicate entry issue, but wouldn't help for potential other issues.
2. Add a task to the end of the Jenkins pipeline. This task would start a container with the website image that was just built and then `curl`/`wget` the homepage to see if the server started properly.
