### ISSUE TITLE
Internal Refactoring for better thread safety

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#4861]
As the API discussions are still ongoing and an agreement on the full API will probably take some time (I still suggest to pick smaller changes which have a clear problem), I suggest that you start with internal refactoring to get the development of the refactoring tool going so that we see what it actually can do.

Following points came to my mind:

- [ ] #4870
       usage of thread safe functions everywhere, especially strerror_r. Systematically search for all occurrences of POSIX functions that have a `_r` version (can be found out with `apropos`).
- [x] #4466
  Imho this is the most important problem, which leads to easily reproducible crashes if two threads do something with `KDB`. I am not sure, however, if and how automatic refactoring can be helpful there.
- [x] #4869
     search for all global variables. If there are any, please report and let us discuss if automatic refactoring makes sense.

**Comment by kodebach** [comment]
>  usage of thread safe functions everywhere

Yes, that seems like a pretty good showcase example.

> Imho the most important problem is

If you're using TOML and see it as an important problem, why not create a PR yourself? The issue already suggests what needs to be done and it shouldn't be too hard to do.

In any case, even if this could be automated, I think doing it by hand is much quicker and easier.

> search for all global variables

Finding global variables should work with plain `tree-sitter`, no need for the tool I'm working on. Refactoring probably can't be automated here either, since what should be done very much depends on what the variable is used for. The only thing that might be automatable would be adding `thread_local`, but that might not work for all cases and also needs C11 (which I'm not sure if we want to require).

**Comment by kodebach** [comment]
Using the list of functions for which POSIX _does not_ guarantee thread-safety from [here](https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_09_01), I have now found that we use (with usage counts):

- `basename`: 1 
- `dirname`: 3
- `dlerror`: 1
- `getenv`: 9
- `getopt`: 1
- `getpwnam`: 1
- `getservbyname`: 1
- `localeconv`: 1
- `nl_langinfo`: 1
- `rand`: 1
- `setenv`: 2
- `setlocale`: 3
- `strerror`: 18
- `strsignal`: 1
- `strtok`: 3
- `system`: 1
- `unsetenv`: 1
- `wctomb`: 1

Full results [here](https://rift-successful-tyrannosaurus.glitch.me/)

I found these replacement functions

- `getpwnam` -> `getpwnam_r`
- `getservbyname` -> `getaddrinfo`
- `localeconv` -> `nl_langinfo_l`
- `nl_langinfo` -> `nl_langinfo_l`
- `strerror` -> `strerror_r`
- `strsignal` -> `strdescr_np` (GNU)
- `strtok` -> `strtok_r`

The other functions listed above have no options at all AFAICT. However, that's not so bad. If we ignore test and example code, as well as the functions which alternatives, we're left with:

- `basename`:
  - [../libelektra/src/plugins/curlget/curlget.c:349:28]
- `dirname`:
  - [../libelektra/src/bindings/intercept/fs/intercept.c:47:23] Deprecated
  - [../libelektra/src/plugins/gitresolver/gitresolver.c:236:24]
  - [../libelektra/src/plugins/resolver/filename.c:97:15]
- `getservbyname`:
  - [../libelektra/src/plugins/network/network.c:78:13]
- `getopt`:
  - [../libelektra/src/tools/pythongen/template/genopt.c:113:14] Deprecated
- `getenv`:
  - [../libelektra/src/plugins/cache/cache.c:67:20]
  - [../libelektra/src/plugins/wresolver/wresolver.c:122:18]
  - [../libelektra/src/plugins/crypto/gpg.c:140:25]
  - [../libelektra/src/plugins/journald/journald.c:43:17]
  - [../libelektra/src/plugins/fcrypt/fcrypt.c:79:12]
  - [../libelektra/src/plugins/desktop/desktop.c:43:6]

I will write a `tree-surgeon` script for `getpwnam` -> `getpwnam_r`, `getservbyname` -> `getaddrinfo`, `localeconv` -> `nl_langinfo_l`, `nl_langinfo` -> `nl_langinfo_l`, `strerror` -> `strerror_r` and `strtok` -> `strtok_r`.

`basename` and `dirname` are marked thread-safe on Linux and I don't know why they wouldn't be on any platform, AFAIK `getenv` can only race with `setenv`, which we only use in tests, and `getopt` is only used in the deprecated pythongen code. So I think we can ignore all of these.

**Comment by kodebach** [comment]
For global variables I found [these 58 results](https://oval-rocky-pelican.glitch.me/). I didn't spend the time to adjust the script to filter out `static const`. After manually doing that  we're left with:

https://github.com/ElektraInitiative/libelektra/blob/0d2b21383e14397ea95c75ad9ddcbf08b223a29b/src/bindings/intercept/fs/intercept.c#L37

Not sure, but `intercept` will probably be removed anyway.

https://github.com/ElektraInitiative/libelektra/blob/0d2b21383e14397ea95c75ad9ddcbf08b223a29b/src/bindings/erl_nif/lib/nif_kdb.c#L1865

Should be made `const`.

https://github.com/ElektraInitiative/libelektra/blob/0d2b21383e14397ea95c75ad9ddcbf08b223a29b/src/bindings/glib/gelektra-key.c#L60

No idea, but no obvious fix AFAICT.

https://github.com/ElektraInitiative/libelektra/blob/0d2b21383e14397ea95c75ad9ddcbf08b223a29b/src/plugins/specload/specload.c#L41

Should be made `const`.

https://github.com/ElektraInitiative/libelektra/blob/0d2b21383e14397ea95c75ad9ddcbf08b223a29b/src/plugins/crypto/crypto.c#L25

Not sure, probably intentional.

https://github.com/ElektraInitiative/libelektra/blob/0d2b21383e14397ea95c75ad9ddcbf08b223a29b/src/plugins/glob/glob.c#L25

Should be made `const`.

https://github.com/ElektraInitiative/libelektra/blob/0d2b21383e14397ea95c75ad9ddcbf08b223a29b/src/plugins/counter/counter.c#L21

Should be moved to plugin data.
