### ISSUE TITLE
Freedesktop page needs some update

### ISSUE THREAD

**Issue by KurtMi** [ElektraInitiative/libelektra#583]
https://www.freedesktop.org/wiki/Software/Elektra/

`Last edited Sat May 18 07:33:26 2013`

**Comment by markus2330** [comment]
Yes, I know. The issue is that they have shut down their version control system and none of admins respond. Its a well-known issue and discussed in mailing lists. Sadly, its now even easier to work with sf.net which had similar problems a while ago, but it is now updated: https://sourceforge.net/projects/elektra/?source=directory

I think its best to redirect https://www.freedesktop.org/wiki/Software/Elektra/ to http://www.libelektra.org, so if you find any way to do so, please do it.

**Comment by KurtMi** [comment]
I have no idea. I will close this issue, it is unsolvable.

**Comment by markus2330** [comment]
At least as long as we don't know anyone with admin rights of the freedesktop wiki ;)
