### ISSUE TITLE
kdb-gen missing in build - PYTHON2INTERP_FOUND not set

### ISSUE THREAD

**Issue by martinschleiss** [ElektraInitiative/libelektra#692]
Hi,

I just tried compiling the framework with `make kdb-full` but could not find the command `kdb gen` in the generated binary. Looking at the sources of kdb-gen I see that it has a dependency on Python (which is not documented in its README.md). CMAKE expects a variable PYTHON2INTERP_FOUND to be set but doing a quick search using Githubs search reveals that this flag is never set. Could it be that I'm missing something? Btw, I already installed python2.7 and  python2.7-dev on Ubuntu 16.04.  

Any help is appreciated :)

**Comment by markus2330** [comment]
Thanks for the report. `kdb` works similar to git: for unknown commands it uses external tools that can be listed with `kdb list-tools`. `kdb gen` is such an external tool, thus you actually do not need `kdb` to invoke gen, you can also directly invoke the python script [src/tools/gen/gen](https://github.com/ElektraInitiative/libelektra/blob/master/src/tools/gen/gen), even without installation `kdb gen` as it is done in its unit tests (see `Makefile` in that directory and the folder `tests`). (You need, however, Elektra to be installed, thus the unit tests try to link against it. You can also easily adapt the Makefile to use a different linker path with `-L` or a different variant of Elektra, e.g. the not-static one with `-lelektra`.)

That said, you can also easily fix the PYTHON2INTERP problem, it seems like you need to set `-DPYTHON2_EXECUTABLE:PATH=/path/to/python2`, some examples how to do so are given in [src/bindings/swig/README.md](https://github.com/ElektraInitiative/libelektra/blob/master/src/bindings/swig/README.md).

Also make sure that `gen` is listed in `TOOLS`. Because you already found out about PYTHON2INTERP_FOUND, it seems like you already figured that out on your own.

Do not hesitate to ask any further questions.

**Comment by martinschleiss** [comment]
Thanks for the hints. Now `kdb-gen` works for me. 

I have another question, it's not that important but in the current implementation it seems like that default values in the `.ini` files have to be defined. Looking at the tests folder, I can see that every `.ini` file has default values defined as well. Maybe this should be noted in the examples of the README.md.

**Comment by markus2330** [comment]
Thank you for the hint, it should be fixed now.
