### ISSUE TITLE
Speed up PR builds by only building/testing changed module

### ISSUE THREAD

**Issue by manuelm** [ElektraInitiative/libelektra#730]
As explained here https://github.com/ElektraInitiative/libelektra/issues/160#issuecomment-219752143 we need a script which inspects the changed paths and dynamically builds the BINDINGS + PLUGINS variable.

To better integrate the script into the different build environments the script shouldn't start the configuration phase itself. Instead it should just output the configuration defines.

e.g. `scripts/magic.sh $TRAVIS_COMMIT_RANGE`
will output: `-DBINDINGS="..." -DPLUGINS="..."`

Regarding the bindings we can make things a little easier:
- touching anything in bindings/swig rebuilds swig_python+swig_python2+swig_lua
- touching anything in bindings/gi or bindings/glib rebuilds glib+gi_python+gi_lua

To make thinks more complicated again:
- touching src/plugins/python should also trigger src/plugins/python2

**Comment by manuelm** [comment]
Scratch the independent script. Please make it a bash function. We can just source the file and call the function.

**Comment by markus2330** [comment]
Sorry, the issue has to wait, others are more important.

**Comment by markus2330** [comment]
A related problem is to know when then build directory needs to be discarded (needed for fast+incremental build jobs). It seems like adding errors/warnings is not safe, cmake does not detect it now, maybe because of #857. I would say, if a CMake file was changed, the script should purge the build directory.

(Btw. the problem is related because the script discussed here -- that only builds plugins as needed -- would be useful for fast+incremental, too)

**Comment by markus2330** [comment]
I think the fast build job now gives timely feedback, and for the others it takes a while anyway. Please reopen if you think the issue is still relevant.

**Comment by markus2330** [comment]
For the plugins and tools it would be quite straight-forward to realize: If src/plugins/<PLUGIN> or src/tools/<TOOL> has modifications, the shell function would set PLUGINS and TOOLS accordingly.

For bindings it seems to be a bit problematic, because there is no convention of how the folders to map to BINDINGS. What about restructuring the bindings to keep the function more simple?

> touching src/plugins/python should also trigger src/plugins/python2

Maybe the `-MM` option helps to find such deps:
```
> cd src/plugins/python2
> gcc -MM -DSWIG_TYPE_TABLE "-DSWIG_RUNTIME=<stdio.h>" "-DELEKTRA_README=<stdio.h>"  python.cpp
python.o: python.cpp ../python/python.cpp ../python/python.hpp
```

Or we write such reverse-deps explicitly in the contract (README.md).

**Comment by waht** [comment]
Here is a rough idea for differential builds:

1. Use `git diff --name-only master..@` to lists all changed files between the current branch and master
2. strip file names from paths and remove duplicates
3. resolve plugins (e.g. a change in `src/plugins/xyz` adds `xyz` to PLUGINS)
4. resolve bindings (e.g. a change in `src/bindings/foo/bar` adds `foo_bar` to BINDINGS)
4. resolve tools (e.g. a change in `src/tools/xyz` adds `xyz` to TOOLS)
5. resolve dependencies
  some plugins require bindings, some bindings other bindings => use README.md to resolve these dependencies via new `requires/bindings|plugins|tools` which contains a list of dependencies. needs to be aware of circular dependencies

Have you considered integrating this feature directly into CMake? It could reuse some code (e.g. README extraction) have direct access to the required variables and we could make it an option e.g. "-DENABLE_DIFFERENTIAL=On" that can be used locally and on the build server.

**Comment by markus2330** [comment]
Thank you for your great ideas and out-of-the-box-thinking!

> Have you considered integrating this feature directly into CMake?

Yes, I considered it but it is not much more than a consideration, see cmake/PrintDependencies.cmake
It is clear that it is not going to be trivial.

**Comment by markus2330** [comment]
Buying more hardware unfortunately is much cheaper
