### ISSUE TITLE
make install fails with CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#754]
Using `-DCMAKE_INSTALL_PREFIX` make install fails because it wants to write to system directories.

```
-- Installing: /etc/bash_completion.d/kdb
-- Installing: /etc/profile.d/kdb.sh
```

Is this intended? I'd like to use it without root permissions.

**Comment by sirblackheart** [comment]
@mpranj can you give this fix a try?

**Comment by mpranj** [comment]
@sirblackheart yes that fixes it (and the path seems to be correct)

**Comment by sirblackheart** [comment]
the question is if we should expose this somehow, as someone might want to install them into `~/.config/`

**Comment by mpranj** [comment]
Wait a sec I might have replied too quickly. With this solution, if you do not set CMAKE_INSTALL_PREFIX it gets installed to /usr/local (default path).

```
-- Installing: /usr/local/etc/bash_completion.d/kdb
-- Installing: /usr/local/etc/profile.d/kdb.sh
```

This is the way that the prefix behaves. https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html

I'm not sure the config has any effect there.

**Comment by sirblackheart** [comment]
> Wait a sec I might have replied too quickly. With this solution, if you do not set CMAKE_INSTALL_PREFIX it gets installed to /usr/local (default path).

ups you are right. i fixed it again. but with this branch you should now get an option to install the scripts to your home folder. Also the paths are now exposed so you can overwrite them.

**Comment by markus2330** [comment]
Whats wrong with simply disabling INSTALL_SYSTEM_FILES? Its purpose is to allow Elektra installation into home-directories.

Do you really think someone wants to install system files using cmake into the home directory? We could rather add a "kdb install-bash-completion" script that installs completion for the current user.

**Comment by sirblackheart** [comment]
I came again across this issue while working on #531 
My proposal would be to switch to `CMakes` [`GNUInstallDirs`](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html) `module`, as it really would be desirable to change the system file installation path for some files.
The current `brew` formula does so by manipulating the CMake files, which seems less then desirable to do so.
```
    inreplace "scripts/CMakeLists.txt",
      "/etc/bash_completion.d", bash_completion
    inreplace "scripts/CMakeLists.txt",
      "/etc/profile.d", prefix/"etc/profile.d"
```
It would be desirable to make Elektras install routine flexible enough so it can be easily used by packaging systems like `homebrew` where profile.d and bash_completion.d 

The behavior of `GNUInstallDirs` `CMAKE_INSTALL_FULL_SYSCONFDIR` is to use `/etc` if `CMAKE_INSTALL_PREFIX` is `/` or `/usr` and uses the `CMAKE_INSTALL_PREFIX` It prefixes it otherwise. It makes perfect sense to install both files into `/usr/local/` if this is chosen as prefix. As this location is meant for files not installed by a package manager.

**Comment by markus2330** [comment]
Do the bash completion and profile.d work  when installed to /usr/etc/..?

If not, it would be a waste of time, simply go for `INSTALL_SYSTEM_FILES=OFF`.

Btw. usually it is possible to change the location where a file should be installed to. Isn't this the simpler option?

**Comment by sirblackheart** [comment]
> Do the bash completion and profile.d work when installed to /usr/etc/..?

why do i write it gets installed to /etc if "/usr" is passed?
> The behavior of GNUInstallDirs CMAKE_INSTALL_FULL_SYSCONFDIR is to use /etc if CMAKE_INSTALL_PREFIX is / or /usr

 well copy paste...

> If not, it would be a waste of time
I think you completely misjudge the situation. No it does not get sourced if it is installed under /usr/local/profile.d etc... But that is the point. If you install stuff under /usr/local it is up to you to do the sourcing.

Homebrew installs its stuff per default under `/usr/local` and installing profile.d and bash-completion.d per default in this location and tells the user that he has to source it.

> simply go for INSTALL_SYSTEM_FILES=OFF.

Just because we already have a working solution for a symptom I really do not think we should stop there and  not work on a better solution. I really feel a little bit upset if getting told to just not solve a problem the right way...

**Comment by markus2330** [comment]
It is not so easy to say what the right way is. There are many people (even maintainers) that would argue that packages should rename files if some system needs non-standard locations. The  GNUInstallDirs seems to be non-standard for CMake, I never heard of it before. It sounds like a lot of work to introduce it, its hardly impossible to test all combinations that GNUInstallDirs would provide, and it makes the cmake process for every maintainer much more difficult because of the overwhelming number of choices users get. It seems to introduce 30 (!) new CMake variables, but our goal actually should be to make CMake configuration simpler, see #111. Please start up a gui for cmake: I would argue we have already too many options hardly needed by anyone.

So I argue that the right way is to make it simpler.  Please also consider the usability for someone new to Elektra, maybe a bit familiar with CMake what "right" would be. But of course I am open to get convinced otherwise. Please open a new proposal for discussion on this specific topic and we can also vote for it.

Btw. see also discussion at #435 for improvements on the installation.

**Comment by sirblackheart** [comment]
> It is not so easy to say what the right way is.

That is why we have an issue for it to discuss it objectively.

> There are many people (even maintainers) that would argue that packages should rename files if some system needs non-standard locations.

You consider `/usr/local` a non-standard location for `etc` files? `/usr/local` is default for non package manged installation. Considering bash-completion a system file is wrong in my opinion and it should also be installed in `/usr/local` for the user to manage e.g. sourcing it.

> The GNUInstallDirs seems to be non-standard for CMake.

Strange it is part of the default cmake package in arch and in the modules folder of the cmake source. If some distro keeps it out of the standard package then there is always the possibility to ship this module in Elektras source.

> I never heard of it before.

Is this really an objective argument. You basically are saying people should not use something because they have not heard of it. Do you suggest to only use software you heard of before?

>  It sounds like a lot of work to introduce it.

I only suggest to use it for the etc installation which would basically change three lines. Do you consider that lot of work?

>  it makes the cmake process for every maintainer much more difficult because of the overwhelming number of choices users get.

It only uses one of them that will be user settable. With this the install targets would behave correctly following the GNU and FHS standard. Just take your time and read the source file of `GNUInstallDirs`

> So I argue that the right way is to make it simpler.
Simple but not very flexible. While a simple small change would make it much more flexible while staying simple.

I consider installing to CMAKE_INSTALL_PREFIX´if it differs from `/` or `/usr` the right way as stuff that does not get installed by a package manager should never be installed outside of the `CMAKE_INSTALL_PREFIX`. `INSTALL_SYSTEM_FILES` is not very clear about its content as variable.

>  maybe a bit familiar with CMake what "right" would be

If you would have taken the time to read the source file of `GNUInstallDirs` you would understand that this is in the right way of CMake by following GNU, FHS standards while honoring the `CMAKE_INSTALL_PREFIX`. It behaves correctly while giving flexibility.

**Comment by markus2330** [comment]
> You consider `/usr/local` a non-standard location for `etc` files?
> `/usr/local` is default for non package manged installation. Considering
> bash-completion a system file is wrong in my opinion and it should also be
> installed in `/usr/local` for the user to manage e.g. sourcing it.

Yes, it is completely non-standard, see http://www.pathname.com/fhs/
Even programs installed to /opt should use /etc/opt and *not* /opt/etc.

About the other discussion points: I think to partly introduce something would 
be a strong mistake, so either we fully support something or leave it 
completely. But we need a new issue for discussions, this issue is about a 
`make install` that fails, not a proposal for changing our CMake system.

For the actual problem: I think copying/moving those two files really is the 
best solution, everything else is completely overkill. Think of it: its only 
copying two unmodified files from the source tree, its a complete triviality 
we are talking about here.

**Comment by sirblackheart** [comment]
> Yes, it is completely non-standard, see http://www.pathname.com/fhs/
> Even programs installed to /opt should use /etc/opt and *not* /opt/etc.

According to its documentation `GNUInstallDirs` does honor this. 

> For ``<dir>`` equal to ``SYSCONFDIR`` or ``LOCALSTATEDIR``, the
> ``CMAKE_INSTALL_FULL_<dir>`` is computed by *appending* the prefix
>  to the value of ``CMAKE_INSTALL_<dir>`` if it is not user-specified
> as an absolute path.  For example, the ``SYSCONFDIR`` value ``etc`` 
> becomes ``/etc/opt/...``.  This is defined by the
>  `Filesystem Hierarchy Standard`_.
> 
> .. _`Filesystem Hierarchy Standard`: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html

I copy pasted the relevant part of the source code in case you overlooked it.
In addition `/opt` (Add-on application software packages) is something completely different from `/usr/local` (Local hierarchy) in this regard.  `/usr/local` has its own `/usr/local/etc` folder while `opt` should use `/opt/etc`

> About the other discussion points: I think to partly introduce something would
be a strong mistake, so either we fully support something or leave it
completely. But we need a new issue for discussions, this issue is about a
`make install` that fails, not a proposal for changing our CMake system.

Personally I am opposed to a complete introductions, as a partially introduction lets as see how well something works, and check errors that appear with that introduction. And it is not like that the rest of the build system does have this specific issues.

Sure using the `GNUInstallDirs` in all install targets would be nice but is out of the scope of this issue. I never proposed anything else then using it for those two lines. It is a marginal change to the build system which most users will not even notice other then being able to install with user privileges without setting a `INSTALL_SYSTEM_FILES`. I am backing this partial change as we now have two issues that would be solved with it without much work other then figuring out any real downfalls this change would introduce.

We also could only use the lines for getting the `etc` path right from the module without getting the whole module with its variables.

> For the actual problem: I think copying/moving those two files really is the
> best solution, everything else is completely overkill. Think of it: its only
> copying two unmodified files from the source tree, its a complete triviality
> we are talking about here.

As trivial as using `GNUInstallDirs` for the two files, which would easily solve two issues.

**Comment by markus2330** [comment]
> > Yes, it is completely non-standard, see 
http://www.pathname.com/fhs/
> > Even programs installed to /opt should use /etc/opt and *not* 
/opt/etc.
> 
> According to its documentation `GNUInstallDirs` does honor this.

It does not make it more standard and as you already noted the files 
would not be used anyway, so the out-of-the-box behavior is 
identical to not installing the files at all.

Something that would improve usability is a script that installs and 
setups the bash completion for the specific user.

> > .. _`Filesystem Hierarchy Standard`:
> > https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html
> I copy pasted the relevant part of the source code in case you 
overlooked
> it. In addition `/opt` (Add-on application software packages) is 
something
> completely different from `/usr/local` (Local hierarchy) in this 
regard. 
> `/usr/local` has its own `/usr/local/etc` folder while `opt` 
should use
> `/opt/etc`

I dont know where you get this from, in the link above (FHS 3.0 and 
2.3) it says "/usr/local/etc may be a symbolic link to /etc/local", 
not that it is a directory that should be used for installation.

Also I do not find your `/opt/etc`, I only find references to 
`/etc/opt`.

And /usr/local today is basically identical to /opt, the original 
usage of /usr as NFS mounted and /usr/local as locally mounted 
partitions is mostly historically. In my opinion correctly packaged 
software should be installed to /usr. But this discussion is not 
leading to anything.

> Personally I am opposed to a complete introductions, as a 
partially
> introduction lets as see how well something works, and check 
errors that
> appear with that introduction. And it is not like that the rest of 
the
> build system does have this specific issues.

I am not talking about complete introduction at once, but to 
completely think it through. And finding someone who is willing to 
do it the full way. But I *really* think we should concentrate on 
Elektra's goals, not on some beautification of the build system.

Maintainers are much more pragmatic on such things. Their needs are 
satisfied, so we should really listen to them.

> Sure using the `GNUInstallDirs` in all install targets would be 
nice but is
> out of the scope of this issue. I never proposed anything else 
then using
> it for those two lines. It is a marginal change to the build 
system which
> most users will not even notice other then being able to install 
with user
> privileges without setting a `INSTALL_SYSTEM_FILES`.

It is a major change interfering with most parts of the build 
system:

1. You get conflicts with KDB_DB_SYSTEM
2. configure and INSTALL documents get more complex
3. Users have to deal with more options to set
4. Confused users why some GNUInstallDirs work, and others not (or 
many other conflicts with the current way libraries and modules are 
installed if we fully go for GNUInstallDirs)

GNUInstallDirs is a somewhat nice idea and I think I would have 
favoured it when we ported from autotools. But now Elektra is 
already packaged by many distributions and it turnes out that such 
"flexibility" is not necessary. Flexibility is in quotes because 
most use cases are still not supported. Even with GNUInstallDirs you 
would not be able to install the profile file and the bash-
autocompletion file to different locations.

So you introduce a lot of complexity without eliminating the need to 
still manually move files.

> We also could only use the lines for getting the `etc` path right 
from the
> module without getting the whole module with its variables.
> > For the actual problem: I think copying/moving those two files 
really is
> > the best solution, everything else is completely overkill. Think 
of it:
> > its only copying two unmodified files from the source tree, its 
a
> > complete triviality we are talking about here.
> 
> As trivial as using `GNUInstallDirs` for the two files, which 
would easily
> solve two issues.

As said above the implications are far from trivial.

And it actually does not solve an issue, it only installs files at 
places where they are not used instead of not installing them at 
all.

Please create a new PR if GNUInstallDirs is important for you, we 
will have to repeat the whole discussion again there. Please do not 
continue the discussion here.

**Comment by sirblackheart** [comment]
Your post is currently completely unreadable on github…

**Comment by sirblackheart** [comment]
I honor your request to move this discussion to a PR but please reformat you last post so it is clearly understandable on github. There seems to be a problem with githubs way of showing the mails citations.

**Comment by markus2330** [comment]
The second quote level seemed to have caused problems with too long lines.

I hope you reconsider and focus on non-build tasks. There is a lot of work there and not much to be gained.

**Comment by markus2330** [comment]
To also state it here: The easiest solution for those two files is to not install them to `/etc` anymore:

- elektraenv.sh can be removed see #833
- fora bash_completion a different place is better anyway: #832 (thanks to @sirblackheart for finding out)

I will close this issue for now, further discussions in the respective tickets please.
