### ISSUE TITLE
fix usage of ksCut in kdb*

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#765]
update ksCut usage with cascading keys?

**Comment by tom-wa** [comment]
ok, this one is a bit tricky.
the problem are the default keys (created by the spec plugin) which are cascading keys. when i try to remove all `spec`-keys from the keyset in `elektraGetDoUpdateWithGlobalHooks` the cascading keys are cut together with the `spec` keys because `/examples/highlevel/gps/status` is below `spec/examples/highlevel` 

i'm not even sure what exactly the expected behaviour would be. it seems like before my change to keyIsBelow default keys were simply ignored because of
```
case KEY_NS_CASCADING:
        validNS = 0;
```

so i'd say the way it currently works is actually correct and i'll either handle the default keys in `elektraGetDoUpdateWithGlobalHooks` or just tell the validation plugins to ignore the `spec` namespace
using keyRel2 in ksCut would work too, but it's too early for that i guess

@markus2330 what would you say should be done here ?

**Comment by markus2330** [comment]
I think you are trying to solve an impossible problem. In the long run we need a `ksCut2` with either a filter function or an enum where you can say how the filtering should be done. Is it possible to reuse the same enum of `keyRel2` for `ksCut2`?

**Comment by tom-wa** [comment]
>I think you are trying to solve an impossible problem.

i came to the same conclusion, i've tried several approaches, the best would be a workaround in ``elektraGetDoUpdateWithGlobalHooks`(i already have a working one) until we have `ksCut2` ready. 

>Is it possible to reuse the same enum of keyRel2 for ksCut2?

actually.. `ELEKTRA_REL_BELOW_SAME_NS` is exactly what you want here. with `keyRel2` `ksCut2` could be implemented in a few lines doing exactly what needs to be done. The only thing we could argue about is if we should introduce some extra enums von convenience regarding the default/cascading keys.


imho we should also review all the unittests to see if they cover everything or if some newer features (like cascading/default keys) are missing

**Comment by markus2330** [comment]
> workaround in  `elektraGetDoUpdateWithGlobalHooks`

okay, hopefully it does not interfer with @mpranj work. He should have a look at the PR in any case.

> reuse of same enum

That would be really nice if both functions can use it. A filter is very powerful, but also  more complicated to use.

> some extra enums von convenience regarding the default/cascading keys

Maybe its useful to let some flags to be combined, e.g., having something like `ELEKTRA_REL_IGNORE_CASCADING`, which will then influence the other flags with respect to cascading keys.

> they cover everything

They do not need to be able to cover everything. They should be extensible that if another feature is needed, that we can extend it (e.g. by adding something to the enum) without inconsistencies or other problems.

**Comment by mpranj** [comment]
If you're just messing with ksCut but you have a workaround, it should be no problem to merge it.

Any commit that changes `elektraGetDoUpdateWithGlobalHooks` will almost surely interfere with my PR. I'm splitting up the function in smaller chunks. The sub-positions etc. would blow `elektraGetDoUpdateWithGlobalHooks` quite over 100 lines and I found it unreadable as is already.

**Comment by markus2330** [comment]
@mpranj Sounds good that you split the function up! Needs proper testing though..

@tom-wa So its better if you place the workaround within a elektraKsDupSpecialHandling for easy integration into @mpranj 's code.

**Comment by markus2330** [comment]
@tom-wa Is this fixed?

**Comment by tom-wa** [comment]
for now: yes. it's a workaround in kdb.c
but ksCut needs to be rewritten/a replacement later.

**Comment by markus2330** [comment]
Thanks for the info!
