### ISSUE TITLE
Elektra Qt Editor: privileged actions

### ISSUE THREAD

**Issue by raetiacorvus** [ElektraInitiative/libelektra#811]
I propose we either offer a way to elevate rights for certain actions (e.g. mounting) or hide them when the application is run without proper rights.

@0003088 what do you think? Should we take a look at polkit support?

**Comment by 0003088** [comment]
Well, I'm not sure if I'm the right person to address here. Shouldn't you discuss this topic with @markus2330?

**Comment by sirblackheart** [comment]
@0003088, sorry I thought I'd ask you first as main developer of the `qt-gui`.

**Comment by 0003088** [comment]
No worries! Sure, I developed the gui but since I completed my bachelor's thesis I'm just fixing bugs or implementing minor features. I'm certainly not involved deeply enough in the project to decide if polkit should be supported or not (btw. I do not have any experience with polkit).

**Comment by markus2330** [comment]
Hi! There was even a discussion with @0003088 about such a feature and of course it would be nice and improve usability. We dropped the idea, however, because of the relatively high effort.

Maybe we can gray out parts if not writable as first step (a feature also proposed by @0003088, which now would also be useful for the isWritable in gsettings). One implementation that comes to mind is to do a kdbGet(), and then use the string of the parentKey (which contains the file name, this is also done by `kdb file`) to run access(2) on it. Unfortunately, it might be very expensive if done for many keys. So you might need to peek into system/elektra/mountpoints and only do a check per mountpoint+namespace.

**Comment by markus2330** [comment]
Closed because of low priority, will be reevaluated after 1.0.
