### ISSUE TITLE
global plugins: test plugin

### ISSUE THREAD

**Issue by mpranj** [ElektraInitiative/libelektra#884]
The current plan to test global plugins is a plugin called `globalhooks` that:
- mounts itself to all possible positions
- checks if it gets called on that position (global plugins get their position information in `parentKey`)

TODO:
- [ ] method to test `foreach` plugins (they don't get their position in `parentKey`)

@markus2330 is this OK for a start? I'm thinking of very simple `strcmp` scenarios here. There's potential to test a lot more in the future.

**Comment by markus2330** [comment]
That are good ideas and thank you for opening this issue.

What is important is some kind of high-level use-case-based testing. So you define e.g. 3 backends, that have some plugins with a pre-defined sequence of return values with modifications on the KeySet, and some global plugins (again with predefined actions).

Given this, the unit test only asserts that the correct sequence of plugins is called with the correct modification at the keyset.

Such an approach is needed for:

- [ ] testing rollback and similar things (plugins must fail then)
- [ ] testing more complex interactions as needed for mmap (e.g. if all foreach resolver plugins say that no update is needed (because all mmap files are up-to-date), then the sequence of plugins must change)

There are (many) other (even more) complex use-cases, but they do not have to be done by you (but the person involved in the respective task).

A small implementation note: for backend mounting, it should be much easier build upon existing libtools infrastructure, creating a keyset with the content of system/elektra/mountpoints would be quite a hassle.

**Comment by markus2330** [comment]
Thank you for keeping it alive. Would be amazing to have more reliable global plugins, in the current form they are not suitable for 1.0.
