### ISSUE TITLE
crypto plugin: move asciifying to plugin

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/libelektra#929]
# Situation / Problem

In the crypto plugin asciifying binary values is done using the following methods:

    kdb_octet_t * elektraCryptoHex2Bin (Key * errorKey, const char * hexBuffer);
    char * elektraCryptoBin2Hex (Key * errorKey, const kdb_octet_t * buffer, const size_t length);

in file `src/plugins/crypto/helper.c`.

# Expected Behaviour (Proposal)

The code should be moved to another plugin or maybe `hexcode` or `ccode` can be used instead.

**Comment by petermax2** [comment]
This is a follow-up task to #892 .

**Comment by petermax2** [comment]
Requires #897 to be solved first.

**Comment by petermax2** [comment]
@markus2330 The token pasting / token concatenation in `ELEKTRA_PLUGIN_FUNCTION` causes trouble when used with the `ELEKTRA_PLUGIN_NAME` symbol which holds the plugin name in quotes (e.g. `#define ELEKTRA_PLUGIN_NAME "crypto_botan"`).

If no `ELEKTRA_VARIANT` is defined (like in the base64 plugin) everything works fine. However, if you define `ELEKTRA_VARIANT` (like the crypto plugin does), the quotes `"` are encoded into the function name causing compiler errors.

    ELEKTRA_PLUGIN_FUNCTION (ELEKTRA_PLUGIN_NAME, base64Encode)

Do you have an idea about how to address this issues?

**Comment by markus2330** [comment]
Seems like it would have been better to pass the ELEKTRA_PLUGIN_NAME without quotes and quote it within src/include/kdbplugin.h so that both variants are available.

Then we could also write `ELEKTRA_PLUGIN_FUNCTION` in a way that the module (ELEKTRA_PLUGIN_NAME) does not need to be passed by argument anymore.

I think it would be okay to change these APIs, because its highly unlikely that anyone external wrote plugins using the variants features.

**Comment by markus2330** [comment]
Is this issue still relevant? Seems to be fixed by the `base64` plugin. Please reopen if there are still tasks lefts.

**Comment by petermax2** [comment]
The task is still open. The `base64` PR just added the plugin. I did not (yet) remove the `hex2bin` and `bin2hex` functions because I had compilation problems (see comment above).
