### ISSUE TITLE
Memleak Crypto Plugin

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#932]
Seems like that the build jobs during PR did not check memleak at least for one debian version:
http://community.markus-raab.org:8080/job/elektra-incremental/lastFailedBuild/console

**Comment by petermax2** [comment]
@markus2330 could you have a look at `gpg.c` please? I am not sure if the valgrind warnig is a false positive or not.

    ==29243== Syscall param execve(argv[i]) points to uninitialised byte(s)
    ==29243==    at 0x639C317: execve (execve.c:33)
    ==29243==    by 0x6CA5823: elektraCryptoGpgCall (gpg.c:417)

valgrind complains about accessing the argument vector `argv[0]` which holds the path to the gpg binary. I don't see where the variable is not getting initialized.

**Comment by petermax2** [comment]
@markus2330 never mind. I found the problem :)

**Comment by petermax2** [comment]
I am afraid the conditional jumps on uninitialized values originate in libgcrypt.

    ==3659== Conditional jump or move depends on uninitialised value(s)
    ==3659==    at 0x4C2D9A4: memcpy@@GLIBC_2.14 (vg_replace_strmem.c:915)
    ==3659==    by 0x4E3982B: keySetRaw (keyvalue.c:541)
    ==3659==    by 0x62F887F: elektraCryptoGcryDecrypt (gcrypt_operations.c:421)
    ==3659==    by 0x62FA9B5: elektraCryptoDecrypt (crypto.c:255)
    ==3659==    by 0x62FA9B5: libelektra_cryptogcrypt_gcrypt_LTX_elektraPluginget (crypto.c:379)
    ==3659==    by 0x40403D: test_crypto_operations (test_internals.h:239)
    ==3659==    by 0x40403D: main (testmod_crypto_gcrypt.c:21)

I tried using a variable length array instead of the heap-allocated buffer and initialized it. Without any changes. The following call (possibly) moves uninitialized data around.

	gcry_err = gcry_cipher_decrypt (*handle, output, payloadLen, NULL, 0);

The way I see it, we can only suppress the valgrind message or go back to using two different arrays for decryption. But I prefer in-place decryption because it makes the code easier to read and maintain.

**Comment by markus2330** [comment]
The PR did not fix every problem:

Potential Memory Leak - 514

Try to write glob that suppress everything that leaks from the crypto libraries we use (but not from our code), the valgrind file is getting unmaintainable.

As said in the PR, you can easily trigger every build job, see doc/GIT.
