### ISSUE TITLE
dbus: non-UTF8 key names

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#955]
```
This is normally a bug in some application using the D-Bus library.
Couldn't add message argumentprocess 6139: arguments to dbus_message_iter_append_basic() were incorrect, assertion "_dbus_check_is_valid_utf8 (*string_p)" failed in file ../../dbus/dbus-message.c line 2676.
```

**Comment by markus2330** [comment]
Happened during `Doing naming tests` of `check_kdb_internal_suite` with dbus mounted as global plugin.

**Comment by markus2330** [comment]
@waht Seems like dbus does not accept arbitrary strings as file names. redis et al. likely have similar issues. Can you take a look?

**Comment by waht** [comment]
Yes this happens if the key name passed to [```dbus_message_append_args``` in sendmessage.c](https://github.com/ElektraInitiative/libelektra/blob/master/src/plugins/dbus/sendmessage.c#L59) contains non-UTF-8 characters. The [D-Bus specification](https://dbus.freedesktop.org/doc/dbus-specification.html#basic-types) requires strings to *validate strictly* as UTF-8. Redis does not require this - strings are [interpreted as binary sequence](https://redis.io/topics/data-types-intro) so encoding is not an issue. This seems also [true for ZeroMQ](http://czmq.zeromq.org/manual:zstr).

As far as I can see Elektra does not care about encoding of key names too. So to fix this issue in the D-Bus plugin keyNames could be converted to UTF-8 if they contain non-UTF-8 characters but what should be used as source encoding? ASCII?

**Comment by markus2330** [comment]
Thank you! Documenting this fact should be enough for now. In the longer term we should extend the iconv plugin to also fix key names.

**Comment by markus2330** [comment]
We should find a proper solution to this. E.g. KDE kopete can have keys with UTF-8 as it allows user-specified status or kmix uses user-specified audio names as section names.

@mpranj did you already try to use our dbus notifications with KDE or GNOME?

**Comment by mpranj** [comment]
> did you already try to use our dbus notifications with KDE or GNOME?

Yes, I used it with GSettings and it was working fine, but I never specifically tested with non-UTF-8 characters.

**Comment by markus2330** [comment]
Did you check if the APIs even allow non-UTF-8 to end up in the KeySet? Nevertheless, we also need some protection to not trigger asserts in the libs that we use.
