### ISSUE TITLE
API documentation has broken links

### ISSUE THREAD

**Issue by eschnett** [ElektraInitiative/libelektra#996]
The [API documentation](https://github.com/ElektraInitiative/libelektra/blob/master/doc/API.md) contains many broken links, e.g. for `KDB (Key Database)`, and all the following entries I checked.

**Comment by markus2330** [comment]
Thank you for reporting!

The links use doxygen features and work only on the generated html pages, e.g.: http://doc.libelektra.org/api/0.8.18/html/
but not directly in the Markdown pages. (The rendered pages are also linked at the beginning of the document, in the end of the section "API Docu").

The issue you found is possible because we have 2 ways of viewing the documentation:

- directly github .. can only link to other github pages
- rendered by doxygen (in html, pdf and also installed man pages displayed with --help) .. can additionally link to API.

@KurtMi already started an discussion how we can better split the docu, so that not (nearly) every page has the requirement to work in both ways. API.md would be a good candidate not to be included, because it is designed to be the main page of doxygen.

Another way to improve the situation would be to have "dummy" links to rendered docu, e.g. instead of
`[KDB (Key Database)](@ref kdb)` -> `[KDB (Key Database)](http://doc.libelektra.org/api/current/html/group__kdb.html#@ref kdb)` and have our [markdownlinkconverter](https://github.com/ElektraInitiative/libelektra/tree/master/doc/markdownlinkconverter) strip the dummy link before doxygen is used. It would only link to the correct page, but it would not jump to the correct API entry, so the fix would be only partial. Currently only 31 such links seem to exist.

As third option we could also avoid these Markdown links that are actually doxygen links alltogether.
